import type { Poem } from "./types";

/** 初中阶段 · 第 1 批（魏晋至唐宋，写景、抒怀、思乡） */
export const JUNIOR_1: Poem[] = [
  {
    slug: "guancanghai",
    title: "观沧海",
    titleEn: "Beholding the Blue Sea",
    author: "曹操",
    authorEn: "Cao Cao",
    dynasty: "东汉",
    dynastyEn: "Eastern Han",
    stage: "初中",
    kind: "诗",
    theme: "山水",
    themeEn: "Landscape",
    level: 2,
    lines: [
      { zh: "东临碣石，以观沧海。", en: "East I climb to Jieshi, to look upon the dark sea." },
      { zh: "水何澹澹，山岛竦峙。", en: "How the waters heave and swell; the island-peak stands sheer." },
      { zh: "日月之行，若出其中；星汉灿烂，若出其里。", en: "Sun and moon in their courses seem to rise out of it; the Milky Way, resplendent, seems to rise from within it." },
    ],
    keywords: [
      { w: "heave and swell", zh: "（水）荡漾起伏" },
      { w: "sheer (adj.)", zh: "耸立的" },
      { w: "course (n.)", zh: "运行、行程" },
      { w: "resplendent (adj.)", zh: "灿烂的" },
    ],
    cross: {
      field: "天文",
      fieldEn: "Astronomy",
      title: "日月星辰真的从海里出来吗？",
      titleEn: "Do sun and stars really rise from the sea?",
      body: "这是很准确的观察。地球自转使所有天体看起来东升西落；站在东岸海边，天体确实是从海平面下方升起的。而「星汉灿烂」指银河，银河是太阳系所在的银河系的盘面投影，夏季夜空中正是银河最明亮的一段。曹操写这首诗时北征乌桓刚回师，站在渤海边的碣石山上——用天体运行的宏大尺度收束全诗，是中国诗里最早的海景名篇之一。",
      bodyEn: "An accurate observation. Earth's rotation makes all celestial bodies rise in the east and set in the west; from an east-facing coast they genuinely climb out of the sea. 「The Milky Way resplendent」 is our own galaxy's disc seen from inside, brightest in summer skies. Cao Cao wrote this after his northern campaign against the Wuhuan, standing on Mount Jieshi by the Bohai Sea — closing a landscape poem on a cosmic scale, one of the earliest great sea poems in Chinese.",
    },
    note: "「若出其中」的「若」是关键——不是真的，是壮阔到让人以为如此。英文用 seem to rise 保留了这份错觉。",
    noteEn: "The hinge is 「若」 — seeming, not being. Hence seem to rise.",
  },
  {
    slug: "wenwangchangling",
    title: "闻王昌龄左迁龙标遥有此寄",
    titleEn: "On Hearing Wang Changling Had Been Demoted to Longbiao, Sent from Afar",
    author: "李白",
    authorEn: "Li Bai",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "送别",
    themeEn: "Farewell",
    level: 2,
    lines: [
      { zh: "杨花落尽子规啼，闻道龙标过五溪。", en: "Willow catkins have fallen, the cuckoo cries; I hear you have passed the Five Streams on the way to Longbiao." },
      { zh: "我寄愁心与明月，随君直到夜郎西。", en: "I entrust my sorrowing heart to the bright moon — may it follow you west, all the way to Yelang." },
    ],
    keywords: [
      { w: "catkin (n.)", zh: "（杨）花絮" },
      { w: "cuckoo (n.)", zh: "子规、杜鹃" },
      { w: "entrust A to B", zh: "把 A 托付给 B" },
      { w: "follow (v.)", zh: "跟随" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "子规是什么鸟？为什么叫声惹愁？",
      titleEn: "What bird is the cuckoo, and why is its cry sad?",
      body: "子规即杜鹃（大杜鹃），典型的巢寄生鸟类：它把蛋产在其他鸟（如苇莺）巢中，由养父母代为孵育。它的叫声在春末夏初彻夜不停，声似「不如归去」，古人因此把它与羁旅、思归、伤春绑在一起。杜鹃在农历三四月鸣叫最盛，正是杨花落尽的时节——李白用两个同时出现的物候，为贬谪的消息铺垫了氛围。",
      bodyEn: "The cuckoo is a brood parasite: it lays its eggs in the nests of other species — reed warblers and the like — which raise the chick. It calls ceaselessly through late spring and early summer, and Chinese ears heard in it 「better go home」. Hence its link with exile, longing and the end of spring. Its calling peaks in the third and fourth months, exactly when willow catkins fall — two phenological signs that set the mood.",
    },
    note: "「寄愁心与明月」是本诗的诗眼：把抽象的愁托付给具体的月亮。英文用 entrust my sorrowing heart to the bright moon 保留拟人。",
    noteEn: "The poetic eye: entrusting abstract sorrow to a concrete moon.",
  },
  {
    slug: "cibeigushanxia",
    title: "次北固山下",
    titleEn: "Mooring Below Mount Beigu",
    author: "王湾",
    authorEn: "Wang Wan",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "思乡",
    themeEn: "Homesickness",
    level: 2,
    lines: [
      { zh: "客路青山外，行舟绿水前。", en: "The traveller's road runs beyond green hills; my boat moves on before green water." },
      { zh: "海日生残夜，江春入旧年。", en: "The sea sun is born in the waning night; river spring enters the old year." },
      { zh: "乡书何处达？归雁洛阳边。", en: "Where can a letter home be delivered? By the homing geese, at Luoyang's edge." },
    ],
    keywords: [
      { w: "waning (adj.)", zh: "将尽的（残夜）" },
      { w: "be born (of the sun)", zh: "（太阳）升起" },
      { w: "deliver (v.)", zh: "送达" },
      { w: "homing (geese)", zh: "归巢的、归乡的" },
    ],
    cross: {
      field: "天文",
      fieldEn: "Astronomy",
      title: "为什么残夜里就日出、旧年里就入春？",
      titleEn: "Why dawn in the old night and spring in the old year?",
      body: "这两句写的是历法与天文的错位。北固山在长江下游，冬至前后夜最长，但冬末时太阳已逐渐北移，日出时间提前——天还没完全亮（残夜）时太阳就已跃出；而立春常在农历新年前后，江边回暖较早，所以「江春入旧年」。古人把这种「新事物在旧框架里提前出现」的现象写成了哲理：残夜未尽，海日已生。",
      bodyEn: "The couplet records a mismatch between calendar and sky. On the lower Yangtze, the sun resumes its northward march after the winter solstice and sunrise comes earlier, so the sun can clear the horizon while night still lingers. The solar term 「spring begins」 often falls around the lunar new year, and riverbanks warm early — spring enters the old year. The ancients turned the fact into a principle: before the old ends, the new is already rising.",
    },
    note: "「生」「入」两个动词把时间写成主动的力量——英文用 is born 与 enters 保留了动词的主动性。",
    noteEn: "Two active verbs — is born, enters — make time itself act.",
  },
  {
    slug: "tianjingshaqiusi",
    title: "天净沙 · 秋思",
    titleEn: "Tianjingsha · Autumn Thoughts",
    author: "马致远",
    authorEn: "Ma Zhiyuan",
    dynasty: "元",
    dynastyEn: "Yuan",
    stage: "初中",
    kind: "词",
    theme: "思乡",
    themeEn: "Homesickness",
    level: 2,
    lines: [
      { zh: "枯藤老树昏鸦，小桥流水人家。", en: "Withered vines, an old tree, a dusk-crow; a little bridge, flowing water, a household." },
      { zh: "古道西风瘦马。夕阳西下，断肠人在天涯。", en: "An ancient road, west wind, a lean horse. The setting sun sinks in the west; one with a broken heart is at the world's edge." },
    ],
    keywords: [
      { w: "withered (adj.)", zh: "枯萎的" },
      { w: "vine (n.)", zh: "藤蔓" },
      { w: "lean (adj.)", zh: "瘦的（马）" },
      { w: "a broken heart", zh: "断肠（心碎）" },
    ],
    cross: {
      field: "语言",
      fieldEn: "Linguistics",
      title: "为什么它能成为「意象叠加」的典范？",
      titleEn: "Why is this the model of piled-up imagery?",
      body: "前三句共 18 字，列出 9 个名词性意象（枯藤、老树、昏鸦、小桥、流水、人家、古道、西风、瘦马），几乎不用动词与连接词。这种写法叫「列锦」或意象并置，靠读者自己在脑中补全关系——英文只能靠并列的名词短语模仿（Withered vines, an old tree, a dusk-crow）。认知语言学认为，读者会自动把这些名词整合为一个场景，参与感越强，画面越鲜明。",
      bodyEn: "Eighteen characters, nine noun-images, almost no verbs or connectives: withered vine, old tree, dusk-crow, little bridge, flowing water, household, ancient road, west wind, lean horse. The device is paratactic juxtaposition — the reader supplies the relations. English can only imitate it with stacked noun phrases. Cognitive linguistics holds that readers integrate these nouns into one scene automatically; the more you participate, the sharper the picture.",
    },
    note: "全篇最后才出现「人」——前面九个意象全是布景，只为最后五个字。英文把 the world's edge 放在句末，收束同样的力道。",
    noteEn: "No person until the final line: nine images are pure staging for those last words.",
  },
  {
    slug: "emeishanyuege",
    title: "峨眉山月歌",
    titleEn: "Song of the Moon over Mount Emei",
    author: "李白",
    authorEn: "Li Bai",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "山水",
    themeEn: "Landscape",
    level: 2,
    lines: [
      { zh: "峨眉山月半轮秋，影入平羌江水流。", en: "The moon of Mount Emei, a half-wheel of autumn; its image falls into the Pingqiang River and flows along." },
      { zh: "夜发清溪向三峡，思君不见下渝州。", en: "At night I leave Qingxi, heading for the Three Gorges; thinking of you and not seeing you, I go on down to Yuzhou." },
    ],
    keywords: [
      { w: "half-wheel", zh: "半轮（月）" },
      { w: "image (n.)", zh: "（月）影" },
      { w: "head for", zh: "前往" },
      { w: "go on down", zh: "顺流而下" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "江里的月亮为什么总跟着船走？",
      titleEn: "Why does the river moon always follow the boat?",
      body: "「影入平羌江水流」写的是水面上的月光倒影。平静水面像一面平面镜，按反射定律成虚像；水一流，像就被拉成粼粼的碎光。更妙的是月影仿佛「随流水走」——这其实是错觉：月球距地球约 38.4 万千米，船行几十里相对这个距离可忽略不计，月亮相对你的张角几乎不变，所以它看起来始终停在原方向、与你同行（天文学上叫「月亮跟着人走」，源于视差极小）。江水只是把同一个月亮映在每一段水面上，船过处不断生成新的倒影，才显得它在随波而下。「半轮秋」则点出时节：初秋夜里的峨眉山月，多半是上弦月（农历初七、八），半明半暗，故曰半轮。",
      bodyEn: "「Its image falls into the Pingqiang River and flows along」 describes the moon's reflection on water. A still surface is like a plane mirror, forming a virtual image by the law of reflection; the moment it moves, the image breaks into shimmering flecks. The trick is that the image seems to travel with the current — an illusion. The Moon is about 384,000 km away, so a boat's drift of a few dozen li barely changes the angle it subtends; it keeps the same bearing and seems to accompany you (astronomers call this 「the Moon follows you」, a result of near-zero parallax). The river merely mirrors the same Moon on every stretch of water, so new reflections keep appearing as the boat passes — making it look as if the image flows downstream. 「A half-wheel of autumn」 pins the season: an early-autumn moon over Mount Emei would most likely be a first-quarter moon (around the 7th–8th of the lunar month), half lit — hence 「half-wheel」.",
    },
    note: "28 字里用了五个地名（峨眉山、平羌江、清溪、三峡、渝州）——行旅路线越具体，思念越真实。",
    noteEn: "Five place-names in twenty-eight characters: the more precise the route, the more real the longing.",
  },
  {
    slug: "jiangnanfengliguinian",
    title: "江南逢李龟年",
    titleEn: "Meeting Li Guinian in the South",
    author: "杜甫",
    authorEn: "Du Fu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "人生",
    themeEn: "Life",
    level: 2,
    lines: [
      { zh: "岐王宅里寻常见，崔九堂前几度闻。", en: "In Prince Qi's house I often saw you; before Cui Jiu's hall I heard you many times." },
      { zh: "正是江南好风景，落花时节又逢君。", en: "Now, just when the south is at its loveliest — in the season of falling blossoms, I meet you again." },
    ],
    keywords: [
      { w: "many times", zh: "几度" },
      { w: "at its loveliest", zh: "风景最好时" },
      { w: "falling blossoms", zh: "落花时节" },
      { w: "meet again", zh: "重逢" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "为什么重逢这么沉重？",
      titleEn: "Why is this reunion so heavy?",
      body: "李龟年是开元盛世宫廷首席乐师，常在岐王李范、殿中监崔涤（崔九）府中演出；杜甫少年时在长安听过他。安史之乱（755—763）后，宫廷乐人流散江南，杜甫也漂泊西南，两人于潭州（今长沙）重逢，此时距开元盛世已过去四十余年。「落花时节」四个字，同时写季节、写两人迟暮、写大唐的由盛转衰——这是中国诗里密度最高的结尾之一。",
      bodyEn: "Li Guinian was the leading musician of the Kaiyuan golden age, performing at the houses of Prince Qi and Cui Di; the young Du Fu heard him in Chang'an. After the An Lushan rebellion (755–763) court musicians scattered south and Du Fu drifted south-west, until they met at Tanzhou (modern Changsha), more than forty years later. 「The season of falling blossoms」 is at once the time of year, the two men's old age, and the decline of the dynasty — one of the densest endings in Chinese poetry.",
    },
    note: "前两句写「常见」「几度闻」，后两句只写「又逢」——中间省去的四十年，才是全诗真正的内容。",
    noteEn: "The poem omits forty years between 「often saw you」 and 「meet you again」; that gap is the real subject.",
  },
  {
    slug: "yeshangshouxiangcheng",
    title: "夜上受降城闻笛",
    titleEn: "Hearing a Flute at Night on Shouxiang Wall",
    author: "李益",
    authorEn: "Li Yi",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "边塞",
    themeEn: "Frontier",
    level: 2,
    lines: [
      { zh: "回乐烽前沙似雪，受降城外月如霜。", en: "Before the beacon at Huile the sand is like snow; outside Shouxiang Wall the moonlight is like frost." },
      { zh: "不知何处吹芦管，一夜征人尽望乡。", en: "From somewhere a reed pipe is playing; all night the soldiers gaze toward home." },
    ],
    keywords: [
      { w: "beacon (n.)", zh: "烽火台" },
      { w: "reed pipe", zh: "芦管、芦笛" },
      { w: "gaze toward", zh: "遥望" },
      { w: "all night", zh: "整夜" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "沙为什么像雪、月光为什么像霜？",
      titleEn: "Why does sand look like snow, moonlight like frost?",
      body: "沙粒主要成分是石英，颜色浅、反射率高，在月光下呈冷白色，视觉上确实接近雪；而月光色温偏冷（约 4100K）且照度极低（满月约 0.1—0.3 勒克斯，仅及白天的十万分之一），人眼在暗光下主要靠视杆细胞工作，几乎不能分辨颜色，只能感知明暗——所以月夜的沙地就是一片没有颜色信息的冷白。两句写景，其实是两次精确的低照度视觉记录。",
      bodyEn: "Sand is mostly quartz: pale and highly reflective, cold-white under moonlight, genuinely snow-like. Moonlight is cool (about 4100 K) and extremely dim — full moon gives roughly 0.1–0.3 lux, a hundred-thousandth of daylight — so the eye runs on rod cells that cannot resolve colour, only brightness. The moonlit sand is therefore a colourless cold white. Both similes are precise records of low-light vision.",
    },
    note: "前两句极静，第三句一声笛，第四句全体思乡——声音是引爆点。英文用 From somewhere 保留了不见其人的效果。",
    noteEn: "Two still lines, then one flute, then everyone homesick: sound is the trigger.",
  },
  {
    slug: "qiuci",
    title: "秋词",
    titleEn: "On Autumn",
    author: "刘禹锡",
    authorEn: "Liu Yuxi",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "四季",
    themeEn: "Seasons",
    level: 2,
    lines: [
      { zh: "自古逢秋悲寂寥，我言秋日胜春朝。", en: "Since ancient times, meeting autumn has meant grieving at its desolation; I say an autumn day surpasses a spring morning." },
      { zh: "晴空一鹤排云上，便引诗情到碧霄。", en: "A single crane cleaves the clouds of the clear sky, and carries my poetic feeling up to the blue vault." },
    ],
    keywords: [
      { w: "desolation (n.)", zh: "寂寥、萧条" },
      { w: "surpass (v.)", zh: "胜过" },
      { w: "cleave (v.)", zh: "劈开、穿过" },
      { w: "vault (n.)", zh: "苍穹" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "鹤为什么会「排云上」？",
      titleEn: "Why does a crane climb through the clouds?",
      body: "鹤是大型涉禽，迁徙时利用热气流与上升气流滑翔，可飞到数千米高空——丹顶鹤等候鸟迁徙高度记录可达 5000 米以上。它们排队成「人」字形或「一」字形，利用前鸟翼尖产生的上升涡流节省体力（可减少约 20%—30% 能耗）。秋天正是南迁季节，刘禹锡看到的「一鹤排云上」，是一个有明确生物学含义的画面：它不悲伤，它在赶路。",
      bodyEn: "Cranes are large waders that migrate by soaring on thermals and rising air, reaching several thousand metres — records for cranes exceed 5,000 m. They fly in V or line formation to exploit the wing-tip vortices of the bird ahead, saving perhaps 20–30% of energy. Autumn is migration season, so the single crane cleaving the clouds is biologically exact: it is not mourning, it is travelling.",
    },
    note: "「我言」是对传统的正面反驳——英文用 I say 起句，语气同样硬气。",
    noteEn: "The poem begins by contradicting tradition: I say.",
  },
  {
    slug: "shiyiyuesifengyu",
    title: "十一月四日风雨大作",
    titleEn: "Great Wind and Rain on the Fourth of the Eleventh Month",
    author: "陆游",
    authorEn: "Lu You",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "初中",
    kind: "诗",
    theme: "家国",
    themeEn: "Nation",
    level: 2,
    lines: [
      { zh: "僵卧孤村不自哀，尚思为国戍轮台。", en: "Stiff, I lie in a lonely village and do not pity myself; still I think of guarding Luntai for the state." },
      { zh: "夜阑卧听风吹雨，铁马冰河入梦来。", en: "Late at night, lying, I listen to wind and rain; iron horses and frozen rivers come into my dream." },
    ],
    keywords: [
      { w: "stiff (adj.)", zh: "僵硬的（衰老）" },
      { w: "pity oneself", zh: "自怜" },
      { w: "guard (v.)", zh: "戍守" },
      { w: "late at night", zh: "夜深" },
    ],
    cross: {
      field: "气象",
      fieldEn: "Meteorology",
      title: "十一月的风雨为什么会「大作」？",
      titleEn: "Why does wind and rain rage in the eleventh month?",
      body: "农历十一月正值冬季风最强盛的时期：西伯利亚高压（蒙古高压）势力强大，冷空气频繁南下，与南方尚存的暖湿气流交绥，形成剧烈降温与雨雪——这就是寒潮。陆游在江南山阴（今绍兴）听到的风雨，正是寒潮过境时的天气。他把它听成了铁马冰河，不是浪漫，是执念：六十八岁的老人，梦里还在打仗。",
      bodyEn: "The eleventh lunar month is peak winter monsoon: the Siberian high is at its strongest and cold air surges south repeatedly, meeting lingering moist air and producing rapid cooling, wind and precipitation — a cold wave. What Lu You heard at Shanyin (modern Shaoxing) was exactly that. He heard in it armoured horses and frozen rivers not romantically but obsessively: at sixty-eight, he still fought in his sleep.",
    },
    note: "「不自哀」三个字是硬骨头；「入梦来」是唯一的软处——英文用 still 与 come into my dream 承接这份反差。",
    noteEn: "「Do not pity myself」 is defiance; the dream is the one soft spot.",
  },
  {
    slug: "tongguan",
    title: "潼关",
    titleEn: "Tong Pass",
    author: "谭嗣同",
    authorEn: "Tan Sitong",
    dynasty: "清",
    dynastyEn: "Qing",
    stage: "初中",
    kind: "诗",
    theme: "山水",
    themeEn: "Landscape",
    level: 2,
    lines: [
      { zh: "终古高云簇此城，秋风吹散马蹄声。", en: "From of old the high clouds cluster over this fortress; the autumn wind scatters the sound of horses' hooves." },
      { zh: "河流大野犹嫌束，山入潼关不解平。", en: "The river crossing the great plain still chafes at being hemmed in; the hills entering Tong Pass refuse to be level." },
    ],
    keywords: [
      { w: "cluster (v.)", zh: "簇拥、聚集" },
      { w: "scatter (v.)", zh: "吹散" },
      { w: "chafe at", zh: "因…而烦躁、不甘" },
      { w: "hem in", zh: "束缚、围困" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "潼关为什么是天下咽喉？",
      titleEn: "Why is Tong Pass the throat of the empire?",
      body: "潼关位于陕西、河南、山西三省交界，南依秦岭，北临黄河，中间仅有一条狭窄通道，是关中平原东出的唯一门户——历史上被称为「三秦锁钥」。黄河在此受秦岭阻挡急转向东（即黄河「几」字最后一折），形成天然屏障。谭嗣同写此诗时十四岁，两年后参与戊戌变法，1898 年就义；诗里「犹嫌束」「不解平」的桀骜，几乎是他人生的预告。",
      bodyEn: "Tong Pass sits where Shaanxi, Henan and Shanxi meet: the Qinling ranges south, the Yellow River north, and a single narrow corridor between — the only eastern gate out of the Guanzhong plain, traditionally called the lock of the three Qins. Here the Yellow River, blocked by the Qinling, turns sharply east (the last bend of its 「几」 shape), making a natural barrier. Tan Sitong was fourteen when he wrote this; he joined the 1898 reform and was executed for it. The unwillingness to be hemmed in reads like a preview of his life.",
    },
    note: "写山水实写少年心气——「犹嫌束」「不解平」两句，是清末最锋利的少年宣言。",
    noteEn: "Landscape as adolescent defiance: still chafes, refuses to be level.",
  },
  {
    slug: "yeyujibei",
    title: "夜雨寄北",
    titleEn: "Night Rain: To My Wife in the North",
    author: "李商隐",
    authorEn: "Li Shangyin",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "思乡",
    themeEn: "Homesickness",
    level: 2,
    lines: [
      { zh: "君问归期未有期，巴山夜雨涨秋池。", en: "You ask when I shall return — no date is set; night rain on the Bashan hills swells the autumn pool." },
      { zh: "何当共剪西窗烛，却话巴山夜雨时。", en: "When shall we together trim the candle at the west window, and speak of this night rain on Bashan?" },
    ],
    keywords: [
      { w: "no date is set", zh: "没有确定的日子" },
      { w: "swell (v.)", zh: "（雨）使涨满" },
      { w: "trim a candle", zh: "剪烛芯" },
      { w: "speak of", zh: "谈起" },
    ],
    cross: {
      field: "气象",
      fieldEn: "Meteorology",
      title: "巴山为什么多夜雨？",
      titleEn: "Why does it rain at night in the Bashan hills?",
      body: "四川盆地与周边山地是中国著名的夜雨区，夜雨率（夜间降水量占比）可达 60%—70%。成因是山谷风环流：夜间山坡冷却快，冷空气沿坡下沉，把谷底暖湿空气抬升，水汽凝结成雨；加上盆地地形封闭、水汽不易散失，云层在夜间增厚致雨。所以李商隐写「巴山夜雨」不是巧合，是当地气候的典型特征，成语「巴山夜雨」也由此而来。",
      bodyEn: "The Sichuan basin and its hills are China's classic night-rain zone: 60–70% of precipitation falls at night. The cause is mountain–valley circulation. At night the slopes cool quickly; cold air drains downslope and lifts the warm moist air in the valley, condensing it; the enclosed basin also traps moisture, so cloud thickens overnight. Li Shangyin's night rain is climatology, not coincidence.",
    },
    note: "全诗把「现在—未来—未来的回忆」三层时间折叠进 28 字——英文用 When shall we… and speak of 保留了这个时间回环。",
    noteEn: "Three time-layers folded into twenty-eight characters: now, then, then remembering now.",
  },
  {
    slug: "mulanshi",
    title: "木兰诗（节选）",
    titleEn: "The Ballad of Mulan (excerpt)",
    author: "北朝民歌",
    authorEn: "Northern Dynasties folk song",
    dynasty: "北朝",
    dynastyEn: "Northern Dynasties",
    stage: "初中",
    kind: "诗",
    theme: "人物",
    themeEn: "People",
    level: 2,
    lines: [
      { zh: "万里赴戎机，关山度若飞。", en: "Ten thousand li she goes to the machinery of war; she crosses passes and mountains as if flying." },
      { zh: "朔气传金柝，寒光照铁衣。", en: "Northern air carries the sound of the metal clapper; cold light shines on iron armour." },
      { zh: "雄兔脚扑朔，雌兔眼迷离；双兔傍地走，安能辨我是雄雌？", en: "A buck's feet kick and scatter, a doe's eyes are soft and dazed; but when two rabbits run side by side along the ground, how can you tell which is male and which is female?" },
    ],
    keywords: [
      { w: "machinery of war", zh: "战事、戎机" },
      { w: "clapper (n.)", zh: "（金）柝、打更器" },
      { w: "armour (n.)", zh: "铠甲" },
      { w: "tell", zh: "分辨（雄雌）" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "花木兰真的存在吗？",
      titleEn: "Did Mulan really exist?",
      body: "史书无确载，她最早见于北朝民歌《木兰辞》，一般认为是文学形象，可能融合了北魏时期北方民族（鲜卑）女子尚武的习俗。北魏实行府兵制，军户自备鞍马兵器，诗中「东市买骏马，西市买鞍鞯」正是自备装备的真实写照；「可汗大点兵」也符合鲜卑君主称可汗的史实。所以人物虽虚构，制度背景是可靠的。",
      bodyEn: "No historical record: she first appears in this Northern Dynasties ballad and is generally taken as a literary figure, perhaps blending the martial customs of Xianbei women under the Northern Wei. That state ran a militia system in which soldier households supplied their own horse and gear — exactly the poem's buying at the east and west markets — and its ruler bore the title khan, matching 「the khan is mustering a great army」. The character is fiction; the institutions behind her are not.",
    },
    note: "结尾「安能辨我是雄雌」是全诗的智取胜——不是争平等，是反问你们根本看不出来。",
    noteEn: "The closing question is a quiet triumph: not a claim of equality, but proof you could not tell.",
  },
  {
    slug: "zhuliguan",
    title: "竹里馆",
    titleEn: "Among the Bamboos",
    author: "王维",
    authorEn: "Wang Wei",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "山水",
    themeEn: "Landscape",
    level: 2,
    lines: [
      { zh: "独坐幽篁里，弹琴复长啸。", en: "Sitting alone in the deep bamboo, I play the lute and then give a long whistle." },
      { zh: "深林人不知，明月来相照。", en: "In the deep wood no one knows me; the bright moon comes and shines on me." },
    ],
    keywords: [
      { w: "deep bamboo", zh: "幽篁" },
      { w: "lute (n.)", zh: "琴" },
      { w: "whistle (v./n.)", zh: "长啸、吟咏" },
      { w: "shine on", zh: "照临" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "幽篁里为什么特别安静？",
      titleEn: "Why is deep bamboo so silent?",
      body: "竹林是天然的吸声体。竹竿中空、排列密集，声波进入后在管壁间多次反射并被孔隙吸收；竹叶表面粗糙多毛，也能散射高频声。实测研究表明成片竹林可降低噪声数分贝。王维在辋川（今陕西蓝田）的竹林里弹琴长啸，「人不知」其实是物理事实：声音出不去，外面确实听不见。",
      bodyEn: "Bamboo is a natural absorber. The hollow culms stand densely, so sound reflects repeatedly between them and is absorbed by pores; rough, hairy leaf surfaces scatter high frequencies. Measurements show mature bamboo stands cut noise by several decibels. Wang Wei played and whistled in the bamboo at Wangchuan (modern Lantian, Shaanxi); 「no one knows」 is literally true — the sound does not get out.",
    },
    note: "四句以「独坐」起、以「明月相照」结——孤独被月光补偿。英文用 comes and shines on me 保留月光的主动性。",
    noteEn: "Aloneness answered by moonlight: the moon comes and shines.",
  },
  {
    slug: "chunyeluocheng",
    title: "春夜洛城闻笛",
    titleEn: "Hearing a Flute on a Spring Night in Luoyang",
    author: "李白",
    authorEn: "Li Bai",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "思乡",
    themeEn: "Homesickness",
    level: 2,
    lines: [
      { zh: "谁家玉笛暗飞声，散入春风满洛城。", en: "From whose house does a jade flute send its hidden sound, scattering into the spring wind and filling Luoyang?" },
      { zh: "此夜曲中闻折柳，何人不起故园情。", en: "Tonight in this tune I hear 「Breaking the Willow」 — who could feel no longing for the old garden?" },
    ],
    keywords: [
      { w: "hidden sound", zh: "暗飞声（不知来处）" },
      { w: "scatter into", zh: "散入" },
      { w: "tune (n.)", zh: "曲调" },
      { w: "old garden", zh: "故园、家乡" },
    ],
    cross: {
      field: "音乐",
      fieldEn: "Music",
      title: "《折柳》是什么曲子？",
      titleEn: "What was the tune 「Breaking the Willow」?",
      body: "《折杨柳》是汉唐横吹曲的名曲，属乐府。古人送别有折柳相赠的习俗：柳与「留」谐音，折一枝柳条是希望对方留下；同时柳极易成活，寓意随遇而安。于是《折杨柳》成为专门的离别曲。李白在洛阳听到这首曲子，触动的是一整套文化联想——不是旋律本身好听，而是它自带含义。",
      bodyEn: "「Breaking the Willow」 was a famous hengchui piece in the Music Bureau repertoire. Parting custom held that one broke a willow spray as a gift: willow (柳) sounds like 「stay」 (留), so a spray asks the traveller to remain; willow also roots easily, suggesting he will settle wherever he lands. The tune therefore carried the meaning of farewell. Hearing it in Luoyang, Li Bai responded to a whole web of associations, not just a melody.",
    },
    note: "「散入春风满洛城」把声音写成可流动的物质——英文用 scattering into… filling 保留了声音的空间感。",
    noteEn: "Sound treated as something that can scatter and fill a city.",
  },
  {
    slug: "fengrujingshi",
    title: "逢入京使",
    titleEn: "Meeting an Envoy Bound for the Capital",
    author: "岑参",
    authorEn: "Cen Shen",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "思乡",
    themeEn: "Homesickness",
    level: 2,
    lines: [
      { zh: "故园东望路漫漫，双袖龙钟泪不干。", en: "Looking east toward the old garden, the road is endless; my two sleeves are soaked, my tears will not dry." },
      { zh: "马上相逢无纸笔，凭君传语报平安。", en: "We meet on horseback, with no paper or brush — I trust you to carry word and report that I am safe." },
    ],
    keywords: [
      { w: "endless (adj.)", zh: "漫长的" },
      { w: "soaked (adj.)", zh: "湿透的" },
      { w: "on horseback", zh: "在马上" },
      { w: "carry word", zh: "捎口信" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "这条路到底有多远？",
      titleEn: "How long was that road?",
      body: "岑参此行赴安西（今新疆库车一带）幕府，从长安出发经河西走廊、敦煌、西域北道，全程约 3500—4000 公里，骑马需数月。唐代在西域设安西、北庭两大都护府，驿传系统发达，但私人信件仍靠使者顺路捎带。「马上相逢无纸笔」正说明这种通讯条件：不是不想写，是写不了。",
      bodyEn: "Cen Shen was bound for Anxi, near modern Kuqa in Xinjiang: the route ran from Chang'an through the Hexi corridor, Dunhuang and the northern Tarim road, some 3,500–4,000 km and months of riding. The Tang maintained two protectorates in the west with an efficient post system, yet private letters still travelled with whoever happened to be going. 「No paper or brush on horseback」 records that constraint exactly: not unwillingness, but impossibility.",
    },
    note: "「报平安」三个字极重：万里之外，能说的只有平安。英文用 report that I am safe 保留了这份克制。",
    noteEn: "All he can send across thousands of miles is one word: safe.",
  },
  {
    slug: "wanchun",
    title: "晚春",
    titleEn: "Late Spring",
    author: "韩愈",
    authorEn: "Han Yu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "四季",
    themeEn: "Seasons",
    level: 2,
    lines: [
      { zh: "草树知春不久归，百般红紫斗芳菲。", en: "Grass and trees know that spring will not stay long; in every shade of red and purple they vie in fragrance and beauty." },
      { zh: "杨花榆荚无才思，惟解漫天作雪飞。", en: "Willow catkins and elm pods have no talent or thoughts — they only know how to fill the sky, flying like snow." },
    ],
    keywords: [
      { w: "vie (v.)", zh: "争相、竞争" },
      { w: "catkin (n.)", zh: "杨花（柳絮）" },
      { w: "elm pod", zh: "榆荚" },
      { w: "fill the sky", zh: "漫天" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "杨花榆荚为什么在春天飞？",
      titleEn: "Why do catkins and elm seeds fly in spring?",
      body: "它们不是花，是种子。柳絮是柳树的种子，外面附生白色绒毛（种缨），靠风传播；榆荚（榆钱）是榆树的翅果，果翅让它旋转下落，同样借风力扩散。植物把繁殖窗口精确安排在春末，此时气温回升、土壤湿润、风力较大，最利于种子远距离传播。韩愈说它们「无才思」，其实是替不能开花结果的树木抱不平——它们有另一种智慧。",
      bodyEn: "They are seeds, not flowers. Willow catkins are seeds wrapped in white hairs for wind dispersal; elm pods are winged samaras that spin as they fall, riding the same wind. Plants time release for late spring, when temperature rises, soil is moist and winds are strong — optimal for long-distance spread. Han Yu calls them talentless with a note of injustice: they have another kind of intelligence.",
    },
    note: "「惟解」是自谦也是褒奖——不会争艳，却能漫天飞雪。英文用 they only know how to 保留了这个低调的转折。",
    noteEn: "「They only know how」 — modest, yet it lets them fill the sky.",
  },
];
