import type { Poem } from "./types";

/** 初中阶段 · 第 4 批（文言文：语录、铭、说、记） */
export const JUNIOR_4: Poem[] = [
  {
    slug: "lunyu",
    title: "《论语》十二章（节选）",
    titleEn: "The Analects: Twelve Chapters (excerpts)",
    author: "孔子弟子及再传弟子",
    authorEn: "Disciples of Confucius",
    dynasty: "先秦",
    dynastyEn: "Pre-Qin",
    stage: "初中",
    kind: "文言文",
    theme: "修身",
    themeEn: "Self-cultivation",
    level: 2,
    lines: [
      { zh: "学而时习之，不亦说乎？有朋自远方来，不亦乐乎？人不知而不愠，不亦君子乎？", en: "To learn and then put it into practice in due season — is that not a pleasure? To have a friend come from afar — is that not a joy? To be unknown to others yet not resentful — is that not a gentleman?" },
      { zh: "温故而知新，可以为师矣。", en: "Review the old and thereby know the new — such a one may be a teacher." },
      { zh: "学而不思则罔，思而不学则殆。", en: "Learning without thinking leads to confusion; thinking without learning leads to peril." },
      { zh: "三人行，必有我师焉。择其善者而从之，其不善者而改之。", en: "Where three walk together, there must be one who can teach me: I choose the good in them and follow it, and the bad in them and correct it in myself." },
      { zh: "逝者如斯夫，不舍昼夜。", en: "What passes is like this — never ceasing, day or night." },
    ],
    fullText: "子曰：「学而时习之，不亦说乎？有朋自远方来，不亦乐乎？人不知而不愠，不亦君子乎？」\n子曰：「温故而知新，可以为师矣。」\n子曰：「学而不思则罔，思而不学则殆。」\n子曰：「三人行，必有我师焉。择其善者而从之，其不善者而改之。」\n子在川上曰：「逝者如斯夫，不舍昼夜。」\n子曰：「三军可夺帅也，匹夫不可夺志也。」\n子夏曰：「博学而笃志，切问而近思，仁在其中矣。」",
    keywords: [
      { w: "in due season", zh: "按时（时习）" },
      { w: "resentful (adj.)", zh: "怨恨的" },
      { w: "confusion (n.)", zh: "迷惘（罔）" },
      { w: "peril (n.)", zh: "危险、疲殆" },
    ],
    cross: {
      field: "哲学",
      fieldEn: "Philosophy",
      title: "「学而不思则罔」为什么是认识论？",
      titleEn: "Why is this a theory of knowledge?",
      body: "这句话给出了一组对称的错误：只有输入（学）没有加工（思），信息无法整合，结果是「罔」（迷惘无所得）；只有加工没有新输入，思维失去材料支持，结果是「殆」（疲惫而危险）。用今天的话说：前者是死记硬背，后者是空想。认知科学同样认为记忆与理解是两条不同的加工路径，只有在二者交互时才形成可用的知识。",
      bodyEn: "The saying pairs two symmetrical failures. Input without processing leaves information unintegrated — 「confusion」; processing without fresh input leaves thought without material — 「peril」. In modern terms, rote learning versus empty speculation. Cognitive science agrees that memorising and comprehending are distinct processes, and usable knowledge arises only where they interact.",
    },
    note: "英译难点在「说」（悦）、「愠」等情感词——英文用 pleasure / resentful 区分了不同层次。",
    noteEn: "The hard part is the vocabulary of feeling: pleasure, joy, and the absence of resentment.",
  },
  {
    slug: "loushiming",
    title: "陋室铭",
    titleEn: "Inscription on a Humble Room",
    author: "刘禹锡",
    authorEn: "Liu Yuxi",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "文言文",
    theme: "修身",
    themeEn: "Self-cultivation",
    level: 2,
    lines: [
      { zh: "山不在高，有仙则名。水不在深，有龙则灵。", en: "A mountain need not be high — if an immortal dwells there it becomes famous. Water need not be deep — if a dragon is in it, it becomes numinous." },
      { zh: "斯是陋室，惟吾德馨。", en: "This is a humble room, yet my virtue makes it fragrant." },
      { zh: "苔痕上阶绿，草色入帘青。谈笑有鸿儒，往来无白丁。", en: "Moss climbs the steps in green; the grass's colour enters the blind, blue. In talk and laughter there are great scholars; among those who come and go, no common men." },
      { zh: "孔子云：何陋之有？", en: "Confucius said: what is humble about it?" },
    ],
    fullText: "山不在高，有仙则名。水不在深，有龙则灵。斯是陋室，惟吾德馨。苔痕上阶绿，草色入帘青。谈笑有鸿儒，往来无白丁。可以调素琴，阅金经。无丝竹之乱耳，无案牍之劳形。南阳诸葛庐，西蜀子云亭。孔子云：何陋之有？",
    keywords: [
      { w: "numinous (adj.)", zh: "灵验的、有灵性" },
      { w: "virtue (n.)", zh: "品德（德）" },
      { w: "blind (n.)", zh: "帘子" },
      { w: "common men", zh: "平民（往来无白丁）" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "为什么他要写「陋室」？",
      titleEn: "Why write about a humble room?",
      body: "刘禹锡参与永贞革新失败后被贬朗州，历任远州司马十余年；据载他在和州（今安徽和县）时，知县故意三次缩小他的住房，最后只给一间半屋，他于是写下这篇铭文刻在门前的石上。铭是铸刻在器物上用于自警或称扬的文体，句式多四字、押韵。「南阳诸葛庐，西蜀子云亭」是以诸葛亮与扬雄的故居自比——房子是小的，参照系是大的。",
      bodyEn: "After the failed Yongzhen reform Liu Yuxi was exiled for over a decade to remote posts. At Hezhou (modern Hexian, Anhui), the magistrate is said to have shrunk his lodgings three times until one small room remained, whereupon he wrote this inscription and had it cut in stone by his gate. A ming was engraved on objects to admonish or praise, in rhymed four-character lines. Comparing his hut to Zhuge Liang's cottage and Yang Xiong's pavilion: small house, large frame of reference.",
    },
    note: "全文的核心是「惟吾德馨」——英文用 yet my virtue makes it fragrant 保留了「馨」（香气）这个通感。",
    noteEn: "The pivot is 「my virtue makes it fragrant」 — virtue rendered as scent.",
  },
  {
    slug: "ailianshuo",
    title: "爱莲说",
    titleEn: "On the Love of the Lotus",
    author: "周敦颐",
    authorEn: "Zhou Dunyi",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "初中",
    kind: "文言文",
    theme: "咏物",
    themeEn: "Nature",
    level: 2,
    lines: [
      { zh: "予独爱莲之出淤泥而不染，濯清涟而不妖。", en: "I alone love the lotus: it rises out of mud yet is not stained; it is washed by clear ripples yet is not flirtatious." },
      { zh: "中通外直，不蔓不枝，香远益清，亭亭净植。", en: "Hollow within, straight without; no creeping vines, no spreading branches. Its fragrance carries far and grows purer; it stands upright, clean and self-possessed." },
      { zh: "莲，花之君子者也。", en: "The lotus is the gentleman among flowers." },
    ],
    fullText: "水陆草木之花，可爱者甚蕃。晋陶渊明独爱菊；自李唐来，世人甚爱牡丹；予独爱莲之出淤泥而不染，濯清涟而不妖，中通外直，不蔓不枝，香远益清，亭亭净植，可远观而不可亵玩焉。予谓菊，花之隐逸者也；牡丹，花之富贵者也；莲，花之君子者也。",
    keywords: [
      { w: "stained (adj.)", zh: "被污染的" },
      { w: "hollow (adj.)", zh: "中空的（中通）" },
      { w: "self-possessed (adj.)", zh: "（亭亭）挺立自持" },
      { w: "flirtatious", zh: "轻慢（不可亵玩）" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "莲花真的出淤泥而不染吗？",
      titleEn: "Is the lotus really unstained by mud?",
      body: "确实，而且有机制。莲叶与花瓣表面布满微米级乳突并覆盖蜡质（疏水），水滴接触角大于 150°，滚动时带走污物，即「荷叶效应」。此外莲的根状茎（藕）虽生于淤泥，但内部有发达的通气组织（孔道），能把空气输送到水下部分，保证有氧呼吸——所以它能在缺氧的淤泥里生长而不腐烂。周敦颐写的是物理事实，借以说人格。",
      bodyEn: "Yes, and for a reason. Lotus leaves and petals carry microscopic wax-coated bumps, giving contact angles above 150°, so water rolls off carrying dirt with it — the lotus effect. The rhizome growing in anoxic mud has extensive air channels that pipe oxygen to submerged parts, sustaining aerobic respiration. Zhou Dunyi took a genuine physical fact and made it a moral one.",
    },
    note: "「出淤泥而不染」已成成语——英文用 rises out of mud yet is not stained 保留了转折。",
    noteEn: "An idiom in Chinese: out of the mud, yet unstained.",
  },
  {
    slug: "sanxia",
    title: "三峡",
    titleEn: "The Three Gorges",
    author: "郦道元",
    authorEn: "Li Daoyuan",
    dynasty: "北魏",
    dynastyEn: "Northern Wei",
    stage: "初中",
    kind: "文言文",
    theme: "山水",
    themeEn: "Landscape",
    level: 2,
    lines: [
      { zh: "自三峡七百里中，两岸连山，略无阙处。", en: "Within the seven hundred li of the Three Gorges, hills line both banks with hardly a break." },
      { zh: "重岩叠嶂，隐天蔽日，自非亭午夜分，不见曦月。", en: "Cliff upon cliff, screen upon screen, they hide the sky and shut out the sun; unless it is noon or midnight, you cannot see sun or moon." },
      { zh: "常有高猿长啸，属引凄异，空谷传响，哀转久绝。", en: "Often the high apes give long cries, drawn out and strangely mournful; the empty valley carries the echo, the sad notes fading only after a long while." },
    ],
    fullText: "自三峡七百里中，两岸连山，略无阙处。重岩叠嶂，隐天蔽日，自非亭午夜分，不见曦月。至于夏水襄陵，沿溯阻绝……春冬之时，则素湍绿潭，回清倒影……每至晴初霜旦，林寒涧肃，常有高猿长啸，属引凄异，空谷传响，哀转久绝。故渔者歌曰：「巴东三峡巫峡长，猿鸣三声泪沾裳。」",
    keywords: [
      { w: "gorge (n.)", zh: "峡" },
      { w: "cliff (n.)", zh: "岩壁" },
      { w: "drawn out", zh: "（声）延长、属引" },
      { w: "echo (n.)", zh: "回响" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "三峡是怎么形成的？",
      titleEn: "How were the Three Gorges formed?",
      body: "长江三峡（瞿塘峡、巫峡、西陵峡）是典型的河流下切峡谷：长江切穿巫山山脉，地壳阶段性抬升与江水持续下切共同作用，形成长达 200 余公里、谷深数百米的峡谷。郦道元《水经注》的记载来自前人的描述而非亲历（他未到过南方），但「隐天蔽日」「不见曦月」完全符合峡谷地形——谷坡陡峭、视角受限，正午之外确实少见天日。",
      bodyEn: "Qutang, Wu and Xiling gorges are classic river-incised canyons: the Yangtze cut through the Wushan ranges as the crust rose in stages while the river incised downward, producing over 200 km of gorge hundreds of metres deep. Li Daoyuan compiled the Commentary on the Water Classic from earlier accounts — he never travelled south — yet 「hiding sky and sun」 matches the terrain: steep walls narrow the sky, and outside midday the sun and moon are genuinely invisible.",
    },
    note: "「隐天蔽日」是峡谷的视觉实录——英文用 hide the sky and shut out the sun 保留了夸张中的真实。",
    noteEn: "Exaggeration grounded in fact: a gorge really does hide the sky.",
  },
  {
    slug: "daxiezhongshushu",
    title: "答谢中书书",
    titleEn: "Reply to Xie Zhongshu",
    author: "陶弘景",
    authorEn: "Tao Hongjing",
    dynasty: "南朝梁",
    dynastyEn: "Liang",
    stage: "初中",
    kind: "文言文",
    theme: "山水",
    themeEn: "Landscape",
    level: 2,
    lines: [
      { zh: "山川之美，古来共谈。高峰入云，清流见底。", en: "The beauty of mountains and rivers has been everyone's subject since ancient times. High peaks enter the clouds; clear streams show their beds." },
      { zh: "两岸石壁，五色交辉。青林翠竹，四时俱备。", en: "The stone walls of both banks gleam in five colours; green woods and emerald bamboo are present in every season." },
      { zh: "晓雾将歇，猿鸟乱鸣；夕日欲颓，沉鳞竞跃。", en: "At dawn the mist is about to lift, and apes and birds cry in confusion; as the evening sun begins to sink, the submerged fish leap in rivalry." },
    ],
    fullText: "山川之美，古来共谈。高峰入云，清流见底。两岸石壁，五色交辉。青林翠竹，四时俱备。晓雾将歇，猿鸟乱鸣；夕日欲颓，沉鳞竞跃。实是欲界之仙都。自康乐以来，未复有能与其奇者。",
    keywords: [
      { w: "stream bed", zh: "（水）底" },
      { w: "gleam (v.)", zh: "交相辉映" },
      { w: "lift (of mist)", zh: "（雾）消散" },
      { w: "submerged (fish)", zh: "（沉）鳞、水中之鱼" },
    ],
    cross: {
      field: "化学",
      fieldEn: "Chemistry",
      title: "石壁为什么会「五色交辉」？",
      titleEn: "Why do the cliffs gleam in five colours?",
      body: "岩石的颜色来自矿物成分：含铁氧化物呈红褐黄（赤铁矿红、褐铁矿黄褐），含铜矿物呈绿蓝，含锰呈黑紫，纯净石英与方解石则近白。加上岩层表面常有地衣、藻类与苔藓（分别呈灰绿、深绿、黄绿），以及不同风化程度造成的光泽差异——阳光照射角度变化时，颜色确实会「交辉」。陶弘景是药物学家，对矿物相当熟悉。",
      bodyEn: "Rock colour comes from minerals: iron oxides give red, brown and yellow (hematite red, limonite yellow-brown), copper minerals green and blue, manganese black-purple, while pure quartz and calcite are near white. Add lichens, algae and mosses — grey-green, deep green, yellow-green — plus varying weathering gloss, and the colours genuinely shift as the light moves. Tao Hongjing was a pharmacologist, well acquainted with minerals.",
    },
    note: "全文只有 68 字，却是一幅完整的山水长卷——英文用四组对偶（peaks/streams, cliffs/woods, mist/sun）保留骈文节奏。",
    noteEn: "Sixty-eight characters; the English keeps the parallel pairs of the original.",
  },
  {
    slug: "jichengtiansi",
    title: "记承天寺夜游",
    titleEn: "A Night Visit to Chengtian Temple",
    author: "苏轼",
    authorEn: "Su Shi",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "初中",
    kind: "文言文",
    theme: "人生",
    themeEn: "Life",
    level: 2,
    lines: [
      { zh: "元丰六年十月十二日夜，解衣欲睡，月色入户，欣然起行。", en: "On the night of the twelfth of the tenth month in the sixth year of Yuanfeng, I undressed and was about to sleep, when moonlight entered the door; delighted, I got up and went out." },
      { zh: "庭下如积水空明，水中藻、荇交横，盖竹柏影也。", en: "The courtyard below was like a pool of standing water, clear and bright, with algae and water-mallows crossing it — but they were only the shadows of bamboo and cypress." },
      { zh: "何夜无月？何处无竹柏？但少闲人如吾两人者耳。", en: "What night has no moon? What place has no bamboo and cypress? There are only too few idle men such as we two." },
    ],
    fullText: "元丰六年十月十二日夜，解衣欲睡，月色入户，欣然起行。念无与为乐者，遂至承天寺寻张怀民。怀民亦未寝，相与步于中庭。庭下如积水空明，水中藻、荇交横，盖竹柏影也。何夜无月？何处无竹柏？但少闲人如吾两人者耳。",
    keywords: [
      { w: "undress (v.)", zh: "解衣" },
      { w: "delighted (adv.)", zh: "欣然" },
      { w: "standing water", zh: "积水" },
      { w: "idle men", zh: "闲人（清闲之人）" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "月光下的院子为什么像积水？",
      titleEn: "Why does the courtyard look like standing water?",
      body: "月光下竹柏的影子落在地面上，轮廓柔和、明暗对比低；而月光照亮的地面呈均匀的冷白色，边缘模糊——两者叠加后，人眼难以判断深度与材质，容易把「亮的一片」误读为水面。这在视觉科学上属于低照度下深度线索缺失（阴影、纹理、运动视差都不可用）。苏轼顺手记下了一次真实的视觉误判，还补了一句「盖竹柏影也」——科学态度。",
      bodyEn: "Under moonlight the shadows of bamboo and cypress fall soft-edged and low in contrast, while the lit ground is a uniform cold white with blurred boundaries; the eye, deprived of depth cues — sharp shadow, texture, motion parallax — can read the bright patch as water. Su Shi records a genuine perceptual misjudgement and then corrects himself: they were only shadows. A scientist's reflex.",
    },
    note: "「闲人」二字最苦：被贬黄州、无事可做，才看得见月色。英文用 idle men 保留了自嘲。",
    noteEn: "「Idle men」 is self-mockery: exiled to Huangzhou with nothing to do, which is why he could see the moon.",
  },
  {
    slug: "yuzhuyuansishu",
    title: "与朱元思书",
    titleEn: "Letter to Zhu Yuansi",
    author: "吴均",
    authorEn: "Wu Jun",
    dynasty: "南朝梁",
    dynastyEn: "Liang",
    stage: "初中",
    kind: "文言文",
    theme: "山水",
    themeEn: "Landscape",
    level: 2,
    lines: [
      { zh: "风烟俱净，天山共色。从流飘荡，任意东西。", en: "Wind and mist are all cleared away; sky and hills share one colour. I drift along with the current, east or west as I please." },
      { zh: "急湍甚箭，猛浪若奔。", en: "The swift rapids outrun an arrow; the fierce waves are like galloping horses." },
      { zh: "鸢飞戾天者，望峰息心；经纶世务者，窥谷忘反。", en: "Those who would soar to the sky like falcons, seeing these peaks, still their ambitions; those busy with worldly affairs, looking into this valley, forget the way back." },
    ],
    fullText: "风烟俱净，天山共色。从流飘荡，任意东西。自富阳至桐庐一百许里，奇山异水，天下独绝。水皆缥碧，千丈见底。游鱼细石，直视无碍。急湍甚箭，猛浪若奔。夹岸高山，皆生寒树，负势竞上，互相轩邈，争高直指，千百成峰。泉水激石，泠泠作响；好鸟相鸣，嘤嘤成韵。蝉则千转不穷，猿则百叫无绝。鸢飞戾天者，望峰息心；经纶世务者，窥谷忘反。",
    keywords: [
      { w: "rapids (n.)", zh: "急湍" },
      { w: "outrun (v.)", zh: "快过（甚箭）" },
      { w: "soar (v.)", zh: "（鸢）高飞" },
      { w: "forget the way back", zh: "忘反（流连忘返）" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "急湍为什么比箭还快？",
      titleEn: "Why do rapids outrun an arrow?",
      body: "富春江桐庐段落差集中，水流受峡谷约束后断面变窄，按连续性方程（流量 = 断面面积 × 流速），断面缩小则流速增大；实测山溪性河流的急流段流速可达 3—5 米/秒，与古代步射箭的初速（约 40—60 米/秒）相比仍慢得多——所以「甚箭」是文学夸张。但作者真正准确的观察在别处：水色「缥碧」「千丈见底」反映的是低含沙量的清澈山溪，这与当地石灰岩与植被良好的流域是一致的。",
      bodyEn: "The Fuchun river drops steeply at Tonglu; confined by gorges, its cross-section narrows and by continuity (discharge = area × velocity) the water speeds up. Torrent reaches may hit 3–5 m/s — fast, though still far below an arrow's 40–60 m/s, so 「outruns an arrow」 is hyperbole. The accurate observation lies elsewhere: the pale blue, seemingly bottomless water reflects a mountain stream with very low sediment, consistent with the karst and well-wooded catchment.",
    },
    note: "全文以「奇山异水，天下独绝」立骨，最后落到「望峰息心」——英文用 still their ambitions 保留了由景入理的转折。",
    noteEn: "Landscape opening, philosophical close: peaks still ambition.",
  },
  {
    slug: "shengyuyouhuan",
    title: "生于忧患，死于安乐",
    titleEn: "Life from Adversity, Death from Ease",
    author: "《孟子》",
    authorEn: "Mencius",
    dynasty: "先秦",
    dynastyEn: "Pre-Qin",
    stage: "初中",
    kind: "文言文",
    theme: "修身",
    themeEn: "Self-cultivation",
    level: 2,
    lines: [
      { zh: "故天将降大任于是人也，必先苦其心志，劳其筋骨，饿其体肤，空乏其身。", en: "Thus, when heaven is about to lay a great charge upon a man, it first embitters his mind and will, toils his sinews and bones, starves his flesh, and empties his body." },
      { zh: "行拂乱其所为，所以动心忍性，曾益其所不能。", en: "It confounds what he does — thereby stirring his heart and hardening his nature, and adding to what he could not do." },
      { zh: "然后知生于忧患而死于安乐也。", en: "From this we know that life comes out of adversity, and death out of ease." },
    ],
    fullText: "舜发于畎亩之中，傅说举于版筑之间，胶鬲举于鱼盐之中，管夷吾举于士，孙叔敖举于海，百里奚举于市。故天将降大任于是人也，必先苦其心志，劳其筋骨，饿其体肤，空乏其身，行拂乱其所为，所以动心忍性，曾益其所不能。人恒过，然后能改；困于心，衡于虑，而后作；征于色，发于声，而后喻。入则无法家拂士，出则无敌国外患者，国恒亡。然后知生于忧患而死于安乐也。",
    keywords: [
      { w: "embitter (v.)", zh: "使…痛苦（苦其心志）" },
      { w: "toil (v.)", zh: "使…劳累" },
      { w: "harden (v.)", zh: "使…坚韧（忍性）" },
      { w: "adversity (n.)", zh: "忧患" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "「生于忧患」有科学依据吗？",
      titleEn: "Is there science behind 「life from adversity」?",
      body: "有一定吻合。适度压力能激发适应性反应，生物学上叫「应激强化」（hormesis）：运动造成的肌肉微损伤促使肌纤维增粗，禁食与低温等轻度胁迫可激活细胞自噬与抗氧化防御。关键在剂量——适度有益，过度有害，慢性重压反而损害免疫与记忆（海马体积缩小）。孟子说的「困于心，衡于虑，而后作」，描述的正是适度的压力促使人反思奋起。",
      bodyEn: "Partly, yes. Moderate stress provokes adaptive responses — biologists call it hormesis: the micro-damage of exercise thickens muscle fibres; mild fasting or cold activates autophagy and antioxidant defences. Dose matters: moderate helps, chronic severe stress harms immunity and memory (shrinking the hippocampus). Mencius's 「troubled in heart, weighed in thought, and then roused」 describes moderate stress prompting reflection and action.",
    },
    note: "开头连举六个人的例子（舜、傅说、胶鬲、管仲、孙叔敖、百里奚）——这是孟子最典型的归纳论证。",
    noteEn: "Six examples, then the generalisation: Mencius's classic inductive move.",
  },
  {
    slug: "yugongyishan",
    title: "愚公移山",
    titleEn: "The Foolish Old Man Removes the Mountains",
    author: "《列子》",
    authorEn: "Liezi",
    dynasty: "先秦",
    dynastyEn: "Pre-Qin",
    stage: "初中",
    kind: "文言文",
    theme: "寓言",
    themeEn: "Fable",
    level: 2,
    lines: [
      { zh: "吾与汝毕力平险，指通豫南，达于汉阴。", en: "You and I shall level the heights with all our strength, opening a way to the south of Yu and reaching the north of the Han." },
      { zh: "虽我之死，有子存焉……子子孙孙无穷匮也，而山不加增，何苦而不平？", en: "Though I die, my son remains… sons and grandsons without end, while the mountains grow no higher — why then should they not be levelled?" },
      { zh: "帝感其诚，命夸娥氏二子负二山。", en: "The god, moved by his sincerity, commanded the two sons of Kua'e to carry the mountains away." },
    ],
    fullText: "北山愚公者，年且九十，面山而居。惩山北之塞，出入之迂也……遂率子孙荷担者三夫，叩石垦壤，箕畚运于渤海之尾。邻人京城氏之孀妻有遗男，始龀，跳往助之。寒暑易节，始一反焉。河曲智叟笑而止之曰：「甚矣，汝之不惠！以残年余力，曾不能毁山之一毛，其如土石何？」北山愚公长息曰：「汝心之固，固不可彻，曾不若孀妻弱子。虽我之死，有子存焉；子又生孙，孙又生子；子子孙孙无穷匮也，而山不加增，何苦而不平？」河曲智叟亡以应……帝感其诚，命夸娥氏二子负二山，一厝朔东，一厝雍南。",
    keywords: [
      { w: "level (v.)", zh: "铲平（平险）" },
      { w: "without end", zh: "无穷匮" },
      { w: "sincerity (n.)", zh: "诚心（其诚）" },
      { w: "grandsons", zh: "孙子（子子孙孙）" },
    ],
    cross: {
      field: "数学",
      fieldEn: "Mathematics",
      title: "愚公的算法真的成立吗？",
      titleEn: "Does the Foolish Old Man's algorithm work?",
      body: "这是一次著名的极限论证。设每代搬运量为 q，山体总量为 V，愚公的论点是：lim(n→∞) n·q = ∞ > V，即有限的山体除以无限的时间必然归零。前提有漏洞（人口并非无限增长、山体也因风化而增加），但推理形式是成立的，而且它是中国古代少见的「无穷」概念运用。智叟看的是当前的算力，愚公看的是时间尺度——这是短视与远见的差别。",
      bodyEn: "A famous limiting argument. With q removed per generation and total volume V, his claim is that lim(n→∞) n·q = ∞ > V: a finite mountain divided by unbounded time goes to zero. The premises are shaky (population does not grow without limit, and weathering adds material), but the form of the argument holds, and it is a rare ancient Chinese use of infinity. The wise old man counts present capacity; the foolish one counts time.",
    },
    note: "「愚」与「智」的名字是反讽——愚公看得远，智叟只会算眼前账。",
    noteEn: "The names are ironic: the foolish one sees far, the wise one counts today.",
  },
  {
    slug: "taohuayuanji",
    title: "桃花源记（节选）",
    titleEn: "Peach Blossom Spring (excerpt)",
    author: "陶渊明",
    authorEn: "Tao Yuanming",
    dynasty: "东晋",
    dynastyEn: "Eastern Jin",
    stage: "初中",
    kind: "文言文",
    theme: "理想",
    themeEn: "Utopia",
    level: 2,
    lines: [
      { zh: "晋太元中，武陵人捕鱼为业。缘溪行，忘路之远近。", en: "In the Taiyuan era of Jin, a man of Wuling made his living by fishing. Following the stream, he forgot how far he had gone." },
      { zh: "土地平旷，屋舍俨然，有良田、美池、桑竹之属。阡陌交通，鸡犬相闻。", en: "The land was level and open, the houses orderly; there were good fields, fair ponds, mulberry and bamboo. Paths crossed one another; cocks and dogs could be heard from house to house." },
      { zh: "问今是何世，乃不知有汉，无论魏晋。", en: "They asked what age it now was — and they had never heard of the Han, let alone the Wei or the Jin." },
      { zh: "太守即遣人随其往，寻向所志，遂迷，不复得路。", en: "The governor at once sent men to go with him, looking for the marks he had made; but they lost their way and never found the road again." },
    ],
    fullText: "晋太元中，武陵人捕鱼为业。缘溪行，忘路之远近。忽逢桃花林，夹岸数百步，中无杂树，芳草鲜美，落英缤纷……林尽水源，便得一山，山有小口，仿佛若有光。便舍船，从口入。初极狭，才通人。复行数十步，豁然开朗。土地平旷，屋舍俨然，有良田、美池、桑竹之属。阡陌交通，鸡犬相闻。其中往来种作，男女衣着，悉如外人。黄发垂髫，并怡然自乐……自云先世避秦时乱，率妻子邑人来此绝境，不复出焉，遂与外人间隔。问今是何世，乃不知有汉，无论魏晋。",
    keywords: [
      { w: "make one's living", zh: "以…为业" },
      { w: "level and open", zh: "平旷" },
      { w: "let alone", zh: "更不用说（无论）" },
      { w: "lose one's way", zh: "迷路" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "「不知有汉，无论魏晋」意味着什么？",
      titleEn: "What does 「never heard of the Han」 mean?",
      body: "秦末（约公元前 206 年）到东晋太元年间（376—396）相隔约六百年，也就是说这批人为避秦乱在此与世隔绝了近六个世纪。这在人口学上近似「创始人效应」的小种群模型：少量迁入者封闭繁衍，形成独立的社会记忆。陶渊明写的不只是仙境想象，而是对现实战乱的回应——东晋末年战祸频仍、赋役沉重，「避秦时乱」四个字同时指秦与当下。",
      bodyEn: "From the fall of Qin (c. 206 BC) to the Taiyuan era (376–396 CE) is some six centuries: a community cut off since the Qin troubles, isolated for around six hundred years. Demographically this resembles a founder-effect model — a small founding group breeding in isolation and developing its own social memory. The tale is not mere fantasy but an answer to Tao Yuanming's own age of war and heavy taxation; 「fleeing the Qin troubles」 points at once to Qin and to the present.",
    },
    note: "结尾「不复得路」是关键：桃花源只能是偶然遇见，不能刻意找到——英文用 never found the road again 保留了这层。",
    noteEn: "The ending matters: it can only be stumbled upon, never found.",
  },
];
