import type { Poem } from "./types";

/** 初中阶段 · 第 5 批（文言文：游记、论说、表、序） */
export const JUNIOR_5: Poem[] = [
  {
    slug: "xiaoshitanji",
    title: "小石潭记（节选）",
    titleEn: "The Little Stone Pool (excerpt)",
    author: "柳宗元",
    authorEn: "Liu Zongyuan",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "文言文",
    theme: "山水",
    themeEn: "Landscape",
    level: 2,
    lines: [
      { zh: "隔篁竹，闻水声，如鸣珮环，心乐之。", en: "Beyond a screen of bamboo I heard the sound of water, like the chiming of jade pendants, and my heart was gladdened." },
      { zh: "潭中鱼可百许头，皆若空游无所依。", en: "In the pool there are some hundred fish, all seeming to swim in emptiness, with nothing to support them." },
      { zh: "日光下澈，影布石上，佁然不动；俶尔远逝，往来翕忽。", en: "Sunlight strikes down through the water, and their shadows spread on the stones, utterly still; then suddenly they dart far away, coming and going with swift flickers." },
      { zh: "凄神寒骨，悄怆幽邃。", en: "It chills the spirit and the bones, silent, sorrowful, deep and far." },
    ],
    fullText: "从小丘西行百二十步，隔篁竹，闻水声，如鸣珮环，心乐之。伐竹取道，下见小潭，水尤清冽。全石以为底，近岸，卷石底以出，为坻，为屿，为嵁，为岩。青树翠蔓，蒙络摇缀，参差披拂。潭中鱼可百许头，皆若空游无所依，日光下澈，影布石上。佁然不动，俶尔远逝，往来翕忽，似与游者相乐。潭西南而望，斗折蛇行，明灭可见。其岸势犬牙差互，不可知其源。坐潭上，四面竹树环合，寂寥无人，凄神寒骨，悄怆幽邃。",
    keywords: [
      { w: "jade pendant", zh: "珮环（玉饰）" },
      { w: "chills", zh: "寒、凉（水尤清冽）" },
      { w: "dart (v.)", zh: "（鱼）忽然游远" },
      { w: "sorrowful", zh: "忧伤（悄怆）" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "鱼为什么像「空游无所依」？",
      titleEn: "Why do the fish seem to swim in emptiness?",
      body: "因为水的折射率（约 1.33）与空气不同，且水面平静时几乎不反光，观察者看到的鱼其实是它的虚像，位置比实物略浅；再加上水极清澈、悬浮颗粒少，光线散射弱，人眼看不到「水」本身，只看到鱼和石上的影子——于是鱼就像悬在空中。柳宗元同时记下了「影布石上」，说明光线足够直入水底，这与水清、潭浅、日光角度有关。",
      bodyEn: "Water's refractive index (~1.33) differs from air, and a still surface barely reflects, so what you see is a virtual image slightly shallower than the real fish. With very clear water and few suspended particles there is little scattering — the eye sees no water, only fish and their shadows on the stone, so the fish appear to hang in air. Liu Zongyuan also notes the shadows cast on the stones, implying light reaching the bottom: clear, shallow water and a favourable sun angle.",
    },
    note: "全文由乐转悲——「心乐之」开头，「悄怆幽邃」结尾，景物没变，视角变了。英文用 gladdened 与 chills 对应。",
    noteEn: "Joy at the start, chill at the end — the scene is unchanged; the viewer is not.",
  },
  {
    slug: "yueyanglouji",
    title: "岳阳楼记（节选）",
    titleEn: "On Yueyang Tower (excerpt)",
    author: "范仲淹",
    authorEn: "Fan Zhongyan",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "初中",
    kind: "文言文",
    theme: "理想",
    themeEn: "Ideals",
    level: 2,
    lines: [
      { zh: "衔远山，吞长江，浩浩汤汤，横无际涯。", en: "It holds the distant hills in its mouth and swallows the Yangtze — vast, rolling on, spreading without bound or shore." },
      { zh: "不以物喜，不以己悲。", en: "Not made glad by outward things, not made sorrowful by one's own lot." },
      { zh: "先天下之忧而忧，后天下之乐而乐。", en: "To worry before all under heaven worries, and to rejoice only after all under heaven rejoices." },
    ],
    fullText: "予观夫巴陵胜状，在洞庭一湖。衔远山，吞长江，浩浩汤汤，横无际涯，朝晖夕阴，气象万千，此则岳阳楼之大观也……予尝求古仁人之心，或异二者之为，何哉？不以物喜，不以己悲；居庙堂之高则忧其民，处江湖之远则忧其君。是进亦忧，退亦忧。然则何时而乐耶？其必曰「先天下之忧而忧，后天下之乐而乐」乎！",
    keywords: [
      { w: "swallow (v.)", zh: "吞（长江）" },
      { w: "without bound or shore", zh: "无边无际" },
      { w: "outward things", zh: "外物（境遇）" },
      { w: "under heaven", zh: "天下" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "洞庭湖为什么能「吞长江」？",
      titleEn: "Why does Dongting swallow the Yangtze?",
      body: "洞庭湖是中国第二大淡水湖，通过松滋、太平、藕池、调弦（已建闸）等「四口」分泄长江洪水，再于城陵矶汇回长江——它是长江中游最重要的天然调蓄湖泊，汛期接纳大量洪峰，枯期补给下游。这种江湖连通关系使洞庭湖面积随季节大幅变化。范仲淹写「衔远山，吞长江」，是对江湖关系的准确概括。",
      bodyEn: "Dongting is China's second-largest freshwater lake. The Yangtze diverts floodwater into it through the Songzi, Taiping, Ouchi and (now gated) Diaoxian outlets, and the water rejoins the river at Chenglingji — making the lake the middle Yangtze's chief natural flood reservoir, absorbing peak flows and releasing them later, with surface area swinging markedly by season. 「Holding the hills and swallowing the river」 describes that relationship exactly.",
    },
    note: "「先忧后乐」四个字后来成了中国士大夫的精神坐标——英文用 before… only after… 保留了顺序。",
    noteEn: "Worry first, rejoice last: the order is everything.",
  },
  {
    slug: "zuiwengtingji",
    title: "醉翁亭记（节选）",
    titleEn: "The Pavilion of the Drunken Old Man (excerpt)",
    author: "欧阳修",
    authorEn: "Ouyang Xiu",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "初中",
    kind: "文言文",
    theme: "山水",
    themeEn: "Landscape",
    level: 2,
    lines: [
      { zh: "醉翁之意不在酒，在乎山水之间也。", en: "The old drunkard's delight is not in wine, but in the hills and water between which he sits." },
      { zh: "山水之乐，得之心而寓之酒也。", en: "The joy of hills and waters is received in the heart and lodged in the wine." },
      { zh: "野芳发而幽香，佳木秀而繁阴，风霜高洁，水落而石出者，山间之四时也。", en: "Wild flowers open with a secret fragrance; fine trees flourish in dense shade; wind and frost are high and clean; the water drops and the stones emerge — these are the four seasons of the hills." },
    ],
    fullText: "环滁皆山也。其西南诸峰，林壑尤美……峰回路转，有亭翼然临于泉上者，醉翁亭也。作亭者谁？山之僧智仙也。名之者谁？太守自谓也。太守与客来饮于此，饮少辄醉，而年又最高，故自号曰醉翁也。醉翁之意不在酒，在乎山水之间也。山水之乐，得之心而寓之酒也……野芳发而幽香，佳木秀而繁阴，风霜高洁，水落而石出者，山间之四时也。朝而往，暮而归，四时之景不同，而乐亦无穷也。",
    keywords: [
      { w: "delight", zh: "意趣（醉翁之意）" },
      { w: "lodge (v.)", zh: "寄托（寓）" },
      { w: "dense shade", zh: "繁阴" },
      { w: "emerge (v.)", zh: "（石）露出" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "「水落而石出」是什么季节？",
      titleEn: "What season is 「water drops and stones appear」?",
      body: "冬季。欧阳修列出的是四季序列：野芳发（春）、佳木秀（夏）、风霜高洁（秋）、水落石出（冬）。冬季降水减少、上游来水与地下水补给降到最低，湖泊河流水位下降，露出的岩石与浅滩增多；而秋季「风霜高洁」指的是冷空气南下后大气透明度提高、天空高朗。四个短语，是一份准确的江淮物候历。",
      bodyEn: "Winter. Ouyang Xiu lists the sequence: wild flowers opening (spring), fine trees in full leaf (summer), high clean wind and frost (autumn), water falling and stones emerging (winter). In winter precipitation and groundwater recharge reach their lowest, river and lake levels drop, and rocks and shoals are exposed. Autumn's 「high clean wind and frost」 marks the improved transparency of air after cold surges. Four phrases, one accurate phenological calendar.",
    },
    note: "全文用了二十一个「也」字——英文无法复制语气助词，只能靠句式节奏（重复的主系表结构）暗示。",
    noteEn: "Twenty-one ye particles in the original; English can only echo the rhythm with repeated structures.",
  },
  {
    slug: "mashuo",
    title: "马说",
    titleEn: "On Horses",
    author: "韩愈",
    authorEn: "Han Yu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "文言文",
    theme: "人才",
    themeEn: "Talent",
    level: 2,
    lines: [
      { zh: "世有伯乐，然后有千里马。千里马常有，而伯乐不常有。", en: "Only let there be a Bo Le in the world, and then there are thousand-li horses. Thousand-li horses are common enough; Bo Le is not." },
      { zh: "策之不以其道，食之不能尽其材，鸣之而不能通其意。", en: "They whip it not in the right way, feed it so that its capacity is not fulfilled, and when it neighs they cannot understand its meaning." },
      { zh: "其真无马邪？其真不知马也！", en: "Is it truly that there are no horses? It is truly that they do not know horses!" },
    ],
    fullText: "世有伯乐，然后有千里马。千里马常有，而伯乐不常有。故虽有名马，祗辱于奴隶人之手，骈死于槽枥之间，不以千里称也。马之千里者，一食或尽粟一石。食马者不知其能千里而食也。是马也，虽有千里之能，食不饱，力不足，才美不外见，且欲与常马等不可得，安求其能千里也？策之不以其道，食之不能尽其材，鸣之而不能通其意，执策而临之，曰：「天下无马！」呜呼！其真无马邪？其真不知马也！",
    keywords: [
      { w: "whip (v.)", zh: "鞭打（策之）" },
      { w: "capacity (n.)", zh: "才能、能力" },
      { w: "neigh (v.)", zh: "（马）嘶鸣" },
      { w: "common", zh: "普通的（常马）" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "千里马需要多少饲料？",
      titleEn: "How much feed does a thousand-li horse need?",
      body: "韩愈说「一食或尽粟一石」是有道理的。马的运动能力取决于能量供给：高强度工作时，一匹 500 公斤的马每日需干物质约 10—12 公斤（精料另计），相当于普通役马的两倍左右。若按能量不足的普通标准喂养（文中「食不饱」），马匹的肌糖原储备与有氧能力下降，自然跑不出千里。所以文章的核心比喻是成立的：识别能力不仅在于眼力，还要懂得相应的投入。",
      bodyEn: "Han Yu's 「a peck of millet at one feeding」 is reasonable. Equine performance depends on energy supply: a 500 kg horse in hard work needs perhaps 10–12 kg of dry matter a day plus concentrates, roughly twice a light draught ration. Fed at ordinary levels — the 「not filled」 of the essay — muscle glycogen and aerobic capacity fall, and no thousand li is possible. The metaphor holds: recognising talent includes knowing what it costs to sustain.",
    },
    note: "全文用三个「不」（不以其道、不能尽其材、不能通其意）层层加码——英文用 not… not… cannot 保留了这个递进。",
    noteEn: "Three negations build the argument step by step.",
  },
  {
    slug: "huxintingkanxue",
    title: "湖心亭看雪",
    titleEn: "Watching Snow from the Mid-Lake Pavilion",
    author: "张岱",
    authorEn: "Zhang Dai",
    dynasty: "明末清初",
    dynastyEn: "Late Ming / early Qing",
    stage: "初中",
    kind: "文言文",
    theme: "山水",
    themeEn: "Landscape",
    level: 2,
    lines: [
      { zh: "大雪三日，湖中人鸟声俱绝。", en: "After three days of heavy snow, the sounds of people and birds on the lake had all ceased." },
      { zh: "雾凇沆砀，天与云与山与水，上下一白。", en: "Rime hangs heavy and vast; sky and cloud and hills and water are one white, above and below." },
      { zh: "湖上影子，惟长堤一痕、湖心亭一点、与余舟一芥、舟中人两三粒而已。", en: "Of shadows on the lake there are only: a stroke of the long causeway, a dot of the mid-lake pavilion, a mustard seed that is my boat, and two or three grains that are the people in it." },
    ],
    fullText: "崇祯五年十二月，余住西湖。大雪三日，湖中人鸟声俱绝。是日更定矣，余拏一小舟，拥毳衣炉火，独往湖心亭看雪。雾凇沆砀，天与云与山与水，上下一白。湖上影子，惟长堤一痕、湖心亭一点、与余舟一芥、舟中人两三粒而已。到亭上，有两人铺毡对坐，一童子烧酒炉正沸……及下船，舟子喃喃曰：「莫说相公痴，更有痴似相公者！」",
    keywords: [
      { w: "cease (v.)", zh: "（声）断绝" },
      { w: "rime (n.)", zh: "雾凇" },
      { w: "a stroke of", zh: "一道（痕迹）" },
      { w: "grain (n.)", zh: "（两三）粒" },
    ],
    cross: {
      field: "气象",
      fieldEn: "Meteorology",
      title: "雾凇是怎么形成的？",
      titleEn: "How does rime form?",
      body: "雾凇是过冷却雾滴（温度低于 0℃ 仍保持液态的小水滴）碰到 0℃ 以下的物体表面时迅速冻结，在迎风面层层累积形成的白色冰晶沉积物。它需要三个条件：充足水汽（雾）、低温、以及微风把雾滴送到物体上。西湖水面蒸发提供水汽，寒潮过后气温骤降——正是雾凇的典型生成环境。张岱看到的「上下一白」，是能见度与反照率都极高时的景象。",
      bodyEn: "Rime forms when supercooled fog droplets — liquid below 0℃ — strike a sub-freezing surface and freeze instantly, building white ice crystals on the windward side. It needs moisture (fog), cold, and a light breeze to deliver droplets. West Lake supplies evaporation; a cold wave supplies the temperature drop: classic rime conditions. The 「one white」 Zhang Dai saw reflects both reduced visibility and snow's very high albedo.",
    },
    note: "「痕、点、芥、粒」四个量词递次缩小——英文用 stroke / dot / mustard seed / grains 保留了这种从大到小的缩放。",
    noteEn: "Four measure words shrink the world: stroke, dot, mustard seed, grains.",
  },
  {
    slug: "yuwosuoyuye",
    title: "鱼我所欲也（节选）",
    titleEn: "Fish Is What I Desire (excerpt)",
    author: "《孟子》",
    authorEn: "Mencius",
    dynasty: "先秦",
    dynastyEn: "Pre-Qin",
    stage: "初中",
    kind: "文言文",
    theme: "哲学",
    themeEn: "Philosophy",
    level: 2,
    lines: [
      { zh: "鱼，我所欲也；熊掌，亦我所欲也。二者不可得兼，舍鱼而取熊掌者也。", en: "Fish is what I desire; bear's paw is also what I desire. If I cannot have both, I give up the fish and take the bear's paw." },
      { zh: "生，亦我所欲也；义，亦我所欲也。二者不可得兼，舍生而取义者也。", en: "Life is what I desire; righteousness is also what I desire. If I cannot have both, I give up life and take righteousness." },
      { zh: "非独贤者有是心也，人皆有之，贤者能勿丧耳。", en: "It is not only the worthy who have this heart — all men have it; the worthy are simply able not to lose it." },
    ],
    fullText: "鱼，我所欲也；熊掌，亦我所欲也。二者不可得兼，舍鱼而取熊掌者也。生，亦我所欲也；义，亦我所欲也。二者不可得兼，舍生而取义者也。生亦我所欲，所欲有甚于生者，故不为苟得也；死亦我所恶，所恶有甚于死者，故患有所不辟也。如使人之所欲莫甚于生，则凡可以得生者何不用也？……非独贤者有是心也，人皆有之，贤者能勿丧耳。",
    keywords: [
      { w: "bear's paw", zh: "熊掌" },
      { w: "cannot have both", zh: "不可得兼" },
      { w: "righteousness (n.)", zh: "义" },
      { w: "the worthy", zh: "贤者" },
    ],
    cross: {
      field: "哲学",
      fieldEn: "Philosophy",
      title: "这个论证的逻辑结构是什么？",
      titleEn: "What is the logical structure?",
      body: "孟子用的是类比 + 归约到极端的两步法：先用人人能懂的选择（鱼与熊掌）建立「两善相权取其重」的原则，再把同一形式套到最难的选择（生与义）上。逻辑学上这叫论证类比（argument by analogy）：如果两件事在相关方面结构相同，那么对前者的判断也应适用于后者。孟子还补了一句关键的话——这个选择能力人人都有，只是贤者「能勿丧」。",
      bodyEn: "Mencius proceeds in two steps: an analogy everyone accepts (fish versus bear's paw) establishes the principle of choosing the greater of two goods; then the same form is applied to the hardest case (life versus righteousness). Logically this is argument by analogy: if two cases share the relevant structure, judgement on one carries to the other. Crucially he adds that everyone has this capacity — the worthy merely keep it.",
    },
    note: "「舍生取义」后来成了成语——英文用 give up life and take righteousness 保留了动词的对仗。",
    noteEn: "Two verbs, give up and take: the whole moral in them.",
  },
  {
    slug: "songdongyang",
    title: "送东阳马生序（节选）",
    titleEn: "Preface Seeing Off Ma, a Student of Dongyang (excerpt)",
    author: "宋濂",
    authorEn: "Song Lian",
    dynasty: "明",
    dynastyEn: "Ming",
    stage: "初中",
    kind: "文言文",
    theme: "勤学",
    themeEn: "Study",
    level: 2,
    lines: [
      { zh: "天大寒，砚冰坚，手指不可屈伸，弗之怠。", en: "In the severest cold, when the inkstone froze hard and my fingers could not bend or straighten, I did not slacken." },
      { zh: "以中有足乐者，不知口体之奉不若人也。", en: "Because there was enough joy within, I did not notice that my food and clothing were not the equal of others'." },
    ],
    fullText: "余幼时即嗜学。家贫，无从致书以观，每假借于藏书之家，手自笔录，计日以还。天大寒，砚冰坚，手指不可屈伸，弗之怠。录毕，走送之，不敢稍逾约……当余之从师也，负箧曳屣，行深山巨谷中，穷冬烈风，大雪深数尺，足肤皲裂而不知……以中有足乐者，不知口体之奉不若人也。",
    keywords: [
      { w: "slacken (v.)", zh: "懈怠" },
      { w: "inkstone", zh: "砚台" },
      { w: "the equal of others", zh: "比得上别人" },
      { w: "within (adv.)", zh: "内心之中" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "砚台为什么会结冰？",
      titleEn: "Why does the inkstone freeze?",
      body: "砚台里的水在 0℃ 以下结冰是常识，但难受之处在于：墨是碳黑颗粒悬浮在含胶的水溶液中，冰晶形成会把胶质与碳颗粒挤到未冻区域，破坏墨的胶体稳定性；解冻后墨色变淡、颗粒沉淀，甚至失去粘性。古代没有取暖的书房时，常需温水化墨或把砚放在炉边（「暖砚」，砚下有炭火腔）。宋濂说「弗之怠」，是对抗严寒的真实记录。",
      bodyEn: "Ink freezes below 0℃, but the damage is subtler: ink is carbon black suspended in a glue solution, and ice crystals expel the colloid and particles into unfrozen pockets, destroying stability — after thawing the ink is pale, settled, less adhesive. Before heated studies, scholars used warm water or a warmed inkstone with a charcoal chamber beneath. Song Lian's 「did not slacken」 is a record of working through exactly that.",
    },
    note: "全文是「现身说法」的劝学文——不摆道理，只讲自己吃过什么苦。英文用 I did not slacken 保留了平实语气。",
    noteEn: "No preaching, only what he himself endured.",
  },
  {
    slug: "caoguijunzhan",
    title: "曹刿论战（节选）",
    titleEn: "Cao Gui Discusses the Battle (excerpt)",
    author: "《左传》",
    authorEn: "Zuo Zhuan",
    dynasty: "先秦",
    dynastyEn: "Pre-Qin",
    stage: "初中",
    kind: "文言文",
    theme: "军事",
    themeEn: "Warfare",
    level: 2,
    lines: [
      { zh: "肉食者鄙，未能远谋。", en: "Those who eat meat are shortsighted; they cannot plan far ahead." },
      { zh: "衣食所安，弗敢专也，必以分人。", en: "Clothing and food, the things that give ease — I dare not keep them to myself; I always share them with others." },
      { zh: "一鼓作气，再而衰，三而竭。彼竭我盈，故克之。", en: "At the first drum, courage rises; at the second it flags; at the third it is spent. When theirs was spent and ours was full, we defeated them." },
    ],
    fullText: "十年春，齐师伐我。公将战，曹刿请见。其乡人曰：「肉食者谋之，又何间焉？」刿曰：「肉食者鄙，未能远谋。」……公曰：「衣食所安，弗敢专也，必以分人。」对曰：「小惠未遍，民弗从也。」……公与之乘，战于长勺。公将鼓之。刿曰：「未可。」齐人三鼓。刿曰：「可矣。」齐师败绩……既克，公问其故。对曰：「夫战，勇气也。一鼓作气，再而衰，三而竭。彼竭我盈，故克之。」",
    keywords: [
      { w: "shortsighted (adj.)", zh: "鄙陋的" },
      { w: "dare not", zh: "不敢" },
      { w: "flag (v.)", zh: "（士气）衰退" },
      { w: "spent (adj.)", zh: "枯竭的" },
    ],
    cross: {
      field: "军事",
      fieldEn: "Military Science",
      title: "「一鼓作气」真的有道理吗？",
      titleEn: "Is 「first drum, courage rises」 really sound?",
      body: "符合军事心理学。士兵冲锋前的士气受生理唤醒水平影响：肾上腺素升高带来兴奋与攻击性，但这种状态持续数分钟后就会回落，若反复发起又反复中止，部队会陷入疲劳与挫败，协同也变差。所以让敌方三次击鼓进攻而未接战，其士气与体力都在消耗——这正是曹刿「彼竭我盈」的原理。公元前 684 年的长勺之战是中国历史上以弱胜强的经典战例。",
      bodyEn: "Sound military psychology. A soldier's morale before a charge rides on physiological arousal: adrenaline raises excitement and aggression, but the state decays within minutes, and repeated starts and halts bring fatigue, frustration and loss of coordination. Letting the enemy drum three assaults without engaging spends their energy and spirit — exactly Cao Gui's 「theirs spent, ours full」. The battle of Changshao in 684 BC is a classic victory of the weaker side.",
    },
    note: "全文的核心是「勇气是消耗品」——英文用 rises / flags / spent 三个动词写出了衰退曲线。",
    noteEn: "Courage as a consumable: rises, flags, spent.",
  },
  {
    slug: "chushibiao",
    title: "出师表（节选）",
    titleEn: "Memorial on Going to War (excerpt)",
    author: "诸葛亮",
    authorEn: "Zhuge Liang",
    dynasty: "三国",
    dynastyEn: "Three Kingdoms",
    stage: "初中",
    kind: "文言文",
    theme: "家国",
    themeEn: "Nation",
    level: 2,
    lines: [
      { zh: "先帝创业未半而中道崩殂，今天下三分，益州疲弊，此诚危急存亡之秋也。", en: "The late emperor's enterprise was but half accomplished when he died along the way; now the empire is divided in three, and Yi province is exhausted — this is truly a crisis of survival." },
      { zh: "亲贤臣，远小人，此先汉所以兴隆也。", en: "To be close to worthy ministers and keep petty men at distance — this is why the Former Han flourished." },
      { zh: "受任于败军之际，奉命于危难之间。", en: "I was entrusted at the moment of defeat and received my charge in the midst of peril." },
      { zh: "鞠躬尽瘁，死而后已。", en: "I shall bend myself to the task until my strength is spent, and stop only at death." },
    ],
    fullText: "先帝创业未半而中道崩殂，今天下三分，益州疲弊，此诚危急存亡之秋也……亲贤臣，远小人，此先汉所以兴隆也；亲小人，远贤臣，此后汉所以倾颓也……臣本布衣，躬耕于南阳，苟全性命于乱世，不求闻达于诸侯。先帝不以臣卑鄙，猥自枉屈，三顾臣于草庐之中……受任于败军之际，奉命于危难之间，尔来二十有一年矣。先帝知臣谨慎，故临崩寄臣以大事也……臣鞠躬尽瘁，死而后已。",
    keywords: [
      { w: "enterprise (n.)", zh: "（创）业" },
      { w: "exhausted (adj.)", zh: "疲弊" },
      { w: "petty men", zh: "小人" },
      { w: "until my strength is spent", zh: "鞠躬尽瘁" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "这份表写于何时？",
      titleEn: "When was this memorial written?",
      body: "蜀汉建兴五年（227），诸葛亮准备第一次北伐曹魏，率军屯于汉中，临行前上表后主刘禅。文中「今天下三分」指魏、蜀、吴；「益州疲弊」是实情——蜀汉当时人口不足百万，兵力约十万，是三国中最弱的一方。至于「鞠躬尽瘁，死而后已」，他确实做到了：此后五次北伐，234 年病卒于五丈原军中，终年五十四岁。",
      bodyEn: "In 227, as Zhuge Liang prepared his first northern campaign against Wei and encamped at Hanzhong, he submitted this memorial to the young emperor Liu Shan. 「The empire is divided in three」 means Wei, Shu and Wu; 「Yi province exhausted」 was true — Shu had under a million people and perhaps a hundred thousand troops, the weakest of the three. As for working until strength was spent: he did. Five more campaigns followed, and he died in camp at Wuzhangyuan in 234, aged fifty-four.",
    },
    note: "「表」是臣子上书的文体，语气既要恭敬又要说理——英文用 This is truly… 保留了那种郑重的判断语气。",
    noteEn: "A memorial must be respectful and frank at once; the English keeps that measured judgement.",
  },
  {
    slug: "zoujifengqiwang",
    title: "邹忌讽齐王纳谏（节选）",
    titleEn: "Zou Ji Persuades the King of Qi to Accept Advice (excerpt)",
    author: "《战国策》",
    authorEn: "Zhanguoce",
    dynasty: "先秦",
    dynastyEn: "Pre-Qin",
    stage: "初中",
    kind: "文言文",
    theme: "政治",
    themeEn: "Politics",
    level: 2,
    lines: [
      { zh: "吾妻之美我者，私我也；妾之美我者，畏我也；客之美我者，欲有求于我也。", en: "My wife calls me handsome because she is partial to me; my concubine, because she fears me; my guest, because he wants something from me." },
      { zh: "宫妇左右莫不私王，朝廷之臣莫不畏王，四境之内莫不有求于王。由此观之，王之蔽甚矣。", en: "In your palace no woman or attendant but is partial to you; in your court no minister but fears you; within your borders none but has some request of you. From this it is clear: your majesty is very greatly blinded." },
      { zh: "群臣进谏，门庭若市；数月之后，时时而间进；期年之后，虽欲言，无可进者。", en: "Ministers offered advice until the court was like a market; after some months, they came only now and then; after a year, even those who wished to speak had nothing left to say." },
    ],
    fullText: "邹忌修八尺有余，而形貌昳丽。朝服衣冠，窥镜，谓其妻曰：「我孰与城北徐公美？」其妻曰：「君美甚，徐公何能及君也？」……旦日，客从外来，与坐谈，问之客曰：「吾与徐公孰美？」客曰：「徐公不若君之美也。」明日徐公来，孰视之，自以为不如；窥镜而自视，又弗如远甚。暮寝而思之，曰：「吾妻之美我者，私我也；妾之美我者，畏我也；客之美我者，欲有求于我也。」于是入朝见威王……王曰：「善。」乃下令：「群臣吏民能面刺寡人之过者，受上赏……」",
    keywords: [
      { w: "be partial to", zh: "偏爱（私）" },
      { w: "blinded (adj.)", zh: "受蒙蔽的（蔽）" },
      { w: "like a market", zh: "门庭若市" },
      { w: "now and then", zh: "时时而间进" },
    ],
    cross: {
      field: "逻辑",
      fieldEn: "Logic",
      title: "邹忌的推理有什么巧妙之处？",
      titleEn: "What makes Zou Ji's reasoning clever?",
      body: "他做的是一次漂亮的归纳与类比：先从自己的三个例子中归纳出一般规律（赞美来自私、畏、有求三种动机，而非事实），再把这个规律应用到国王身上——国王身边的人同样具备这三种动机，因此国王听到的话必定失真。这是「信息源偏差」的早期分析：判断一条信息，不能只看内容，还要看说话人的处境与利益。进谏效果显著：一年后「无可进者」。",
      bodyEn: "A neat induction followed by analogy: from three personal cases he generalises a rule (praise flows from partiality, fear and self-interest, not from fact), then applies it to the king, whose entourage shares those motives — so what the king hears must be distorted. It is an early analysis of source bias: judge a claim by the speaker's position and interest, not only its content. The remedy worked: within a year there was nothing left to criticise.",
    },
    note: "「暮寝而思之」是全篇的转折——别人都在夸他，他却自己夜里想明白了。英文用 think it over that night 保留了这一步。",
    noteEn: "Everyone flatters him; he works it out alone at night.",
  },
];
