import type { Poem } from "./types";

/** 初中阶段 · 第 2 批（登临、边塞、田园、咏史） */
export const JUNIOR_2: Poem[] = [
  {
    slug: "dengyouzhoutai",
    title: "登幽州台歌",
    titleEn: "Song on Climbing Youzhou Tower",
    author: "陈子昂",
    authorEn: "Chen Zi'ang",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "人生",
    themeEn: "Life",
    level: 2,
    lines: [
      { zh: "前不见古人，后不见来者。", en: "Behind me I see not the men of old; before me I see not those yet to come." },
      { zh: "念天地之悠悠，独怆然而涕下。", en: "I think of heaven and earth, endlessly long — and alone, stricken, I let the tears fall." },
    ],
    keywords: [
      { w: "the men of old", zh: "古人" },
      { w: "endlessly (adv.)", zh: "悠悠、无穷尽地" },
      { w: "stricken (adj.)", zh: "悲伤怆然的" },
      { w: "let the tears fall", zh: "落泪" },
    ],
    cross: {
      field: "天文",
      fieldEn: "Astronomy",
      title: "「天地之悠悠」有多久？",
      titleEn: "How long is 「heaven and earth, endlessly long」?",
      body: "陈子昂的感慨放在今天有精确的数字参照：地球年龄约 45.4 亿年，宇宙约 138 亿年，而人类文明不过几千年，个体寿命不足百年。他在幽州台（相传为燕昭王招贤的黄金台旧址）想到的是「明君难遇」——燕昭王那样肯礼贤下士的君主已成古人，而后人能否理解自己则不可知。用宇宙尺度衡量人生，是全诗力量的来源。",
      bodyEn: "His lament can be measured today: Earth is about 4.54 billion years old, the universe 13.8 billion, human civilisation a few thousand, and one life under a century. Standing at Youzhou — the site of King Zhao of Yan's terrace for recruiting talent — he thought how rarely a ruler truly honours ability: the enlightened kings are gone, and whether those to come will understand him is unknown. Measuring a life against cosmic time is the source of the poem's force.",
    },
    note: "全诗句式参差（前两句五字、后两句六字），故意打破整齐——英文用 not… not… 的重复保留了这种顿挫。",
    noteEn: "Irregular line lengths deliberately break the pattern; the doubled not carries the pause.",
  },
  {
    slug: "wangyue",
    title: "望岳",
    titleEn: "Gazing at Mount Tai",
    author: "杜甫",
    authorEn: "Du Fu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "山水",
    themeEn: "Landscape",
    level: 2,
    lines: [
      { zh: "岱宗夫如何？齐鲁青未了。", en: "What then is the Great Peak like? Over Qi and Lu its green has no end." },
      { zh: "造化钟神秀，阴阳割昏晓。", en: "Nature gathers there its divine beauty; the dark north slope and bright south cut dawn from dusk." },
      { zh: "会当凌绝顶，一览众山小。", en: "One day I must stand upon its highest peak, and see at a glance how small all other mountains are." },
    ],
    keywords: [
      { w: "at a glance", zh: "一览" },
      { w: "one day I must", zh: "会当（定要）" },
      { w: "cut A from B", zh: "把 A 与 B 分割" },
      { w: "divine beauty", zh: "神秀" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "为什么泰山能「阴阳割昏晓」？",
      titleEn: "Why does Tai Shan cut dawn from dusk?",
      body: "泰山主峰玉皇顶海拔 1545 米，耸立于华北平原东缘，相对高差超过 1300 米。山体高大到足以造成两侧光照差异：南坡（阳坡）日照充足，北坡（阴坡）长期背阴，同一时刻坡上坡下的明暗宛如晨昏之别。这在地理学上叫坡向效应——阳坡蒸发强、植被带更高，阴坡湿润、土壤发育不同。杜甫写的是视觉印象，背后是真实的地形与光照差。",
      bodyEn: "Tai Shan's summit, Yuhuang Ding, rises to 1,545 m at the eastern edge of the North China Plain, with over 1,300 m of local relief — enough to create a real lighting contrast: the sunlit south slope and shaded north slope look like dawn and dusk at the same moment. Geographers call this the aspect effect: sunny slopes lose more water to evaporation and carry vegetation higher; shady slopes stay moister with different soils. Du Fu's impression rests on genuine topography.",
    },
    note: "「会当」是「总有一天一定要」——还没登，气势已经到了山顶。英文用 One day I must 保留这份未完成的决心。",
    noteEn: "「会当」 means some day, certainly — the resolve arrives before the climb.",
  },
  {
    slug: "dengfeilaifeng",
    title: "登飞来峰",
    titleEn: "Climbing Feilai Peak",
    author: "王安石",
    authorEn: "Wang Anshi",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "初中",
    kind: "诗",
    theme: "人生",
    themeEn: "Life",
    level: 2,
    lines: [
      { zh: "飞来山上千寻塔，闻说鸡鸣见日升。", en: "On Feilai Mountain stands a tower a thousand fathoms high; they say at cock-crow you can watch the sun rise." },
      { zh: "不畏浮云遮望眼，自缘身在最高层。", en: "I do not fear the drifting clouds that would block my sight — for I stand on the highest storey." },
    ],
    keywords: [
      { w: "cock-crow", zh: "鸡鸣（拂晓）" },
      { w: "drifting clouds", zh: "浮云" },
      { w: "block my sight", zh: "遮挡视线" },
      { w: "for (conj.)", zh: "因为（自缘）" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "站得高为什么看得远？",
      titleEn: "Why does height extend the view?",
      body: "因为地球是球体。地平线距离 d ≈ √(2Rh)，R 为地球半径约 6371 公里，h 为眼高。地面上看（h≈1.7 米）视距约 5 公里；站在一千多米的山顶，视距可达 100 公里以上，且视线越过近处云层——云通常在低空（层云高度几百米），所以人在高处反而是在云之上，「浮云遮望眼」不成立。王安石把这个物理事实变成了政治隐喻：站得高，就不怕遮蔽。",
      bodyEn: "Because Earth is round. Horizon distance d ≈ √(2Rh), with R ≈ 6,371 km and h the eye height. At ground level (h ≈ 1.7 m) you see about 5 km; from a summit over a kilometre up, more than 100 km — and above the low cloud deck, since stratus often sits only a few hundred metres up. So at height the drifting clouds are below you. Wang Anshi turns that geometry into politics: from the top, nothing blocks the view.",
    },
    note: "「自缘身在最高层」——不是浮云不存在，是位置不同。英文用 for I stand on 保留了因果。",
    noteEn: "The clouds exist; the position differs. For I stand on keeps the cause.",
  },
  {
    slug: "youshanxicun",
    title: "游山西村",
    titleEn: "Touring a Village West of the Hills",
    author: "陆游",
    authorEn: "Lu You",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "初中",
    kind: "诗",
    theme: "田园",
    themeEn: "Pastoral",
    level: 2,
    lines: [
      { zh: "山重水复疑无路，柳暗花明又一村。", en: "Hills upon hills, streams upon streams — I doubt there is a way out; willows dark, blossoms bright, and another village appears." },
      { zh: "箫鼓追随春社近，衣冠简朴古风存。", en: "Flutes and drums follow one another: the spring sacrifice is near. Dress is plain and simple — the old ways survive." },
    ],
    keywords: [
      { w: "doubt (v.)", zh: "怀疑、以为" },
      { w: "there is a way out", zh: "有路可走" },
      { w: "plain and simple", zh: "简朴" },
      { w: "the old ways", zh: "古风" },
    ],
    cross: {
      field: "民俗",
      fieldEn: "Folklore",
      title: "春社是什么节日？",
      titleEn: "What was the spring sacrifice?",
      body: "春社是立春后第五个戊日，祭祀土地神（社神）以祈求丰收，是中国最古老的农事节日之一；秋社则在立秋后，报谢土地。社日要杀牲、祭社、聚饮、击鼓吹箫，全村参与——所以陆游听到「箫鼓追随」。这个节日在宋代极盛，后来逐渐与社火、庙会融合。诗里「衣冠简朴古风存」说的正是这种未被城市风气改变的乡俗。",
      bodyEn: "The spring sacrifice fell on the fifth wu-day after the start of spring, honouring the god of the soil and praying for harvest — among China's oldest farming festivals; an autumn counterpart gave thanks. The day meant offering animals, libations, communal drinking, drums and flutes, the whole village taking part — hence the 「flutes and drums」 Lu You heard. It flourished in the Song and later merged with temple fairs. 「The old ways survive」 notes a custom not yet reshaped by urban fashion.",
    },
    note: "「山重水复疑无路，柳暗花明又一村」已变成成语——英文用 doubt there is a way out 与 another village appears 保留了「绝处逢生」的结构。",
    noteEn: "Now an idiom: blocked, then suddenly another village.",
  },
  {
    slug: "jihaizashi",
    title: "己亥杂诗 · 其五",
    titleEn: "Miscellaneous Poems of the Jihai Year · V",
    author: "龚自珍",
    authorEn: "Gong Zizhen",
    dynasty: "清",
    dynastyEn: "Qing",
    stage: "初中",
    kind: "诗",
    theme: "家国",
    themeEn: "Nation",
    level: 2,
    lines: [
      { zh: "浩荡离愁白日斜，吟鞭东指即天涯。", en: "Vast and surging, the grief of parting, as the white sun slants; I hum, point my whip east — and that is the world's edge." },
      { zh: "落红不是无情物，化作春泥更护花。", en: "The fallen blossom is not a thing without feeling; it turns into spring mud and goes on to nourish the flowers." },
    ],
    keywords: [
      { w: "surging (adj.)", zh: "浩荡的" },
      { w: "slant (v.)", zh: "（日）偏斜" },
      { w: "fallen blossom", zh: "落红" },
      { w: "nourish (v.)", zh: "滋养" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "落花真的能护花吗？",
      titleEn: "Do fallen petals really nourish the flowers?",
      body: "能，这是生态系统物质循环的基本环节。花瓣、落叶等凋落物被真菌、细菌和土壤动物（蚯蚓、跳虫等）分解，其中的氮、磷、钾等元素矿化后重新被根系吸收——这就是「化作春泥更护花」的现代说法，生态学上叫养分归还（nutrient return）。龚自珍辞官南归时写下此诗，用这个自然过程比喻自己虽离朝堂，仍要以另一种方式效力。",
      bodyEn: "Yes — it is the basic loop of nutrient cycling. Petals and leaves are broken down by fungi, bacteria and soil fauna (earthworms, springtails), and their nitrogen, phosphorus and potassium are mineralised for roots to take up again: ecologists call it nutrient return. Gong Zizhen resigned and headed south when he wrote this, using the natural cycle to say that leaving office was only another way to serve.",
    },
    note: "「落红」是全诗的诗眼——英文用 fallen blossom 保留了颜色词（红→blossom 后接 nourish the flowers）。",
    noteEn: "The whole poem turns on the fallen blossom: it becomes mud, and feeds the next flowers.",
  },
  {
    slug: "boqinhuai",
    title: "泊秦淮",
    titleEn: "Mooring on the Qinhuai",
    author: "杜牧",
    authorEn: "Du Mu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "咏史",
    themeEn: "History",
    level: 2,
    lines: [
      { zh: "烟笼寒水月笼沙，夜泊秦淮近酒家。", en: "Mist shrouds the cold water, moonlight shrouds the sand; at night I moor on the Qinhuai, near a tavern." },
      { zh: "商女不知亡国恨，隔江犹唱后庭花。", en: "The singing girl knows nothing of the grief of a fallen state — across the river she still sings 「Flowers in the Rear Courtyard」." },
    ],
    keywords: [
      { w: "shroud (v.)", zh: "笼罩" },
      { w: "singing girl", zh: "歌女" },
      { w: "fallen state", zh: "亡国之痛" },
      { w: "still (adv.)", zh: "仍然" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "《后庭花》是什么曲子？",
      titleEn: "What is the song 「Flowers in the Rear Courtyard」?",
      body: "《玉树后庭花》是南朝陈后主（陈叔宝）所作乐曲，他在位时大兴宫室、日夜与妃嫔宴饮作乐，589 年陈被隋所灭。后世遂把这支曲子当作「亡国之音」的象征。杜牧在晚唐的秦淮河上听到有人唱它，触发的是对现实的忧惧：此时的唐王朝已是藩镇割据、宦官专权，离灭亡不到五十年。「不知亡国恨」骂的不是歌女，是听歌的人。",
      bodyEn: "「Jade Trees and Flowers in the Rear Courtyard」 was composed by Chen Shubao, last emperor of the Chen dynasty, who built palaces and feasted with his concubines day and night until the Sui destroyed his state in 589. The tune became the emblem of a state's ruin. Hearing it on the Qinhuai in the late Tang, Du Mu feared the parallel: the Tang was riven by warlord provinces and eunuch power, less than fifty years from its end. The rebuke is aimed not at the singer but at those who listen.",
    },
    note: "「犹」字最狠——国将不国，歌声照旧。英文用 still 单独拎出来，保留了这份刺。",
    noteEn: "Everything rests on still: the state is failing, the song goes on.",
  },
  {
    slug: "jiasheng",
    title: "贾生",
    titleEn: "The Scholar Jia",
    author: "李商隐",
    authorEn: "Li Shangyin",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "咏史",
    themeEn: "History",
    level: 2,
    lines: [
      { zh: "宣室求贤访逐臣，贾生才调更无伦。", en: "In the Xuan chamber the emperor sought talent, and questioned an exiled minister; Jia's gifts were beyond compare." },
      { zh: "可怜夜半虚前席，不问苍生问鬼神。", en: "Pitiful that at midnight he moved his mat forward in vain — asking not about the people, but about ghosts and gods." },
    ],
    keywords: [
      { w: "exiled minister", zh: "被贬的臣子" },
      { w: "beyond compare", zh: "无与伦比" },
      { w: "in vain", zh: "徒然、白白地" },
      { w: "the people", zh: "苍生、百姓" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "汉文帝问的是什么？",
      titleEn: "What did Emperor Wen ask about?",
      body: "贾谊是西汉政论家，写过《过秦论》《论积贮疏》，主张削藩、重农、抗匈奴，因触怒权贵被贬长沙。汉文帝后来召他回长安，在宣室（未央宫前殿的正室）接见，却只与他谈论鬼神之事——据《史记》记载，文帝因刚举行过祭祀而问鬼神之本，谈至夜半，还不知不觉把坐席前移。李商隐抓住这个细节讽刺：真正的贤才被闲置，皇帝关心的却是虚无之事。",
      bodyEn: "Jia Yi was a Western Han political thinker — author of The Faults of Qin and memorials on grain storage — who urged curbing the feudal states, exalting agriculture and resisting the Xiongnu, and was exiled to Changsha for offending powerful men. Emperor Wen later recalled him and received him in the Xuan chamber, but talked only of ghosts and gods: the Records of the Grand Historian says the emperor had just performed a sacrifice and asked about the origin of spirits, talking past midnight and edging his mat forward as he listened. Li Shangyin seizes on the detail: real talent idle, while the throne worries about the supernatural.",
    },
    note: "「不问苍生问鬼神」是全诗的刀——英文用 asking not about the people, but about 保留了对比结构。",
    noteEn: "The blade: asking not about the people, but about ghosts and gods.",
  },
  {
    slug: "guosongyuan",
    title: "过松源晨炊漆公店",
    titleEn: "Passing Songyuan, Breakfasting at Qigong's Inn",
    author: "杨万里",
    authorEn: "Yang Wanli",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "初中",
    kind: "诗",
    theme: "人生",
    themeEn: "Life",
    level: 2,
    lines: [
      { zh: "莫言下岭便无难，赚得行人错喜欢。", en: "Do not say that going downhill removes all difficulty — it cheats the traveller into a false rejoicing." },
      { zh: "正入万山圈子里，一山放过一山拦。", en: "You are right inside a ring of ten thousand hills: one hill lets you pass, the next one blocks the way." },
    ],
    keywords: [
      { w: "remove (v.)", zh: "消除（困难）" },
      { w: "cheat sb. into", zh: "骗得某人…" },
      { w: "let pass", zh: "放过、放行" },
      { w: "block the way", zh: "拦路" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "下山为什么反而难？",
      titleEn: "Why is going down harder than going up?",
      body: "从运动与生理看，下山并不轻松：重心下降时肌肉要做离心收缩来缓冲（比向心收缩更易造成肌肉微损伤，这也是下山后腿更酸的原因），且重力持续加速，需不断制动，对膝关节冲击可达体重的 3—4 倍。在南方山区连绵的丘陵地带，翻过一岭紧接着又是下一岭——杨万里写的「一山放过一山拦」正是这种地貌的真实体验。",
      bodyEn: "Descending is not easy. Lowering the body's centre of mass requires eccentric muscle contraction to brake — more damaging than concentric work, which is why legs ache more after descent — while gravity keeps accelerating you, loading the knee joints with three to four times body weight. In the rolling hill country of the south, one ridge follows another: Yeung Wanli's 「one hill lets you pass, the next blocks the way」 is literally that terrain.",
    },
    note: "全诗是一则生活哲理：以为过了一关，其实关是连环的。英文用 Do not say 起句，语气像劝告。",
    noteEn: "A homily: the obstacle you pass is followed by another.",
  },
  {
    slug: "yueke",
    title: "约客",
    titleEn: "Expecting a Guest",
    author: "赵师秀",
    authorEn: "Zhao Shixiu",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "初中",
    kind: "诗",
    theme: "四季",
    themeEn: "Seasons",
    level: 2,
    lines: [
      { zh: "黄梅时节家家雨，青草池塘处处蛙。", en: "In the season of yellow plums, rain at every house; by the grassy pond, frogs everywhere." },
      { zh: "有约不来过夜半，闲敲棋子落灯花。", en: "He was invited but has not come, and now it is past midnight — idly I tap a chess piece, and knock down the wick's charred flower." },
    ],
    keywords: [
      { w: "yellow plums", zh: "黄梅（梅子）" },
      { w: "at every house", zh: "家家" },
      { w: "past midnight", zh: "过夜半" },
      { w: "idly (adv.)", zh: "闲散地" },
    ],
    cross: {
      field: "气象",
      fieldEn: "Meteorology",
      title: "黄梅天为什么一直下雨？",
      titleEn: "Why does the plum rain never stop?",
      body: "梅雨是东亚特有的天气现象：每年 6—7 月，来自海洋的暖湿气流与北方冷空气在江淮一带势均力敌，形成准静止锋（梅雨锋），锋面长时间徘徊，带来持续阴雨，空气湿度常在 80% 以上。此时正值江南梅子成熟，故称「梅雨」「黄梅天」。诗里「家家雨」是写实：梅雨期降水日数可达全月的三分之二。",
      bodyEn: "The plum rain is an East Asian phenomenon: from June to July, moist maritime air and northern cold air reach a stand-off over the Yangtze–Huai region, forming a quasi-stationary front that lingers, with humidity often above 80%. It coincides with the ripening of plums in the south, hence the name. 「Rain at every house」 is literal: rain may fall on two days in three through the season.",
    },
    note: "全诗用声音写等待：雨声、蛙声、棋子声。英文用 idly tap 把最后一点声响落在最轻的动作上。",
    noteEn: "Waiting rendered as sound: rain, frogs, then one tapped chess piece.",
  },
  {
    slug: "yewang",
    title: "野望",
    titleEn: "Gazing over the Countryside",
    author: "王绩",
    authorEn: "Wang Ji",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "山水",
    themeEn: "Landscape",
    level: 2,
    lines: [
      { zh: "树树皆秋色，山山唯落晖。", en: "Every tree wears autumn colour; every hill holds only the dying light." },
      { zh: "相顾无相识，长歌怀采薇。", en: "We look at each other and none is known to me; I sing a long song, thinking of those who gathered fern." },
    ],
    keywords: [
      { w: "dying light", zh: "落晖、夕阳余晖" },
      { w: "look at each other", zh: "相顾" },
      { w: "long song", zh: "长歌" },
      { w: "gather fern", zh: "采薇（隐居）" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "「采薇」是什么典故？",
      titleEn: "What is the allusion to gathering fern?",
      body: "出自《史记·伯夷列传》：商末伯夷、叔齐反对武王伐纣，商亡后不食周粟，隐于首阳山采薇（野豌豆）而食，最终饿死。后世「采薇」遂成为隐居守节的代称。王绩身处隋唐易代之际，两次出仕又两次归隐，诗里「相顾无相识」写的是孤独——不认识的人无法理解他，他只能与古人对话。",
      bodyEn: "From the Records of the Grand Historian: Bo Yi and Shu Qi opposed King Wu's campaign against the last Shang king and, after the fall, refused to eat Zhou grain, hiding on Mount Shouyang to live on wild vetch until they starved. Gathering fern became shorthand for principled retirement. Wang Ji served twice and withdrew twice across the Sui–Tang transition; 「we look at each other and none is known」 is loneliness — no one present understands him, so he converses with the ancients.",
    },
    note: "「皆」「唯」两个副词把整个视野统一成一种色调——英文用 Every… every… 保留了这个铺陈。",
    noteEn: "Two adverbs unify the whole field of view; English mirrors it with every … every ….",
  },
  {
    slug: "shizhisaishang",
    title: "使至塞上",
    titleEn: "Sent as Envoy to the Frontier",
    author: "王维",
    authorEn: "Wang Wei",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "边塞",
    themeEn: "Frontier",
    level: 2,
    lines: [
      { zh: "征蓬出汉塞，归雁入胡天。", en: "Like tumbleweed I leave the Han frontier; the homing geese enter the northern sky." },
      { zh: "大漠孤烟直，长河落日圆。", en: "Over the great desert, a lone column of smoke stands straight; along the long river, the setting sun is round." },
    ],
    keywords: [
      { w: "tumbleweed (n.)", zh: "蓬草（飘转不定）" },
      { w: "lone column", zh: "一缕孤烟" },
      { w: "straight (adj.)", zh: "笔直的" },
      { w: "round (adj.)", zh: "圆的" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "孤烟为什么是「直」的？",
      titleEn: "Why does the smoke stand straight?",
      body: "狼烟（或烽火烟）在无风的清晨或傍晚垂直上升，说明大气层结稳定、几乎没有水平风与湍流——烟囱原理：热烟气密度低，浮力使其上升，若环境风速小，烟柱就能保持笔直到很高的高度。沙漠昼夜温差大，日出前后常有短暂的静风时段。王维抓住了沙漠最典型的那一瞬，也顺手定义了中国边塞诗的视觉标准。",
      bodyEn: "A smoke column rising vertically means the atmosphere is stable with almost no horizontal wind or turbulence: the hot gases are buoyant, and with little ambient wind the plume stays coherent to great height. Deserts, with their huge day–night temperature swings, often have brief near-calm periods around sunrise and sunset. Wang Wei caught the desert's signature moment and set the visual standard for frontier poetry.",
    },
    note: "「直」「圆」两个几何词是全诗最硬的地方——英文用 straight 与 round 保留了这种几何感。",
    noteEn: "Two geometry words — straight and round — make the hardest, cleanest image.",
  },
  {
    slug: "dujingmensongbie",
    title: "渡荆门送别",
    titleEn: "Farewell at Crossing Jingmen",
    author: "李白",
    authorEn: "Li Bai",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "山水",
    themeEn: "Landscape",
    level: 2,
    lines: [
      { zh: "山随平野尽，江入大荒流。", en: "The hills end where the flat plain begins; the river flows on into the great wilderness." },
      { zh: "月下飞天镜，云生结海楼。", en: "The moon, falling, is like a mirror flying down; clouds gather and build a sea-tower." },
      { zh: "仍怜故乡水，万里送行舟。", en: "Still I love the water of my home — for ten thousand li it has escorted my boat." },
    ],
    keywords: [
      { w: "flat plain", zh: "平野" },
      { w: "wilderness (n.)", zh: "荒原" },
      { w: "sea-tower", zh: "海楼（海市蜃楼）" },
      { w: "escort (v.)", zh: "护送" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "「海楼」是什么？",
      titleEn: "What is the sea-tower?",
      body: "海市蜃楼，一种大气光学现象。空气密度随温度分层：近地面冷、上层暖时，光线向下弯曲（上现蜃景），远处景物被折射到观察者眼中，看起来像悬在空中或水上的楼台。江面与沙漠是最常见的发生地，因为水面/沙面能形成强温度梯度。李白在江上看到的「云生结海楼」，很可能就是真实的蜃景。",
      bodyEn: "A mirage — an atmospheric optical effect. When air is stratified by temperature (cool below, warmer above), light rays bend downward (superior mirage) and distant objects are refracted into view, appearing as towers suspended above the horizon. River surfaces and deserts are classic sites because they create strong thermal gradients. What Li Bai saw on the river may well have been a real mirage.",
    },
    note: "「山随平野尽」写的是地形突变：出三峡，山一下子没了——英文用 The hills end where 保留了这句的空间感。",
    noteEn: "「The hills end where the flat plain begins」 records a real break in terrain as the gorges open out.",
  },
  {
    slug: "qiantanghuchunxing",
    title: "钱塘湖春行",
    titleEn: "A Spring Walk by Qiantang Lake",
    author: "白居易",
    authorEn: "Bai Juyi",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "四季",
    themeEn: "Seasons",
    level: 2,
    lines: [
      { zh: "几处早莺争暖树，谁家新燕啄春泥。", en: "Here and there early orioles contend for the warm trees; from whose house do the new swallows peck spring mud?" },
      { zh: "乱花渐欲迷人眼，浅草才能没马蹄。", en: "Scattered flowers begin to dazzle the eye; the short grass has just grown enough to hide a horse's hoof." },
    ],
    keywords: [
      { w: "contend for", zh: "争抢" },
      { w: "peck (v.)", zh: "啄" },
      { w: "dazzle (v.)", zh: "使…迷乱" },
      { w: "just enough to", zh: "刚刚能够" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "燕子为什么要啄泥？",
      titleEn: "Why do swallows peck at mud?",
      body: "家燕筑巢用的是湿泥混合草茎与唾液，一层层垒成碗状，泥干后坚硬牢固——唾液中的糖蛋白起粘结作用，原理接近天然的复合材料（泥为骨料、唾液纤维为增强）。它们通常每年回到旧巢修补再用。白居易写「早莺争暖树、新燕啄春泥」，两个动词分别对应动物的两个行为学场景：争夺向阳栖位与就地取材筑巢。",
      bodyEn: "Barn swallows build with wet mud mixed with grass and saliva, laid in successive courses into a bowl; once dry the nest is hard, the glycoproteins in saliva acting as binder — a natural composite of mineral aggregate reinforced by fibres. They often return to repair the same nest each year. 「Orioles contend for warm trees」 and 「swallows peck spring mud」 record two behaviours precisely: competing for sun-facing perches, and gathering local material to build.",
    },
    note: "「渐欲」「才能」两个副词最妙——都是「刚刚开始」的程度。英文用 begin to 与 just enough to 保留了分寸。",
    noteEn: "Two adverbs of 「just beginning」 carry the whole early-spring feel.",
  },
  {
    slug: "yinjiu-wu",
    title: "饮酒 · 其五",
    titleEn: "Drinking · V",
    author: "陶渊明",
    authorEn: "Tao Yuanming",
    dynasty: "东晋",
    dynastyEn: "Eastern Jin",
    stage: "初中",
    kind: "诗",
    theme: "田园",
    themeEn: "Pastoral",
    level: 2,
    lines: [
      { zh: "结庐在人境，而无车马喧。", en: "I built my hut among men, yet there is no noise of carriage or horse." },
      { zh: "采菊东篱下，悠然见南山。", en: "Picking chrysanthemums by the eastern fence, at ease I see the southern hills." },
      { zh: "此中有真意，欲辨已忘言。", en: "In all this there is a true meaning — I would explain it, but have already forgotten the words." },
    ],
    keywords: [
      { w: "among men", zh: "在人境（人世间）" },
      { w: "at ease", zh: "悠然" },
      { w: "true meaning", zh: "真意" },
      { w: "forget the words", zh: "忘言" },
    ],
    cross: {
      field: "哲学",
      fieldEn: "Philosophy",
      title: "为什么「忘言」反而是最高评价？",
      titleEn: "Why is forgetting words the highest praise?",
      body: "「欲辨已忘言」化用《庄子·外物》「言者所以在意，得意而忘言」——语言是工具，领悟才是目的；一旦真正领会，工具就可以放下。这与现代认知科学的发现相通：许多体验（尤其审美与身体感受）难以完全命题化，强行描述反而损失信息。陶渊明说的是：真正的体会会说不出话来。采菊见山的一瞬，正是那个状态。",
      bodyEn: "The line draws on Zhuangzi: words exist to convey meaning; once the meaning is grasped, the words may be forgotten. Language is a tool; understanding is the goal. Cognitive science agrees that much of experience — aesthetic and embodied especially — resists full proposition, and forcing description loses information. Tao Yuanming's point: a genuine experience leaves you speechless. Picking chrysanthemums and looking up at the hills is that moment.",
    },
    note: "「见」读 jiàn 还是 xiàn 有争议，但都指向「不经意地望见」——英文用 at ease I see 保留了这份无意。",
    noteEn: "Whether the verb is read as see or appear, the sense is unstudied: at ease I see.",
  },
  {
    slug: "chunwang",
    title: "春望",
    titleEn: "Spring Prospect",
    author: "杜甫",
    authorEn: "Du Fu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "家国",
    themeEn: "Nation",
    level: 2,
    lines: [
      { zh: "国破山河在，城春草木深。", en: "The state is broken, the mountains and rivers remain; the city turns to spring, grass and trees grow deep." },
      { zh: "感时花溅泪，恨别鸟惊心。", en: "Moved by the times, the flowers draw my tears; hating parting, the birds startle my heart." },
      { zh: "烽火连三月，家书抵万金。", en: "Beacon fires have burned for three months on end; a letter from home is worth ten thousand in gold." },
    ],
    keywords: [
      { w: "broken (state)", zh: "残破的（国）" },
      { w: "beacon fire", zh: "烽火（战火）" },
      { w: "on end", zh: "连续不断" },
      { w: "be worth", zh: "值…" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "这首诗写于何时？",
      titleEn: "When was this written?",
      body: "唐肃宗至德二年（757）春，安史之乱爆发后第二年。前一年杜甫把家人安顿在鄜州羌村后北上投奔肃宗，途中被叛军俘至长安，困居城中写下此诗。此时长安已被安禄山部占领、宫室焚掠，史载「宫室焚烧，十不存一」。「国破山河在」五个字，是亲眼见到废墟后写下的事实。",
      bodyEn: "Spring of 757, the second year of the An Lushan rebellion. Having settled his family at Qiangcun in Fuzhou, Du Fu went north to join Emperor Suzong and was captured by the rebels and taken to Chang'an, where he wrote this while trapped. The city had been sacked; records say fewer than one building in ten of the palaces survived. 「The state is broken, the mountains and rivers remain」 is reportage from inside the ruin.",
    },
    note: "「溅泪」「惊心」的主语是花与鸟，也是人——英文用 my tears / my heart 把二者合一。",
    noteEn: "Flowers and birds, or the poet? The English lets both readings stand.",
  },
];
