import type { Poem } from "./types";

/** 初中阶段 · 第 3 批（长调、乐府、诗经、歌行） */
export const JUNIOR_3: Poem[] = [
  {
    slug: "yanmentaishouxing",
    title: "雁门太守行",
    titleEn: "Ballad of the Governor of Yanmen",
    author: "李贺",
    authorEn: "Li He",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "边塞",
    themeEn: "Frontier",
    level: 2,
    lines: [
      { zh: "黑云压城城欲摧，甲光向日金鳞开。", en: "Black clouds press on the city, the city seems about to break; the armour's light turns to the sun, opening golden scales." },
      { zh: "角声满天秋色里，塞上燕脂凝夜紫。", en: "Horn notes fill the sky in autumn colour; on the frontier, rouge-like blood congeals to purple in the night." },
      { zh: "报君黄金台上意，提携玉龙为君死。", en: "To repay the intent of the golden terrace — I take up the jade dragon and will die for you." },
    ],
    keywords: [
      { w: "press on", zh: "（云）压向" },
      { w: "congeal (v.)", zh: "凝结" },
      { w: "to repay", zh: "报答" },
      { w: "take up (arms)", zh: "拿起（武器）" },
    ],
    cross: {
      field: "化学",
      fieldEn: "Chemistry",
      title: "血为什么会「凝夜紫」？",
      titleEn: "Why does blood turn purple at night?",
      body: "血液的红色来自血红蛋白中的亚铁离子与氧结合（氧合血红蛋白呈鲜红）。一旦流出体外，血液凝固：血小板聚集、纤维蛋白原转化为纤维蛋白形成网状凝块，同时红细胞破裂、血红蛋白被氧化为高铁血红蛋白及胆绿素等，颜色由鲜红转为暗红、紫褐，最后呈黑褐色。这是一个真实的化学过程，李贺用「燕脂凝夜紫」写它——以胭脂喻血，是唐诗里最著名的色彩处理之一。",
      bodyEn: "Blood is red because ferrous iron in haemoglobin binds oxygen (oxyhaemoglobin is bright red). Once shed it clots: platelets aggregate, fibrinogen converts to a fibrin mesh, red cells rupture and haemoglobin oxidises to methaemoglobin and biliverdin, so the colour shifts from bright red to dark red, purple-brown, finally blackish. Li He's 「rouge congeals to purple at night」 is that chemistry, and among the most famous colour effects in Tang poetry.",
    },
    note: "李贺写色彩从不写实——「金鳞」「燕脂」「夜紫」层层加浓。英文用 golden scales / rouge / purple 保留了色彩堆叠。",
    noteEn: "Li He's colours are never documentary: golden scales, rouge, purple, laid on thicker each time.",
  },
  {
    slug: "chibi",
    title: "赤壁",
    titleEn: "Red Cliff",
    author: "杜牧",
    authorEn: "Du Mu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "咏史",
    themeEn: "History",
    level: 2,
    lines: [
      { zh: "折戟沉沙铁未销，自将磨洗认前朝。", en: "A broken halberd buried in sand, its iron not yet consumed; I take it up, grind and wash it, and read the former dynasty." },
      { zh: "东风不与周郎便，铜雀春深锁二乔。", en: "Had the east wind not done Zhou a favour, the Bronze Sparrow Terrace in deep spring would have locked away the two Qiaos." },
    ],
    keywords: [
      { w: "halberd (n.)", zh: "戟（古代兵器）" },
      { w: "consume (v.)", zh: "（锈蚀）消尽" },
      { w: "grind and wash", zh: "磨洗" },
      { w: "do sb. a favour", zh: "给某人方便" },
    ],
    cross: {
      field: "气象",
      fieldEn: "Meteorology",
      title: "赤壁之战真的靠东风吗？",
      titleEn: "Did the Battle of Red Cliff really depend on an east wind?",
      body: "公元 208 年冬，孙刘联军以火攻破曹军于赤壁。火攻能否成功取决于风向——曹军在北岸（乌林），周瑜在南岸，需要东南风才能把火船吹向敌营。长江中游冬季盛行偏北风，但冷暖气流交替时确实会出现短暂的东南风天气（锋面气旋过境时的风向转变）。所以「东风」不是传说，是一次可遇不可求的天气窗口，火攻的关键正在于抓住它。",
      bodyEn: "In the winter of 208 the allied forces of Sun and Liu burned Cao Cao's fleet at Red Cliff. Success depended on wind direction: Cao's camp lay on the north bank (Wulin), Zhou Yu's to the south, so a south-easterly was needed to drive fire-ships onto the enemy. The middle Yangtze favours northerlies in winter, but brief south-easterlies do occur as fronts pass. The east wind was not legend — it was a rare weather window, and seizing it was the whole point of the fire attack.",
    },
    note: "「铜雀春深锁二乔」是反事实假设——英文用 Had… not 的虚拟语气，正好对应这种「如果不是」。",
    noteEn: "A counterfactual — English carries it with the subjunctive Had … not.",
  },
  {
    slug: "yujiaao-qiusi",
    title: "渔家傲 · 秋思",
    titleEn: "Yujiaao · Autumn Thoughts",
    author: "范仲淹",
    authorEn: "Fan Zhongyan",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "初中",
    kind: "词",
    theme: "边塞",
    themeEn: "Frontier",
    level: 2,
    lines: [
      { zh: "塞下秋来风景异，衡阳雁去无留意。", en: "Autumn comes to the frontier, the scene unlike any other; the geese leave for Hengyang without a thought of staying." },
      { zh: "浊酒一杯家万里，燕然未勒归无计。", en: "One cup of cloudy wine, home ten thousand li away; Yanran not yet inscribed — no plan for returning." },
      { zh: "人不寐，将军白发征夫泪。", en: "Men cannot sleep: the general's white hair, the soldier's tears." },
    ],
    keywords: [
      { w: "without a thought of", zh: "毫无…之意" },
      { w: "cloudy wine", zh: "浊酒（未滤的酒）" },
      { w: "inscribe (v.)", zh: "刻石记功（勒石）" },
      { w: "no plan for", zh: "无从（归计）" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "「燕然未勒」是什么典故？",
      titleEn: "What is the Yanran allusion?",
      body: "东汉永元元年（89），窦宪率军大破北匈奴，登燕然山（今蒙古杭爱山）刻石记功，由班固撰写《封燕然山铭》。2017 年，中蒙联合考古队在蒙古国杭爱山确认发现了这处摩崖石刻，与史书记载吻合。「燕然未勒」遂成为「功业未成、不能回家」的代称。范仲淹任陕西经略副使时写下此词，那是真实的边防职务，不是文人想象。",
      bodyEn: "In 89 CE Dou Xian crushed the Northern Xiongnu and ascended Mount Yanran (the Khangai range in Mongolia) to carve a record of victory, the inscription composed by Ban Gu. A joint Chinese–Mongolian team rediscovered the cliff inscription in 2017, matching the histories. 「Yanran not yet inscribed」 came to mean the task unfinished, home impossible. Fan Zhongyan wrote this while serving as deputy military commissioner in Shaanxi — real frontier duty, not literary fantasy.",
    },
    note: "「将军白发征夫泪」是全词的落点——不是豪情，是消耗。英文用 the general's white hair, the soldier's tears 保留并置。",
    noteEn: "It ends not on heroism but attrition: white hair and tears, set side by side.",
  },
  {
    slug: "jiangchengzi-mizhou",
    title: "江城子 · 密州出猎",
    titleEn: "Jiangchengzi · Hunting at Mizhou",
    author: "苏轼",
    authorEn: "Su Shi",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "初中",
    kind: "词",
    theme: "家国",
    themeEn: "Nation",
    level: 2,
    lines: [
      { zh: "老夫聊发少年狂，左牵黄，右擎苍。", en: "Let this old man give way to a young man's madness: on the left a yellow hound, on the wrist a grey falcon." },
      { zh: "会挽雕弓如满月，西北望，射天狼。", en: "I shall draw the carved bow to a full moon, look north-west, and shoot at the Wolf." },
    ],
    keywords: [
      { w: "give way to", zh: "姑且抒发" },
      { w: "hound (n.)", zh: "猎犬（黄犬）" },
      { w: "falcon (n.)", zh: "苍鹰" },
      { w: "draw a bow", zh: "拉弓" },
    ],
    cross: {
      field: "天文",
      fieldEn: "Astronomy",
      title: "天狼星指什么？",
      titleEn: "What is the Wolf star?",
      body: "天狼（大犬座 α 星，Sirius）是夜空中最亮的恒星，视星等 −1.46，距地球约 8.6 光年。在中国星官体系中它属井宿，被视为「主侵掠」的凶星；苏轼的「西北望，射天狼」用的是这个传统意象——北宋中期西北方向的西夏正是最大边患。同时代的「弧矢」星官（弓箭）正对着天狼，所以射天狼在星图上是有成说的。",
      bodyEn: "Sirius (alpha Canis Majoris) is the brightest star in the night sky, magnitude −1.46, about 8.6 light-years away. In Chinese star lore it belonged to the Well mansion and presaged raid and plunder, so Su Shi's 「look north-west and shoot the Wolf」 draws on that tradition — the north-west being where the Western Xia threatened Song. A neighbouring asterism, the Bow and Arrow, points straight at Sirius, so shooting it was an established figure.",
    },
    note: "「老夫」其实才四十岁——自称老，是宋人写豪放词的一种姿态。英文用 this old man 保留了自嘲。",
    noteEn: "He was only forty: calling himself old is a stylised swagger.",
  },
  {
    slug: "shuidiaogetou",
    title: "水调歌头 · 明月几时有",
    titleEn: "Shuidiaogetou · When Did the Bright Moon First Appear",
    author: "苏轼",
    authorEn: "Su Shi",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "初中",
    kind: "词",
    theme: "咏月",
    themeEn: "The Moon",
    level: 2,
    lines: [
      { zh: "明月几时有？把酒问青天。", en: "When did the bright moon first appear? Cup in hand, I ask the blue sky." },
      { zh: "人有悲欢离合，月有阴晴圆缺，此事古难全。", en: "Men have sorrow and joy, parting and meeting; the moon has dark and clear, waxing and waning — this has never been complete since ancient times." },
      { zh: "但愿人长久，千里共婵娟。", en: "I only wish that we may live long — though a thousand li apart, sharing the same lovely moon." },
    ],
    keywords: [
      { w: "waxing and waning", zh: "（月）圆缺、盈亏" },
      { w: "parting and meeting", zh: "离合" },
      { w: "never complete", zh: "难以圆满" },
      { w: "share (the moon)", zh: "共赏" },
    ],
    cross: {
      field: "天文",
      fieldEn: "Astronomy",
      title: "千里之外真能共赏一轮月吗？",
      titleEn: "Can people a thousand li apart share one moon?",
      body: "基本可以。月亮距地球约 38 万公里，而地面上相距千里的两地（视角差不过十几度）看到的月球几乎同一面、同一相位；严格说会有极小的视差（月面相对于背景星的位置略偏），但肉眼无法分辨。所以「千里共婵娟」在几何上是站得住的——这也是为什么月亮成了中国古代最常见的情感共享物：它几乎是唯一真正「共时共见」的天体。",
      bodyEn: "Very nearly. The moon is some 380,000 km away; two places a thousand li apart differ in viewing angle by only a dozen degrees, so they see the same face at the same phase. Strictly there is a tiny parallax — the moon shifts slightly against the background stars — but the eye cannot detect it. This is why the moon became China's great shared object: it is almost the only celestial body genuinely seen at once by everyone.",
    },
    note: "「此事古难全」是全词的理性核心——先承认不圆满，才谈得上下一句的祝愿。",
    noteEn: "The rational core: admit that nothing is complete, then wish well anyway.",
  },
  {
    slug: "xinglunan",
    title: "行路难 · 其一",
    titleEn: "The Way Is Hard · I",
    author: "李白",
    authorEn: "Li Bai",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "人生",
    themeEn: "Life",
    level: 2,
    lines: [
      { zh: "停杯投箸不能食，拔剑四顾心茫然。", en: "I set down the cup and throw down the chopsticks, unable to eat; I draw my sword and look about — my heart is at a loss." },
      { zh: "欲渡黄河冰塞川，将登太行雪满山。", en: "I would cross the Yellow River, but ice chokes the stream; I would climb Taihang, but snow fills the hills." },
      { zh: "长风破浪会有时，直挂云帆济沧海。", en: "There will be a time when a great wind breaks the waves: I shall hoist a cloud-white sail and cross the dark sea." },
    ],
    keywords: [
      { w: "choke (v.)", zh: "堵塞（冰塞川）" },
      { w: "at a loss", zh: "茫然" },
      { w: "break the waves", zh: "破浪" },
      { w: "cross (the sea)", zh: "渡（济）" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "黄河真的会冰封吗？",
      titleEn: "Does the Yellow River really freeze over?",
      body: "会。黄河上游（宁夏、内蒙古河段）冬季气温可低至 −20℃ 以下，河面封冻，冰厚可达数十厘米；每年春季解冻时，上游先融、下游仍封，冰块堆积形成「凌汛」，是黄河特有的洪灾类型。李白用「冰塞川」与「雪满山」把自然障碍写成人生障碍——这两条路他确实走过：出长安东行要渡黄河、过太行。",
      bodyEn: "Yes. On the upper reaches (Ningxia and Inner Mongolia) winter temperatures fall below −20℃ and the river freezes tens of centimetres thick. In spring the upper river thaws before the lower, and ice jams produce the 「ice flood」 peculiar to the Yellow River. Li Bai turns these obstacles into life's obstacles along a route he actually travelled: east from Chang'an crossing the Yellow River and Taihang.",
    },
    note: "情绪走了一个完整的 V 形：茫然 → 受阻 → 忽然振作。英文用 There will be a time 把最后的上扬立住。",
    noteEn: "The mood traces a V: at a loss, blocked, then sudden resolve.",
  },
  {
    slug: "chouletian",
    title: "酬乐天扬州初逢席上见赠",
    titleEn: "Replying to Bai Juyi at Our First Meeting in Yangzhou",
    author: "刘禹锡",
    authorEn: "Liu Yuxi",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "人生",
    themeEn: "Life",
    level: 2,
    lines: [
      { zh: "巴山楚水凄凉地，二十三年弃置身。", en: "The hills of Ba and waters of Chu, a desolate land — twenty-three years, a discarded man." },
      { zh: "沉舟侧畔千帆过，病树前头万木春。", en: "Beside the sunken boat a thousand sails pass on; before the sick tree, ten thousand trees are spring." },
    ],
    keywords: [
      { w: "desolate (adj.)", zh: "凄凉的" },
      { w: "discarded (adj.)", zh: "被弃置的" },
      { w: "sunken boat", zh: "沉舟" },
      { w: "pass on", zh: "驶过、继续前行" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "「病树前头万木春」符合生态规律吗？",
      titleEn: "Is 「ten thousand trees in spring」 ecologically sound?",
      body: "符合，而且相当深刻。森林生态中，枯立木（snag）与倒木是更新的重要条件：它们死后释放养分、形成林窗，让阳光到达地面，幼苗得以生长；腐朽的木质还是真菌、昆虫与鸟类的栖息地。所以一棵树的衰亡恰恰是下一代生长的前提——生态学上叫林窗动态（gap dynamics）。刘禹锡不是比喻，他观察到了森林更新的真实机制。",
      bodyEn: "Remarkably so. In forest ecology, standing dead and fallen trees are engines of renewal: they release nutrients, open gaps in the canopy so light reaches the floor, and let seedlings establish; decaying wood hosts fungi, insects and cavity-nesting birds. One tree's decline is the next generation's precondition — what ecologists call gap dynamics. Liu Yuxi was not merely inventing an image; he had seen how a forest regenerates.",
    },
    note: "「二十三年」是实指——他被贬外放整整二十三年。数字越精确，后面「千帆过」「万木春」的豁达越有分量。",
    noteEn: "The twenty-three years are literal. Precision gives the magnanimity its weight.",
  },
  {
    slug: "wuti-xiangjian",
    title: "无题 · 相见时难别亦难",
    titleEn: "Untitled · Hard to Meet, Hard to Part",
    author: "李商隐",
    authorEn: "Li Shangyin",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "人生",
    themeEn: "Life",
    level: 2,
    lines: [
      { zh: "相见时难别亦难，东风无力百花残。", en: "Hard to meet, and hard to part; the east wind is spent and a hundred flowers wither." },
      { zh: "春蚕到死丝方尽，蜡炬成灰泪始干。", en: "The spring silkworm spins until death before its thread is done; the candle's tears dry only when it turns to ash." },
    ],
    keywords: [
      { w: "spent (adj.)", zh: "（风）无力的、衰竭的" },
      { w: "wither (v.)", zh: "凋残" },
      { w: "spin (v.)", zh: "（蚕）吐丝" },
      { w: "turn to ash", zh: "化为灰烬" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "春蚕真的到死才吐完丝吗？",
      titleEn: "Does a silkworm really spin until it dies?",
      body: "基本准确。家蚕（Bombyx mori）五龄末期，体内丝腺已充满液态丝素，蚕开始吐丝结茧，连续约 2—3 天吐出 1000—1500 米长的丝，把丝腺排空后在茧内化蛹。严格说它「吐完丝」后仍活着（化为蛹），并非丝尽即死；但茧化成蛾后口器退化、不再进食，数日内死亡。李商隐取的是常识印象，却极为贴切：丝腺排空意味着幼虫阶段的终结。",
      bodyEn: "Close enough. At the end of its fifth instar the silkworm's silk glands are packed with liquid fibroin; it spins a cocoon for two to three days, laying down 1,000–1,500 m of filament, empties the glands and pupates. Strictly it survives the spinning — it becomes a pupa rather than dying — though the moth, with vestigial mouthparts, cannot feed and dies in days. Li Shangyin uses the common impression, and aptly: emptying the gland ends the larval life.",
    },
    note: "「丝」谐音「思」，是汉语特有的双关——英文无法复制，只能靠 spin 与 thread 保留「持续不断」的意象。",
    noteEn: "Silk (丝) puns with longing (思) — untranslatable; English keeps only the image of an unending thread.",
  },
  {
    slug: "songdushaofu",
    title: "送杜少府之任蜀州",
    titleEn: "Seeing Off Vice-Magistrate Du to Shu Prefecture",
    author: "王勃",
    authorEn: "Wang Bo",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "送别",
    themeEn: "Farewell",
    level: 2,
    lines: [
      { zh: "城阙辅三秦，风烟望五津。", en: "The palace walls are guarded by the three Qins; through wind and mist we gaze toward the five fords." },
      { zh: "海内存知己，天涯若比邻。", en: "Within the four seas there is one who knows your heart, and the world's far edge is like next door." },
    ],
    keywords: [
      { w: "palace walls", zh: "城阙（指长安）" },
      { w: "ford (n.)", zh: "渡口" },
      { w: "one who knows your heart", zh: "知己" },
      { w: "next door", zh: "比邻" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "三秦与五津在哪里？",
      titleEn: "Where are the three Qins and the five fords?",
      body: "三秦指关中一带：项羽灭秦后把关中分为雍、塞、翟三国，故称三秦，即长安所在。五津是岷江上的五个渡口（白华津、万里津、江首津、涉头津、江南津），在今四川，代指杜少府赴任的蜀州。长安到成都直线约 600 公里，实际走金牛道（经汉中、剑门）超过 1000 公里，翻越秦岭与大巴山——「天涯」不是夸张，是地理事实。",
      bodyEn: "The three Qins are the Guanzhong region: after destroying Qin, Xiang Yu split it into three kingdoms (Yong, Sai, Di), hence the name — the area of Chang'an. The five fords are crossings on the Min River in Sichuan, standing for Shu, where Du was posted. Straight-line distance from Chang'an to Chengdu is about 600 km, but the route — the Jinniu road through Hanzhong and Jianmen, over the Qinling and Daba ranges — exceeded 1,000 km. 「The world's far edge」 is geography, not hyperbole.",
    },
    note: "「天涯若比邻」是初唐罕见的开阔——英文用 the world's far edge is like next door 保留了空间对心理的改写。",
    noteEn: "Distance rewritten by affection: the far edge becomes next door.",
  },
  {
    slug: "wangdongtinghu",
    title: "望洞庭湖赠张丞相",
    titleEn: "Gazing at Dongting Lake: For Chancellor Zhang",
    author: "孟浩然",
    authorEn: "Meng Haoran",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "干谒",
    themeEn: "Seeking Office",
    level: 2,
    lines: [
      { zh: "气蒸云梦泽，波撼岳阳城。", en: "Its vapour steams the Yunmeng marshes; its waves shake the walls of Yueyang." },
      { zh: "欲济无舟楫，端居耻圣明。", en: "I would cross over, but have no boat or oar; to sit idle at home shames an enlightened age." },
      { zh: "坐观垂钓者，徒有羡鱼情。", en: "I sit and watch the angler, with nothing but envy for the fish." },
    ],
    keywords: [
      { w: "steam (v.)", zh: "（水汽）蒸腾" },
      { w: "shake (v.)", zh: "撼动" },
      { w: "idle (adj.)", zh: "闲居的" },
      { w: "envy (n.)", zh: "羡慕（羡鱼情）" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "云梦泽是什么地方？",
      titleEn: "What was the Yunmeng marsh?",
      body: "云梦泽是先秦至唐宋时期江汉平原上的大型湖泊沼泽群，范围极广（先秦时面积可达上万平方公里）。由于长江与汉水携带的泥沙长期淤积、加上围垦，云梦泽逐渐萎缩分解，今天的江汉平原上散布的洪湖、梁子湖等就是它的残余；洞庭湖面积也从历史上的数千平方公里缩到今天的约 2600 平方公里。孟浩然写「气蒸云梦泽」时，它仍是水汽蒸腾的巨大水面。",
      bodyEn: "Yunmeng was a vast complex of lakes and marshes on the Jianghan plain from pre-Qin to Tang times — at its largest perhaps ten thousand square kilometres. Sediment from the Yangtze and Han plus land reclamation shrank and fragmented it; today's Honghu and Liangzi lakes are remnants, and Dongting itself has contracted from several thousand square kilometres to roughly 2,600. When Meng Haoran wrote of its steaming vapours, it was still a great sheet of water.",
    },
    note: "这是一首「求职诗」——通篇写湖，最后两句才说出目的。英文用 I would cross over, but 保留了这个委婉转折。",
    noteEn: "A job application in verse: lake, lake, lake, then the request.",
  },
  {
    slug: "maowu",
    title: "茅屋为秋风所破歌",
    titleEn: "My Thatched Roof Is Ruined by the Autumn Wind",
    author: "杜甫",
    authorEn: "Du Fu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "家国",
    themeEn: "Nation",
    level: 2,
    lines: [
      { zh: "八月秋高风怒号，卷我屋上三重茅。", en: "In the eighth month, autumn sky high, the wind howls in rage and rolls up the three layers of thatch on my roof." },
      { zh: "安得广厦千万间，大庇天下寒士俱欢颜，风雨不动安如山。", en: "How might I get a thousand, ten thousand spacious halls, to shelter all the poor scholars under heaven and make them beam with joy — unmoved by wind or rain, firm as a mountain?" },
      { zh: "呜呼！何时眼前突兀见此屋，吾庐独破受冻死亦足！", en: "Alas — when shall such houses suddenly stand before my eyes? Then, though my own hut alone were ruined and I froze to death, it would be enough!" },
    ],
    keywords: [
      { w: "howl (v.)", zh: "（风）怒号" },
      { w: "roll up", zh: "卷起" },
      { w: "shelter (v.)", zh: "庇护" },
      { w: "firm as a mountain", zh: "安如山" },
    ],
    cross: {
      field: "气象",
      fieldEn: "Meteorology",
      title: "秋风为什么能掀翻茅草屋顶？",
      titleEn: "Why can autumn wind strip a thatched roof?",
      body: "原理是伯努利效应与压力差：气流经过屋顶时流速快、压强低，屋内气压相对较高，产生向上的净升力；茅草屋顶自重轻、靠草绳绑扎，一旦边缘被掀起就会连锁剥离。杜甫的草堂在成都浣花溪畔，当地秋季多阵性大风（西南地区秋风常伴冷空气南下）。屋顶被毁后「床头屋漏无干处」，是真实的居住困境，也是全诗推己及人的起点。",
      bodyEn: "Bernoulli's principle: air moving over a roof is fast and low-pressure, while pressure indoors stays higher, producing net lift. A thatch roof is light and bound with grass cord, so once an edge lifts the stripping cascades. Du Fu's cottage stood by the Flower Rinsing Brook at Chengdu, where autumn brings gusty winds as cold air pushes south from the plateau. The ruined roof, dripping everywhere, is a real predicament — and the point from which the poem widens to everyone.",
    },
    note: "从「我的屋顶破了」推到「天下寒士」，是杜甫最伟大的一步——英文用 though my own hut alone were ruined 保留了这个递进。",
    noteEn: "From my ruined roof to all poor scholars: the leap that makes Du Fu great.",
  },
  {
    slug: "maitanweng",
    title: "卖炭翁",
    titleEn: "The Old Charcoal Seller",
    author: "白居易",
    authorEn: "Bai Juyi",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "悯农",
    themeEn: "Labour",
    level: 2,
    lines: [
      { zh: "满面尘灰烟火色，两鬓苍苍十指黑。", en: "His face is dust and ash, the colour of smoke; his temples are grey, his ten fingers black." },
      { zh: "可怜身上衣正单，心忧炭贱愿天寒。", en: "Pitiful: his clothes are thin, yet dreading cheap charcoal he prays for cold weather." },
      { zh: "半匹红绡一丈绫，系向牛头充炭直。", en: "Half a bolt of red silk, a length of damask — tied to the ox's head as payment for the charcoal." },
    ],
    keywords: [
      { w: "charcoal (n.)", zh: "木炭" },
      { w: "temple (n.)", zh: "鬓角" },
      { w: "dread (v.)", zh: "担忧" },
      { w: "payment (n.)", zh: "（炭的）价钱" },
    ],
    cross: {
      field: "化学",
      fieldEn: "Chemistry",
      title: "木炭是怎么烧出来的？",
      titleEn: "How is charcoal made?",
      body: "木材在隔绝空气（或限氧）条件下加热到约 400—700℃，发生热解：纤维素、半纤维素与木质素分解，析出水分、醋酸、甲醇和木煤气等挥发分，剩下的主要是碳（含碳量可达 80%—90%），这就是木炭。因为挥发分已除去，木炭燃烧时无烟、火焰小、放热集中，热值约 30 MJ/kg，比木材高得多——所以唐代长安冬天取暖首选木炭，也才有「宫市」强买的故事。",
      bodyEn: "Wood heated to roughly 400–700℃ without air undergoes pyrolysis: cellulose, hemicellulose and lignin break down, driving off water, acetic acid, methanol and wood gas, leaving mostly carbon — charcoal is 80–90% carbon. With volatiles gone it burns nearly smokeless with a small flame and concentrated heat, around 30 MJ/kg versus far less for raw wood. That is why Tang Chang'an warmed itself with charcoal, and why the palace market could extort it.",
    },
    note: "「愿天寒」三个字最残酷——老人盼着冷，才能把炭卖出去。英文用 he prays for cold weather 保留了这个悖论。",
    noteEn: "The cruellest line: he prays for cold so that his charcoal will sell.",
  },
  {
    slug: "guanju",
    title: "诗经 · 关雎",
    titleEn: "Book of Songs · Guan Ju",
    author: "《诗经》",
    authorEn: "Book of Songs",
    dynasty: "先秦",
    dynastyEn: "Pre-Qin",
    stage: "初中",
    kind: "诗",
    theme: "爱情",
    themeEn: "Love",
    level: 2,
    lines: [
      { zh: "关关雎鸠，在河之洲。窈窕淑女，君子好逑。", en: "Guan, guan cry the ospreys, on the islet in the river. The gentle and lovely girl is a fine match for the gentleman." },
      { zh: "参差荇菜，左右流之。窈窕淑女，寤寐求之。", en: "Ragged are the water-mallows; left and right one gathers them. The gentle and lovely girl — waking and sleeping he seeks her." },
    ],
    keywords: [
      { w: "osprey (n.)", zh: "雎鸠（水鸟）" },
      { w: "islet (n.)", zh: "（河）洲、小岛" },
      { w: "match (n.)", zh: "配偶、匹配" },
      { w: "waking and sleeping", zh: "寤寐、日夜" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "雎鸠是什么鸟？",
      titleEn: "What bird is the osprey?",
      body: "雎鸠一般释为鱼鹰（鹗，osprey），是大型食鱼猛禽，常成对活动、配偶关系稳定，并会长期沿用同一巢。古人正是看中它「挚而有别」「雌雄情意专一」的行为特征，才用它起兴引出婚姻主题——这叫「兴」。《诗经》里的动植物起兴往往有据：荇菜是真实的水生植物（莕菜），可食，采摘也是实际的劳动。",
      bodyEn: "The bird is usually identified as the osprey, a large fish-eating raptor that pairs for life, stays with one mate and reuses its nest for years. Classical commentators prized it as faithful and thus a fitting opening for a marriage poem — the device of 「xing」, the affective image. The botany is equally real: the water-mallow is an edible aquatic plant, and gathering it actual work.",
    },
    note: "「关关」是拟声（鸟鸣），「参差」是形态——英文用 Guan, guan 与 Ragged 分别对应声音与形状。",
    noteEn: "Sound and shape: Guan, guan for the cry; ragged for the plant.",
  },
  {
    slug: "jianjia",
    title: "诗经 · 蒹葭",
    titleEn: "Book of Songs · The Reeds",
    author: "《诗经》",
    authorEn: "Book of Songs",
    dynasty: "先秦",
    dynastyEn: "Pre-Qin",
    stage: "初中",
    kind: "诗",
    theme: "爱情",
    themeEn: "Love",
    level: 2,
    lines: [
      { zh: "蒹葭苍苍，白露为霜。所谓伊人，在水一方。", en: "The reeds are dense and green; white dew has turned to frost. The one I speak of is on the other side of the water." },
      { zh: "溯洄从之，道阻且长。溯游从之，宛在水中央。", en: "Going upstream to seek her, the way is hard and long; going downstream to seek her, she seems there in mid-stream." },
    ],
    keywords: [
      { w: "reed (n.)", zh: "芦苇" },
      { w: "upstream (adv.)", zh: "溯洄、逆流而上" },
      { w: "downstream (adv.)", zh: "溯游、顺流而下" },
      { w: "seem (v.)", zh: "仿佛、宛然" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "白露为什么会「为霜」？",
      titleEn: "Why does white dew become frost?",
      body: "霜与露的形成条件只差温度：当近地物体表面温度降到 0℃ 以下，空气中的水汽直接凝华成冰晶，就是霜；若表面温度高于 0℃，水汽凝结成液态，就是露。秋季晴朗无风的夜晚，地面辐射散热强烈（辐射冷却），温度可降到 0℃ 以下——所以《诗经》把「白露为霜」与深秋清晨对应得极准确，也暗含了时间的推移。",
      bodyEn: "Dew and frost differ only in temperature. If a surface cools below 0℃, water vapour deposits directly as ice crystals — frost; above 0℃ it condenses as liquid — dew. On clear, calm autumn nights the ground loses heat by radiation and can fall below freezing. The Book of Songs thus links white dew, frost and a late-autumn dawn with real precision, and the change also marks time passing.",
    },
    note: "全诗三章只换几个字（苍苍、萋萋、采采），是《诗经》重章叠句的典型——英文用重复的句法保留了这个回环。",
    noteEn: "Three stanzas differing by a word or two: the Book of Songs' signature refrain.",
  },
  {
    slug: "guisushou",
    title: "龟虽寿",
    titleEn: "Though the Tortoise Lives Long",
    author: "曹操",
    authorEn: "Cao Cao",
    dynasty: "东汉",
    dynastyEn: "Eastern Han",
    stage: "初中",
    kind: "诗",
    theme: "人生",
    themeEn: "Life",
    level: 2,
    lines: [
      { zh: "老骥伏枥，志在千里。烈士暮年，壮心不已。", en: "An old warhorse in the stable still dreams of a thousand li; a man of resolve in his late years does not still his great heart." },
      { zh: "盈缩之期，不但在天；养怡之福，可得永年。", en: "The span of life is not decreed by heaven alone; the blessing of a well-tended life can lengthen one's years." },
    ],
    keywords: [
      { w: "warhorse (n.)", zh: "（老）骥、战马" },
      { w: "stable (n.)", zh: "马槽、厩" },
      { w: "man of resolve", zh: "烈士（有抱负的人）" },
      { w: "lengthen one's years", zh: "延年益寿" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "乌龟真的能活很久吗？",
      titleEn: "Do tortoises really live long?",
      body: "能。龟类以长寿著称，加拉帕戈斯象龟可活 100 年以上，已记录的个体寿命超过 170 年。原因包括：基础代谢率极低、端粒缩短速度慢、细胞抗氧化能力强，以及坚硬的甲壳带来的低捕食压力。诗里曹操用「神龟虽寿，犹有竟时」起兴，正是承认长寿也有尽头，然后把重点转到人：寿命有限，志气不受限。",
      bodyEn: "Yes. Tortoises are famously long-lived: Galápagos tortoises exceed a century, with recorded individuals past 170 years. Reasons include a very low basal metabolic rate, slow telomere shortening, strong cellular antioxidant defences, and the low predation pressure that a shell confers. Cao Cao opens with the divine tortoise precisely to concede that even long life ends — then shifts the argument to what does not: resolve.",
    },
    note: "曹操写此诗时约五十三岁，正是「老骥伏枥」的年纪——英文用 still dreams of a thousand li 把「志在千里」译成了主动的愿望。",
    noteEn: "He was around fifty-three — old horse, thousand li, still.",
  },
];
