import type { Poem } from "./types";

/** 初中阶段 · 第 6 批（宋词名篇 + 先秦两汉寓言） */
export const JUNIOR_6: Poem[] = [
  {
    slug: "qingleyuncunju",
    title: "清平乐·村居",
    titleEn: "Qingpingyue: Village Life",
    author: "辛弃疾",
    authorEn: "Xin Qiji",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "初中",
    kind: "词",
    theme: "田园",
    themeEn: "Pastoral",
    level: 1,
    lines: [
      { zh: "茅檐低小，溪上青青草。", en: "Low eaves of thatch; above the stream, grass fresh and green." },
      { zh: "醉里吴音相媚好，白发谁家翁媪？", en: "Tipsy, in soft Wu accents they tease each other fondly — whose white-haired old couple is this?" },
      { zh: "大儿锄豆溪东，中儿正织鸡笼。", en: "The eldest hoes beans east of the creek; the middle one is weaving a chicken coop." },
      { zh: "最喜小儿亡赖，溪头卧剥莲蓬。", en: "Best of all, the young scamp lies at the creek's head, peeling a lotus pod." },
    ],
    keywords: [
      { w: "thatch", zh: "茅草" },
      { w: "coop", zh: "笼子" },
      { w: "lotus pod", zh: "莲蓬" },
      { w: "scamp", zh: "顽皮孩子" },
    ],
    note: "一家五口没有一句对话，但每一笔都有声音。「亡赖」即「无赖」，是疼爱的骂。",
    noteEn: "Not one line of dialogue in a household of five, yet every stroke has sound in it. 「亡赖」 is 「无赖」 — a scolding made of affection.",
  },
  {
    slug: "xijiangyue",
    title: "西江月·夜行黄沙道中",
    titleEn: "Xijiangyue: Night March on the Huangsha Road",
    author: "辛弃疾",
    authorEn: "Xin Qiji",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "初中",
    kind: "词",
    theme: "田园",
    themeEn: "Pastoral",
    level: 2,
    lines: [
      { zh: "明月别枝惊鹊，清风半夜鸣蝉。", en: "The bright moon startles magpies from a branch; a cool wind brings midnight cicadas." },
      { zh: "稻花香里说丰年，听取蛙声一片。", en: "Amid the fragrance of rice flowers, talk of a good harvest — and a whole field of frogs to listen to." },
      { zh: "七八个星天外，两三点雨山前。", en: "Seven or eight stars beyond the sky's edge; two or three raindrops before the hill." },
      { zh: "旧时茅店社林边，路转溪桥忽见。", en: "The old thatched inn by the temple grove — the path turns, a creek bridge, and suddenly there it is." },
    ],
    keywords: [
      { w: "startle", zh: "惊起" },
      { w: "harvest", zh: "丰收" },
      { w: "thatched inn", zh: "茅店" },
    ],
    note: "数星星、数雨点，都是数得清的；「忽见」两个字里全是重逢的意外之喜。",
    noteEn: "Counting stars, counting raindrops — all countable. The joy hides in 'suddenly there it is'.",
  },
  {
    slug: "pozhenzi",
    title: "破阵子·为陈同甫赋壮词以寄之",
    titleEn: "Pozhenzi: A Strong Song for Chen Tongfu",
    author: "辛弃疾",
    authorEn: "Xin Qiji",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "初中",
    kind: "词",
    theme: "豪情",
    themeEn: "Heroic Dreams",
    level: 3,
    lines: [
      { zh: "醉里挑灯看剑，梦回吹角连营。", en: "Drunk, I trim the lamp and study my sword; in dreams, horns blow through camp after camp." },
      { zh: "八百里分麾下炙，五十弦翻塞外声，沙场秋点兵。", en: "Roast beef shared among the ranks; fifty strings play the tunes beyond the passes — on the autumn battlefield, the troops are drawn up." },
      { zh: "马作的卢飞快，弓如霹雳弦惊。", en: "Horses fly like Dilu; bows crack like thunder-claps." },
      { zh: "了却君王天下事，赢得生前身后名。可怜白发生！", en: "Settle the realm for the sovereign, win renown in life and after — and then, how pitiable: white hair has already grown." },
    ],
    keywords: [
      { w: "sword", zh: "剑" },
      { w: "horn", zh: "号角" },
      { w: "thunder-clap", zh: "霹雳" },
      { w: "renown", zh: "名声" },
    ],
    note: "前九句一口气没换，最后五个字把梦摁灭。壮词是壮的，作者是疼的。",
    noteEn: "Nine lines in one breath, then five characters snuff the dream out. The song is strong; the writer is in pain.",
  },
  {
    slug: "busuanzi-me",
    title: "卜算子·咏梅",
    titleEn: "Busuanzi: On the Plum",
    author: "陆游",
    authorEn: "Lu You",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "初中",
    kind: "词",
    theme: "咏物",
    themeEn: "Integrity",
    level: 2,
    lines: [
      { zh: "驿外断桥边，寂寞开无主。", en: "Beyond the post-station, by a broken bridge, it blooms alone with no one to claim it." },
      { zh: "已是黄昏独自愁，更著风和雨。", en: "Dusk already, and sorrowing by itself — and now wind and rain on top of it." },
      { zh: "无意苦争春，一任群芳妒。", en: "It has no wish to fight for spring; let the other flowers be jealous." },
      { zh: "零落成泥碾作尘，只有香如故。", en: "Fallen, trodden to mud, ground to dust — still the fragrance is as it always was." },
    ],
    keywords: [
      { w: "post-station", zh: "驿站" },
      { w: "be jealous", zh: "妒忌" },
      { w: "fragrance", zh: "香气" },
      { w: "grind to dust", zh: "碾作尘" },
    ],
    note: "「只有香如故」五个字可以当墓志铭。陆游写梅花，一句也没离开自己。",
    noteEn: "'Still the fragrance is as it always was' could serve as an epitaph. Lu You writes of the plum without once leaving himself.",
  },
  {
    slug: "busuanzi-changjiang",
    title: "卜算子·我住长江头",
    titleEn: "Busuanzi: I Live at the River's Head",
    author: "李之仪",
    authorEn: "Li Zhiyi",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "初中",
    kind: "词",
    theme: "爱情",
    themeEn: "Love",
    level: 2,
    lines: [
      { zh: "我住长江头，君住长江尾。", en: "I live where the river begins; you live where it ends." },
      { zh: "日日思君不见君，共饮长江水。", en: "Daily I think of you and do not see you — though we drink from the same river." },
      { zh: "此水几时休，此恨何时已。", en: "When will this water ever stop? When will this longing ever end?" },
      { zh: "只愿君心似我心，定不负相思意。", en: "May only your heart be like my heart — then this love will not have been in vain." },
    ],
    keywords: [
      { w: "where the river begins", zh: "江头" },
      { w: "in vain", zh: "辜负" },
      { w: "longing", zh: "思念" }
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "长江头和长江尾有多远？",
      titleEn: "How far apart are the river's head and tail?",
      body: "长江全长约6300公里，源头在青海唐古拉山，入海口在上海。「共饮长江水」在地理上完全成立——同一条流域，上中下游的水是连通的。这是中国最长的一条相思线。",
      bodyEn: "The Yangtze runs about 6,300 km, from the Tanggula Mountains in Qinghai to the sea near Shanghai. 'Drinking from the same river' is hydrologically literal: one watershed, connected water. The longest love-line a river can draw.",
    },
    note: "用一条六千公里的江当信使——这是汉语里最长的异地恋情书。",
    noteEn: "A six-thousand-kilometre river as messenger: the longest long-distance love letter in the language.",
  },
  {
    slug: "zuihuayin",
    title: "醉花阴·薄雾浓云愁永昼",
    titleEn: "Zuihuayin: Thin Mist, Heavy Clouds",
    author: "李清照",
    authorEn: "Li Qingzhao",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "初中",
    kind: "词",
    theme: "思念",
    themeEn: "Longing",
    level: 3,
    lines: [
      { zh: "薄雾浓云愁永昼，瑞脑销金兽。", en: "Thin mist and heavy clouds sour the endless day; the censer's dragon slowly burns its incense away." },
      { zh: "佳节又重阳，玉枕纱厨，半夜凉初透。", en: "Again the Double Ninth — jade pillow, gauze curtains, and midnight cold seeping through." },
      { zh: "东篱把酒黄昏后，有暗香盈袖。", en: "By the eastern hedge after dusk, wine in hand; a hidden fragrance fills my sleeves." },
      { zh: "莫道不销魂，帘卷西风，人比黄花瘦。", en: "Say not the soul is not consumed: the west wind lifts the curtain — and I am thinner than the yellow chrysanthemum." },
    ],
    keywords: [
      { w: "censer", zh: "香炉" },
      { w: "seep through", zh: "透过" },
      { w: "chrysanthemum", zh: "菊花" },
    ],
    note: "「人比黄花瘦」把相思写成了一件可以量的事：比花还瘦。",
    noteEn: "'Thinner than the yellow chrysanthemum' makes longing measurable — thinner than a flower.",
  },
  {
    slug: "wulingchun",
    title: "武陵春·风住尘香花已尽",
    titleEn: "Wulingchun: The Wind Has Stopped",
    author: "李清照",
    authorEn: "Li Qingzhao",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "初中",
    kind: "词",
    theme: "悼亡",
    themeEn: "Grief",
    level: 3,
    lines: [
      { zh: "风住尘香花已尽，日晚倦梳头。", en: "The wind has stopped; the dust is fragrant, the flowers all fallen. Day rises, and I cannot be bothered to comb my hair." },
      { zh: "物是人非事事休，欲语泪先流。", en: "Things remain, people do not; everything is over. Before words come, tears do." },
      { zh: "闻说双溪春尚好，也拟泛轻舟。", en: "They say the twin creeks still hold spring; I mean to take a light boat there — I almost do." },
      { zh: "只恐双溪舴艋舟，载不动许多愁。", en: "But I fear the little mayfly boats of the twin creeks could not carry so much sorrow." },
    ],
    keywords: [
      { w: "sorrow", zh: "愁" },
      { w: "light boat", zh: "轻舟" },
      { w: "cannot carry", zh: "载不动" },
    ],
    note: "愁第一次有了重量，能压沉一条船——李清照之后，写愁都要报吨位。",
    noteEn: "Sorrow gains weight for the first time — heavy enough to sink a boat. After Li Qingzhao, every poet must declare their sorrow's tonnage.",
  },
  {
    slug: "shanpoyang",
    title: "山坡羊·潼关怀古",
    titleEn: "Shanpoyang: Meditations at Tong Pass",
    author: "张养浩",
    authorEn: "Zhang Yanghao",
    dynasty: "元",
    dynastyEn: "Yuan",
    stage: "初中",
    kind: "词",
    theme: "怀古",
    themeEn: "History's Cost",
    level: 3,
    lines: [
      { zh: "峰峦如聚，波涛如怒，山河表里潼关路。", en: "Peaks cluster like a crowd; waves seethe with rage; hills within, river without — the road through Tong Pass." },
      { zh: "望西都，意踌躇。伤心秦汉经行处，宫阙万间都做了土。", en: "I gaze toward the Western Capital and my heart hesitates. Sorrowful at all the Qin and Han marches through here: ten thousand palaces, all turned to dust." },
      { zh: "兴，百姓苦；亡，百姓苦。", en: "Dynasties rise — the people suffer. Dynasties fall — the people suffer." },
    ],
    keywords: [
      { w: "seethe", zh: "汹涌（怒）" },
      { w: "palace", zh: "宫阙" },
      { w: "turn to dust", zh: "化为土" },
    ],
    note: "最后八个字是元曲里最重的一句：改朝换代是史书的事，苦是老百姓的。",
    noteEn: "The eight final characters are the heaviest in all qu: dynasties belong to the history books; the suffering belongs to the people.",
  },
  {
    slug: "wuyixiang",
    title: "乌衣巷",
    titleEn: "Wuyi Lane",
    author: "刘禹锡",
    authorEn: "Liu Yuxi",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "怀古",
    themeEn: "Time",
    level: 2,
    lines: [
      { zh: "朱雀桥边野草花，乌衣巷口夕阳斜。", en: "By Zhuque Bridge wild grasses flower; at the mouth of Wuyi Lane the evening sun slants low." },
      { zh: "旧时王谢堂前燕，飞入寻常百姓家。", en: "The swallows that once nested in the halls of Wang and Xie now fly into the homes of ordinary people." },
    ],
    keywords: [
      { w: "ordinary people", zh: "寻常百姓" },
      { w: "slant (of sun)", zh: "斜照" },
      { w: "swallows", zh: "燕子" },
      { w: "nested", zh: "筑巢（栖息）" }
    ],
    note: "朝代更替不写一个字，只写燕子换了门牌。",
    noteEn: "Not a word about dynasties falling — only swallows changing address.",
  },
  {
    slug: "yueye-yishe",
    title: "月夜忆舍弟",
    titleEn: "Moonlit Night, Missing My Brothers",
    author: "杜甫",
    authorEn: "Du Fu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "亲情",
    themeEn: "Family",
    level: 3,
    lines: [
      { zh: "戍鼓断人行，边秋一雁声。", en: "Garrison drums stop all travel; in border autumn, one wild goose cries." },
      { zh: "露从今夜白，月是故乡明。", en: "Dew turns white from tonight; the moon is brighter back home." },
      { zh: "有弟皆分散，无家问死生。", en: "I have brothers, all scattered; no home left to ask who lives and who has died." },
      { zh: "寄书长不达，况乃未休兵。", en: "Letters I send rarely arrive — and the war has not yet ended." },
    ],
    keywords: [
      { w: "garrison", zh: "戍卒（驻军）" },
      { w: "wild goose", zh: "雁" },
      { w: "the war has not ended", zh: "未休兵" },
    ],
    note: "「月是故乡明」完全不讲道理——但月亮一旦讲道理，就不是乡愁了。",
    noteEn: "'The moon is brighter back home' is entirely unreasonable — but once the moon starts reasoning, homesickness is over.",
  },
  {
    slug: "wenguanjun",
    title: "闻官军收河南河北",
    titleEn: "Hearing the Imperial Army Has Recovered the Henan and Hebei Regions",
    author: "杜甫",
    authorEn: "Du Fu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "初中",
    kind: "诗",
    theme: "豪情",
    themeEn: "Joy",
    level: 3,
    lines: [
      { zh: "剑外忽传收蓟北，初闻涕泪满衣裳。", en: "Beyond Jiange the news comes suddenly: Jibei is recovered. At first hearing, tears soak my robe." },
      { zh: "却看妻子愁何在，漫卷诗书喜欲狂。", en: "I turn to my wife and children — where has the sorrow gone? My books roll up anyhow; I am mad with joy." },
      { zh: "白日放歌须纵酒，青春作伴好还乡。", en: "In broad daylight, singing and wine; with spring as companion, the road home is good." },
      { zh: "即从巴峡穿巫峡，便下襄阳向洛阳。", en: "From Ba Gorge through Wu Gorge, then down to Xiangyang and on to Luoyang." },
    ],
    keywords: [
      { w: "recover", zh: "收复" },
      { w: "roll up", zh: "卷起" },
      { w: "mad with joy", zh: "喜欲狂" },
    ],
    note: "尾联四个地名一气跑完，是杜甫一生最快的一首诗——人没动，心先到了。",
    noteEn: "Four place-names sprint through the final couplet — the fastest poem Du Fu ever wrote. The man has not moved; his heart has arrived.",
  },
  {
    slug: "zixiangmaodun",
    title: "自相矛盾",
    titleEn: "Self-Contradiction",
    author: "韩非子",
    authorEn: "Han Feizi",
    dynasty: "战国",
    dynastyEn: "Warring States",
    stage: "初中",
    kind: "文言文",
    theme: "寓言",
    themeEn: "Fable",
    level: 1,
    lines: [
      { zh: "楚人有鬻盾与矛者，誉之曰：「吾盾之坚，物莫能陷也。」", en: "A man of Chu selling shields and spears boasted: 'My shield is so strong nothing can pierce it.'" },
      { zh: "又誉其矛曰：「吾矛之利，于物无不陷也。」", en: "And of his spear: 'My spear is so sharp there is nothing it cannot pierce.'" },
      { zh: "或曰：「以子之矛陷子之盾，何如？」其人弗能应也。", en: "Someone asked: 'What if your spear met your shield?' The man could not answer." },
    ],
    fullText: "楚人有鬻盾与矛者，誉之曰：「吾盾之坚，物莫能陷也。」又誉其矛曰：「吾矛之利，于物无不陷也。」或曰：「以子之矛陷子之盾，何如？」其人弗能应也。夫不可陷之盾与无不陷之矛，不可同世而立。",
    keywords: [
      { w: "boast", zh: "吹嘘" },
      { w: "pierce", zh: "刺穿" },
      { w: "cannot answer", zh: "弗能应" },
    ],
    note: "「弗能应也」四个字写尽被拆穿的瞬间——这个楚国人一句话造出了全世界的「矛盾」。",
    noteEn: "'He could not answer' captures the moment of being seen through. One Chu salesman gave the world the word 'contradiction'.",
  },
  {
    slug: "zhengrenmailv",
    title: "郑人买履",
    titleEn: "The Man of Zheng Buys Shoes",
    author: "韩非子",
    authorEn: "Han Feizi",
    dynasty: "战国",
    dynastyEn: "Warring States",
    stage: "初中",
    kind: "文言文",
    theme: "寓言",
    themeEn: "Fable",
    level: 1,
    lines: [
      { zh: "郑人有且置履者，先自度其足而置之其坐，至之市而忘操之。", en: "A man of Zheng about to buy shoes measured his feet first and set the measure on his seat; but when he reached the market he found he had forgotten to bring it." },
      { zh: "已得履，乃曰：「吾忘持度。」反归取之。及反，市罢，遂不得履。", en: "Having found shoes, he said, 'I forgot my measure,' and went back for it. By the time he returned the market had closed — so he got no shoes." },
      { zh: "人曰：「何不试之以足？」曰：「宁信度，无自信也。」", en: "People said: 'Why not try them with your feet?' He said: 'I would rather trust the measure than trust myself.'" },
    ],
    fullText: "郑人有且置履者，先自度其足而置之其坐，至之市而忘操之。已得履，乃曰：「吾忘持度。」反归取之。及反，市罢，遂不得履。人曰：「何不试之以足？」曰：「宁信度，无自信也。」",
    keywords: [
      { w: "measure (n.)", zh: "量好的尺码" },
      { w: "rather than", zh: "宁可……而不……" },
      { w: "the market had closed", zh: "市罢" },
    ],
    note: "「宁信度，无自信也」——尺码是死的，脚是活的。今天我们叫它「本本主义」。",
    noteEn: "'Rather trust the measure than trust myself': the measure is dead, the foot is alive. We now call it dogmatism.",
  },
  {
    slug: "kezhouqiujian",
    title: "刻舟求剑",
    titleEn: "Carving the Boat to Find the Sword",
    author: "吕不韦（编）",
    authorEn: "Lü Buwei (compiled)",
    dynasty: "战国",
    dynastyEn: "Warring States",
    stage: "初中",
    kind: "文言文",
    theme: "寓言",
    themeEn: "Fable",
    level: 1,
    lines: [
      { zh: "楚人有涉江者，其剑自舟中坠于水，遽契其舟，曰：「是吾剑之所从坠。」", en: "A man of Chu crossing the river dropped his sword from the boat into the water. He quickly cut a notch on the boat: 'This is where my sword fell.'" },
      { zh: "舟止，从其所契者入水求之。舟已行矣，而剑不行，求剑若此，不亦惑乎！", en: "When the boat stopped, he entered the water where the notch was to search. The boat had moved; the sword had not. To seek a sword like this — is it not bewildered?" },
    ],
    fullText: "楚人有涉江者，其剑自舟中坠于水，遽契其舟，曰：「是吾剑之所从坠。」舟止，从其所契者入水求之。舟已行矣，而剑不行，求剑若此，不亦惑乎！",
    keywords: [
      { w: "notch", zh: "刻痕" },
      { w: "fall into", zh: "坠入" },
      { w: "bewildered", zh: "迷惑" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "他选错了参照系",
      titleEn: "He chose the wrong frame of reference",
      body: "剑落水后相对河底静止，而船相对河底继续运动。「剑在哪里」取决于你选什么做参照物：以船为参照，剑一直在「刻痕」处；以河岸为参照，剑早已落在后方。楚人的错误不是不聪明，而是默认了「船不动」这个参照系——物理学的第一课就是检查参照系。",
      bodyEn: "After the sword sank it was at rest relative to the riverbed, while the boat kept moving. Where the sword 'is' depends on the frame you pick: relative to the boat it stays at the notch; relative to the bank it lies far behind. The man's error was not stupidity but an unexamined assumption that the boat stands still — lesson one of physics is to check your frame.",
    },
    note: "船在动，剑没动——这是一则物理寓言，也是一则哲学寓言。",
    noteEn: "The boat moves, the sword does not: a physics fable that is also a philosophy fable.",
  },
  {
    slug: "huashetianzu",
    title: "画蛇添足",
    titleEn: "Drawing Legs on a Snake",
    author: "刘向（辑）",
    authorEn: "Liu Xiang (compiler)",
    dynasty: "西汉",
    dynastyEn: "Western Han",
    stage: "初中",
    kind: "文言文",
    theme: "寓言",
    themeEn: "Fable",
    level: 1,
    lines: [
      { zh: "楚有祠者，赐其舍人卮酒。舍人相谓曰：「数人饮之不足，一人饮之有余。请画地为蛇，先成者饮酒。」", en: "A man of Chu held a sacrifice and gave his retainers a cup of wine. They said: 'Several of us — not enough; one alone — too much. Let us draw snakes on the ground, and the first to finish drinks.'" },
      { zh: "一人蛇先成，引酒且饮之，乃左手持卮，右手画蛇，曰：「吾能为之足。」", en: "One finished his snake first, took the wine in his left hand, and with his right went on drawing: 'I can give it feet.'" },
      { zh: "未成，一人之蛇成，夺其卮曰：「蛇固无足，子安能为之足？」遂饮其酒。为蛇足者，终亡其酒。", en: "Before the feet were done, another's snake was finished; he snatched the cup: 'A snake has no feet — how can you draw them?' and drank. He who added feet lost his wine." },
    ],
    fullText: "楚有祠者，赐其舍人卮酒。舍人相谓曰：「数人饮之不足，一人饮之有余。请画地为蛇，先成者饮酒。」一人蛇先成，引酒且饮之，乃左手持卮，右手画蛇，曰：「吾能为之足。」未成，一人之蛇成，夺其卮曰：「蛇固无足，子安能为之足？」遂饮其酒。为蛇足者，终亡其酒。",
    keywords: [
      { w: "sacrifice", zh: "祭祀" },
      { w: "retainer", zh: "门客" },
      { w: "snatch", zh: "夺" },
    ],
    note: "多画的那四只脚，把赢定的酒输掉了——「赢」字后面常常跟着一个「够」字。",
    noteEn: "The four extra feet lost the wine already won. Behind the word 'win' there usually hides the word 'enough'.",
  },
  {
    slug: "hujiahuwei",
    title: "狐假虎威",
    titleEn: "The Fox Borrows the Tiger's Might",
    author: "刘向（辑）",
    authorEn: "Liu Xiang (compiler)",
    dynasty: "西汉",
    dynastyEn: "Western Han",
    stage: "初中",
    kind: "文言文",
    theme: "寓言",
    themeEn: "Fable",
    level: 1,
    lines: [
      { zh: "虎求百兽而食之，得狐。狐曰：「子无敢食我也！天帝使我长百兽，今子食我，是逆天帝命也。」", en: "A tiger hunted all beasts for food and caught a fox. The fox said: 'You dare not eat me! The Emperor of Heaven has made me chief of the beasts — to eat me is to defy his command.'" },
      { zh: "吾为子先行，子随我后，观百兽之见我而敢不走乎？", en: "Walk behind while I lead, and watch whether the beasts do not flee at the sight of me." },
      { zh: "虎不知兽畏己而走也，以为畏狐也。", en: "The tiger, not knowing the beasts feared him, believed they feared the fox." },
    ],
    fullText: "虎求百兽而食之，得狐。狐曰：「子无敢食我也！天帝使我长百兽，今子食我，是逆天帝命也。子以我为不信，吾为子先行，子随我后，观百兽之见我而敢不走乎？」虎以为然，故遂与之行。兽见之皆走。虎不知兽畏己而走也，以为畏狐也。",
    keywords: [
      { w: "defy", zh: "违抗" },
      { w: "flee", zh: "逃走" },
      { w: "believed", zh: "（错）以为" },
    ],
    note: "百兽逃的是虎，不是狐——受骗的原理永远一样：看错了真正的参照物。",
    noteEn: "The beasts fled from the tiger, not the fox. Deception always works the same way: fix your eyes on the wrong reference point.",
  },
  {
    slug: "yubangxiangzheng",
    title: "鹬蚌相争",
    titleEn: "The Snipe and the Clam",
    author: "刘向（辑）",
    authorEn: "Liu Xiang (compiler)",
    dynasty: "西汉",
    dynastyEn: "Western Han",
    stage: "初中",
    kind: "文言文",
    theme: "寓言",
    themeEn: "Fable",
    level: 1,
    lines: [
      { zh: "蚌方出曝，而鹬啄其肉，蚌合而箝其喙。", en: "A clam came out to sun itself; a snipe pecked at its flesh, and the clam clamped shut on the snipe's beak." },
      { zh: "鹬曰：「今日不雨，明日不雨，即有死蚌！」蚌亦谓鹬曰：「今日不出，明日不出，即有死鹬！」", en: "The snipe said: 'No rain today, no rain tomorrow — there will be a dead clam.' The clam replied: 'I will not let go today, nor tomorrow — there will be a dead snipe.'" },
      { zh: "两者不肯相舍，渔者得而并禽之。", en: "Neither would yield to the other — till a fisherman came and took them both." },
    ],
    fullText: "蚌方出曝，而鹬啄其肉，蚌合而箝其喙。鹬曰：「今日不雨，明日不雨，即有死蚌！」蚌亦谓鹬曰：「今日不出，明日不出，即有死鹬！」两者不肯相舍，渔者得而并禽之。",
    keywords: [
      { w: "clam", zh: "蚌" },
      { w: "snipe", zh: "鹬" },
      { w: "yield", zh: "让步" },
      { w: "fisherman", zh: "渔翁" },
    ],
    note: "「并禽之」三个字是结局，也是所有僵局的注脚——第三方正在旁边看着。",
    noteEn: "'Took them both' is the ending — and the footnote to every standoff: the third party is already watching.",
  },
  {
    slug: "nanyuanbeizhe",
    title: "南辕北辙",
    titleEn: "South Shaft, North Track",
    author: "刘向（辑）",
    authorEn: "Liu Xiang (compiler)",
    dynasty: "西汉",
    dynastyEn: "Western Han",
    stage: "初中",
    kind: "文言文",
    theme: "寓言",
    themeEn: "Fable",
    level: 1,
    lines: [
      { zh: "今者臣来，见人于大行，方北面而持其驾，告臣曰：「我欲之楚。」", en: "Coming here, I met a man on the great road, heading north with his carriage, who told me: 'I am going to Chu.'" },
      { zh: "臣曰：「马虽良，此非楚之路也。」曰：「吾用多。」臣曰：「用虽多，此非楚之路也。」曰：「吾善用御。」", en: "I said: 'Good horses — but this is not the road to Chu.' 'I have plenty of money.' 'Plenty of money — but this is not the road to Chu.' 'My driver is excellent.'" },
      { zh: "此数者愈善，而离楚愈远耳。", en: "The better each of these, the farther from Chu he would go." },
    ],
    fullText: "今者臣来，见人于大行，方北面而持其驾，告臣曰：「我欲之楚。」臣曰：「君之楚，将奚为北面？」曰：「吾马良。」臣曰：「马虽良，此非楚之路也。」曰：「吾用多。」臣曰：「用虽多，此非楚之路也。」曰：「吾善用御。」臣曰：「用虽多，此非楚之路也。」曰：「吾御者善。」此数者愈善，而离楚愈远耳。",
    keywords: [
      { w: "carriage", zh: "车驾" },
      { w: "plenty of money", zh: "盘缠充足" },
      { w: "driver", zh: "御者" },
    ],
    note: "资源越好，方向错时输得越彻底——这句话今天写在所有规划书的第一页。",
    noteEn: "The better your resources, the more thoroughly you lose when the direction is wrong — this line now heads every planning document.",
  },
  {
    slug: "qirenyoutian",
    title: "杞人忧天",
    titleEn: "The Man of Qi Feared the Sky Would Fall",
    author: "列子",
    authorEn: "Liezi",
    dynasty: "战国",
    dynastyEn: "Warring States",
    stage: "初中",
    kind: "文言文",
    theme: "寓言",
    themeEn: "Fable",
    level: 1,
    lines: [
      { zh: "杞国有人忧天地崩坠，身亡所寄，废寝食者。", en: "A man of Qi worried that heaven and earth might collapse and he would have nowhere to rest — so much that he gave up sleep and food." },
      { zh: "又有忧彼之所忧者，因往晓之。", en: "Another man, worried about his worry, went to enlighten him." },
      { zh: "其人舍然大喜，晓之者亦舍然大喜。", en: "At last the worrier was relieved and greatly cheered; and the man who had enlightened him was relieved too." },
    ],
    fullText: "杞国有人忧天地崩坠，身亡所寄，废寝食者。又有忧彼之所忧者，因往晓之，曰：「天，积气耳，亡处亡气。若躇步跐蹈，终日在天中行止，奈何忧崩坠乎？」其人曰：「天果积气，日月星宿，不当坠耶？」晓之者曰：「日月星宿，亦积气中之有光耀者，只使坠，亦不能有所中伤。」其人曰：「奈地坏何？」晓者曰：「地，积块耳，充塞四虚，亡处亡块。若躇步跐蹈，终日在地上行止，奈何忧其坏？」其人舍然大喜，晓之者亦舍然大喜。",
    keywords: [
      { w: "collapse", zh: "崩坠" },
      { w: "give up sleep and food", zh: "废寝食" },
      { w: "enlighten", zh: "开导" },
    ],
    cross: {
      field: "天文",
      fieldEn: "Astronomy",
      title: "天真的会「坠」东西吗？",
      titleEn: "Does anything ever fall from the sky?",
      body: "杞人怕的事有一部分是真的：「天」就是大气层，而每天都有约几十吨的流星体坠入大气，大部分烧成流星，少数落到地面成为陨石。列子的开导者说天是「积气」——竟与今天「大气层」的概念意外接近；只是他没料到，积气之中真会掉东西下来。",
      bodyEn: "Part of the worry is real: the 'sky' is the atmosphere, and dozens of tonnes of meteoroids enter it daily — most burn as meteors, a few land as meteorites. Liezi's counsellor called the sky 'accumulated vapour', oddly close to our idea of an atmosphere; he simply never imagined that things do sometimes come down.",
    },
    note: "「废寝食」三个字，让两千年后的失眠者瞬间有了同类。",
    noteEn: "In 'gave up sleep and food', every insomniac of the last two thousand years finds a fellow sufferer.",
  },
  {
    slug: "saiweng",
    title: "塞翁失马",
    titleEn: "The Old Man at the Frontier Loses His Horse",
    author: "刘安（编）",
    authorEn: "Liu An (compiled)",
    dynasty: "西汉",
    dynastyEn: "Western Han",
    stage: "初中",
    kind: "文言文",
    theme: "寓言",
    themeEn: "Fable",
    level: 2,
    lines: [
      { zh: "近塞上之人有善术者，马无故亡而入胡。人皆吊之。其父曰：「此何遽不为福乎？」", en: "Among those living near the frontier was a man skilled in divination. For no reason his horse ran off into the lands of the Hu. Everyone condoled with him. His father said: 'How do you know this will not turn out to be a blessing?'" },
      { zh: "居数月，其马将胡骏马而归，人皆贺之。其父曰：「此何遽不能为祸乎？」", en: "After some months the horse returned, bringing fine Hu horses with it. Everyone congratulated him. His father said: 'How do you know this will not turn out to be a curse?'" },
      { zh: "家富良马，其子好骑，堕而折其髀。人皆吊之。其父曰：「此何遽不为福乎？」", en: "Rich in fine horses, his son loved riding, fell, and broke his thigh. Everyone condoled. His father said: 'How do you know this will not be a blessing?'" },
      { zh: "居一年，胡人大入塞，丁壮者引弦而战，塞上之人死者十九。此独以跛之故，父子相保。", en: "A year later the Hu invaded in force; every able man drew a bow and fought, and nine of ten frontier men died. He alone, because of his lame leg, and his father kept each other alive." },
    ],
    fullText: "近塞上之人有善术者，马无故亡而入胡。人皆吊之。其父曰：「此何遽不为福乎？」居数月，其马将胡骏马而归，人皆贺之。其父曰：「此何遽不能为祸乎？」家富良马，其子好骑，堕而折其髀。人皆吊之。其父曰：「此何遽不为福乎？」居一年，胡人大入塞，丁壮者引弦而战，塞上之人死者十九。此独以跛之故，父子相保。",
    keywords: [
      { w: "divination", zh: "占卜" },
      { w: "condole", zh: "慰问（吊）" },
      { w: "thigh", zh: "大腿（髀）" },
      { w: "nine in ten", zh: "死者十九" },
    ],
    note: "故事讲完没下结论——因为「福祸」的翻译官永远迟到一步。",
    noteEn: "The story ends without a moral, because the interpreter between blessing and curse is always one step late.",
  },
  {
    slug: "yongxue-sxny",
    title: "咏雪",
    titleEn: "On Snow",
    author: "刘义庆",
    authorEn: "Liu Yiqing",
    dynasty: "南朝",
    dynastyEn: "Southern Dynasties",
    stage: "初中",
    kind: "文言文",
    theme: "家庭",
    themeEn: "Family Wit",
    level: 1,
    lines: [
      { zh: "谢太傅寒雪日内集，与儿女讲论文义。", en: "On a day of cold snow Grand Tutor Xie gathered the family and talked with the young ones about literature." },
      { zh: "俄而雪骤，公欣然曰：「白雪纷纷何所似？」", en: "Soon the snow fell thick and fast. He said, delighted: 'The white snow falling, falling — what does it resemble?'" },
      { zh: "兄子胡儿曰：「撒盐空中差可拟。」兄女曰：「未若柳絮因风起。」公大笑乐。", en: "His nephew said: 'Scattering salt in the air would come close.' His niece said: 'Not so well as willow catkins rising on the wind.' The Grand Tutor laughed with great delight." },
    ],
    fullText: "谢太傅寒雪日内集，与儿女讲论文义。俄而雪骤，公欣然曰：「白雪纷纷何所似？」兄子胡儿曰：「撒盐空中差可拟。」兄女曰：「未若柳絮因风起。」公大笑乐。即公大兄无奕女，左将军王凝之妻也。",
    keywords: [
      { w: "resemble (v.)", zh: "像" },
      { w: "catkins", zh: "柳絮" },
      { w: "delight", zh: "欣然 / 乐" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "盐和柳絮，差的其实是下落速度",
      titleEn: "The real difference between salt and catkins is falling speed",
      body: "盐粒密度大、体积小，在空气中几乎直线下落，末速度快，所以是「撒」；雪片是六角形晶体，结构里裹挟了大量空气，密度极低，下落时受空气阻力大、末速度小，还会打转飘摆，所以像柳絮「因风起」。谢道韫赢在观察：她抓到了雪的运动方式，而不只是颜色。",
      bodyEn: "Salt grains are dense and small, dropping almost straight with high terminal velocity — they are 'scattered'. Snowflakes are hexagonal crystals that trap air, extremely light, so air resistance slows them to a drift with flutter and sway — like catkins 'rising on the wind'. Xie Daoyun won on observation: she captured how snow moves, not merely its colour.",
    },
    note: "谢道韫一开口，盐就输了——雪的质感是「起」，不是「撒」。",
    noteEn: "The moment Xie Daoyun spoke, the salt lost: snow's texture is 'rising', not 'scattering'.",
  },
  {
    slug: "chentaiqiu",
    title: "陈太丘与友期",
    titleEn: "Chen Taiqiu and a Friend's Appointment",
    author: "刘义庆",
    authorEn: "Liu Yiqing",
    dynasty: "南朝",
    dynastyEn: "Southern Dynasties",
    stage: "初中",
    kind: "文言文",
    theme: "守信",
    themeEn: "Integrity",
    level: 1,
    lines: [
      { zh: "陈太丘与友期行，期日中，过中不至，太丘舍去，去后乃至。", en: "Chen Taiqiu arranged to travel with a friend at noon. Past noon the friend had not come; Taiqiu left. After he had gone, the friend arrived." },
      { zh: "客问元方：「尊君在不？」答曰：「待君久不至，已去。」", en: "The guest asked Yuanfang: 'Is your father in?' The answer: 'He waited for you a long time; you did not come — he has gone.'" },
      { zh: "元方曰：「君与家君期日中。日中不至，则是无信；对子骂父，则是无礼。」友人惭，下车引之。元方入门不顾。", en: "Yuanfang said: 'You and my father fixed noon. No arrival by noon is faithlessness; scolding a father to his son's face is rudeness.' Ashamed, the friend got down from his carriage to take his hand. Yuanfang went in the gate without looking back." },
    ],
    fullText: "陈太丘与友期行，期日中，过中不至，太丘舍去，去后乃至。元方时年七岁，门外戏。客问元方：「尊君在不？」答曰：「待君久不至，已去。」友人便怒曰：「非人哉！与人期行，相委而去。」元方曰：「君与家君期日中。日中不至，则是无信；对子骂父，则是无礼。」友人惭，下车引之。元方入门不顾。",
    keywords: [
      { w: "fixed noon", zh: "约定正午（期）" },
      { w: "faithlessness", zh: "无信" },
      { w: "without looking back", zh: "不顾" },
    ],
    note: "七岁小孩的逻辑链一环扣一环——最后「不顾」二字，是把道理讲完之后的自尊。",
    noteEn: "A seven-year-old's logic, link by link — and the final 'without looking back' is the self-respect that comes after the argument is won.",
  },
];
