import type { Poem } from "./types";

/** 小学阶段 · 第 1 批（咏物、四季、边塞、送别） */
export const PRIMARY_1: Poem[] = [
  {
    slug: "yongeo",
    title: "咏鹅",
    titleEn: "Ode to a Goose",
    author: "骆宾王",
    authorEn: "Luo Binwang",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "咏物",
    themeEn: "Nature",
    level: 1,
    lines: [
      { zh: "鹅，鹅，鹅，曲项向天歌。", en: "Goose, goose, goose — you arch your neck and sing toward the sky." },
      { zh: "白毛浮绿水，红掌拨清波。", en: "White feathers float on green water; red webs paddle the clear ripples." },
    ],
    keywords: [
      { w: "arch (v.)", zh: "弯成弧形" },
      { w: "web (n.)", zh: "（禽类的）蹼" },
      { w: "paddle (v.)", zh: "划水、拨水" },
      { w: "ripple (n.)", zh: "涟漪" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "鹅的叫声为什么那么大？",
      titleEn: "Why are geese so loud?",
      body: "家鹅由大雁驯化而来，保留了祖先高声鸣叫的习性。它们的气管很长且在胸骨内盘曲，相当于一段「共鸣管」，能把声音放大；加上群体生活需要靠叫声警戒和联络，所以鹅既吵又警觉——甚至能当看家禽。诗里「向天歌」写的正是伸直脖子、仰头大叫的典型姿态。",
      bodyEn: "Domestic geese descend from wild geese and kept their loud voices. Their long windpipe coils inside the breastbone, acting as a resonating tube that amplifies sound; as flock animals they also rely on calls to warn and stay in touch. Hence the noisy, watchful bird that can even guard a yard. 「Singing toward the sky」 captures exactly the head-up, neck-stretched posture of a honking goose.",
    },
    note: "相传是骆宾王七岁所作。三个「鹅」字连用是孩子的惊喜，英文用 Goose, goose, goose 保留这份天真；颜色词 white/green/red/clear 是全诗的画面骨架。",
    noteEn: "Said to be written at age seven. The triple 「鹅」 is a child's delight — kept as Goose, goose, goose. The colour words white / green / red build the whole picture.",
  },
  {
    slug: "jiangnan",
    title: "江南",
    titleEn: "South of the Yangtze",
    author: "汉乐府",
    authorEn: "Han Music Bureau",
    dynasty: "汉",
    dynastyEn: "Han",
    stage: "小学",
    kind: "诗",
    theme: "四季",
    themeEn: "Seasons",
    level: 1,
    lines: [
      { zh: "江南可采莲，莲叶何田田。", en: "South of the Yangtze, the lotus is ready to gather — how lush the lotus leaves are!" },
      { zh: "鱼戏莲叶间。", en: "Fish play among the lotus leaves." },
      { zh: "鱼戏莲叶东，鱼戏莲叶西，鱼戏莲叶南，鱼戏莲叶北。", en: "They play east of the leaves, and west of them, south of them, and north of them." },
    ],
    keywords: [
      { w: "lotus (n.)", zh: "莲、荷" },
      { w: "lush (adj.)", zh: "茂盛的" },
      { w: "gather (v.)", zh: "采集" },
      { w: "play (v.)", zh: "嬉戏（鱼戏）" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "莲叶为什么不沾水？",
      titleEn: "Why doesn't water wet a lotus leaf?",
      body: "莲叶表面布满微米级的乳突，上面还覆盖一层蜡质，水滴接触时只能托在乳突顶端，接触角超过 150°，一滚就带走灰尘——这就是「荷叶效应」，也是自清洁材料的灵感来源。莲叶田田，靠的正是这层结构；而叶下阴凉、溶氧充足，正好成了鱼群穿梭的地方。",
      bodyEn: "A lotus leaf is covered with microscopic bumps coated in wax. Water rests on the tips of those bumps with a contact angle above 150°, rolling off and carrying dirt with it — the famous 「lotus effect」 that inspired self-cleaning materials. The same dense canopy shades the water below, making it cool and well-oxygenated, which is why fish crowd beneath the leaves.",
    },
    note: "汉乐府是配乐演唱的民歌。五个方位词东、西、南、北反复出现，看似啰嗦，其实是民歌的一唱三叹——英文用排比保留这种回旋感。",
    noteEn: "A Han-dynasty folk song meant to be sung. The repeated east / west / south / north looks redundant, but it is the refrain of a ballad — the English keeps the parallel rhythm.",
  },
  {
    slug: "hua",
    title: "画",
    titleEn: "A Painting",
    author: "佚名（传王维）",
    authorEn: "Anonymous (attr. Wang Wei)",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "咏物",
    themeEn: "Nature",
    level: 1,
    lines: [
      { zh: "远看山有色，近听水无声。", en: "Seen from afar the hills have colour; heard up close, the water makes no sound." },
      { zh: "春去花还在，人来鸟不惊。", en: "Spring is gone, yet the blossoms remain; a man comes near, yet the bird is not startled." },
    ],
    keywords: [
      { w: "from afar", zh: "从远处" },
      { w: "up close", zh: "凑近看" },
      { w: "blossom (n.)", zh: "花（多指果木花）" },
      { w: "startle (v.)", zh: "使惊飞、受惊" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "为什么画里的水没有声音？",
      titleEn: "Why is painted water silent?",
      body: "声音来自物体振动，是机械波，必须靠介质传播。画上的瀑布只是颜料反射的可见光——光是电磁波，能在真空中传播，却完全不会引起空气振动。所以「近听水无声」不是错觉，而是物理必然：你接收到的是画面反射的光，不是声源。反过来说，也正因为如此，画只能骗眼睛，骗不了耳朵。",
      bodyEn: "Sound is a mechanical wave: it needs a vibrating source and a medium. A painted waterfall only reflects visible light — electromagnetic waves that travel through vacuum but never set air vibrating. So 「no sound up close」 is not an illusion, it is physics: what reaches you is reflected light, not a sound source. A painting can fool the eye, never the ear.",
    },
    note: "全诗是一则谜语，谜底就是「画」。四句各写一处矛盾（有色却无声、春去花仍在、人近鸟不惊），英文用 yet 转折把矛盾撑住。",
    noteEn: "The whole poem is a riddle, and the answer is 「a painting」. Each couplet sets up one contradiction — the English carries them with yet.",
  },
  {
    slug: "minnong-yi",
    title: "悯农 · 其一",
    titleEn: "Pitying the Farmer · I",
    author: "李绅",
    authorEn: "Li Shen",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "悯农",
    themeEn: "Labour",
    level: 1,
    lines: [
      { zh: "春种一粒粟，秋收万颗子。", en: "One grain sown in spring — ten thousand grains reaped in autumn." },
      { zh: "四海无闲田，农夫犹饿死。", en: "Within the four seas no field lies idle, and still the farmer starves to death." },
    ],
    keywords: [
      { w: "sow (v.)", zh: "播种" },
      { w: "reap (v.)", zh: "收割" },
      { w: "idle (adj.)", zh: "闲置的" },
      { w: "starve (v.)", zh: "挨饿、饿死" },
    ],
    cross: {
      field: "农学",
      fieldEn: "Agronomy",
      title: "一粒种子真能收万颗吗？",
      titleEn: "Can one seed really yield ten thousand?",
      body: "能，甚至更多。一株水稻可分蘖十几到几十个穗，每穗百粒左右，籽粒产量比（繁殖系数）常在 1:100 以上，好的杂交稻可达 1:500。粟（谷子）的繁殖系数也在数百倍量级。所以「春种一粒粟，秋收万颗子」不是文学夸张，而是合乎农学事实的数字。真正反常的是下一句：产量这么高，农夫却饿死——问题不在地，而在赋税与分配。",
      bodyEn: "Yes — often more. A single rice plant tillers into a dozen or more panicles with about a hundred grains each, giving a multiplication ratio well above 1:100 (hybrid rice can reach 1:500); foxtail millet is similar. So the numbers are agronomically sound rather than poetic exaggeration. What is perverse is the next line: with such yields, the farmer still starves — the failure is taxation and distribution, not the land.",
    },
    note: "与「锄禾日当午」是组诗，一写生产过程，一写劳动辛苦。注意 one / ten thousand 的巨大落差，最后 still 一词把愤怒压在句末。",
    noteEn: "A companion to the famous second poem: one shows production, the other toil. Notice the one / ten thousand gap, and how still carries the anger at the very end.",
  },
  {
    slug: "gulangyuexing",
    title: "古朗月行（节选）",
    titleEn: "Ancient Ballad of the Bright Moon (excerpt)",
    author: "李白",
    authorEn: "Li Bai",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "咏月",
    themeEn: "The Moon",
    level: 1,
    lines: [
      { zh: "小时不识月，呼作白玉盘。", en: "As a child I did not know the moon; I called it a plate of white jade." },
      { zh: "又疑瑶台镜，飞在青云端。", en: "Then I thought it a mirror from the jade terrace, flying high beyond the blue clouds." },
    ],
    keywords: [
      { w: "jade (n.)", zh: "玉" },
      { w: "plate (n.)", zh: "盘子" },
      { w: "terrace (n.)", zh: "台、高台" },
      { w: "beyond (prep.)", zh: "在…之外" },
    ],
    cross: {
      field: "天文",
      fieldEn: "Astronomy",
      title: "月亮为什么有时像盘子？",
      titleEn: "Why does the moon look like a plate?",
      body: "满月时月亮是「白玉盘」；月初月末只剩一道弯钩。这不是月亮变了形状，而是日、地、月三者相对位置变化，使我们看到的被照亮半球面积不同——月相。周期约 29.5 天。另一个冷知识：月亮看起来在天空中的位置越高显得越小（月亮错觉），越是中秋满月，人们越觉得它「又大又圆」，其中一部分是大脑的错觉在帮忙。",
      bodyEn: "At full moon it is a plate of jade; at crescent it is a hook. The moon does not change shape — the sun, earth and moon shift relative to one another, so we see a different fraction of the lit hemisphere. That is the lunar phase, cycling in about 29.5 days. Another twist: the moon illusion makes a low moon look huge, so part of that 「big round harvest moon」 is your brain helping out.",
    },
    note: "「呼作」「又疑」两个动词写出小孩认错的两次过程，英文用 called it / then thought it 一模一样的节奏。",
    noteEn: "The two verbs 「呼作」 and 「又疑」 trace a child making, then correcting, a mistake — mirrored by called it / then thought it.",
  },
  {
    slug: "feng",
    title: "风",
    titleEn: "The Wind",
    author: "李峤",
    authorEn: "Li Qiao",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "咏物",
    themeEn: "Nature",
    level: 1,
    lines: [
      { zh: "解落三秋叶，能开二月花。", en: "It can strip the leaves of late autumn; it can open the flowers of the second month." },
      { zh: "过江千尺浪，入竹万竿斜。", en: "Crossing the river it raises waves a thousand feet; entering the bamboo it bends ten thousand stalks." },
    ],
    keywords: [
      { w: "strip (v.)", zh: "剥落、吹落" },
      { w: "raise (waves)", zh: "掀起（浪）" },
      { w: "bend (v.)", zh: "使弯曲" },
      { w: "stalk (n.)", zh: "竿、茎" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "风是怎么来的？",
      titleEn: "Where does wind come from?",
      body: "太阳把地面晒得冷热不均，热处空气膨胀上升、气压降低，冷处空气密度大、气压高，空气就从高压区流向低压区——这一流动就是风。温差越大，气压梯度越大，风越强。风本身看不见，只能靠它作用的对象来观察：落叶、开花、浪、竹斜。李峤全诗不写一个「风」字，正是这个道理。",
      bodyEn: "The sun heats the ground unevenly. Warm air expands and rises, lowering pressure; where it is cold the air is dense and pressure is high, so air flows from high to low — that flow is wind. The bigger the temperature contrast, the steeper the pressure gradient and the stronger the wind. Wind itself is invisible; you only see what it does, which is exactly why Li Qiao never writes the word.",
    },
    note: "题目是「风」，四句却一个风字都没有——全靠动词 strip / open / raise / bend 让人看见风。这是咏物诗的高级写法。",
    noteEn: "Titled 「Wind」, yet the word never appears. The four verbs strip / open / raise / bend make you see it. That is the sophisticated way to write an object poem.",
  },
  {
    slug: "liangzhouci-wzh",
    title: "凉州词",
    titleEn: "Liangzhou Song",
    author: "王之涣",
    authorEn: "Wang Zhihuan",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "边塞",
    themeEn: "Frontier",
    level: 1,
    lines: [
      { zh: "黄河远上白云间，一片孤城万仞山。", en: "The Yellow River climbs far up among white clouds; a lonely keep stands among mountains of ten thousand fathoms." },
      { zh: "羌笛何须怨杨柳，春风不度玉门关。", en: "Why should the Qiang flute grieve for the willow? The spring wind does not cross Yumen Pass." },
    ],
    keywords: [
      { w: "keep (n.)", zh: "堡垒、孤城" },
      { w: "grieve (v.)", zh: "哀怨、悲伤" },
      { w: "pass (n.)", zh: "关隘" },
      { w: "cross (v.)", zh: "越过" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "春风真的吹不过玉门关吗？",
      titleEn: "Does the spring wind really stop at Yumen Pass?",
      body: "基本是真的，而且有地理原因。玉门关在甘肃敦煌西北，深处内陆，夏季风（来自太平洋的湿润东南季风）长途跋涉到这里已是强弩之末；加上周边山脉阻挡，年降水量常不足 50 毫米，属极端干旱区。古人不懂季风环流，却凭经验准确总结出这条界线——今天地理学上的季风区与非季风区分界，大致仍从这里附近穿过。",
      bodyEn: "Largely true, for a geographic reason. Yumen Pass lies north-west of Dunhuang, deep inland. The summer monsoon — moist south-easterly air from the Pacific — has spent its force long before arriving, and surrounding ranges block what is left; annual rainfall is often under 50 mm. The ancients knew nothing of monsoon circulation, yet drew the line correctly from experience: the modern boundary between monsoon and non-monsoon China still runs near here.",
    },
    note: "「何须怨」是强作宽慰——不是不怨，是怨也没用。英文 Why should… 把这个反问语气留住了。",
    noteEn: "「Why grieve」 is forced consolation: not that there is no grief, but that grieving changes nothing. The English keeps it as a rhetorical question.",
  },
  {
    slug: "chusai",
    title: "出塞",
    titleEn: "Beyond the Frontier",
    author: "王昌龄",
    authorEn: "Wang Changling",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "边塞",
    themeEn: "Frontier",
    level: 1,
    lines: [
      { zh: "秦时明月汉时关，万里长征人未还。", en: "The moon of Qin, the passes of Han — men gone ten thousand li have not come home." },
      { zh: "但使龙城飞将在，不教胡马度阴山。", en: "If only the Flying General of Longcheng were still here, no northern horse would cross Mount Yin." },
    ],
    keywords: [
      { w: "passes", zh: "关隘（边塞）" },
      { w: "if only", zh: "要是…就好了" },
      { w: "cross", zh: "越过（不教胡马度阴山）" },
      { w: "come home", zh: "归来" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "「飞将」是谁？",
      titleEn: "Who was the Flying General?",
      body: "指西汉名将李广。他驻守边郡、匈奴畏服，称之「汉之飞将军」，数十年不敢南下。但李广终身未得封侯，后世遂把他当作良将不得志的象征。王昌龄说「但使龙城飞将在」，表面怀古，实则讽刺：不是没有李广那样的将军，而是朝廷不用、赏罚不明。",
      bodyEn: "He is Li Guang, the Western Han general who guarded the northern marches so well that the Xiongnu called him the Flying General of Han and dared not raid for decades. Yet Li Guang was never enfeoffed as a marquis, and later ages made him the emblem of a good commander ill-used. Wang Changling's wish is not really about the past: it implies the empire fails to use or reward such men.",
    },
    note: "第一句把秦、汉两个朝代并置，写的是「从古至今一直如此」——英文用 moon of Qin, passes of Han 保留这种时空压缩。",
    noteEn: "Line one puts two dynasties side by side to say 「it has always been like this」 — kept as moon of Qin, passes of Han.",
  },
  {
    slug: "furonglou",
    title: "芙蓉楼送辛渐",
    titleEn: "Seeing Xin Jian Off at Lotus Tower",
    author: "王昌龄",
    authorEn: "Wang Changling",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "送别",
    themeEn: "Farewell",
    level: 1,
    lines: [
      { zh: "寒雨连江夜入吴，平明送客楚山孤。", en: "Cold rain merges with the river as night enters Wu; at daybreak I see my guest off and the Chu hills stand alone." },
      { zh: "洛阳亲友如相问，一片冰心在玉壶。", en: "If friends and kin in Luoyang ask after me: a heart of ice, in a vase of jade." },
    ],
    keywords: [
      { w: "merge with", zh: "与…连成一片" },
      { w: "daybreak (n.)", zh: "天亮、黎明" },
      { w: "see sb. off", zh: "为某人送行" },
      { w: "ask after sb.", zh: "问候、问起某人" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "吴、楚、洛阳在哪里？",
      titleEn: "Where are Wu, Chu and Luoyang?",
      body: "诗里的地理跨度很大：芙蓉楼在今江苏镇江（古属吴地），楚山指镇江一带的山（战国时属楚），而洛阳在河南，是王昌龄亲友所在。也就是说，诗人在江南的雨夜送朋友北上回洛阳，托他带一句话给故乡的亲友。古人送别常因交通困难而格外沉重——从镇江到洛阳约七八百公里，靠车马船行要走一个月以上。",
      bodyEn: "The geography spans far: Lotus Tower stood at present-day Zhenjiang in Jiangsu (old Wu); the Chu hills are the hills around it, once part of Chu; Luoyang in Henan is where the poet's people are. So he sees a friend off north from a rainy southern night and entrusts him with a message home. Parting weighed heavily because travel was slow — Zhenjiang to Luoyang is some 700–800 km, a month or more by cart, horse and boat.",
    },
    note: "「冰心」「玉壶」是王昌龄自证清白的暗语——他当时被贬，谣言不少。英文 a heart of ice in a vase of jade 保留了两个意象的对仗。",
    noteEn: "Heart of ice and jade vase are Wang Changling's self-defence: he was under a cloud of rumours while demoted. The English keeps both images in balance.",
  },
  {
    slug: "wangtianmenshan",
    title: "望天门山",
    titleEn: "Looking at Tianmen Mountain",
    author: "李白",
    authorEn: "Li Bai",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "山水",
    themeEn: "Landscape",
    level: 1,
    lines: [
      { zh: "天门中断楚江开，碧水东流至此回。", en: "Heaven's Gate is cleft in two, the Chu river opens through; green water running east turns back at this point." },
      { zh: "两岸青山相对出，孤帆一片日边来。", en: "Blue hills on either bank rise face to face; a single sail comes out of the sun's edge." },
    ],
    keywords: [
      { w: "cleft (adj.)", zh: "裂开的" },
      { w: "bank (n.)", zh: "河岸" },
      { w: "face to face", zh: "相对、面对面" },
      { w: "sail (n.)", zh: "帆（代指船）" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "天门山真的是被水劈开的吗？",
      titleEn: "Was Tianmen Mountain really cut by water?",
      body: "天门山在安徽芜湖一带的长江两岸，东岸梁山、西岸西梁山隔江对峙如门。江水长期侵蚀、溶蚀两岸石灰岩，加上地壳抬升使河道下切，逐渐形成陡峭峡谷——「楚江开」说的是水流切开山体，这在地质学上叫河流下切与侧向侵蚀。李白写的「碧水东流至此回」，也符合此处江道收窄、水流湍急回旋的水文特征。",
      bodyEn: "Tianmen Mountain straddles the Yangtze near Wuhu in Anhui: two hills face each other like a gate. The river's long-term erosion and solution of the limestone banks, plus crustal uplift that let the channel incise downward, carved the steep gorge — what geologists call river incision and lateral erosion. 「Green water running east turns back here」 also matches the hydrology: the channel narrows and the current swirls.",
    },
    note: "动词是其灵魂：断、开、流、回、出、来——六个动词把静止的山水写成了一场迎面而来的相遇。英文用 cleft / opens / running / turns / rise / comes 一一对应。",
    noteEn: "Six verbs drive the poem — cleft, opens, running, turns, rise, comes — turning still landscape into a head-on encounter.",
  },
  {
    slug: "zengwanglun",
    title: "赠汪伦",
    titleEn: "To Wang Lun",
    author: "李白",
    authorEn: "Li Bai",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "送别",
    themeEn: "Farewell",
    level: 1,
    lines: [
      { zh: "李白乘舟将欲行，忽闻岸上踏歌声。", en: "I board the boat and am about to go, when suddenly I hear singing and stamping on the shore." },
      { zh: "桃花潭水深千尺，不及汪伦送我情。", en: "Peach Blossom Pool is a thousand feet deep, yet it is nothing to the depth of Wang Lun's seeing me off." },
    ],
    keywords: [
      { w: "be about to", zh: "正要（做某事）" },
      { w: "stamp (v.)", zh: "踏地、跺脚打拍子" },
      { w: "be nothing to", zh: "比不上" },
      { w: "depth (n.)", zh: "深度；深厚" },
    ],
    cross: {
      field: "数学",
      fieldEn: "Mathematics",
      title: "「不及」是一种什么比较？",
      titleEn: "What kind of comparison is 「不及」?",
      body: "这是中国诗里典型的「以深比深」——把抽象的感情深度嫁接到可测量的水深上。数学上它属于不可通约量的修辞比较：千尺是有限数，情谊没有单位，诗人却强行让两者相比，结论是「有限 < 无限」。桃花潭实际水深当然不足千尺，这种夸张叫 hyperbole（夸张法），英文里 I love you more than all the stars 是同一套路。",
      bodyEn: "This is the classic Chinese move of measuring feeling by depth. Mathematically it is a comparison of incommensurable quantities: a thousand feet is finite, affection has no unit, yet the poet forces the comparison and concludes finite < infinite. The real pool is nowhere near a thousand feet deep — that is hyperbole, the same device as 「more than all the stars」.",
    },
    note: "「忽闻」二字是全诗转折——本来只是普通告别，朋友却唱着歌追来了。英文用 suddenly 把惊喜放在句中。",
    noteEn: "The hinge is 「忽然」: an ordinary farewell turns into a friend chasing the boat with a song. The English puts suddenly mid-line for the surprise.",
  },
  {
    slug: "wangdongting",
    title: "望洞庭",
    titleEn: "Viewing Dongting Lake",
    author: "刘禹锡",
    authorEn: "Liu Yuxi",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "山水",
    themeEn: "Landscape",
    level: 1,
    lines: [
      { zh: "湖光秋月两相和，潭面无风镜未磨。", en: "Lake light and autumn moon are in perfect harmony; the windless surface is a mirror left unpolished." },
      { zh: "遥望洞庭山水翠，白银盘里一青螺。", en: "Seen from afar, Dongting's hills and water are emerald — a single green snail in a silver plate." },
    ],
    keywords: [
      { w: "harmony (n.)", zh: "和谐、相称" },
      { w: "windless (adj.)", zh: "无风的" },
      { w: "unpolished (adj.)", zh: "未打磨的" },
      { w: "emerald (adj./n.)", zh: "翠绿的；翡翠" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "为什么无风时水面像镜子？",
      titleEn: "Why does calm water mirror the sky?",
      body: "水面反光遵循反射定律。水面平静时是一块光滑平面，发生镜面反射，能成清晰倒影；风一起，水面变成无数朝向各异的小斜面，光被反射到四面八方，形成漫反射，倒影就碎了。古人说「镜未磨」很内行：铜镜没打磨前也是模糊的，正好对应月光下略微朦胧的水面。",
      bodyEn: "Reflection follows a simple law. A flat, calm surface gives specular reflection and a clear image; wind breaks it into countless tiny facets at different angles, sending light in all directions — diffuse reflection, and the image shatters. 「A mirror left unpolished」 is expertly chosen: an unpolished bronze mirror is likewise slightly hazy, just like moonlit water.",
    },
    note: "两个比喻一个比水面、一个比全景：unpolished mirror 写质感，silver plate 写构图——从近到远，镜头在拉。",
    noteEn: "Two similes at different scales: an unpolished mirror for texture, a silver plate for composition — the camera pulls back.",
  },
  {
    slug: "langtaosha-yi",
    title: "浪淘沙 · 其一",
    titleEn: "Sand-Sifting Waves · I",
    author: "刘禹锡",
    authorEn: "Liu Yuxi",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "词",
    theme: "山水",
    themeEn: "Landscape",
    level: 1,
    lines: [
      { zh: "九曲黄河万里沙，浪淘风簸自天涯。", en: "Nine bends of the Yellow River, ten thousand li of sand — waves sift it, winds toss it, all the way from the sky's edge." },
      { zh: "如今直上银河去，同到牵牛织女家。", en: "Now let us sail straight up the Milky Way, and call together at the Herd-boy's and the Weaver's house." },
    ],
    keywords: [
      { w: "sift (v.)", zh: "淘洗、筛选" },
      { w: "toss (v.)", zh: "抛起、颠簸" },
      { w: "the Milky Way", zh: "银河" },
      { w: "call at", zh: "拜访、停驻" },
    ],
    cross: {
      field: "天文",
      fieldEn: "Astronomy",
      title: "牵牛织女是哪两颗星？",
      titleEn: "Which stars are the Herd-boy and the Weaver?",
      body: "牵牛星即天鹰座 α 星（Altair，牛郎星），织女星是天琴座 α 星（Vega，织女星），两者隔着银河遥遥相对。Altair 距地球约 16.7 光年，Vega 约 25 光年，彼此相距约 16 光年——它们从来没有「一年一会」，那只是人间给星空编的故事。夏季夜空，这两颗星与天津四组成著名的「夏季大三角」。",
      bodyEn: "The Herd-boy is Altair (alpha Aquilae) and the Weaver is Vega (alpha Lyrae), facing each other across the Milky Way. Altair lies about 16.7 light-years away, Vega about 25; they are some 16 light-years apart and never meet, once a year or otherwise — the romance is ours, not theirs. In summer the two form the Summer Triangle with Deneb.",
    },
    note: "从黄河一路想到银河，靠的是「黄河—天河」的字面联想。英文用 the Yellow River 与 the Milky Way 前后呼应，保留了这层跳跃。",
    noteEn: "The leap from the Yellow River to the Milky Way rests on their names. English keeps it by echoing the Yellow River with the Milky Way.",
  },
  {
    slug: "chishang",
    title: "池上",
    titleEn: "On the Pond",
    author: "白居易",
    authorEn: "Bai Juyi",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "童趣",
    themeEn: "Childhood",
    level: 1,
    lines: [
      { zh: "小娃撑小艇，偷采白莲回。", en: "A little child poles a little boat, stealing white lotus on the way back." },
      { zh: "不解藏踪迹，浮萍一道开。", en: "Too young to hide his tracks: a pathway opens through the duckweed." },
    ],
    keywords: [
      { w: "pole (v.)", zh: "用篙撑船" },
      { w: "steal (v.)", zh: "偷摘（此处带俏皮义）" },
      { w: "hide his tracks", zh: "掩盖行踪" },
      { w: "duckweed (n.)", zh: "浮萍" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "浮萍为什么一划就「开」？",
      titleEn: "Why does duckweed part so easily?",
      body: "浮萍是漂浮水生植物，整株几乎就是一片叶状体，没有挺水的茎，根只是几条悬在水里的细丝，彼此之间不相连，靠水面张力和自身浮力铺成一层。所以船一过就被推开，随后又慢慢合拢——「一道开」写的是它被打散又浮回的状态。浮萍繁殖极快，在富营养水体中几天就能铺满池塘。",
      bodyEn: "Duckweed is a floating plant: the whole body is a tiny leaf-like thallus with no upright stem and only a few hair-like roots hanging in water. The fronds are unconnected, held on the surface by surface tension and buoyancy, so a boat pushes them apart and they drift back together — exactly the 「pathway opening」 of the poem. In nutrient-rich water it can carpet a pond within days.",
    },
    note: "「不解藏踪迹」是善意的笑话：小孩以为偷了没人知道，其实浮萍替他画了一条路。英文用 Too young to 把这句的宠溺语气写出来。",
    noteEn: "The joke is affectionate: the child thinks no one will know, but the duckweed draws his route for all to see.",
  },
  {
    slug: "xiaochi",
    title: "小池",
    titleEn: "The Little Pool",
    author: "杨万里",
    authorEn: "Yang Wanli",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "诗",
    theme: "四季",
    themeEn: "Seasons",
    level: 1,
    lines: [
      { zh: "泉眼无声惜细流，树阴照水爱晴柔。", en: "The spring's eye is silent, grudging its thin stream; tree shade rests on the water, loving the soft sunshine." },
      { zh: "小荷才露尖尖角，早有蜻蜓立上头。", en: "The little lotus has only just shown its pointed tip, when already a dragonfly stands upon it." },
    ],
    keywords: [
      { w: "grudge (v.)", zh: "吝惜、舍不得" },
      { w: "shade (n.)", zh: "树荫" },
      { w: "tip (n.)", zh: "尖、顶端" },
      { w: "dragonfly (n.)", zh: "蜻蜓" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "蜻蜓为什么喜欢停在最尖的地方？",
      titleEn: "Why do dragonflies perch on the highest point?",
      body: "蜻蜓是视觉猎手，复眼由上万个小眼组成，视野接近 360°。停在高处（枝头、荷尖）视野最开阔，既能发现飞虫，也能警惕天敌；而且高处起飞不受阻挡，有利于它高速捕食。蜻蜓的稚虫（水虿）在水中生活，靠直肠鳃呼吸，所以我们常在池塘边看到成虫——它们羽化后就守着水边。杨万里抓的正是这个典型画面。",
      bodyEn: "Dragonflies are visual hunters with compound eyes of tens of thousands of ommatidia and near-360° vision. The highest perch gives the widest view: good for spotting prey and for watching predators, and unobstructed take-off for high-speed pursuit. Their nymphs live underwater breathing through rectal gills, which is why adults stay near water after emerging. Yang Wanli caught the signature pose.",
    },
    note: "「才」与「早」是一对时间副词，写出两个动作几乎同时发生——英文用 only just… when already 完美对应。",
    noteEn: "「才」 and 「早」 are a pair of timing adverbs: two things happening almost at once — matched by only just … when already.",
  },
];
