import type { Poem } from "./types";

/** 小学阶段 · 第 3 批（田园、家国、咏怀、民歌） */
export const PRIMARY_3: Poem[] = [
  {
    slug: "shuhuyinxianshengbi",
    title: "书湖阴先生壁",
    titleEn: "Written on the Wall of Mr. Huyin's House",
    author: "王安石",
    authorEn: "Wang Anshi",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "诗",
    theme: "田园",
    themeEn: "Pastoral",
    level: 1,
    lines: [
      { zh: "茅檐长扫净无苔，花木成畦手自栽。", en: "The thatched eaves are kept swept, clean of moss; flowers and trees stand in orderly rows, planted by his own hands." },
      { zh: "一水护田将绿绕，两山排闼送青来。", en: "A stream shields the fields, winding green around them; two hills push the gate open and send in their blue." },
    ],
    keywords: [
      { w: "thatched (adj.)", zh: "茅草盖的" },
      { w: "moss (n.)", zh: "苔藓" },
      { w: "in rows", zh: "成畦、成排" },
      { w: "shield (v.)", zh: "护卫、环绕" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "「排闼」是什么动作？",
      titleEn: "What does 「排闼」 mean?",
      body: "「闼」是门（多指小门），「排闼」即推门直入。这个典故出自《汉书·樊哙传》：樊哙听说刘邦病重不见人，情急之下「排闼直入」，推开门闯进去进谏。王安石借用这个典故形容两座山像老朋友一样推门送青进来——把静态的山写成有礼数的访客，是他晚年诗风的典型手法。",
      bodyEn: "「闼」 is a small door; 「排闼」 means pushing it open and walking in. The phrase comes from the Book of Han: when Emperor Gaozu was ill and refused visitors, the general Fan Kuai 「pushed open the gate and strode in」 to remonstrate. Wang Anshi borrows it to make two hills act like old friends who push the gate open and bring their blue indoors — a signature move of his late style.",
    },
    note: "「护」「绕」「排」「送」四个动词把山水写成有情的邻居——英文用 shields / winding / push / send 对应。",
    noteEn: "Four verbs — shields, winding, push, send — turn landscape into attentive neighbours.",
  },
  {
    slug: "wanghulou",
    title: "六月二十七日望湖楼醉书",
    titleEn: "Drunk, Written at Lake-View Tower on the 27th of the Sixth Month",
    author: "苏轼",
    authorEn: "Su Shi",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "诗",
    theme: "山水",
    themeEn: "Landscape",
    level: 1,
    lines: [
      { zh: "黑云翻墨未遮山，白雨跳珠乱入船。", en: "Black clouds, ink overturned, have not yet hid the hills; white rain, beads that leap, pelts wildly into the boat." },
      { zh: "卷地风来忽吹散，望湖楼下水如天。", en: "A wind sweeps along the ground and suddenly blows them apart; below Lake-View Tower the water is like the sky." },
    ],
    keywords: [
      { w: "overturned (ink)", zh: "打翻的（墨）" },
      { w: "pelt (v.)", zh: "（雨点）砸落" },
      { w: "sweep along", zh: "席卷" },
      { w: "blow apart", zh: "吹散" },
    ],
    cross: {
      field: "气象",
      fieldEn: "Meteorology",
      title: "夏天的暴雨为什么来得快去得快？",
      titleEn: "Why do summer storms come and go so fast?",
      body: "诗里写的是典型的强对流天气。夏季地表强烈受热，暖湿空气急剧上升形成浓积云甚至积雨云（黑云如墨），水汽凝结释放潜热进一步加剧上升，十分钟内就能从晴空发展到暴雨；但积雨云生命史短（通常半小时到一两小时），下沉气流切断上升支后云体迅速消散，于是「忽吹散」「水如天」。苏轼把一场雷阵雨的完整生命史写进了 28 个字。",
      bodyEn: "This is textbook convective weather. Strong summer heating drives moist air upward into towering cumulonimbus (the ink-black cloud); latent heat released by condensation intensifies the updraught, so clear sky can turn to downpour within minutes. But such clouds live only half an hour to a couple of hours — downdraughts cut off the updraught and the system collapses, hence 「suddenly blown apart」 and water like sky. Su Shi compressed a thunderstorm's whole life cycle into twenty-eight characters.",
    },
    note: "四句四个镜头，快得像剪辑：黑云、白雨、狂风、静水。英文用现在分词 ink overturned / beads that leap 保留速度感。",
    noteEn: "Four shots cut fast: black cloud, white rain, gust, still water.",
  },
  {
    slug: "yinhushang",
    title: "饮湖上初晴后雨",
    titleEn: "Drinking on the Lake, First Clear then Rainy",
    author: "苏轼",
    authorEn: "Su Shi",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "诗",
    theme: "山水",
    themeEn: "Landscape",
    level: 1,
    lines: [
      { zh: "水光潋滟晴方好，山色空蒙雨亦奇。", en: "The water shimmers — fair in clear weather; the hills grow hazy — strange and lovely in rain too." },
      { zh: "欲把西湖比西子，淡妆浓抹总相宜。", en: "If I compare West Lake to the lady Xi, light makeup or heavy, she is always becoming." },
    ],
    keywords: [
      { w: "shimmer (v.)", zh: "波光闪动" },
      { w: "hazy (adj.)", zh: "朦胧的" },
      { w: "compare A to B", zh: "把 A 比作 B" },
      { w: "becoming (adj.)", zh: "得体的、相宜的" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "西湖为什么晴雨都好看？",
      titleEn: "Why is West Lake lovely in both sun and rain?",
      body: "西湖是典型的泻湖成因：原为钱塘江口的海湾，泥沙淤积使湾口封闭，逐渐淡化成内陆湖，湖面约 6.4 平方公里，平均水深仅约 2.3 米。水浅意味着风浪小、能清晰倒映天光山影（晴好），而水汽充足时湖面蒸腾形成薄雾，远山层次朦胧（雨奇）。苏轼的观察后来变成了一句成语——淡妆浓抹总相宜。",
      bodyEn: "West Lake began as a bay at the Qiantang estuary; sediment sealed the mouth and the water freshened into an inland lake of about 6.4 km² with a mean depth of only 2.3 m. Shallowness means small waves and clean reflections of sky and hills (fine in sun), while abundant evaporation lays a thin mist over the water and softens the distant ranges (lovely in rain). Su Shi's observation became an idiom.",
    },
    note: "把风景比作美人不是苏东坡首创，但「淡妆浓抹」的双向肯定是他给的——英文用 light makeup or heavy 保留两个状态。",
    noteEn: "Comparing scenery to a beauty was not new; the double endorsement — light or heavy makeup — was his.",
  },
  {
    slug: "huichongchunjiang",
    title: "惠崇春江晚景",
    titleEn: "Evening Scene on a Spring River, after Huichong's Painting",
    author: "苏轼",
    authorEn: "Su Shi",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "诗",
    theme: "四季",
    themeEn: "Seasons",
    level: 1,
    lines: [
      { zh: "竹外桃花三两枝，春江水暖鸭先知。", en: "Beyond the bamboo, two or three peach blossom sprays; the spring river warms, and the ducks are first to know." },
      { zh: "蒌蒿满地芦芽短，正是河豚欲上时。", en: "Wormwood covers the ground, reed shoots are still short — this is just when the pufferfish come upstream." },
    ],
    keywords: [
      { w: "spray (n.)", zh: "（花）枝" },
      { w: "be first to know", zh: "最先知道" },
      { w: "shoot (n.)", zh: "嫩芽" },
      { w: "come upstream", zh: "（鱼）溯游而上" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "鸭子真的能先知道水暖吗？",
      titleEn: "Can ducks really feel the water warming first?",
      body: "有一定道理。鸭类体表有厚绒羽与尾脂腺分泌的油脂防水，冷水刺激对其影响小，它们全天候在水中活动，对水温变化的接触机会远多于岸上的人。更关键的是水温回升时水生昆虫、螺类与水草萌发，鸭子的食物随之活跃——它们「先知」的其实是食物链的信号。河豚春季从海入江产卵，也是水温驱动的洄游，苏轼的物候链条是准确的。",
      bodyEn: "Largely yes. Ducks have dense down and oil from the preen gland that keeps cold water off the skin, so they stay in the water all day and register temperature shifts far more often than people on shore. More importantly, warming water awakens aquatic insects, snails and new shoots — the ducks are reading a food-chain signal. Pufferfish likewise migrate upstream to spawn as water warms; Su Shi's chain of phenology is accurate.",
    },
    note: "这是一首题画诗——画上画不出的「水暖」和「欲上」，苏轼用联想补了出来。英文用 the ducks are first to know 保留拟人。",
    noteEn: "A poem on a painting: the painter cannot show warmth or the urge to spawn, so Su Shi supplies them.",
  },
  {
    slug: "xiarijueju",
    title: "夏日绝句",
    titleEn: "Summer Quatrain",
    author: "李清照",
    authorEn: "Li Qingzhao",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "诗",
    theme: "家国",
    themeEn: "Nation",
    level: 1,
    lines: [
      { zh: "生当作人杰，死亦为鬼雄。", en: "Living, one should be a hero among men; dead, one should be a hero among ghosts." },
      { zh: "至今思项羽，不肯过江东。", en: "Even now I think of Xiang Yu, who refused to cross back to the east of the river." },
    ],
    keywords: [
      { w: "hero (n.)", zh: "豪杰" },
      { w: "refuse to", zh: "不肯" },
      { w: "even now", zh: "至今" },
      { w: "think of", zh: "思念、想起" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "项羽为什么不肯过江东？",
      titleEn: "Why wouldn't Xiang Yu cross the river?",
      body: "公元前 202 年垓下之战，项羽被刘邦围困，突围至乌江（今安徽和县）。乌江亭长备船劝他渡江回江东（其起兵的吴中故地，今苏南一带），以图再起。项羽答：我与江东八千子弟渡江西去，今无一生还，纵江东父老怜我、奉我为王，我有何面目见之？遂自刎。李清照写此诗时正值北宋灭亡、宋室南渡——她是在借项羽讽刺南宋君臣的苟安。",
      bodyEn: "In 202 BC, after defeat at Gaixia, Xiang Yu broke out and reached the Wu River (present-day Hexian, Anhui). The ferry master urged him to cross east — his home base around Wu in the south — and rebuild. He replied that he had led eight thousand sons of the east across the river and not one had returned; even if the elders pitied and crowned him, how could he face them? He killed himself. Li Qingzhao wrote this after the Northern Song fell and the court fled south — Xiang Yu is her rebuke to those who settled for survival.",
    },
    note: "二十个字，全用判断语气（当作、亦为），没有一句写景——英文用 should be 的重复保留了这种斩钉截铁。",
    noteEn: "Twenty characters, all verdicts — no scenery. The doubled should be keeps the absolute tone.",
  },
  {
    slug: "shier",
    title: "示儿",
    titleEn: "To My Sons",
    author: "陆游",
    authorEn: "Lu You",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "诗",
    theme: "家国",
    themeEn: "Nation",
    level: 1,
    lines: [
      { zh: "死去元知万事空，但悲不见九州同。", en: "I knew all along that at death all things turn empty — I only grieve that I shall not see the nine provinces made one." },
      { zh: "王师北定中原日，家祭无忘告乃翁。", en: "On the day the royal armies recover the central plain, forget not, at the family sacrifice, to tell your father." },
    ],
    keywords: [
      { w: "all along", zh: "本来（元知）" },
      { w: "grieve (v.)", zh: "悲伤" },
      { w: "recover (v.)", zh: "收复" },
      { w: "forget not", zh: "不要忘记（古体）" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "「九州」指哪里？",
      titleEn: "What does 「the nine provinces」 mean?",
      body: "九州是战国以来对中国的地理划分（冀、兖、青、徐、扬、荆、豫、梁、雍），后来成为「天下」的代称。陆游所处的南宋，淮河以北的中原被金朝占据已近百年，所谓「北定中原」即收复黄河流域。他写此诗时八十五岁，临终遗言式的作品；而南宋最终未能收复中原，反而亡于蒙古——这使这首诗成了中国文学史上最沉重的一句嘱托。",
      bodyEn: "The nine provinces were a Warring States division of China (Ji, Yan, Qing, Xu, Yang, Jing, Yu, Liang, Yong), later a synonym for the whole realm. In Lu You's Southern Song, the central plain north of the Huai had been under the Jin for nearly a century; 「recover the central plain」 means taking back the Yellow River basin. He was eighty-five, writing as a deathbed charge — and the Song never did recover it, falling instead to the Mongols, which makes this the heaviest request in Chinese literature.",
    },
    note: "「但悲」是全诗唯一的情感出口：万事皆空，只有这一件事放不下。英文用 only grieve 收束。",
    noteEn: "Everything empties except one thing — held by a single only grieve.",
  },
  {
    slug: "qiuyelimeng",
    title: "秋夜将晓出篱门迎凉有感",
    titleEn: "Thoughts on Stepping out of the Fence Gate before Dawn on an Autumn Night",
    author: "陆游",
    authorEn: "Lu You",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "诗",
    theme: "家国",
    themeEn: "Nation",
    level: 2,
    lines: [
      { zh: "三万里河东入海，五千仞岳上摩天。", en: "Thirty thousand li of river run east into the sea; mountains of five thousand fathoms brush the sky." },
      { zh: "遗民泪尽胡尘里，南望王师又一年。", en: "The people left behind have wept their tears dry in Tartar dust, looking south for the royal armies — another year." },
    ],
    keywords: [
      { w: "brush (v.)", zh: "触碰、摩" },
      { w: "weep (v.)", zh: "哭泣" },
      { w: "left behind", zh: "被遗弃的（遗民）" },
      { w: "another year", zh: "又一年" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "三万里河、五千仞岳指什么？",
      titleEn: "Which river and mountains are these?",
      body: "「三万里河」指黄河，「五千仞岳」指华山（一说泰山）。黄河全长约 5464 公里，古人以「三万里」极言其长；华山位于陕西华阴，海拔 2154 米，以险峻著称，五岳中最高。陆游写此诗时在南宋山阴（今浙江绍兴），黄河、华山都在沦陷区——他是靠记忆与想象在写故国的山河，两个数字越是壮阔，后面「泪尽胡尘」就越痛。",
      bodyEn: "The river is the Yellow River — some 5,464 km, with「thirty thousand li」 as hyperbole. The mountain is Mount Hua in Shaanxi (or Tai Shan), 2,154 m and the steepest of the Five Great Peaks. Lu You wrote this at Shanyin in Zhejiang, deep in Southern Song territory: both lie in occupied land, so he writes from memory. The grander the two numbers, the sharper 「tears dried in Tartar dust」.",
    },
    note: "前两句极壮阔，后两句极凄凉，中间没有任何过渡——英文用 another year 收尾，把「一年又一年的等待」压在最轻的词上。",
    noteEn: "Grandeur, then desolation, with no transition: another year carries decades of waiting.",
  },
  {
    slug: "sishitianyuan",
    title: "四时田园杂兴 · 其三十一",
    titleEn: "Four Seasons of the Fields · No. 31",
    author: "范成大",
    authorEn: "Fan Chengda",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "诗",
    theme: "田园",
    themeEn: "Pastoral",
    level: 1,
    lines: [
      { zh: "昼出耘田夜绩麻，村庄儿女各当家。", en: "By day they weed the fields, by night they twist hemp; the sons and daughters of the village each keep a household." },
      { zh: "童孙未解供耕织，也傍桑阴学种瓜。", en: "The grandchildren cannot yet help with ploughing or weaving, but by the mulberry shade they learn to sow melons." },
    ],
    keywords: [
      { w: "weed (v.)", zh: "除草、耘田" },
      { w: "twist (hemp)", zh: "搓（麻线）" },
      { w: "keep a household", zh: "当家、持家" },
      { w: "learn to", zh: "学着（做）" },
    ],
    cross: {
      field: "农学",
      fieldEn: "Agronomy",
      title: "为什么要「昼耘田、夜绩麻」？",
      titleEn: "Why weed by day and twist hemp by night?",
      body: "这是江南稻作区典型的一年两熟农事节律：白天田间管理（耘田即在稻行间除草松土，促进根系通气），夜里做家庭手工业。麻（大麻或苎麻）收割后需沤制、剥皮、劈丝、绩成线，才能织布——这些工序不占农时、可在灯下完成。范成大写的是「男耕女织」的经济结构，也是小农家庭靠副业补足生计的真实图景。",
      bodyEn: "This is the double-cropping rhythm of the rice south: field work by day (weeding between rice rows loosens soil and aerates roots), handicraft by night. Hemp must be retted, stripped, split and twisted into thread before it can be woven — all tasks that fit under a lamp without stealing field time. Fan Chengda documents not just 「men plough, women weave」 but how a smallholding survived on by-work.",
    },
    note: "最后一句最妙：孩子只是在玩，却已经在学着谋生——英文用 learn to sow melons 保留了这份郑重。",
    noteEn: "The children think they are playing, yet they are already learning a living — kept straight in learn to sow melons.",
  },
  {
    slug: "zhizinongbing",
    title: "稚子弄冰",
    titleEn: "A Child Plays with Ice",
    author: "杨万里",
    authorEn: "Yang Wanli",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "诗",
    theme: "童趣",
    themeEn: "Childhood",
    level: 1,
    lines: [
      { zh: "稚子金盆脱晓冰，彩丝穿取当银钲。", en: "At dawn the child lifts ice from the bronze basin, threads it with coloured string to serve as a silver gong." },
      { zh: "敲成玉磬穿林响，忽作玻璃碎地声。", en: "Struck, it rings like a jade chime through the woods — then suddenly breaks, with the sound of glass shattering on the ground." },
    ],
    keywords: [
      { w: "lift (v.)", zh: "脱出、取出" },
      { w: "thread (v.)", zh: "用线穿" },
      { w: "strike (v.)", zh: "敲击" },
      { w: "shatter (v.)", zh: "碎裂" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "冰为什么会「响」？",
      titleEn: "Why does ice ring?",
      body: "声音由振动产生，音高取决于物体的形状、材质与刚度。铜盆里冻出的冰是一块薄而均匀、且内部气泡少的冰片——敲击时它像锣一样整体振动，能发出清脆的高音；一旦出现裂纹，整体振动被破坏，声音立刻变成碎裂的噪声。杨万里写的从「玉磬穿林响」到「玻璃碎地声」，正是一次完整的声学状态转换，观察极其准确。",
      bodyEn: "Sound comes from vibration; pitch depends on shape, material and stiffness. Ice frozen in a bronze basin forms a thin, even sheet with few bubbles — struck, it vibrates as a whole like a gong and rings clearly. Once it cracks, the coherent vibration breaks up and the tone collapses into noise. The poem moves from jade chime to shattering glass: one complete acoustic transition, recorded precisely.",
    },
    note: "杨万里的绝活是抓瞬间——从得意到失落，只有一句的距离。英文用 suddenly 标记这个转折。",
    noteEn: "Yang Wanli's speciality is the instant: pride to loss in one line, marked by suddenly.",
  },
  {
    slug: "xiaochujingci",
    title: "晓出净慈寺送林子方",
    titleEn: "Leaving Jingci Temple at Dawn, Seeing Lin Zifang Off",
    author: "杨万里",
    authorEn: "Yang Wanli",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "诗",
    theme: "四季",
    themeEn: "Seasons",
    level: 1,
    lines: [
      { zh: "毕竟西湖六月中，风光不与四时同。", en: "After all, at West Lake in the sixth month, the scene is unlike any other season." },
      { zh: "接天莲叶无穷碧，映日荷花别样红。", en: "Lotus leaves reaching the sky are boundlessly green; blossoms facing the sun are red as nowhere else." },
    ],
    keywords: [
      { w: "after all", zh: "毕竟" },
      { w: "unlike (prep.)", zh: "不同于" },
      { w: "boundlessly (adv.)", zh: "无穷地" },
      { w: "as nowhere else", zh: "别样（独特地）" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "荷花为什么六月开得最好？",
      titleEn: "Why does the lotus peak in the sixth month?",
      body: "荷花（莲）是典型的长日照、喜温植物，水温稳定在 20℃ 以上、日长 13 小时以上才开始大量开花，盛花期正好落在公历 6—8 月。它的花朵还能自调节温度：开花时通过呼吸作用产热，使花心温度高于环境约 2—3℃，既保护花蕊又利于吸引传粉昆虫。杨万里笔下「六月中」的西湖，正是物候学上的盛花期。",
      bodyEn: "The lotus is a long-day, warmth-loving plant: it blooms heavily once water stays above about 20℃ and day length exceeds thirteen hours, which falls in June–August. The flower even thermoregulates, raising its core temperature a couple of degrees above ambient by respiratory heat — protecting the reproductive parts and attracting pollinating insects. The sixth lunar month at West Lake is precisely peak flowering.",
    },
    note: "两句一绿一红，靠颜色撑起整个画面——英文用 boundlessly green 与 red as nowhere else 让色彩互为对照。",
    noteEn: "One green line, one red: colour carries the whole picture.",
  },
  {
    slug: "cunwan",
    title: "村晚",
    titleEn: "Village Evening",
    author: "雷震",
    authorEn: "Lei Zhen",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "诗",
    theme: "田园",
    themeEn: "Pastoral",
    level: 1,
    lines: [
      { zh: "草满池塘水满陂，山衔落日浸寒漪。", en: "Grass fills the pond, water brims the bank; the hills hold the setting sun, steeped in cold ripples." },
      { zh: "牧童归去横牛背，短笛无腔信口吹。", en: "The herdboy goes home lying across the ox's back, playing a short flute with no fixed tune, just as he pleases." },
    ],
    keywords: [
      { w: "brim (v.)", zh: "（水）满溢" },
      { w: "steep (v.)", zh: "浸、泡" },
      { w: "lie across", zh: "横卧" },
      { w: "as one pleases", zh: "随口、随意" },
    ],
    cross: {
      field: "音乐",
      fieldEn: "Music",
      title: "「无腔」是什么样的吹法？",
      titleEn: "What is a tune with no 「腔」?",
      body: "「腔」指固定的曲调、板眼。中国笛乐有严格曲牌与宫调体系，而牧童吹的是即兴散曲，没有固定旋律与节拍，属于民间最原始的演奏形态。民族音乐学上这类即兴叫 improvisation，与文人记谱的音乐相对。诗人特意强调「无腔」，正是为了突出这份不受规矩约束的野趣——英文 with no fixed tune 保留了这层意思。",
      bodyEn: "「腔」 is the fixed melodic framework — mode, metre, set tune. Chinese flute music has an elaborate notation of fixed airs; the herdboy plays free improvisation with no set melody or beat, the oldest stratum of folk music making. Ethnomusicologists would call it improvisation, standing against notated literati repertoire. Emphasising 「no fixed tune」 foregrounds that untutored freedom.",
    },
    note: "「山衔落日」的「衔」字极妙——山像含着太阳；英文用 hold 保留了口部动作。",
    noteEn: "The word 「衔」 — the hills hold the sun in their mouths — survives as hold.",
  },
  {
    slug: "congjunxing",
    title: "从军行 · 其四",
    titleEn: "Song of the Campaign · IV",
    author: "王昌龄",
    authorEn: "Wang Changling",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "边塞",
    themeEn: "Frontier",
    level: 1,
    lines: [
      { zh: "青海长云暗雪山，孤城遥望玉门关。", en: "Over Qinghai, long clouds darken the snow mountains; a lonely keep looks far toward Yumen Pass." },
      { zh: "黄沙百战穿金甲，不破楼兰终不还。", en: "In yellow sands, a hundred battles have pierced our mail; until we break Loulan, we shall not return." },
    ],
    keywords: [
      { w: "darken (v.)", zh: "使…变暗" },
      { w: "mail (n.)", zh: "铠甲（锁子甲）" },
      { w: "pierce (v.)", zh: "磨穿、刺穿" },
      { w: "until", zh: "直到…才" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "楼兰在哪里？为什么一定要「破」它？",
      titleEn: "Where was Loulan, and why destroy it?",
      body: "楼兰是西域古国，位于罗布泊西北岸，是丝绸之路南道上的咽喉城邦，西汉时屡次依附匈奴、袭击汉使，所以汉唐诗人常以「楼兰」代指西北敌患。公元 4 世纪前后，楼兰因孔雀河改道、罗布泊萎缩而废弃，唐代时早已是废墟——王昌龄用的是典故，不是实指。今天楼兰古城遗址是新疆的重要考古现场，出土过著名的「楼兰美女」干尸。",
      bodyEn: "Loulan was a Silk Road kingdom on the north-west shore of Lop Nur, commanding the southern route. It repeatedly sided with the Xiongnu and attacked Han envoys, so poets used its name as shorthand for the northern threat. It was abandoned around the 4th century when the Kongque River shifted and Lop Nur shrank; by Tang it was already ruin, so Wang Changling is citing a legend, not a live target. The site is now a major archaeological zone in Xinjiang — source of the famous Loulan Beauty mummy.",
    },
    note: "「穿金甲」是磨损到透——不是勇猛，是久战。英文用 pierced our mail 保留了这份消耗感。",
    noteEn: "「Mail pierced」 means worn through — not valour but attrition.",
  },
  {
    slug: "changgeixing",
    title: "长歌行（节选）",
    titleEn: "Long Song Ballad (excerpt)",
    author: "汉乐府",
    authorEn: "Han Music Bureau",
    dynasty: "汉",
    dynastyEn: "Han",
    stage: "小学",
    kind: "诗",
    theme: "人生",
    themeEn: "Life",
    level: 1,
    lines: [
      { zh: "青青园中葵，朝露待日晞。", en: "Green, green the mallows in the garden; the morning dew awaits the sun to dry it." },
      { zh: "少壮不努力，老大徒伤悲。", en: "If one does not strive while young and strong, in old age one grieves in vain." },
    ],
    keywords: [
      { w: "dew (n.)", zh: "露水" },
      { w: "dry (v.)", zh: "晒干" },
      { w: "strive (v.)", zh: "努力" },
      { w: "in vain", zh: "徒然、白费" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "露水为什么会消失？",
      titleEn: "Where does the dew go?",
      body: "露水是夜间地面与植物辐射冷却，使近地空气温度降到露点以下，水汽在叶面凝结成的小水滴。日出后太阳短波辐射加热叶面，露滴吸收热量蒸发（液态变气态，需吸收约 2260 kJ/kg 的汽化潜热），几分钟到几十分钟就消失。诗里「朝露待日晞」把这个物理过程用作人生比喻：短暂的、必然蒸发的东西，正是青春。",
      bodyEn: "Dew forms when surfaces cool by radiation at night until nearby air drops below its dew point and water vapour condenses on leaves. Sunlight warms the leaf, the droplets absorb heat and evaporate (liquid to vapour costs about 2,260 kJ/kg of latent heat), vanishing within minutes. The poem turns that physics into a moral: youth is the thing that inevitably evaporates.",
    },
    note: "全诗从园中葵写到百川东到海，最后落在「少壮不努力」——英文用 in vain 把「徒」字的无奈收住。",
    noteEn: "From mallows to rivers running east, it lands on one warning — in vain carries the futility.",
  },
  {
    slug: "chilege",
    title: "敕勒歌",
    titleEn: "The Song of Chile",
    author: "北朝民歌",
    authorEn: "Northern Dynasties folk song",
    dynasty: "北朝",
    dynastyEn: "Northern Dynasties",
    stage: "小学",
    kind: "诗",
    theme: "边塞",
    themeEn: "Frontier",
    level: 1,
    lines: [
      { zh: "敕勒川，阴山下。天似穹庐，笼盖四野。", en: "The Chile plain, below Mount Yin. The sky is like a great yurt, covering the four quarters of the land." },
      { zh: "天苍苍，野茫茫，风吹草低见牛羊。", en: "Sky so blue, the wilds so vast — the wind lowers the grass, and cattle and sheep appear." },
    ],
    keywords: [
      { w: "yurt (n.)", zh: "穹庐、毡帐（蒙古包）" },
      { w: "cover (v.)", zh: "笼罩" },
      { w: "vast (adj.)", zh: "辽阔的" },
      { w: "lower (v.)", zh: "（风）吹低" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "阴山与敕勒川在哪里？",
      titleEn: "Where are Mount Yin and the Chile plain?",
      body: "阴山横亘内蒙古中部，平均海拔约 1500—2000 米，是中国重要的地理分界线：山北是内蒙古高原，山南是河套平原；它同时阻挡北下的寒潮，使山南积温更高、适宜农耕。敕勒川一般指阴山南麓的草原地带（今呼和浩特、包头一带，即土默川平原）。敕勒是古代游牧民族（一说即高车、丁零），这首北朝民歌原本用鲜卑语歌唱，后译成汉语。",
      bodyEn: "The Yin mountains run across central Inner Mongolia at 1,500–2,000 m, a major divide: the Mongolian plateau lies north, the Hetao plain south. They also block cold surges from the north, leaving the southern side warmer and farmable. The Chile plain is the grassland at their southern foot — today's Tumochuan around Hohhot and Baotou. The Chile were a pastoral people (often identified with the Gaoju or Dingling); the song was originally sung in a Xianbei language and later rendered into Chinese.",
    },
    note: "「天似穹庐」是游牧民族才有的比喻——把天比作自己的帐篷。英文用 yurt 而不是 tent，保留了这层文化身份。",
    noteEn: "Only a herding people would compare the sky to their own dwelling — yurt, not tent, keeps that identity.",
  },
  {
    slug: "momei",
    title: "墨梅",
    titleEn: "Ink Plum",
    author: "王冕",
    authorEn: "Wang Mian",
    dynasty: "元",
    dynastyEn: "Yuan",
    stage: "小学",
    kind: "诗",
    theme: "咏物",
    themeEn: "Nature",
    level: 1,
    lines: [
      { zh: "我家洗砚池头树，朵朵花开淡墨痕。", en: "The tree by my inkstone-rinsing pool — every blossom opens in the tint of pale ink." },
      { zh: "不要人夸好颜色，只留清气满乾坤。", en: "It asks no one to praise its pretty colour; it only leaves its clean air filling heaven and earth." },
    ],
    keywords: [
      { w: "inkstone (n.)", zh: "砚台" },
      { w: "tint (n.)", zh: "淡淡的色调" },
      { w: "praise (v.)", zh: "夸赞" },
      { w: "heaven and earth", zh: "乾坤、天地" },
    ],
    cross: {
      field: "化学",
      fieldEn: "Chemistry",
      title: "墨为什么能千年不褪？",
      titleEn: "Why does ink last a thousand years?",
      body: "传统墨用松烟或油烟（碳黑）加动物胶制成。碳黑是单质碳，化学性质极稳定，常温下不与氧气、水、一般酸碱反应，也不易被微生物分解；光照射也不会使它分解——这与有机染料（靛蓝、花青等）遇光易褪色的机理完全不同。所以水墨画能保存千年，而许多彩色颜料却变色了。王冕「只留清气」说的是品格，但墨本身确实是最耐久的颜料。",
      bodyEn: "Traditional ink is pine-soot or oil-soot carbon black bound with animal glue. Elemental carbon is chemically inert: at room temperature it resists oxygen, water and ordinary acids and bases, and microbes cannot digest it; light will not break it down either — unlike organic dyestuffs (indigo, anthocyanins) that photodegrade. Hence ink paintings survive a millennium while colours fade. Wang Mian meant character by 「clean air」, but the ink itself is the most durable pigment there is.",
    },
    note: "「清气」既指梅香，也指人品——英文用 clean air 保留了这层双关。",
    noteEn: "「Clean air」 means both the plum's scent and a person's integrity — the pun survives.",
  },
];
