import type { Poem } from "./types";

/** 小学阶段 · 第 5 批（唐诗名篇、宋诗理趣、小令、上古神话） */
export const PRIMARY_5: Poem[] = [
  {
    slug: "huanghelou",
    title: "黄鹤楼送孟浩然之广陵",
    titleEn: "Seeing Meng Haoran Off to Guangling at Yellow Crane Tower",
    author: "李白",
    authorEn: "Li Bai",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "送别",
    themeEn: "Farewell",
    level: 1,
    lines: [
      { zh: "故人西辞黄鹤楼，烟花三月下扬州。", en: "My old friend bids farewell at Yellow Crane Tower, and sails down to Yangzhou in the misty flowers of the third month." },
      { zh: "孤帆远影碧空尽，唯见长江天际流。", en: "His lone sail fades into the blue void — I see only the Yangtze flowing to the edge of the sky." },
    ],
    keywords: [
      { w: "lone sail", zh: "孤帆" },
      { w: "fade into", zh: "消失在" },
      { w: "misty", zh: "烟雾迷蒙的" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "为什么是「下」扬州？",
      titleEn: "Why does he go down to Yangzhou?",
      body: "黄鹤楼在武汉，扬州在长江下游近入海口处。水往低处流，从武汉到扬州是顺流，「下」字既是行船的方向，也是中国地势西高东低的注脚——古人乘船东下快而省力，逆流西上才要「两岸猿声啼不住」地赶路。",
      bodyEn: "Yellow Crane Tower stands in Wuhan; Yangzhou lies near the river's mouth far downstream. Chinese terrain falls from west to east, so sailing east is going down — fast with the current, while travelling back up was the slow, toiling direction.",
    },
    note: "帆已经看不见了还在望——送别送到最后，看的不是人，是江水。",
    noteEn: "The sail is long gone, and he is still watching. At the end of a farewell you are no longer watching the person — you are watching the river.",
  },
  {
    slug: "duzuojingtingshan",
    title: "独坐敬亭山",
    titleEn: "Sitting Alone on Jingting Mountain",
    author: "李白",
    authorEn: "Li Bai",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "孤独",
    themeEn: "Solitude",
    level: 1,
    lines: [
      { zh: "众鸟高飞尽，孤云独去闲。", en: "The birds have all flown high and gone; a single cloud drifts off, unhurried, alone." },
      { zh: "相看两不厌，只有敬亭山。", en: "We gaze at each other and neither tires — the Jingting Mountains and I." },
    ],
    keywords: [
      { w: "drift off", zh: "飘走" },
      { w: "tire of", zh: "看厌" },
      { w: "gaze at each other", zh: "相看" },
    ],
    note: "全诗只有一个坐着的人，却写出了两个都不肯走的朋友。",
    noteEn: "One man sits alone, yet the poem gives him a friend who refuses to leave.",
  },
  {
    slug: "qiupuge",
    title: "秋浦歌·其十五",
    titleEn: "Song of Qiupu (XV)",
    author: "李白",
    authorEn: "Li Bai",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "咏叹",
    themeEn: "Feelings",
    level: 2,
    lines: [
      { zh: "白发三千丈，缘愁似个长。", en: "My white hair is thirty thousand feet long — my sorrow is just as long." },
      { zh: "不知明镜里，何处得秋霜。", en: "I wonder where, in this bright mirror, those autumn frosts have come from." },
    ],
    keywords: [
      { w: "sorrow", zh: "愁绪" },
      { w: "autumn frost", zh: "秋霜（喻白发）" },
      { w: "thirty thousand feet", zh: "三千丈" },
      { w: "wonder", zh: "不知、纳闷" }
    ],
    note: "先把头发说到三千丈，再回头找原因——倒着说，惊讶才立得住。",
    noteEn: "First the thirty-thousand-foot hair, then the cause — said backwards, the astonishment stands.",
  },
  {
    slug: "songyuanger",
    title: "送元二使安西",
    titleEn: "Seeing Yuan the Second Off on a Mission to Anxi",
    author: "王维",
    authorEn: "Wang Wei",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "送别",
    themeEn: "Farewell",
    level: 1,
    lines: [
      { zh: "渭城朝雨浥轻尘，客舍青青柳色新。", en: "Morning rain in Weicheng lays the light dust; the guesthouse greens, the willows fresh." },
      { zh: "劝君更尽一杯酒，西出阳关无故人。", en: "I urge you to drink one more cup — west of Yang Pass, you will meet no old friends." },
    ],
    keywords: [
      { w: "urge", zh: "劝" },
      { w: "one more cup", zh: "再饮一杯" },
      { w: "old friends", zh: "故人" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "阳关以西是什么？",
      titleEn: "What lies west of Yang Pass?",
      body: "阳关在今甘肃敦煌西南，出了阳关就是塔克拉玛干沙漠边缘的西域——再无农田绿洲的密集人烟。所以「无故人」不是修辞，是准确的地理：丝路商旅要走几十天才能见到下一座城。",
      bodyEn: "Yang Pass sits near Dunhuang in Gansu; beyond it lay the Western Regions at the edge of the Taklamakan — no dense farmland, no crowds. 'No old friends' is not rhetoric but geography: the next town on the Silk Road was weeks away.",
    },
    note: "「更尽」二字最重——不是第一杯，也不是最后一杯，是再来一杯。",
    noteEn: "The weight is in 'one more cup': not the first, not the last — just one more, and one more after that.",
  },
  {
    slug: "jueju-chiri",
    title: "绝句·迟日江山丽",
    titleEn: "Quatrain: The Days Grow Long",
    author: "杜甫",
    authorEn: "Du Fu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "写景",
    themeEn: "Landscape",
    level: 1,
    lines: [
      { zh: "迟日江山丽，春风花草香。", en: "The days grow long, the rivers and hills grow fair; spring wind carries the scent of grass and flowers." },
      { zh: "泥融飞燕子，沙暖睡鸳鸯。", en: "The thawed mud keeps the swallows busy; the warmed sand, the sleeping mandarin ducks." },
    ],
    keywords: [
      { w: "thaw", zh: "解冻" },
      { w: "mandarin duck", zh: "鸳鸯" },
      { w: "scent", zh: "香气" },
    ],
    note: "泥融与沙暖都是春天的温度——燕子在动，鸳鸯在睡，一动一静。",
    noteEn: "Thawed mud and warmed sand are spring's own temperatures: swallows in motion, ducks asleep — movement against stillness.",
  },
  {
    slug: "chuzhouxijian",
    title: "滁州西涧",
    titleEn: "The West Stream at Chuzhou",
    author: "韦应物",
    authorEn: "Wei Yingwu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "写景",
    themeEn: "Landscape",
    level: 1,
    lines: [
      { zh: "独怜幽草涧边生，上有黄鹂深树鸣。", en: "I love best the quiet grass growing by the stream, and above it orioles singing deep in the trees." },
      { zh: "春潮带雨晚来急，野渡无人舟自横。", en: "Spring tides with evening rain rise fast; at the empty ferry a boat lies across the current, no one there." },
    ],
    keywords: [
      { w: "oriole", zh: "黄鹂" },
      { w: "ferry", zh: "渡口" },
      { w: "lie across", zh: "横陈" },
    ],
    note: "「舟自横」的「自」字——没有人，船自己横着，自在又寂寥。",
    noteEn: "The key word is 'of itself': no one there, the boat lies sideways on its own — at ease and lonely at once.",
  },
  {
    slug: "hanshi",
    title: "寒食",
    titleEn: "Cold Food Day",
    author: "韩翃",
    authorEn: "Han Hong",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "风俗",
    themeEn: "Customs",
    level: 2,
    lines: [
      { zh: "春城无处不飞花，寒食东风御柳斜。", en: "In the spring city flowers fly everywhere; on Cold Food Day the east wind slants the palace willows." },
      { zh: "日暮汉宫传蜡烛，轻烟散入五侯家。", en: "At dusk the Han palace passes candles along; light smoke drifts into the houses of the five marquises." },
    ],
    keywords: [
      { w: "drift into", zh: "飘进" },
      { w: "pass along", zh: "依次传递" },
      { w: "slants", zh: "吹斜" },
      { w: "marquises", zh: "五侯" }
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "寒食为什么要禁火？",
      titleEn: "Why no fire on Cold Food Day?",
      body: "相传为纪念介子推——春秋时他随晋公子重耳流亡，曾割股充饥；重耳复国后封赏遗漏了他，他隐入绵山，晋文公放火逼他出山，他抱树而死。为纪念他，这一日禁火冷食，次日用宫中赐的新火。「传蜡烛」传的就是这簇新火，能被赐火是极大的恩宠。",
      bodyEn: "The custom honours Jie Zitui, who once cut flesh from his thigh to feed the exiled Prince Chong'er. Overlooked when the prince became Duke Wen of Jin, Jie hid in Mian Mountain; the duke set fires to force him out, and he died in the flames. Fires were banned that day, and new fire was bestowed from the palace — a candle passed along the court was a signal mark of favour.",
    },
    note: "前两句是满城的花，后两句只写「轻烟」——讽刺藏在平静里。",
    noteEn: "Two lines of city-wide blossoms, then only drifting smoke — the satire hides inside the calm.",
  },
  {
    slug: "qiusi-zhangji",
    title: "秋思",
    titleEn: "Autumn Thoughts",
    author: "张籍",
    authorEn: "Zhang Ji",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "思乡",
    themeEn: "Homesickness",
    level: 2,
    lines: [
      { zh: "洛阳城里见秋风，欲作家书意万重。", en: "In Luoyang city I feel the autumn wind rise; I try to write home, but the meanings are ten thousandfold." },
      { zh: "复恐匆匆说不尽，行人临发又开封。", en: "Fearing the hasty letter has not said it all, I open the sealed envelope again as the messenger leaves." },
    ],
    keywords: [
      { w: "messenger", zh: "信使" },
      { w: "seal / unseal", zh: "封上 / 拆开" },
      { w: "ten thousandfold", zh: "万重" },
    ],
    note: "全诗只写了一个动作：拆开已经封好的信。思念全在这个动作里。",
    noteEn: "The whole poem is one gesture: opening a letter already sealed. All the longing is in that gesture.",
  },
  {
    slug: "shiwuye",
    title: "十五夜望月",
    titleEn: "Gazing at the Moon on the Fifteenth Night",
    author: "王建",
    authorEn: "Wang Jian",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "思乡",
    themeEn: "Homesickness",
    level: 1,
    lines: [
      { zh: "中庭地白树栖鸦，冷露无声湿桂花。", en: "The courtyard floor is white with moonlight, crows rest in the trees; cold dew, without a sound, wets the osmanthus." },
      { zh: "今夜月明人尽望，不知秋思落谁家。", en: "Tonight the bright moon draws every gaze — but into whose home will this autumn longing fall?" },
    ],
    keywords: [
      { w: "cold dew", zh: "冷露" },
      { w: "osmanthus", zh: "桂花" },
      { w: "longing", zh: "思念" },
    ],
    note: "不写自己想家，只问月光落进谁家——所有的家都答了。",
    noteEn: "He never says he misses home; he asks whose home the longing falls into — and every home answers.",
  },
  {
    slug: "mashi",
    title: "马诗·其五",
    titleEn: "Horse Poems (V)",
    author: "李贺",
    authorEn: "Li He",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "咏物",
    themeEn: "Ambition",
    level: 2,
    lines: [
      { zh: "大漠沙如雪，燕山月似钩。", en: "In the great desert the sand is like snow; over Yan Mountain the moon is like a hook." },
      { zh: "何当金络脑，快走踏清秋。", en: "When will this horse wear a golden bridle and gallop fast through the clear autumn?" },
    ],
    keywords: [
      { w: "bridle", zh: "马笼头" },
      { w: "gallop", zh: "奔驰" },
      { w: "hook", zh: "钩（弯月）" },
    ],
    note: "前两句全是冷色，末句一个「快」字把凉意跑成了热。",
    noteEn: "Two lines of cold colours, then one word — fast — gallops the chill into heat.",
  },
  {
    slug: "xunyinzhe",
    title: "寻隐者不遇",
    titleEn: "Visiting a Hermit and Not Finding Him",
    author: "贾岛",
    authorEn: "Jia Dao",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "访友",
    themeEn: "A Visit",
    level: 1,
    lines: [
      { zh: "松下问童子，言师采药去。", en: "Beneath the pines I ask the boy; he says his master has gone to gather herbs." },
      { zh: "只在此山中，云深不知处。", en: "He is somewhere in this very mountain — but the clouds are deep, and no one knows where." },
    ],
    keywords: [
      { w: "master", zh: "师父（隐者）" },
      { w: "gather herbs", zh: "采药" },
      { w: "clouds are deep", zh: "云深" },
    ],
    note: "二十个字里有一座山、一朵云、一个找不到的人——问与答都被山吞掉了一半。",
    noteEn: "Twenty characters hold a mountain, a cloud, and a man who cannot be found — the mountain has swallowed half the dialogue.",
  },
  {
    slug: "fengxue",
    title: "逢雪宿芙蓉山主人",
    titleEn: "Lodging at Furong Mountain on a Snowy Night",
    author: "刘长卿",
    authorEn: "Liu Changqing",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "行旅",
    themeEn: "Travel",
    level: 2,
    lines: [
      { zh: "日暮苍山远，天寒白屋贫。", en: "At dusk the grey hills recede; in the cold, the thatched hut looks poorer still." },
      { zh: "柴门闻犬吠，风雪夜归人。", en: "At the wicker gate a dog barks — someone is coming home through wind and snow at night." },
    ],
    keywords: [
      { w: "thatched hut", zh: "茅屋" },
      { w: "bark (v.)", zh: "犬吠" },
      { w: "wicker gate", zh: "柴门" },
    ],
    note: "后两句十一字是一部小电影：先听见犬吠，再看见风雪，最后人才出现。",
    noteEn: "The last eleven characters are a tiny film: first the barking, then the snow, and only at the end, the man.",
  },
  {
    slug: "chan",
    title: "蝉",
    titleEn: "The Cicada",
    author: "虞世南",
    authorEn: "Yu Shinan",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "咏物",
    themeEn: "Character",
    level: 1,
    lines: [
      { zh: "垂緌饮清露，流响出疏桐。", en: "It sips clear dew, its long voice pouring out of the sparse wutong trees." },
      { zh: "居高声自远，非是藉秋风。", en: "Perched high, its voice carries far of itself — it does not ride the autumn wind." },
    ],
    keywords: [
      { w: "dew", zh: "露水" },
      { w: "carry far", zh: "传得远" },
      { w: "of itself", zh: "自然而然" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "蝉真的「饮清露」吗？",
      titleEn: "Does the cicada really sip dew?",
      body: "蝉用口针刺进树枝吸食树汁，不是喝露水；发声也不靠嘴，而是腹部两侧的鼓膜肌快速振动，像一面小鼓。所以「居高声自远」在生物学上完全成立：位置越高、树越疏，声音传播的障碍越少——它确实不需要秋风。",
      bodyEn: "Cicadas pierce twigs with a stylet and drink sap, not dew; and they do not sing with the mouth but with tymbal membranes on the abdomen, clicking like tiny drums. 'Perched high, its voice carries far' is thus sound biology: the higher and more open the perch, the fewer the obstacles — no autumn wind needed.",
    },
    note: "「自远」对「藉秋风」——声望靠自己还是靠风口，唐人早想明白了。",
    noteEn: "'Of itself' against 'riding the wind': whether fame comes from within or from the trend — the Tang thought it through.",
  },
  {
    slug: "shihuiyin",
    title: "石灰吟",
    titleEn: "Song of the Lime",
    author: "于谦",
    authorEn: "Yu Qian",
    dynasty: "明",
    dynastyEn: "Ming",
    stage: "小学",
    kind: "诗",
    theme: "咏物",
    themeEn: "Integrity",
    level: 1,
    lines: [
      { zh: "千锤万凿出深山，烈火焚烧若等闲。", en: "Ten thousand blows cut it from the deep hills; fierce fire burns it as if nothing were happening." },
      { zh: "粉骨碎身浑不怕，要留清白在人间。", en: "Crushed to powder, broken to pieces, it does not care — it means to leave its whiteness in the world." },
    ],
    keywords: [
      { w: "fierce fire", zh: "烈火" },
      { w: "as if nothing", zh: "若等闲" },
      { w: "whiteness", zh: "清白" },
    ],
    cross: {
      field: "化学",
      fieldEn: "Chemistry",
      title: "这首诗是石灰的生产流程",
      titleEn: "The poem is literally the lime production process",
      body: "石灰石（碳酸钙）先「千锤万凿」开采，再「烈火焚烧」煅烧成生石灰（氧化钙），加水变成熟石灰，粉刷上墙后吸收二氧化碳又变回碳酸钙——墙就「留了清白在人间」。每一步都是化学方程式，于谦把一张工艺流程图写成了一首明志诗。",
      bodyEn: "Limestone (calcium carbonate) is quarried by 'ten thousand blows', then calcined in 'fierce fire' into quicklime (calcium oxide), slaked with water for plastering; on the wall it reabsorbs carbon dioxide and turns back to carbonate — leaving its 'whiteness in the world'. Every line is a chemical step; Yu Qian turned a process diagram into a vow.",
    },
    note: "把石灰的生产流程写成一个人的一生——「清白」既是白色，也是品格。",
    noteEn: "The lime-making process becomes one person's life: 'whiteness' is both a colour and a character.",
  },
  {
    slug: "chunri",
    title: "春日",
    titleEn: "A Spring Day",
    author: "朱熹",
    authorEn: "Zhu Xi",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "诗",
    theme: "哲理",
    themeEn: "Philosophy",
    level: 1,
    lines: [
      { zh: "胜日寻芳泗水滨，无边光景一时新。", en: "On a fine day I seek fragrance by the Si River's banks; the boundless scene turns new all at once." },
      { zh: "等闲识得东风面，万紫千红总是春。", en: "Anyone can know the face of the east wind: ten thousand purples, a thousand reds — all of it is spring." },
    ],
    keywords: [
      { w: "boundless", zh: "无边" },
      { w: "east wind", zh: "春风" },
      { w: "all of it is spring", zh: "总是春" },
    ],
    note: "泗水当时已在金人手里，朱熹根本去不了——他寻的不是花，是孔门之道；「东风面」是道理的脸。",
    noteEn: "The Si River lay in Jin-held territory; Zhu Xi could never have gone. He was seeking not flowers but the way of Confucius — 'the face of the east wind' is the face of the doctrine.",
  },
  {
    slug: "guanshuyougan",
    title: "观书有感·其一",
    titleEn: "Feelings from Reading (I)",
    author: "朱熹",
    authorEn: "Zhu Xi",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "诗",
    theme: "哲理",
    themeEn: "Learning",
    level: 2,
    lines: [
      { zh: "半亩方塘一鉴开，天光云影共徘徊。", en: "A half-acre square pond opens like a mirror; sky-light and cloud-shadows linger together in it." },
      { zh: "问渠那得清如许？为有源头活水来。", en: "Ask how the pond stays so clear: because fresh water keeps coming from its source." },
    ],
    keywords: [
      { w: "mirror", zh: "镜子" },
      { w: "linger", zh: "徘徊" },
      { w: "source", zh: "源头" },
    ],
    note: "整首诗是一个比喻——读书就是给心找源头活水。「渠」是「它」，不是水渠。",
    noteEn: "The poem is one long metaphor: reading keeps the mind fed with fresh water. Note that 「渠」 here means 'it', not 'canal'.",
  },
  {
    slug: "dongyedushu",
    title: "冬夜读书示子聿",
    titleEn: "Reading on a Winter Night, Shown to My Son Yu",
    author: "陆游",
    authorEn: "Lu You",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "诗",
    theme: "哲理",
    themeEn: "Learning",
    level: 2,
    lines: [
      { zh: "古人学问无遗力，少壮工夫老始成。", en: "The ancients spared no effort in learning; work begun young ripens only in age." },
      { zh: "纸上得来终觉浅，绝知此事要躬行。", en: "What you get from paper always feels shallow; to truly know a thing, you must do it yourself." },
    ],
    keywords: [
      { w: "spare no effort", zh: "不遗余力" },
      { w: "shallow (adj.)", zh: "浅的" },
      { w: "do it yourself", zh: "躬行（亲自去做）" },
    ],
    note: "后两句是所有实验课、实习岗的开场白。",
    noteEn: "The last couplet is the opening speech of every lab class and internship.",
  },
  {
    slug: "tilinandi",
    title: "题临安邸",
    titleEn: "Written on a Wall in Lin'an",
    author: "林升",
    authorEn: "Lin Sheng",
    dynasty: "南宋",
    dynastyEn: "Southern Song",
    stage: "小学",
    kind: "诗",
    theme: "讽喻",
    themeEn: "Satire",
    level: 2,
    lines: [
      { zh: "山外青山楼外楼，西湖歌舞几时休？", en: "Hills beyond hills, towers beyond towers; when will the songs and dances by West Lake ever stop?" },
      { zh: "暖风熏得游人醉，直把杭州作汴州。", en: "Warm winds have made the revellers drunk — they take Hangzhou for Bianzhou." },
    ],
    keywords: [
      { w: "reveller", zh: "醉游之人" },
      { w: "take A for B", zh: "把A当成B" },
      { w: "hills beyond hills", zh: "山外青山" },
      { w: "ever stop", zh: "何时休" }
    ],
    note: "杭州越美，汴州越痛——两句诗里叠着两个都城，一座是眼前，一座是伤口。",
    noteEn: "The lovelier Hangzhou, the deeper the wound of Bianzhou: two capitals stacked in one couplet — one before the eyes, one in the chest.",
  },
  {
    slug: "rumengling",
    title: "如梦令·常记溪亭日暮",
    titleEn: "Like a Dream: I Often Remember",
    author: "李清照",
    authorEn: "Li Qingzhao",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "词",
    theme: "田园",
    themeEn: "Pastoral",
    level: 2,
    lines: [
      { zh: "常记溪亭日暮，沉醉不知归路。", en: "Often I remember the pavilion by the stream at dusk, drunk on wine, no longer knowing the way home." },
      { zh: "兴尽晚回舟，误入藕花深处。", en: "Pleasure spent, I rowed back late, and strayed deep into the lotus flowers." },
      { zh: "争渡，争渡，惊起一滩鸥鹭。", en: "Rowing, rowing hard — and up startle a whole shore of gulls and herons." },
    ],
    keywords: [
      { w: "stray into", zh: "误入" },
      { w: "lotus", zh: "藕花（荷花）" },
      { w: "startle", zh: "惊起" },
    ],
    note: "结尾六个字全是声音：桨声、水声、翅膀炸开的声音。",
    noteEn: "The last six characters are all sound: oars, water, and the burst of wings.",
  },
  {
    slug: "changxiangsi",
    title: "长相思·山一程",
    titleEn: "Everlasting Longing",
    author: "纳兰性德",
    authorEn: "Nalan Xingde",
    dynasty: "清",
    dynastyEn: "Qing",
    stage: "小学",
    kind: "词",
    theme: "思乡",
    themeEn: "Homesickness",
    level: 2,
    lines: [
      { zh: "山一程，水一程，身向榆关那畔行，夜深千帐灯。", en: "A stage of hills, a stage of rivers; my body travels toward the far side of Yu Pass. Deep in the night, a thousand tents of lamps." },
      { zh: "风一更，雪一更，聒碎乡心梦不成，故园无此声。", en: "One watch of wind, one watch of snow; they shatter homesick dreams before they form. In my old garden there was no such sound." },
    ],
    keywords: [
      { w: "tent", zh: "帐篷" },
      { w: "shatter", zh: "震碎" },
      { w: "the old garden", zh: "故园" },
    ],
    note: "千帐灯是行军的壮阔，「故园无此声」是壮阔底下一句耳语。",
    noteEn: "A thousand tents of lamps is the grandeur of a march; 'no such sound in my old garden' is the whisper beneath it.",
  },
  {
    slug: "jingwei",
    title: "精卫填海",
    titleEn: "Jingwei Fills the Sea",
    author: "佚名",
    authorEn: "Anonymous",
    dynasty: "先秦",
    dynastyEn: "Pre-Qin",
    stage: "小学",
    kind: "文言文",
    theme: "神话",
    themeEn: "Myth",
    level: 1,
    lines: [
      { zh: "炎帝之少女，名曰女娃。", en: "Yandi's youngest daughter was named Nüwa." },
      { zh: "女娃游于东海，溺而不返，故为精卫，常衔西山之木石，以堙于东海。", en: "Nüwa swam in the Eastern Sea, drowned, and did not return — so she became the jingwei bird, forever carrying twigs and stones from the western hills to fill the Eastern Sea." },
    ],
    fullText: "又北二百里，曰发鸠之山，其上多柘木，有鸟焉，其状如乌，文首，白喙，赤足，名曰：「精卫」，其鸣自詨。是炎帝之少女，名曰女娃。女娃游于东海，溺而不返，故为精卫，常衔西山之木石，以堙于东海。漳水出焉，东流注于河。",
    keywords: [
      { w: "drown", zh: "溺水" },
      { w: "twigs and stones", zh: "木石" },
      { w: "fill (v.)", zh: "填" },
    ],
    note: "一只小鸟对大海的报复，用「常衔」两个字坚持了三千年。",
    noteEn: "A little bird's revenge on the sea, carried on for three thousand years in two words: 'forever carrying'.",
  },
  {
    slug: "kuafu",
    title: "夸父逐日",
    titleEn: "Kuafu Chases the Sun",
    author: "佚名",
    authorEn: "Anonymous",
    dynasty: "先秦",
    dynastyEn: "Pre-Qin",
    stage: "小学",
    kind: "文言文",
    theme: "神话",
    themeEn: "Myth",
    level: 1,
    lines: [
      { zh: "夸父与日逐走，入日；渴，欲得饮，饮于河、渭；河、渭不足，北饮大泽。", en: "Kuafu raced the sun. As he caught up with its light he grew thirsty and drank the Yellow River and the Wei dry — not enough, so he turned north toward the Great Marsh." },
      { zh: "未至，道渴而死。弃其杖，化为邓林。", en: "He never got there: he died of thirst on the road. His staff fell from his hand and became a peach forest." },
    ],
    fullText: "夸父与日逐走，入日；渴，欲得饮，饮于河、渭；河、渭不足，北饮大泽。未至，道渴而死。弃其杖，化为邓林。",
    keywords: [
      { w: "race with", zh: "与……赛跑" },
      { w: "thirst", zh: "口渴" },
      { w: "staff", zh: "手杖" },
      { w: "peach forest", zh: "邓林（桃林）" },
    ],
    note: "人没追上太阳，手杖替他追上了——化作桃林，给后来赶路的人解渴。",
    noteEn: "The man never caught the sun, but his staff did: it became a peach forest to quench the thirst of those still running.",
  },
];
