import type { Poem } from "./types";

/**
 * 小学阶段 · 第 4 批（文言短文）
 * 文言文处理原则：lines 为关键句的英译，fullText 为全文（中文），
 * 便于对照学习；难度按小学段设为 1。
 */
export const PRIMARY_4: Poem[] = [
  {
    slug: "simaguang",
    title: "司马光（破瓮救友）",
    titleEn: "Sima Guang Saves a Friend",
    author: "《宋史》",
    authorEn: "History of Song",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "文言文",
    theme: "人物",
    themeEn: "People",
    level: 1,
    lines: [
      { zh: "群儿戏于庭，一儿登瓮，足跌没水中。", en: "A group of children were playing in the courtyard; one boy climbed onto a water jar, lost his footing, and fell in." },
      { zh: "众皆弃去，光持石击瓮破之，水迸，儿得活。", en: "The others all ran off, but Guang seized a stone and smashed the jar; the water gushed out, and the boy survived." },
    ],
    fullText: "群儿戏于庭，一儿登瓮，足跌没水中。众皆弃去，光持石击瓮破之，水迸，儿得活。",
    keywords: [
      { w: "courtyard (n.)", zh: "庭院" },
      { w: "lose one's footing", zh: "失足" },
      { w: "run off", zh: "跑开、弃去" },
      { w: "gush out", zh: "涌出" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "为什么砸缸比拉人更快？",
      titleEn: "Why smash the jar instead of pulling the boy?",
      body: "瓮是口小腹大的陶器，孩子掉进去后卡在窄口之下，从上面拉要克服重力还要挤过瓶口，很难发力；而砸破瓮身，水立刻靠重力流出，水位下降，孩子自然脱困——这是把「救人」换成「放水」的思路转换，工程上叫改变约束条件。这个故事的关键不是力气，是判断：目标不是把人拉出来，而是让水离开。",
      bodyEn: "The jar is narrow-necked and wide-bellied; a child inside is wedged below the mouth, so pulling means fighting gravity and squeezing through the neck. Break the body of the jar instead and gravity empties it at once — the level drops and the child is free. It is a change of constraints: the goal shifts from lifting the boy to removing the water. The point of the story is judgement, not strength.",
    },
    note: "全文仅 30 字，却有人物、动作、结果与反衬（众皆弃去 vs 光持石击瓮）。英文注意过去式的连贯叙事。",
    noteEn: "Thirty characters, yet it has characters, action, result and contrast (the others flee vs Guang smashes). Notice the past-tense chain.",
  },
  {
    slug: "shouzhudaitu",
    title: "守株待兔",
    titleEn: "Waiting by the Stump for a Hare",
    author: "《韩非子》",
    authorEn: "Han Feizi",
    dynasty: "先秦",
    dynastyEn: "Pre-Qin",
    stage: "小学",
    kind: "文言文",
    theme: "寓言",
    themeEn: "Fable",
    level: 1,
    lines: [
      { zh: "兔走触株，折颈而死。", en: "A hare ran past, struck the stump, broke its neck and died." },
      { zh: "因释其耒而守株，冀复得兔。", en: "So he cast aside his plough and kept watch by the stump, hoping to get another hare." },
      { zh: "兔不可复得，而身为宋国笑。", en: "No second hare came, and he himself became the laughing-stock of the state of Song." },
    ],
    fullText: "宋人有耕者。田中有株，兔走触株，折颈而死。因释其耒而守株，冀复得兔。兔不可复得，而身为宋国笑。",
    keywords: [
      { w: "stump (n.)", zh: "树桩" },
      { w: "cast aside", zh: "放下、丢弃" },
      { w: "keep watch", zh: "守候" },
      { w: "laughing-stock (n.)", zh: "笑柄" },
    ],
    cross: {
      field: "数学",
      fieldEn: "Mathematics",
      title: "守株待兔错在哪？",
      titleEn: "What is the error in waiting by the stump?",
      body: "这是概率论里最经典的误解：把一个极小概率事件当成了可重复规律。兔子撞桩的概率可能万分之一，且各次事件相互独立——已经发生一次，不会提高第二次发生的概率（这就是「赌徒谬误」的反面形式）。更糟的是成本结构：守株放弃了稳定的耕作收益（期望收益为正且持续），去换取期望值极低的撞兔收益。韩非用这则寓言讽刺不知变通的治国者。",
      bodyEn: "A textbook probabilistic error: treating an extremely rare event as a repeatable rule. The chance of a hare hitting the stump might be one in ten thousand, and events are independent — one occurrence does not raise the odds of the next (the inverse of the gambler's fallacy). Worse is the cost structure: he trades a steady, positive farming return for a lottery with near-zero expectation. Han Fei aimed the fable at rulers who would not adapt.",
    },
    note: "「释其耒而守株」里两个动作对比最锋利：放下工具 vs 空等运气。英文用 cast aside 保留「放弃正业」的意味。",
    noteEn: "The sharpest contrast: casting aside the plough versus waiting on luck.",
  },
  {
    slug: "nangyingyedu",
    title: "囊萤夜读",
    titleEn: "Reading by Fireflies in a Bag",
    author: "《晋书》",
    authorEn: "Book of Jin",
    dynasty: "唐（记晋事）",
    dynastyEn: "Tang (Jin history)",
    stage: "小学",
    kind: "文言文",
    theme: "勤学",
    themeEn: "Study",
    level: 1,
    lines: [
      { zh: "家贫不常得油，夏月则练囊盛数十萤火以照书，以夜继日焉。", en: "His family was too poor to afford lamp oil often; in summer he would put dozens of fireflies in a white silk bag to light his book, and so carried the night on into the day." },
    ],
    fullText: "胤恭勤不倦，博学多通。家贫不常得油，夏月则练囊盛数十萤火以照书，以夜继日焉。",
    keywords: [
      { w: "too poor to", zh: "穷得无法" },
      { w: "lamp oil", zh: "灯油" },
      { w: "dozens of", zh: "数十" },
      { w: "carry on into", zh: "以…继…" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "萤火虫的光真的能看书吗？",
      titleEn: "Could you really read by firefly light?",
      body: "理论上很难。萤火虫的发光是荧光素酶催化荧光素氧化的生物发光，效率极高（几乎不产热，故称冷光），但单只亮度只有约 0.0006 流明；要凑到能阅读的光照，科学家估算需数千只以上。故事里的「数十萤火」是象征性数字，重点不在可行，而在勤学之心。顺带一提：萤火虫成虫寿命一般只有一两周，且发光主要用于求偶。",
      bodyEn: "In practice, barely. Firefly light is bioluminescence — luciferase oxidising luciferin — nearly heat-free, hence cold light, but one insect emits only about 0.0006 lumens; reading would need thousands. The 「dozens」 in the story is symbolic: the point is diligence, not optics. Incidentally, adult fireflies live only a week or two, and their light is mostly a mating signal.",
    },
    note: "「以夜继日」是把夜晚接在白天后面继续用——英文 carry the night on into the day 保留了「接续」的动词。",
    noteEn: "「以夜继日」 literally joins night to day — kept as carry the night on into the day.",
  },
  {
    slug: "tiechuchengzhen",
    title: "铁杵成针",
    titleEn: "Grinding an Iron Bar into a Needle",
    author: "《方舆胜览》",
    authorEn: "Fangyu Shenglan",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "文言文",
    theme: "勤学",
    themeEn: "Study",
    level: 1,
    lines: [
      { zh: "逢老媪方磨铁杵，问之，曰：「欲作针。」", en: "He met an old woman grinding an iron bar. When asked, she said: 「I want to make a needle.」" },
      { zh: "太白感其意，还卒业。", en: "Li Bai was moved by her resolve, and went back to finish his studies." },
    ],
    fullText: "磨针溪，在象耳山下。世传李太白读书山中，未成，弃去。过是溪，逢老媪方磨铁杵，问之，曰：「欲作针。」太白感其意，还卒业。",
    keywords: [
      { w: "grind (v.)", zh: "磨" },
      { w: "iron bar", zh: "铁杵" },
      { w: "resolve (n.)", zh: "意志、决心" },
      { w: "finish his studies", zh: "完成学业" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "铁棒真能磨成针吗？",
      titleEn: "Can an iron bar really become a needle?",
      body: "能，原理就是磨削加工：用硬度更高的磨石反复摩擦，每次削去极薄一层金属，累积起来就能把粗棒变细成针。古代制针正是这样——先把熟铁拉拔成细丝，再在磨石上磨出针尖、钻出针眼。「只要功夫深」说的不是奇迹，而是把大工程量拆成无数次小加工：这正是现代制造业的核心思路（减材制造）。",
      bodyEn: "Yes — it is simply grinding. A harder abrasive stone removes a very thin layer of metal with each pass; accumulate enough passes and a thick bar becomes a needle. Ancient needles were made exactly so: wrought iron drawn into wire, then ground to a point and pierced for the eye. The saying is not a miracle but a lesson in decomposition: many tiny subtractive steps, which is what manufacturing still is.",
    },
    note: "「感其意」的「意」是关键——李白感动的不是老太太的力气，是她的决心。英文用 resolve 而非 effort。",
    noteEn: "What moves Li Bai is not the labour but the resolve — hence resolve, not effort.",
  },
  {
    slug: "yangshizhizi",
    title: "杨氏之子",
    titleEn: "The Son of the Yang Family",
    author: "《世说新语》",
    authorEn: "A New Account of the Tales of the World",
    dynasty: "南朝宋",
    dynastyEn: "Liu Song",
    stage: "小学",
    kind: "文言文",
    theme: "人物",
    themeEn: "People",
    level: 1,
    lines: [
      { zh: "孔君平诣其父，父不在，乃呼儿出。", en: "Kong Junping called on his father; the father was out, so he asked the boy to come out." },
      { zh: "未闻孔雀是夫子家禽。", en: "I have never heard that the peacock is your family's bird." },
    ],
    fullText: "梁国杨氏子九岁，甚聪惠。孔君平诣其父，父不在，乃呼儿出。为设果，果有杨梅。孔指以示儿曰：「此是君家果。」儿应声答曰：「未闻孔雀是夫子家禽。」",
    keywords: [
      { w: "call on sb.", zh: "拜访某人" },
      { w: "peacock", zh: "孔雀" },
      { w: "was out", zh: "（父亲）不在家" },
      { w: "I have never heard that", zh: "未闻" },
    ],
    cross: {
      field: "语言",
      fieldEn: "Linguistics",
      title: "妙答的机关在哪里？",
      titleEn: "How does the witty reply work?",
      body: "这是一次「以其人之道还治其人」：孔君平用「杨」姓与「杨梅」同字开玩笑，说杨梅是杨家的果子；孩子立刻用同样的逻辑反问——若杨梅属杨家，那孔雀就该属孔家。逻辑学上，这是把对方的规则原样套回对方身上，揭示规则的不成立（reductio，归谬）。魏晋清谈极重机锋对答，《世说新语》专收这类言语智慧。",
      bodyEn: "The boy returns the joke on its maker: Kong puns on the surname Yang shared with the bayberry (杨梅), calling it the family fruit. The child applies the same rule to Kong's own surname and the peacock (孔雀). Logically it is a reductio — taking an opponent's rule and applying it back to show it fails. Such repartee was prized in Wei-Jin conversation, and this collection exists to preserve it.",
    },
    note: "九岁的应答，胜在「应声」二字——没有犹豫。英文用 respond at once 保留速度感。",
    noteEn: "The genius is in 「应声」 — no hesitation. Hence respond at once.",
  },
  {
    slug: "wangrong",
    title: "王戎不取道旁李",
    titleEn: "Wang Rong Does Not Take the Plums by the Road",
    author: "《世说新语》",
    authorEn: "A New Account of the Tales of the World",
    dynasty: "南朝宋",
    dynastyEn: "Liu Song",
    stage: "小学",
    kind: "文言文",
    theme: "人物",
    themeEn: "People",
    level: 1,
    lines: [
      { zh: "看道边李树多子折枝，诸儿竞走取之，唯戎不动。", en: "Seeing a plum tree by the road bent with fruit, the boys all ran to pick it; only Rong did not move." },
      { zh: "树在道边而多子，此必苦李。", en: "The tree stands by the road yet is full of fruit — these plums must be bitter." },
    ],
    fullText: "王戎七岁，尝与诸小儿游。看道边李树多子折枝，诸儿竞走取之，唯戎不动。人问之，答曰：「树在道边而多子，此必苦李。」取之，信然。",
    keywords: [
      { w: "bent with fruit", zh: "果实压弯枝头" },
      { w: "ran to pick", zh: "抢着去摘（竞相）" },
      { w: "bitter (adj.)", zh: "苦的" },
      { w: "stands by the road", zh: "立在道旁" },
    ],
    cross: {
      field: "逻辑",
      fieldEn: "Logic",
      title: "七岁孩子的推理形式",
      titleEn: "The seven-year-old's form of reasoning",
      body: "这是标准的溯因推理（abduction）：观察到反常现象（路边的树居然还挂满果子），提出最能解释它的假设（果子难吃，所以没人摘），再用结果验证。它与演绎不同——演绎从一般推个别，溯因是从结果反推最可能的原因，也是科学发现中最常用的推理形式。王戎的可贵在于：别人看到「有果子」，他看到「为什么还有果子」。",
      bodyEn: "This is textbook abduction: observe something anomalous (a roadside tree still heavy with fruit), propose the hypothesis that best explains it (the fruit is inedible, so nobody picked it), then check. Unlike deduction, which moves from general to particular, abduction infers the likeliest cause from a result — the form most scientific discoveries take. The boy's edge is that others saw fruit while he asked why the fruit remained.",
    },
    note: "「取之，信然」四个字是验证——英文用 and so it proved 收住，把推理闭环。",
    noteEn: "「They picked one, and so it proved」 closes the loop: hypothesis confirmed.",
  },
  {
    slug: "boyagugin",
    title: "伯牙鼓琴",
    titleEn: "Boyu Plays the Lute",
    author: "《吕氏春秋》",
    authorEn: "Lüshi Chunqiu",
    dynasty: "先秦",
    dynastyEn: "Pre-Qin",
    stage: "小学",
    kind: "文言文",
    theme: "知音",
    themeEn: "Kindred Spirits",
    level: 1,
    lines: [
      { zh: "方鼓琴而志在太山，锺子期曰：「善哉乎鼓琴，巍巍乎若太山。」", en: "When Boyu played, thinking of Mount Tai, Zhong Ziqi said: 「How well you play — lofty, like Mount Tai!」" },
      { zh: "锺子期死，伯牙破琴绝弦，终身不复鼓琴。", en: "When Zhong Ziqi died, Boyu smashed his lute and cut its strings, and never played again for the rest of his life." },
    ],
    fullText: "伯牙鼓琴，锺子期听之。方鼓琴而志在太山，锺子期曰：「善哉乎鼓琴，巍巍乎若太山。」少选之间而志在流水，锺子期又曰：「善哉乎鼓琴，汤汤乎若流水。」锺子期死，伯牙破琴绝弦，终身不复鼓琴，以为世无足复为鼓琴者。",
    keywords: [
      { w: "lofty (adj.)", zh: "巍峨的" },
      { w: "smash (v.)", zh: "摔破" },
      { w: "cut the strings", zh: "断弦" },
      { w: "never again", zh: "不再" },
    ],
    cross: {
      field: "音乐",
      fieldEn: "Music",
      title: "「知音」为什么从音乐里来？",
      titleEn: "Why does 「understanding sound」 mean a soulmate?",
      body: "古琴音乐没有歌词，演奏者的「志」（心中所想）只能靠音色、节奏、泛音与指法传达，信息高度依赖听者的解码能力。所以能听出「志在高山」的听者，等于读懂了演奏者的内心——这就是「知音」的本义。声学上，古琴有效弦长长、泛音丰富，且吟猱绰注等左手技法能做出连续的音高变化，确实擅长模拟水声与山势的意象。",
      bodyEn: "The qin has no words: the player's intent must travel through timbre, rhythm, harmonics and fingering alone, so decoding it depends entirely on the listener. Hearing 「Mount Tai」 in the music means reading the player's mind — the literal sense of 「knowing the sound」. Acoustically, the qin's long vibrating string length and rich harmonics, plus left-hand slides, produce continuous pitch inflections well suited to evoking water and mountains.",
    },
    note: "「以为世无足复为鼓琴者」——不是没人听，是没人值得听。英文用 never played again 保留了这份决绝。",
    noteEn: "Not that nobody would listen, but that nobody was worth playing for.",
  },
  {
    slug: "shudaishonghuaniu",
    title: "书戴嵩画牛",
    titleEn: "On Dai Song's Painting of an Ox",
    author: "苏轼",
    authorEn: "Su Shi",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "文言文",
    theme: "艺术",
    themeEn: "Art",
    level: 2,
    lines: [
      { zh: "牛斗，力在角，尾搐入两股间，今乃掉尾而斗，谬矣。", en: "When oxen fight, the strength is in the horns and the tail is tucked between the hind legs; here the tail swings as they fight — that is wrong." },
      { zh: "耕当问奴，织当问婢。", en: "Ask a farmhand about ploughing, ask a maid about weaving." },
    ],
    fullText: "蜀中有杜处士，好书画，所宝以百数。有戴嵩牛一轴，尤所爱，锦囊玉轴，常以自随。一日曝书画，有一牧童见之，拊掌大笑曰：「此画斗牛也。牛斗，力在角，尾搐入两股间，今乃掉尾而斗，谬矣。」处士笑而然之。古语有云：「耕当问奴，织当问婢。」不可改也。",
    keywords: [
      { w: "tuck (v.)", zh: "夹（尾）、缩入" },
      { w: "hind legs", zh: "后腿" },
      { w: "swing (v.)", zh: "摇摆（掉尾）" },
      { w: "wrong (adj.)", zh: "错误的（谬）" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "牛打架真的夹着尾巴吗？",
      titleEn: "Do fighting cattle really tuck their tails?",
      body: "基本正确。牛在全力顶撞时后躯发力、身体前倾，尾部肌肉紧张，尾巴会夹紧贴住臀部——这是四足动物在发力与紧张状态下的常见姿态（狗在攻击或极度紧张时同样夹尾）。牧童天天放牛，看的是真实行为；画家的错误是把牛画成了奔跑姿态的甩尾。苏轼借这件事说的道理是：专业判断要来自有实践经验的人，而不是权威。",
      bodyEn: "Largely right. When cattle push with all their weight, the hindquarters drive forward and the tail muscles tense, clamping the tail against the rump — the posture of effort in quadrupeds (a dog tucks its tail under stress or attack). A herdboy saw real behaviour daily; the painter copied a running animal's swinging tail. Su Shi's moral: expert judgement belongs to those with practice, not to authority.",
    },
    note: "结尾「耕当问奴，织当问婢」是全篇论点——英文用 Ask a farmhand about… 保留对仗。",
    noteEn: "The closing proverb states the thesis: ask the person who actually does the work.",
  },
  {
    slug: "xueyi",
    title: "学弈",
    titleEn: "Learning to Play Weiqi",
    author: "《孟子》",
    authorEn: "Mencius",
    dynasty: "先秦",
    dynastyEn: "Pre-Qin",
    stage: "小学",
    kind: "文言文",
    theme: "勤学",
    themeEn: "Study",
    level: 2,
    lines: [
      { zh: "其一人专心致志，惟弈秋之为听。", en: "One of them gave his whole mind to it, listening to nothing but Master Qiu." },
      { zh: "一人虽听之，一心以为有鸿鹄将至，思援弓缴而射之。", en: "The other listened, yet all the while thought a swan was about to pass, and wondered how he might take his bow and shoot it." },
      { zh: "为是其智弗若与？曰：非然也。", en: "Is it that his wits are inferior? No — it is not so." },
    ],
    fullText: "弈秋，通国之善弈者也。使弈秋诲二人弈，其一人专心致志，惟弈秋之为听；一人虽听之，一心以为有鸿鹄将至，思援弓缴而射之。虽与之俱学，弗若之矣。为是其智弗若与？曰：非然也。",
    keywords: [
      { w: "give one's mind to", zh: "专心致志" },
      { w: "all the while", zh: "与此同时、一直" },
      { w: "inferior (adj.)", zh: "不如的" },
      { w: "it is not so", zh: "不是这样" },
    ],
    cross: {
      field: "心理",
      fieldEn: "Psychology",
      title: "专心到底差多少？",
      titleEn: "How much does attention matter?",
      body: "现代认知科学把这个差距叫「注意力控制」：工作记忆容量有限，同时想着天鹅的人，把认知资源分给了无关任务，棋局信息只能在浅层加工，无法进入长期记忆形成棋感模式。研究显示，任务切换会带来显著的时间与准确率损失（切换代价）。孟子两千多年前就指出：差距不在智力，在注意力——这与今天的研究结论一致。",
      bodyEn: "Cognitive science calls it attention control. Working memory is limited: the student thinking of swans spends resources on an irrelevant task, so chess information stays shallow and never consolidates into the pattern memory that makes a strong player. Research shows task-switching imposes measurable costs in time and accuracy. Mencius said the same two millennia ago: the gap is attention, not intelligence.",
    },
    note: "全文用对比结构，最后自问自答——英文用 Is it that…? No — it is not so 保留了设问句。",
    noteEn: "Built on contrast, ending in a question answered by itself.",
  },
  {
    slug: "liangxiaoerbianri",
    title: "两小儿辩日",
    titleEn: "Two Children Argue about the Sun",
    author: "《列子》",
    authorEn: "Liezi",
    dynasty: "先秦",
    dynastyEn: "Pre-Qin",
    stage: "小学",
    kind: "文言文",
    theme: "思辨",
    themeEn: "Reasoning",
    level: 2,
    lines: [
      { zh: "日初出大如车盖，及日中则如盘盂，此不为远者小而近者大乎？", en: "At sunrise the sun is big as a carriage canopy; at noon it is but a bowl — is that not 「far seems small, near seems large」?" },
      { zh: "日初出沧沧凉凉，及其日中如探汤，此不为近者热而远者凉乎？", en: "At sunrise it is cool and fresh; at noon it is like reaching into hot water — is that not 「near feels hot, far feels cool」?" },
      { zh: "孔子东游，见两小儿辩斗，问其故……孔子不能决也。", en: "Confucius travelling east saw two children arguing and asked why… and he could not settle it." },
    ],
    fullText: "孔子东游，见两小儿辩斗，问其故。一儿曰：「我以日始出时去人近，而日中时远也。」一儿曰：「我以日初出远，而日中时近也。」一儿曰：「日初出大如车盖，及日中则如盘盂，此不为远者小而近者大乎？」一儿曰：「日初出沧沧凉凉，及其日中如探汤，此不为近者热而远者凉乎？」孔子不能决也。两小儿笑曰：「孰为汝多知乎？」",
    keywords: [
      { w: "carriage canopy", zh: "车盖" },
      { w: "settle (v.)", zh: "判定、裁决" },
      { w: "at noon", zh: "正午" },
      { w: "reach into", zh: "把手伸进" },
    ],
    cross: {
      field: "天文",
      fieldEn: "Astronomy",
      title: "两小儿谁说得对？",
      titleEn: "Which child was right?",
      body: "两个都不对，而且理由很有意思。太阳早晨与中午的实际距离差极小（地球半径相对日地距离可忽略），真正变化的是：① 早晨太阳斜射，穿过更厚的大气，路径长、热量被削弱，所以凉；中午直射，单位面积接收的能量大，所以热——这是辐射几何问题。② 早晨太阳看起来大，是「月亮错觉」的同类：靠近地平线时有地面参照物对比，大脑把它判为更大，实际上太阳视直径全天基本不变。",
      bodyEn: "Neither, and the reasons are instructive. The actual distance barely differs (Earth's radius is negligible against 150 million km). What changes: (1) at sunrise the sun's rays slant through far more atmosphere, losing energy, so it feels cool; at noon they strike nearly vertically and deliver more energy per unit area — a matter of radiation geometry. (2) The apparent size change is the moon illusion: near the horizon the brain compares the sun with terrestrial objects and judges it larger; its angular diameter barely varies all day.",
    },
    note: "孔子「不能决」不是丢脸——承认不知道，正是这则寓言要教的。英文用 could not settle it，坦率。",
    noteEn: "Confucius's 「cannot decide」 is not shame — admitting ignorance is the lesson.",
  },
];
