import type { Poem } from "./types";

/** 小学阶段 · 第 2 批（咏柳、早春、节令、讽喻） */
export const PRIMARY_2: Poem[] = [
  {
    slug: "yongliu",
    title: "咏柳",
    titleEn: "Ode to the Willow",
    author: "贺知章",
    authorEn: "He Zhizhang",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "咏物",
    themeEn: "Nature",
    level: 1,
    lines: [
      { zh: "碧玉妆成一树高，万条垂下绿丝绦。", en: "Like a tree dressed in jade, so tall; ten thousand branches hang down as green silk ribbons." },
      { zh: "不知细叶谁裁出，二月春风似剪刀。", en: "Who cut out these delicate leaves? The second-month spring wind is like a pair of scissors." },
    ],
    keywords: [
      { w: "dress (v.)", zh: "装扮" },
      { w: "ribbon (n.)", zh: "丝带" },
      { w: "cut out", zh: "裁剪出" },
      { w: "delicate (adj.)", zh: "纤细的" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "柳叶真的是被「剪」出来的吗？",
      titleEn: "Are willow leaves really cut out?",
      body: "柳叶细长如眉，边缘有细锯齿，这是长期适应形成的叶形：窄叶减少水分蒸腾，锯齿边缘在早春能加速叶缘的蒸腾流，帮助矿物质输送。真正决定叶形的是叶原基中生长素（auxin）的浓度分布——浓度高的位置细胞分裂快，叶缘就长出锯齿。所以「春风似剪刀」是绝妙的比喻，但真正的剪刀是植物激素。",
      bodyEn: "Willow leaves are narrow with fine serrations — an adaptation: the narrow blade limits water loss, and toothed edges speed transpiration flow in early spring, helping move minerals. The actual shape is set by the distribution of auxin in the leaf primordium: where the hormone concentrates, cells divide faster and teeth form. So 「spring wind like scissors」 is a beautiful image, but the real scissors are plant hormones.",
    },
    note: "两个比喻层层递进：先整体比作碧玉树，再把春风比作剪刀——英文保留 dressed in jade 与 like a pair of scissors。",
    noteEn: "Two similes build on each other: the whole tree as jade, then the wind as scissors.",
  },
  {
    slug: "huixiangoushu",
    title: "回乡偶书",
    titleEn: "Casual Lines on Returning Home",
    author: "贺知章",
    authorEn: "He Zhizhang",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "思乡",
    themeEn: "Homesickness",
    level: 1,
    lines: [
      { zh: "少小离家老大回，乡音无改鬓毛衰。", en: "I left home young and return old; my village accent is unchanged, but my temples have thinned to grey." },
      { zh: "儿童相见不相识，笑问客从何处来。", en: "The children meet me and do not know me; smiling, they ask from where this guest has come." },
    ],
    keywords: [
      { w: "accent (n.)", zh: "口音" },
      { w: "temple (n.)", zh: "鬓角、太阳穴" },
      { w: "unchanged (adj.)", zh: "未改变的" },
      { w: "guest (n.)", zh: "客人" },
    ],
    cross: {
      field: "语言",
      fieldEn: "Linguistics",
      title: "为什么乡音最难改？",
      titleEn: "Why is a home accent so hard to lose?",
      body: "语音习得有关键期。儿童期（大约 12 岁前）大脑听觉皮层与运动皮层高度可塑，能自然建立母语的声母、韵母与声调范畴；青春期后这套神经回路固化，再学新音系就会带上「口音」，而早年形成的母语发音模式反而极难消除。贺知章离乡五十余年仍乡音无改，正是这个道理——语音记忆比容貌更顽固。",
      bodyEn: "Speech learning has a critical period. Before roughly age twelve the auditory and motor cortices are highly plastic, and a child builds the sound categories of a first language effortlessly. After puberty those circuits stabilise: new phonology comes with an accent, while early-acquired patterns resist erasure. He Zhizhang left for fifty years and kept his accent — sound memory outlasts looks.",
    },
    note: "「笑问客从何处来」最扎心：故乡把归人当成了外人。英文用 smiling 保留了孩子的天真——正因天真，才更伤。",
    noteEn: "The sting is in 「smiling, they ask where the guest is from」: home treats the homecomer as a stranger. Smiling keeps the children's innocence — which is what makes it hurt.",
  },
  {
    slug: "liangzhouci-wh",
    title: "凉州词 · 葡萄美酒",
    titleEn: "Liangzhou Song · Wine of Grapes",
    author: "王翰",
    authorEn: "Wang Han",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "边塞",
    themeEn: "Frontier",
    level: 1,
    lines: [
      { zh: "葡萄美酒夜光杯，欲饮琵琶马上催。", en: "Fine grape wine in a cup that glows at night; I would drink, but the pipa on horseback urges me on." },
      { zh: "醉卧沙场君莫笑，古来征战几人回。", en: "Do not laugh if I lie drunk on the battlefield — since ancient times, how many who went to war have come back?" },
    ],
    keywords: [
      { w: "glow (v.)", zh: "发光" },
      { w: "urge on", zh: "催促" },
      { w: "battlefield (n.)", zh: "沙场、战场" },
      { w: "since ancient times", zh: "自古以来" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "夜光杯是什么做的？",
      titleEn: "What were glowing cups made of?",
      body: "夜光杯出自甘肃酒泉，用祁连山一带的墨玉（蛇纹石质玉石）雕琢而成。玉质杯壁极薄，斟满酒后月光或烛光透过薄壁，酒色与玉色相映，看着像在发光——其实杯本身并不发光。酒泉至今仍产夜光杯，「葡萄美酒」则是汉代自西域传入的酿造传统，唐代凉州一带已有成熟的葡萄酒业。",
      bodyEn: "Glowing cups come from Jiuquan in Gansu, carved from dark serpentine jade of the Qilian mountains. The walls are cut so thin that moonlight or lamplight passes through, and the wine's colour glows against the stone — the cup itself emits nothing. Jiuquan still makes them today. As for grape wine, the craft came from the Western Regions in Han times; by Tang, Liangzhou had a mature wine industry.",
    },
    note: "最后一句是反问——不是抱怨，是明知必死仍然要饮的豪气。英文用 how many… have come back 保留了反问句式。",
    noteEn: "The last line is a rhetorical question: not complaint but bravado — drinking anyway, knowing what war costs.",
  },
  {
    slug: "biedongda",
    title: "别董大",
    titleEn: "Farewell to Dong Da",
    author: "高适",
    authorEn: "Gao Shi",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "送别",
    themeEn: "Farewell",
    level: 1,
    lines: [
      { zh: "千里黄云白日曛，北风吹雁雪纷纷。", en: "For a thousand li, yellow clouds; the white sun grows dim. North wind drives the wild geese through driving snow." },
      { zh: "莫愁前路无知己，天下谁人不识君。", en: "Do not worry that the road ahead holds no friend — who under heaven does not know you?" },
    ],
    keywords: [
      { w: "dim (adj.)", zh: "昏暗的" },
      { w: "driving (snow)", zh: "纷飞的（雪）" },
      { w: "worry (v.)", zh: "担忧" },
      { w: "under heaven", zh: "天下" },
    ],
    cross: {
      field: "气象",
      fieldEn: "Meteorology",
      title: "为什么下雪前的云是黄的？",
      titleEn: "Why are the clouds yellow before snow?",
      body: "阴天时云层厚、水滴与冰晶密集，阳光穿过时波长较长的红黄光散射损失小、透射率高，短波蓝光被散射掉，云就呈现灰黄或土黄色——气象上常把它当作雨雪将至的信号。诗里「千里黄云白日曛」写的正是这种低云压顶、日光被吞没的天气，紧接着就是「雪纷纷」，观察非常准确。",
      bodyEn: "In overcast, thick cloud the droplets and ice crystals scatter short blue light away, while longer red and yellow wavelengths pass through — the cloud turns dirty yellow, a classic sign of coming rain or snow. 「Yellow clouds for a thousand li, the white sun dim」 describes precisely that lowering overcast, and the snow follows. Accurate observation.",
    },
    note: "前两句极惨，后两句极豪——越是惨淡的景，越衬得出这句劝勉的分量。英文用 Do not worry 把转折立住。",
    noteEn: "Two bleak lines, then two generous ones: the darker the scene, the stronger the comfort.",
  },
  {
    slug: "zaochun-hanyu",
    title: "早春呈水部张十八员外",
    titleEn: "Early Spring — To Zhang, Eighteenth of the Water Board",
    author: "韩愈",
    authorEn: "Han Yu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "四季",
    themeEn: "Seasons",
    level: 1,
    lines: [
      { zh: "天街小雨润如酥，草色遥看近却无。", en: "A light rain on the imperial street, moist as cream; the grass looks green from afar, but up close there is nothing." },
      { zh: "最是一年春好处，绝胜烟柳满皇都。", en: "This is the best moment of the spring year, far better than when smoky willows fill the capital." },
    ],
    keywords: [
      { w: "moist (adj.)", zh: "湿润的" },
      { w: "cream (n.)", zh: "酥油、奶油" },
      { w: "from afar", zh: "从远处" },
      { w: "far better than", zh: "远胜于" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "为什么草色「遥看近却无」？",
      titleEn: "Why does grass look green from afar but not up close?",
      body: "早春草芽刚破土，单株的绿极少、极淡，凑近看只见土色；但远处观看时，视野内成片稀疏的嫩芽叠加，绿色在视网膜上被空间累加，于是呈现一层若有若无的青色。这在视觉科学上属于颜色信号的低对比度整合——韩愈用两句诗写活了一个真实的视觉现象，也是全诗最出名的地方。",
      bodyEn: "In early spring each shoot is tiny and pale; close up you see mostly soil. From a distance, thousands of sparse shoots fall within one visual angle and their weak greens sum on the retina, producing that faint wash of colour. Vision science would call it low-contrast spatial integration — Han Yu turned a real perceptual effect into the poem's most famous line.",
    },
    note: "写早春而不写繁花，专挑草色似有似无的一刻——英译 far / up close 的对比是全诗命门。",
    noteEn: "He skips blossoms for the moment grass is barely there — the far / up close contrast is the whole point.",
  },
  {
    slug: "yugezi",
    title: "渔歌子",
    titleEn: "Fisherman's Song",
    author: "张志和",
    authorEn: "Zhang Zhihe",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "词",
    theme: "山水",
    themeEn: "Landscape",
    level: 1,
    lines: [
      { zh: "西塞山前白鹭飞，桃花流水鳜鱼肥。", en: "Before Mount Xisai the egrets fly; peach blossoms fall on flowing water, and the mandarin fish are fat." },
      { zh: "青箬笠，绿蓑衣，斜风细雨不须归。", en: "A blue bamboo hat, a green straw cloak — in slanted wind and fine rain, there is no need to go home." },
    ],
    keywords: [
      { w: "egret (n.)", zh: "白鹭" },
      { w: "mandarin fish", zh: "鳜鱼" },
      { w: "cloak (n.)", zh: "蓑衣、披风" },
      { w: "there is no need to", zh: "不必" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "鳜鱼为什么春天最肥？",
      titleEn: "Why are mandarin fish fattest in spring?",
      body: "鳜鱼是凶猛的肉食性淡水鱼，靠伏击捕食小鱼虾。冬季水温低，代谢慢、摄食少，体能消耗大；春季水温回升，饵料鱼繁殖活跃，鳜鱼大量进食，为春夏繁殖蓄积脂肪，此时肌肉饱满、脂肪适中，正是最肥美的时候。民间所谓「桃花流水鳜鱼肥」，把鱼的肥美和桃花汛（春汛）准确对应在了一起。",
      bodyEn: "The mandarin fish is a predatory freshwater species that ambushes small fish and shrimp. Winter's cold water slows metabolism and feeding, draining reserves; as water warms in spring, prey fish spawn and become active, so the predator gorges, storing fat for its own breeding season. Flesh is then firm and richly marbled — exactly the season the poem names, linking fatness to the spring peach-blossom flood.",
    },
    note: "「不须归」三个字是全词的魂：不是不能回，是不必回。英文 no need to go home 保留了这份洒脱。",
    noteEn: "The soul is 「不须归」 — not unable to go home, but no need to.",
  },
  {
    slug: "saixiaqu",
    title: "塞下曲",
    titleEn: "Song of the Frontier",
    author: "卢纶",
    authorEn: "Lu Lun",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "边塞",
    themeEn: "Frontier",
    level: 1,
    lines: [
      { zh: "月黑雁飞高，单于夜遁逃。", en: "The moon is dark, the wild geese fly high; the chieftain flees under cover of night." },
      { zh: "欲将轻骑逐，大雪满弓刀。", en: "About to send light horse in pursuit — but heavy snow already fills the bows and blades." },
    ],
    keywords: [
      { w: "flee (v.)", zh: "逃跑" },
      { w: "under cover of night", zh: "趁夜色" },
      { w: "in pursuit", zh: "追击" },
      { w: "bow (n.)", zh: "弓" },
    ],
    cross: {
      field: "气象",
      fieldEn: "Meteorology",
      title: "为什么「月黑」时大雁飞得高？",
      titleEn: "Why do geese fly high on a moonless night?",
      body: "候鸟迁徙多在夜间，靠星辰与地磁导航。无月之夜天空最暗，高飞能避开地面障碍物，也能减少被猛禽发现的概率；而高空气温低、空气密度小，长距离滑翔更省力。更妙的是：大雁受惊起飞会发出叫声，古人正是靠「雁飞高 + 雁鸣」判断夜里有人马经过——所以「月黑雁飞高」是敌军夜逃的旁证，不是写景。",
      bodyEn: "Migrants often travel at night, navigating by stars and geomagnetism. A moonless sky is darkest, so flying high avoids ground obstacles and nocturnal predators; cold, thin air at altitude also makes long glides cheaper. Better still: startled geese call as they rise, so watchers used high-flying, calling geese as evidence of movement below — 「moon dark, geese fly high」 is a clue to the enemy's flight, not scenery.",
    },
    note: "末句是神来之笔：追兵未发，大雪已经压满弓刀，写雪就是写将士的肃杀。英文用 but 把这个停顿留住。",
    noteEn: "The closing image: the pursuit never starts because snow already loads the weapons — the snow itself conveys the soldiers' readiness.",
  },
  {
    slug: "jueju-dufu",
    title: "绝句 · 两个黄鹂",
    titleEn: "A Quatrain · Two Golden Orioles",
    author: "杜甫",
    authorEn: "Du Fu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "四季",
    themeEn: "Seasons",
    level: 1,
    lines: [
      { zh: "两个黄鹂鸣翠柳，一行白鹭上青天。", en: "Two golden orioles sing in the green willow; a line of white egrets rises into the blue sky." },
      { zh: "窗含西岭千秋雪，含窗西岭千秋雪。", en: "My window frames the western range with its thousand-year snow." },
      { zh: "门泊东吴万里船。", en: "At my door lie the boats of Wu, ten thousand li away." },
    ],
    keywords: [
      { w: "oriole (n.)", zh: "黄鹂" },
      { w: "a line of", zh: "一行" },
      { w: "frame (v.)", zh: "（窗）框住、容纳" },
      { w: "lie (of boats)", zh: "停泊" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "西岭千秋雪真的终年不化吗？",
      titleEn: "Does the western range really keep snow all year?",
      body: "西岭指成都西侧的邛崃山脉，主峰四姑娘山海拔 6250 米，高海拔使气温随高度递减（约每千米降 6℃），山顶常年低于 0℃，形成现代冰川与永久积雪。杜甫在成都草堂能望见它，直线距离约 80 公里——空气通透的日子（雨后初晴），远山雪线确实清晰可见。所谓「千秋雪」，是诗人对时间尺度的夸张，但物理上完全成立。",
      bodyEn: "The western range is the Qionglai mountains west of Chengdu; its main peak, Mount Siguniang, rises to 6,250 m. Temperature drops about 6℃ per kilometre of altitude, so the summits stay below freezing, holding permanent snow and small glaciers. From his thatched cottage Du Fu could see them some 80 km away on clear, washed air after rain. 「Thousand-year snow」 exaggerates the timescale, but the physics holds.",
    },
    note: "四句四景，两句近、两句远，「窗含」「门泊」把远景收进一方小屋——英文用 frames 与 lie 保留这个构图。",
    noteEn: "Four lines, four views: two near, two far. Frame and lie gather distant scenery into one small cottage.",
  },
  {
    slug: "jiangpandubu",
    title: "江畔独步寻花",
    titleEn: "Walking Alone by the River, Looking for Flowers",
    author: "杜甫",
    authorEn: "Du Fu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "四季",
    themeEn: "Seasons",
    level: 1,
    lines: [
      { zh: "黄四娘家花满蹊，千朵万朵压枝低。", en: "At Yellow Fourth Lady's, flowers crowd the path; a thousand, ten thousand blooms weigh the branches low." },
      { zh: "留连戏蝶时时舞，自在娇莺恰恰啼。", en: "Lingering butterflies dance without pause; carefree, pretty orioles sing right on cue." },
    ],
    keywords: [
      { w: "crowd (v.)", zh: "挤满" },
      { w: "weigh down", zh: "压弯" },
      { w: "linger (v.)", zh: "留恋不去" },
      { w: "carefree (adj.)", zh: "自在的" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "蝴蝶为什么围着花打转？",
      titleEn: "Why do butterflies hover over flowers?",
      body: "这是经典的传粉互利：花提供花蜜（糖分）作为报酬，蝴蝶在吸食时身上沾上花粉，飞到下一朵就完成了异花授粉。蝴蝶的视觉对紫外光敏感，许多花瓣上有肉眼看不见的「蜜导」斑纹，专门给传粉者指路。诗里说的「留连」很准确——同一只蝴蝶往往在一小片花丛内反复采食，形成稳定的采食路径（trapline）。",
      bodyEn: "Classic pollination mutualism: the flower pays in nectar sugar, the butterfly carries pollen to the next bloom, achieving cross-pollination. Butterflies see ultraviolet, and many petals bear nectar guides invisible to us. 「Lingering」 is precise — a butterfly often revisits the same patch in a fixed route, behaviour ecologists call trap-lining.",
    },
    note: "这是杜甫难得轻快的作品（成都草堂时期）。数词 thousand / ten thousand 与副词 without pause / right on cue 一起，把春天的喧闹写出来。",
    noteEn: "Rarely so light: written in his Chengdu cottage years. Numbers and adverbs together build the noise of spring.",
  },
  {
    slug: "qingming",
    title: "清明",
    titleEn: "The Qingming Festival",
    author: "杜牧",
    authorEn: "Du Mu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "节俗",
    themeEn: "Festivals",
    level: 1,
    lines: [
      { zh: "清明时节雨纷纷，路上行人欲断魂。", en: "At Qingming the rain falls thick and fine; the traveller on the road feels his soul nearly break." },
      { zh: "借问酒家何处有，牧童遥指杏花村。", en: "I ask where a tavern might be found; the herdboy points afar to Apricot Blossom Village." },
    ],
    keywords: [
      { w: "thick and fine", zh: "（雨）纷纷" },
      { w: "traveller (n.)", zh: "行人" },
      { w: "tavern (n.)", zh: "酒家" },
      { w: "point afar", zh: "遥指" },
    ],
    cross: {
      field: "气象",
      fieldEn: "Meteorology",
      title: "清明为什么总在下雨？",
      titleEn: "Why does it always rain around Qingming?",
      body: "清明在公历 4 月 4—6 日，正值东亚春季过渡期：南方暖湿气流北上，北方冷空气尚未完全退去，两者在长江中下游一带交汇形成准静止锋，带来持续细雨。所以江南「清明时节雨纷纷」是气候统计事实，不是文学修饰。谚语「清明前后，种瓜点豆」也来自同一气候条件：气温回升、雨水充沛，正是播种时机。",
      bodyEn: "Qingming falls on 4–6 April, exactly when moist southerly air pushes north while cold northern air has not withdrawn. The two meet over the middle-lower Yangtze as a quasi-stationary front, producing persistent fine rain — so the drizzle is a climatological fact in the south, not decoration. The farming saying 「sow melons and beans around Qingming」 rests on the same warm, wet window.",
    },
    note: "「欲断魂」不是真的断魂，是又冷又累又想家；最后牧童一指，气氛立刻转暖——英文用 points afar 收住这个镜头。",
    noteEn: "「Soul nearly break」 means cold, tired and homesick; the herdboy's pointing hand warms the ending at once.",
  },
  {
    slug: "jiangnanchun",
    title: "江南春",
    titleEn: "Spring in the South",
    author: "杜牧",
    authorEn: "Du Mu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "四季",
    themeEn: "Seasons",
    level: 1,
    lines: [
      { zh: "千里莺啼绿映红，水村山郭酒旗风。", en: "For a thousand li the orioles sing, green set against red; by water villages and hill walls, tavern banners in the wind." },
      { zh: "南朝四百八十寺，多少楼台烟雨中。", en: "The Southern Dynasties left four hundred and eighty temples — how many towers and halls now stand in mist and rain?" },
    ],
    keywords: [
      { w: "banner (n.)", zh: "旗子" },
      { w: "set against", zh: "与…相映" },
      { w: "temple (n.)", zh: "寺庙" },
      { w: "mist (n.)", zh: "烟雨、雾气" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "南朝真的有 480 座寺庙吗？",
      titleEn: "Did the Southern Dynasties really have 480 temples?",
      body: "数字是约数，但不是吹牛。南朝（宋齐梁陈）都城建康（今南京）佛教极盛，梁武帝甚至四次舍身同泰寺，据《南史》等记载，梁代都下佛寺五百余所，僧尼十余万。唐代诗人看到的，是杜牧追忆中已成废墟的南朝遗迹。杜牧本人反对过度崇佛（晚唐曾有灭佛），这句「多少楼台烟雨中」既是怀古，也含讽喻：再盛的楼台，也终归于烟雨。",
      bodyEn: "The number is round but not invented. Under the Southern Dynasties, Buddhism flourished at Jiankang (modern Nanjing); Emperor Wu of Liang gave himself to a monastery four times, and records speak of over five hundred temples and a hundred thousand monks and nuns in the capital region. By Du Mu's Tang the glory was ruin. He was no friend of monastic wealth — late Tang would soon suppress Buddhism — so 「how many towers in mist and rain」 is elegy and warning at once.",
    },
    note: "前两句浓艳，后两句苍茫——一句之内从「绿映红」到「烟雨中」，是典型的杜牧式落差。",
    noteEn: "Bright first, hazy last: from green against red to mist and rain — a characteristically Du Mu collapse of mood.",
  },
  {
    slug: "leyouyuan",
    title: "乐游原",
    titleEn: "On Leyou Plain",
    author: "李商隐",
    authorEn: "Li Shangyin",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "人生",
    themeEn: "Life",
    level: 1,
    lines: [
      { zh: "向晚意不适，驱车登古原。", en: "Toward evening my spirits fail; I drive my carriage up the ancient plain." },
      { zh: "夕阳无限好，只是近黄昏。", en: "The setting sun is infinitely lovely — only, it is nearing dusk." },
    ],
    keywords: [
      { w: "toward evening", zh: "向晚" },
      { w: "spirits fail", zh: "心情不佳" },
      { w: "infinitely (adv.)", zh: "无限地" },
      { w: "nearing (prep.)", zh: "临近" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "夕阳为什么比正午红？",
      titleEn: "Why is the setting sun redder than noon sun?",
      body: "这是瑞利散射。阳光穿过大气时，波长短的蓝紫光被空气分子强烈散射（天空因此是蓝的），而红橙光散射弱、透射强。正午阳光路径短，颜色接近白；日落时阳光要斜穿几十倍厚的大气层，蓝光几乎全被散射掉，只剩下红橙光抵达眼睛——于是夕阳又红又大。李商隐写「无限好」，首先是因为它真的美得不讲道理。",
      bodyEn: "This is Rayleigh scattering. Air molecules scatter short blue and violet wavelengths strongly — which is why the sky is blue — while red and orange pass through. At noon the path is short and the sun looks white; at sunset light slants through many times more atmosphere, the blue is scattered away entirely, and only red-orange reaches the eye. Hence a sun both redder and apparently larger.",
    },
    note: "「只是」是全诗转折——美是真的，短暂也是真的。英文用 only 一个词承载了整句的重量。",
    noteEn: "Everything turns on 「只是」: lovely, yes — and nearly gone. One word, only, carries the whole weight.",
  },
  {
    slug: "feng-luoyin",
    title: "蜂",
    titleEn: "The Bees",
    author: "罗隐",
    authorEn: "Luo Yin",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "小学",
    kind: "诗",
    theme: "悯农",
    themeEn: "Labour",
    level: 1,
    lines: [
      { zh: "不论平地与山尖，无限风光尽被占。", en: "Whether on flat ground or mountain peaks, they have taken over all the boundless scenery." },
      { zh: "采得百花成蜜后，为谁辛苦为谁甜。", en: "After gathering a hundred flowers into honey — for whom the toil, and for whom the sweetness?" },
    ],
    keywords: [
      { w: "take over", zh: "占据" },
      { w: "boundless (adj.)", zh: "无限的" },
      { w: "gather (v.)", zh: "采集" },
      { w: "toil (n.)", zh: "辛苦劳作" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "蜜蜂酿蜜要飞多远？",
      titleEn: "How far do bees fly to make honey?",
      body: "一只工蜂要酿出 1 千克蜂蜜，需采集约数百万朵花，累计飞行距离可达十几万公里——相当于绕地球好几圈。采集时蜜蜂用口器吸取花蜜存入蜜囊，回巢后反复吞吐、加入转化酶把蔗糖分解为葡萄糖和果糖，再靠扇风蒸发水分，把含水量从约 60% 降到 18% 以下才封蜡保存。所以「为谁辛苦为谁甜」不是抒情，是一笔真实的劳动账。",
      bodyEn: "For one kilogram of honey, a colony's workers visit millions of flowers and fly the equivalent of several laps around the earth. A forager sucks nectar into her honey stomach, then in the hive passes it mouth to mouth while enzymes split sucrose into glucose and fructose; finally the bees fan it until water falls from roughly 60% to below 18% before sealing the cell. The poem's question is not sentiment — it is a labour accounts sheet.",
    },
    note: "两个「为谁」把劳动者与果实分离——英文用 for whom… and for whom… 的重复保留了质问的力量。",
    noteEn: "The doubled for whom separates the worker from the reward — repetition keeps the accusation alive.",
  },
  {
    slug: "jiangshangyuzhe",
    title: "江上渔者",
    titleEn: "The Fisherman on the River",
    author: "范仲淹",
    authorEn: "Fan Zhongyan",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "诗",
    theme: "悯农",
    themeEn: "Labour",
    level: 1,
    lines: [
      { zh: "江上往来人，但爱鲈鱼美。", en: "Those who come and go upon the river all love the sea bass for its delicate flesh." },
      { zh: "君看一叶舟，出没风波里。", en: "But look at that boat, a single leaf, rising and vanishing among the wind and waves." },
    ],
    keywords: [
      { w: "come and go", zh: "来来往往" },
      { w: "delicate (flesh)", zh: "（肉）鲜美" },
      { w: "a single leaf", zh: "一叶（舟）" },
      { w: "rise and vanish", zh: "出没" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "鲈鱼为什么肉质鲜美？",
      titleEn: "Why is sea bass so tender?",
      body: "鲈鱼（花鲈）肌肉中肌纤维较细、结缔组织少，肌间刺少，加上富含游离氨基酸（尤其呈鲜味的谷氨酸、天冬氨酸）和一定量的不饱和脂肪酸，口感细嫩带鲜甜。它是广盐性鱼类，能在淡水、河口与海水中生活，江海交汇处饵料丰富，体型肥美。范仲淹写这首诗时看到的可能正是长江口的捕鲈场景。",
      bodyEn: "Sea bass has fine muscle fibres, little connective tissue and few intermuscular bones, plus abundant free amino acids — notably glutamate and aspartate, the umami compounds — and healthy unsaturated fats, giving tender, sweet flesh. It is euryhaline, living in fresh, brackish and sea water; estuaries offer rich feeding, so the fish grow fat. Fan Zhongyan probably watched exactly such a catch near the Yangtze mouth.",
    },
    note: "全诗只有 20 字，结构却是「众人只知鱼美 → 你看那条船」。英文用 But look 完成这个视角切换。",
    noteEn: "Twenty characters, one pivot: everyone loves the fish — but look at that boat.",
  },
  {
    slug: "bochuanguazhou",
    title: "泊船瓜洲",
    titleEn: "Mooring at Guazhou",
    author: "王安石",
    authorEn: "Wang Anshi",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "小学",
    kind: "诗",
    theme: "思乡",
    themeEn: "Homesickness",
    level: 1,
    lines: [
      { zh: "京口瓜洲一水间，钟山只隔数重山。", en: "Between Jingkou and Guazhou lies a single stretch of water; Mount Zhong is barred by only a few ranges." },
      { zh: "春风又绿江南岸，明月何时照我还。", en: "The spring wind has greened the southern bank again — when will the bright moon light me home?" },
    ],
    keywords: [
      { w: "barred by", zh: "相隔、被隔开" },
      { w: "a stretch of water", zh: "一水之隔" },
      { w: "green (v.)", zh: "吹绿（形容词作动词）" },
      { w: "light sb. home", zh: "照着某人回家" },
    ],
    cross: {
      field: "语文",
      fieldEn: "Language",
      title: "「绿」字为什么改了十几次？",
      titleEn: "Why was the word 「green」 revised so many times?",
      body: "据洪迈《容斋随笔》记载，王安石写这句时先用「到」，改「过」，又改「入」「满」，最后定为「绿」。「绿」的妙处在于形容词作动词：春风不仅吹过，还带来了颜色变化这一结果，一句里既有动作又有结果。英文里同样可以活用词性——green 作动词（to green the land）正是最贴切的译法。这是中文诗眼英译的经典案例。",
      bodyEn: "According to Hong Mai's notes, Wang Anshi tried 「arrive」, then 「pass」, then 「enter」 and 「fill」, before settling on 「green」. Its brilliance is the shift from adjective to verb: the wind does not merely pass, it produces a visible result — action and outcome in one word. English allows the same conversion: to green the land. A textbook case of rendering a Chinese poetic eye into English.",
    },
    note: "地理上离家很近（只隔数重山），政治上前路未卜——「何时照我还」问的不是能不能回，是局势能不能容他回。",
    noteEn: "Geographically close, politically uncertain: the question is not whether he can go home, but whether the court will let him.",
  },
];
