import type { Poem } from "./types";

/** 高中阶段 · 第 1 批（楚辞、歌行、长调） */
export const SENIOR_1: Poem[] = [
  {
    slug: "lisao",
    title: "离骚（节选）",
    titleEn: "Encountering Sorrow (excerpt)",
    author: "屈原",
    authorEn: "Qu Yuan",
    dynasty: "战国",
    dynastyEn: "Warring States",
    stage: "高中",
    kind: "诗",
    theme: "家国",
    themeEn: "Nation",
    level: 3,
    lines: [
      { zh: "长太息以掩涕兮，哀民生之多艰。", en: "I heave a long sigh and wipe my tears — grieving that the people's life is so full of hardship." },
      { zh: "亦余心之所善兮，虽九死其犹未悔。", en: "What my heart holds good — though I were to die nine times, I would not regret it." },
      { zh: "路漫漫其修远兮，吾将上下而求索。", en: "The road is long and far, and I shall search high and low." },
    ],
    keywords: [
      { w: "heave a sigh", zh: "长叹（太息）" },
      { w: "hardship (n.)", zh: "艰难" },
      { w: "search (v.)", zh: "求索" },
      { w: "high and low", zh: "上下（到处）" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "屈原与端午节是怎么连上的？",
      titleEn: "How did Qu Yuan become linked to the Dragon Boat Festival?",
      body: "屈原是楚国贵族、政治家，主张联齐抗秦，被流放后于公元前 278 年秦军攻破郢都时投汨罗江自尽。端午节（农历五月初五）的竞渡与投粽，南朝《荆楚岁时记》等文献已明确与屈原相联系——竞渡源于抢救、粽子源于投江祭奠。但学者多认为端午的节俗（避疫、龙舟）本就存在，后来才与屈原的传说叠合。这是民俗学上典型的「传说附会于节俗」。",
      bodyEn: "Qu Yuan was a Chu aristocrat and statesman who urged alliance against Qin; exiled, he drowned himself in the Miluo river in 278 BC when Qin took the Chu capital. By the Southern Dynasties, texts such as the Record of the Seasons of Jingchu already linked the fifth day of the fifth month — racing boats, rice dumplings thrown into water — to him: racing as rescue, dumplings as offering. Scholars hold that the festival's customs (plague-avoidance, boat rites) predate him and the legend was attached later, a common folkloric process.",
    },
    note: "「兮」是楚辞的标志性语气词，英文无法对应，只能用破折号或停顿代替。",
    noteEn: "The particle xi has no English equivalent; here it becomes a pause.",
  },
  {
    slug: "duangexing",
    title: "短歌行（节选）",
    titleEn: "Short Song Ballad (excerpt)",
    author: "曹操",
    authorEn: "Cao Cao",
    dynasty: "东汉",
    dynastyEn: "Eastern Han",
    stage: "高中",
    kind: "诗",
    theme: "人生",
    themeEn: "Life",
    level: 3,
    lines: [
      { zh: "对酒当歌，人生几何！譬如朝露，去日苦多。", en: "Facing wine, we should sing — how long is a man's life? It is like the morning dew: the days gone by are bitterly many." },
      { zh: "青青子衿，悠悠我心。但为君故，沉吟至今。", en: "Blue, blue the collar of your robe; long, long my thoughts. It is only because of you that I have brooded to this day." },
      { zh: "月明星稀，乌鹊南飞。绕树三匝，何枝可依？", en: "The moon is bright, the stars are few; ravens and magpies fly south. Circling the tree three times — on what branch may they rest?" },
      { zh: "山不厌高，海不厌深。周公吐哺，天下归心。", en: "Hills do not weary of height, seas do not weary of depth. The Duke of Zhou spat out his meal — and all under heaven turned their hearts to him." },
    ],
    keywords: [
      { w: "brood (v.)", zh: "沉思吟咏" },
      { w: "circle (v.)", zh: "绕（树）" },
      { w: "weary of", zh: "厌倦、满足于（不厌）" },
      { w: "turned their hearts to him", zh: "归心" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "「周公吐哺」是什么典故？",
      titleEn: "What is the Duke of Zhou allusion?",
      body: "出自《史记·鲁周公世家》：周公（姬旦）礼贤下士，洗头时多次握着湿发出来见客，吃饭时多次吐出口中的食物去接待贤士，史称「一沐三握发，一饭三吐哺」。曹操在赤壁之战前写下《短歌行》，正是求贤若渴之时——他用周公自比，表明自己要像周公那样招揽人才、统一天下。这首诗本质上是一篇招聘启事。",
      bodyEn: "From the Records of the Grand Historian: the Duke of Zhou (Ji Dan) honoured talent so eagerly that while washing his hair he would come out with it still wet, and during meals he would spit out his food to receive worthies — hence 「grasp the hair three times in one wash, spit out the food three times in one meal」. Cao Cao wrote this before the Battle of Red Cliff, when he was hungry for talent; comparing himself to the Duke of Zhou announced that he meant to gather the realm's ability and unify the empire. The poem is essentially a recruitment notice.",
    },
    note: "「乌鹊南飞，何枝可依」是借鸟问人才：天下动荡，你们要投奔谁？英文用 on what branch may they rest 保留了问句。",
    noteEn: "The birds are talent in a disordered world, asked where they will settle.",
  },
  {
    slug: "guiyuantianju-yi",
    title: "归园田居 · 其一",
    titleEn: "Returning to Garden and Field · I",
    author: "陶渊明",
    authorEn: "Tao Yuanming",
    dynasty: "东晋",
    dynastyEn: "Eastern Jin",
    stage: "高中",
    kind: "诗",
    theme: "田园",
    themeEn: "Pastoral",
    level: 3,
    lines: [
      { zh: "少无适俗韵，性本爱丘山。误落尘网中，一去三十年。", en: "From youth I had no taste for the world's tune; by nature I loved hills and mountains. By mistake I fell into the dust-net, and was gone thirty years." },
      { zh: "羁鸟恋旧林，池鱼思故渊。", en: "The caged bird longs for its old wood; the pond fish thinks of its former pool." },
      { zh: "久在樊笼里，复得返自然。", en: "Long caged, I have won my way back to what is natural." },
    ],
    keywords: [
      { w: "by nature", zh: "本性（性本）" },
      { w: "dust-net", zh: "尘网（仕途）" },
      { w: "caged (adj.)", zh: "被囚笼的（羁）" },
      { w: "won my way back", zh: "复得返" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "「池鱼思故渊」符合动物行为吗？",
      titleEn: "Do fish really long for their old pool?",
      body: "「归属感」难以证实，但鱼类的标记洄游与归巢行为确实存在：鲑鱼靠嗅觉记忆回到出生河流，误差可小于百公里；许多淡水鱼被移到别处后会沿原水道返回栖息地。至于「羁鸟恋旧林」则更有据——许多留鸟对繁殖地有强烈的固着性（philopatry），次年返回同一片林地的比例很高。陶渊明用两种动物自比，都抓住了它们与生境的绑定关系。",
      bodyEn: "Whether fish feel homesick is unprovable, but homing behaviour is real: salmon return by olfactory memory to their natal river, often accurately to within tens of kilometres, and many freshwater fish relocated elsewhere work their way back. 「Caged bird」 is on firmer ground — many resident birds show strong philopatry, returning to the same breeding woodland year after year. Tao Yuanming picked two animals defined by their attachment to a place.",
    },
    note: "「尘网」「樊笼」两个比喻把官场写成物理空间——英文用 dust-net 与 caged 保留了空间的禁锢感。",
    noteEn: "Office as enclosure: a dust net, a cage.",
  },
  {
    slug: "mengyoutianmu",
    title: "梦游天姥吟留别（节选）",
    titleEn: "Climbing Tianmu in a Dream: A Song of Parting (excerpt)",
    author: "李白",
    authorEn: "Li Bai",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "高中",
    kind: "诗",
    theme: "山水",
    themeEn: "Landscape",
    level: 3,
    lines: [
      { zh: "天姥连天向天横，势拔五岳掩赤城。天台四万八千丈，对此欲倒东南倾。", en: "Tianmu joins the sky and lies across it; its bulk out-tops the Five Peaks and hides Chicheng. Tiantai, forty-eight thousand fathoms high, would tip and fall south-east before it." },
      { zh: "半壁见海日，空中闻天鸡。", en: "Halfway up the cliff I see the sea-sun; in the void I hear the celestial cock." },
      { zh: "安能摧眉折腰事权贵，使我不得开心颜！", en: "How can I bow my head and bend my back to serve the powerful, and so never let my face open in joy!" },
    ],
    keywords: [
      { w: "out-top (v.)", zh: "超出（拔）" },
      { w: "tip (v.)", zh: "倾倒" },
      { w: "in the void", zh: "空中" },
      { w: "bow my head", zh: "摧眉（低头）" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "天姥山、天台山在哪里？",
      titleEn: "Where are Mounts Tianmu and Tiantai?",
      body: "都在浙江。天姥山在新昌县，海拔约 900 米；天台山主峰华顶山海拔 1098 米。李白的夸张（天台四万八千丈）是典型的浪漫主义手法——按唐代一丈约 3 米计，四万八千丈高达 144 公里，远超任何山脉。这类数字夸张在李白诗中常见（白发三千丈、飞流直下三千尺），是他的风格标记，也是浪漫主义与写实主义的分野。",
      bodyEn: "Both lie in Zhejiang: Tianmu in Xinchang county at about 900 m; Tiantai's main peak, Huading, at 1,098 m. Li Bai's exaggeration is characteristic — at roughly 3 m per Tang fathom, 48,000 fathoms is 144 km, taller than anything on Earth. Such numbers recur throughout his work (white hair of thirty thousand fathoms, a fall of three thousand feet), marking him as a romantic rather than a realist.",
    },
    note: "全诗从梦境写到惊醒，落点是最后一句——梦越奇幻，醒后的骨气越硬。英文用 How can I 保留了反问式的决绝。",
    noteEn: "The dream is fantastical; the waking line is pure steel.",
  },
  {
    slug: "shudaonan",
    title: "蜀道难（节选）",
    titleEn: "The Road to Shu Is Hard (excerpt)",
    author: "李白",
    authorEn: "Li Bai",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "高中",
    kind: "诗",
    theme: "山水",
    themeEn: "Landscape",
    level: 3,
    lines: [
      { zh: "西当太白有鸟道，可以横绝峨眉巅。", en: "West, facing Taibai, there is a bird path, by which one can cross to the summit of Emei." },
      { zh: "连峰去天不盈尺，枯松倒挂倚绝壁。", en: "Peak after peak, less than a foot from the sky; dead pines hang upside down against the sheer cliffs." },
      { zh: "剑阁峥嵘而崔嵬，一夫当关，万夫莫开。", en: "Jiange is jagged and towering — one man at the pass, and ten thousand cannot force it." },
    ],
    keywords: [
      { w: "sheer (adj.)", zh: "陡峭的（绝壁）" },
      { w: "hang upside down", zh: "倒挂" },
      { w: "jagged (adj.)", zh: "峥嵘、崎岖" },
      { w: "force (a pass)", zh: "攻破（关口）" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "蜀道为什么这么难？",
      titleEn: "Why is the road to Shu so hard?",
      body: "蜀道指穿越秦巴山地、连接关中与四川盆地的道路（金牛道、褒斜道、子午道等）。北侧是秦岭（主峰太白山 3771 米），南侧是大巴山与米仓山，中间是嘉陵江等深切河谷，道路需在悬崖上开凿栈道。剑门关位于剑阁县，两侧峭壁如剑、中间仅数十米宽，是天然隘口——「一夫当关，万夫莫开」是地形的真实描述。这一屏障使四川盆地长期保持相对独立的政治单元。",
      bodyEn: "The Shu roads cross the Qinling and Daba mountains linking Guanzhong with the Sichuan basin — the Jinniu, Baoye and Ziwu routes among them. North stands the Qinling range (Taibai peak, 3,771 m), south the Daba and Micang ranges, with deep valleys such as the Jialing between, so the road had to be cut as plank galleries along cliffs. Jianmen pass in Jiange county, with sword-like walls and a gap only tens of metres wide, is a natural chokepoint: one man at the pass is literally true. The barrier long made Sichuan a semi-independent political unit.",
    },
    note: "「一夫当关，万夫莫开」已进入日常语言——英文用 one man at the pass, and ten thousand cannot force it 保留了军事含义。",
    noteEn: "A line that became everyday speech: one man holds the pass.",
  },
  {
    slug: "jiangjinjiu",
    title: "将进酒（节选）",
    titleEn: "Bring in the Wine (excerpt)",
    author: "李白",
    authorEn: "Li Bai",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "高中",
    kind: "诗",
    theme: "人生",
    themeEn: "Life",
    level: 3,
    lines: [
      { zh: "君不见黄河之水天上来，奔流到海不复回。", en: "Do you not see — the waters of the Yellow River come down from heaven, race to the sea and never return?" },
      { zh: "君不见高堂明镜悲白发，朝如青丝暮成雪。", en: "Do you not see — in bright mirrors in high halls they grieve at white hair, at morning black silk, by evening snow?" },
      { zh: "天生我材必有用，千金散尽还复来。", en: "Heaven made me with talent that must have a use; a thousand gold scattered will come again." },
    ],
    keywords: [
      { w: "race (v.)", zh: "奔流" },
      { w: "black silk", zh: "青丝（黑发）" },
      { w: "scatter (v.)", zh: "散尽（花钱）" },
      { w: "come again", zh: "还复来" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "黄河真的「天上来」吗？",
      titleEn: "Does the Yellow River really come from heaven?",
      body: "黄河发源于青海巴颜喀拉山北麓，源头海拔约 4600—4800 米，是名副其实的高原河流；从源头到入海口总落差约 4480 米。古人不知道海拔，但看到它从西方高原滚滚而下，用「天上来」形容非常贴切。至于「奔流到海不复回」，水循环意义上是错的——海水蒸发、水汽输送、降水补给，水一直在回；但在河流的水文意义上，同一股水确实一去不返。",
      bodyEn: "The Yellow River rises on the north slope of the Bayan Har mountains in Qinghai at 4,600–4,800 m — genuinely a river of high plateaus — and drops some 4,480 m to the sea. The ancients knew nothing of altitude, yet seeing it pour down from the western heights, 「comes from heaven」 fits. As for never returning: false in the hydrological cycle, where evaporation, transport and rainfall constantly recycle the water, though true of any given parcel of flow.",
    },
    note: "「朝如青丝暮成雪」是全诗的加速器——英文用 at morning… by evening 保留了昼夜之间的人生压缩。",
    noteEn: "Morning to evening: a whole life compressed into one day.",
  },
  {
    slug: "denggao",
    title: "登高",
    titleEn: "Climbing High",
    author: "杜甫",
    authorEn: "Du Fu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "高中",
    kind: "诗",
    theme: "人生",
    themeEn: "Life",
    level: 3,
    lines: [
      { zh: "风急天高猿啸哀，渚清沙白鸟飞回。", en: "The wind is sharp, the sky high, the gibbons wail mournfully; the islet is clear, the sand white, and birds wheel home." },
      { zh: "无边落木萧萧下，不尽长江滚滚来。", en: "Leaves fall, boundless, rustling down; the long river rolls on, never ending." },
      { zh: "万里悲秋常作客，百年多病独登台。", en: "Ten thousand li of autumn sorrow, forever a guest; a hundred years, much illness, climbing the terrace alone." },
    ],
    keywords: [
      { w: "wail (v.)", zh: "（猿）啸" },
      { w: "wheel (v.)", zh: "（鸟）盘旋" },
      { w: "boundless (adj.)", zh: "无边" },
      { w: "roll on", zh: "滚滚（奔流）" },
    ],
    cross: {
      field: "气象",
      fieldEn: "Meteorology",
      title: "为什么登高时风特别急？",
      titleEn: "Why is the wind sharper up high?",
      body: "近地面风受树木、建筑与地形摩擦，风速被削弱；高度增加后摩擦减小，风速随高度按对数律或指数律增大（风廓线）。在山顶或高台上，风速常比地面高出数成到一倍。杜甫写此诗于夔州（今重庆奉节）白帝城外的高台，长江三峡入口处，峡谷效应还会进一步加速气流——「风急天高」是真实的体感记录。",
      bodyEn: "Surface wind is slowed by trees, buildings and terrain; with height, friction falls away and speed rises logarithmically or by a power law — the wind profile. On a summit or terrace, wind is commonly tens of percent to twice as fast as at ground level. Du Fu wrote this on a height outside Baidicheng at Kuizhou (modern Fengjie, Chongqing), at the mouth of the Three Gorges, where the canyon effect accelerates flow further. 「Wind sharp, sky high」 is a bodily fact.",
    },
    note: "八句全用对仗，是七律的极致——英文用成对的分句保留了这种对称（wind/sky, islet/sand）。",
    noteEn: "Every couplet is antithetical; the English mirrors it with paired clauses.",
  },
  {
    slug: "pipaxing",
    title: "琵琶行（节选）",
    titleEn: "Song of the Pipa (excerpt)",
    author: "白居易",
    authorEn: "Bai Juyi",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "高中",
    kind: "诗",
    theme: "人生",
    themeEn: "Life",
    level: 3,
    lines: [
      { zh: "大弦嘈嘈如急雨，小弦切切如私语。", en: "The thick strings clatter like sudden rain; the thin strings murmur like whispered talk." },
      { zh: "嘈嘈切切错杂弹，大珠小珠落玉盘。", en: "Clatter and murmur, struck in mingled fashion — big pearls and small pearls dropping on a jade plate." },
      { zh: "别有幽愁暗恨生，此时无声胜有声。", en: "There arises a hidden sorrow, a secret regret — and here, the silence is worth more than any sound." },
      { zh: "同是天涯沦落人，相逢何必曾相识。", en: "We are both people fallen to the world's far edge — what need to have met before, to meet now?" },
    ],
    keywords: [
      { w: "clatter (v.)", zh: "（弦声）嘈嘈" },
      { w: "murmur (v.)", zh: "（弦声）切切" },
      { w: "mingled (adj.)", zh: "错杂的" },
      { w: "fallen (adj.)", zh: "沦落的" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "大弦和小弦为什么声音不同？",
      titleEn: "Why do thick and thin strings sound different?",
      body: "弦的基频 f = (1/2L)·√(T/μ)，其中 μ 是线密度。粗弦（大弦）μ 大，频率低、音色浑厚；细弦（小弦）μ 小，频率高、音色清亮。琵琶四弦由粗到细，正对应「嘈嘈如急雨」与「切切如私语」。白居易还写对了演奏法：琵琶用拨子或指甲「弹」，声音颗粒感强，所以听起来像珠子落盘——这是拨弦乐器与拉弦乐器的根本区别。",
      bodyEn: "A string's fundamental is f = (1/2L)·√(T/μ), where μ is linear density. Thick strings have larger μ: lower pitch, darker timbre; thin strings, higher and brighter. The pipa's four strings run thick to thin, matching clatter and murmur. Bai Juyi also got the technique right: the pipa is plucked with a plectrum or nails, giving a granular attack — pearls on a jade plate — which distinguishes plucked from bowed instruments.",
    },
    note: "「无声胜有声」是全诗的音乐哲学——英文用 the silence is worth more than any sound 保留了休止的价值。",
    noteEn: "A philosophy of music: the rest is worth more than the note.",
  },
  {
    slug: "jinshe",
    title: "锦瑟",
    titleEn: "The Brocade Zither",
    author: "李商隐",
    authorEn: "Li Shangyin",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "高中",
    kind: "诗",
    theme: "人生",
    themeEn: "Life",
    level: 3,
    lines: [
      { zh: "锦瑟无端五十弦，一弦一柱思华年。", en: "The brocade zither, for no reason, has fifty strings; each string, each bridge, recalls a splendid year." },
      { zh: "庄生晓梦迷蝴蝶，望帝春心托杜鹃。", en: "Zhuangzi's dawn dream, bewildered by a butterfly; Emperor Wang's spring heart entrusted to the cuckoo." },
      { zh: "沧海月明珠有泪，蓝田日暖玉生烟。", en: "In the sea under the moon, the pearl has tears; at Lantian the sun is warm and jade gives off smoke." },
      { zh: "此情可待成追忆，只是当时已惘然。", en: "Could this feeling have waited to become a memory? Only that even then, it was already bewildering." },
    ],
    keywords: [
      { w: "for no reason", zh: "无端" },
      { w: "bridge (n.)", zh: "（琴）柱" },
      { w: "entrust (v.)", zh: "寄托" },
      { w: "bewildering (adj.)", zh: "惘然的" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "珍珠真的会「有泪」吗？",
      titleEn: "Do pearls really have tears?",
      body: "珍珠由珍珠贝外套膜分泌的珍珠质（主要成分为碳酸钙文石晶体与贝壳硬蛋白）层层包裹异物形成，本身不含水也不会流泪。但古人把珍珠的圆润光泽与泪滴联系是有道理的：珍珠表面由纳米级文石板片规则排列，产生薄膜干涉与镜面反射，形成柔和的晕彩与湿润感——视觉上确实像含着一滴水。李商隐用四个典故（庄周梦蝶、望帝啼鹃、鲛人泣珠、蓝田玉烟）叠成全诗，是中国诗里最难解的谜之一。",
      bodyEn: "A pearl is layers of nacre — aragonite tablets and conchiolin — secreted by a mollusc's mantle around an irritant; it holds no water and sheds no tears. Yet the association is apt: the surface is a regular array of nanoscale aragonite plates that produce thin-film interference and specular reflection, giving a soft, wet-looking lustre that does resemble a held tear. Li Shangyin stacks four allusions (Zhuangzi's butterfly, Emperor Wang's cuckoo, the mermaid's pearl, Lantian jade smoke) into one of poetry's great puzzles.",
    },
    note: "全诗几乎由典故组成，理解难度极高——英文保留典故本身（Zhuangzi, Emperor Wang），不做解释性翻译。",
    noteEn: "Almost pure allusion; the English keeps the names rather than explaining them.",
  },
  {
    slug: "yumeiren",
    title: "虞美人",
    titleEn: "The Beautiful Lady Yu",
    author: "李煜",
    authorEn: "Li Yu",
    dynasty: "五代",
    dynastyEn: "Five Dynasties",
    stage: "高中",
    kind: "词",
    theme: "家国",
    themeEn: "Nation",
    level: 3,
    lines: [
      { zh: "春花秋月何时了？往事知多少。", en: "Spring blossoms, autumn moon — when will they end? And how much of the past is known?" },
      { zh: "小楼昨夜又东风，故国不堪回首月明中。", en: "Last night, at my small tower, the east wind again — my lost kingdom, unbearable to look back on in the bright moonlight." },
      { zh: "问君能有几多愁？恰似一江春水向东流。", en: "You ask how much sorrow I can hold? It is like a river of spring water flowing east." },
    ],
    keywords: [
      { w: "unbearable (adj.)", zh: "不堪" },
      { w: "look back on", zh: "回首" },
      { w: "sorrow (n.)", zh: "愁" },
      { w: "is like", zh: "恰似" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "这首词的代价是什么？",
      titleEn: "What did this poem cost?",
      body: "李煜是南唐末代国君，975 年宋军攻破金陵，他被俘至汴京（今开封），封「违命侯」，实为囚徒。978 年七夕（他的生日），他写下了这首《虞美人》，据宋人记载，宋太宗闻「小楼昨夜又东风」及「一江春水向东流」后大怒，赐牵机药毒杀了他，时年四十二岁。亡国之君的词之所以动人，正因为其中的痛不是修辞。",
      bodyEn: "Li Yu was the last ruler of the Southern Tang. In 975 the Song took Jinling and he was carried to Bianjing (modern Kaifeng), titled Marquis who Defied Orders, in reality a prisoner. On Qixi in 978 — his birthday — he wrote this song; Song sources say Emperor Taizong, hearing 「the east wind again」 and 「a river of spring water flowing east」, flew into a rage and sent poison, killing him at forty-two. These lyrics move because the pain is not a figure of speech.",
    },
    note: "「恰似一江春水向东流」把愁变成了可度量的流体——英文用 like a river of spring water flowing east 保留了这个量纲转换。",
    noteEn: "Sorrow becomes measurable: a river of spring water.",
  },
  {
    slug: "chibi-huaigu",
    title: "念奴娇 · 赤壁怀古",
    titleEn: "Niannujiao · Red Cliff, Remembering the Past",
    author: "苏轼",
    authorEn: "Su Shi",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "高中",
    kind: "词",
    theme: "咏史",
    themeEn: "History",
    level: 3,
    lines: [
      { zh: "大江东去，浪淘尽，千古风流人物。", en: "The great river runs east; its waves have washed away every gallant figure of a thousand ages." },
      { zh: "乱石穿空，惊涛拍岸，卷起千堆雪。", en: "Jumbled rocks pierce the sky; startling breakers beat the shore, rolling up a thousand heaps of snow." },
      { zh: "遥想公瑾当年，小乔初嫁了，雄姿英发。", en: "I think far back to Gongjin in his day: Xiao Qiao just married, his bearing martial, his spirit blazing." },
      { zh: "人生如梦，一尊还酹江月。", en: "Life is like a dream — I pour a cup in libation to the river moon." },
    ],
    keywords: [
      { w: "wash away", zh: "淘尽" },
      { w: "pierce (v.)", zh: "穿空" },
      { w: "bearing (n.)", zh: "姿态、风度" },
      { w: "libation (n.)", zh: "（酹）洒酒祭奠" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "苏轼去的是真赤壁吗？",
      titleEn: "Did Su Shi visit the real Red Cliff?",
      body: "很可能不是。学界一般认为周瑜破曹的赤壁在今湖北赤壁市（原蒲圻）西北的长江南岸，而苏轼贬黄州时游览的是黄州（今黄冈）城外的赤鼻矶，两地相距约 100 公里。苏轼自己也存疑——他在《与范子丰书》中说「黄州少西山麓，斗入江中，石室如丹，传云曹公败所，所谓赤壁者，或曰非也」。但这不影响词的价值：他写的是怀古，不是考证。",
      bodyEn: "Probably not. Scholars place Zhou Yu's victory over Cao at Red Cliff on the south bank of the Yangtze north-west of modern Chibi city (old Puqi), while Su Shi, exiled to Huangzhou, visited the Chibi promontory outside Huangzhou (modern Huanggang) — some 100 km away. He knew the doubt himself, writing that local tradition called the reddish cliffs Cao's defeat 「though some say it is not」. It hardly matters: the poem is memory, not topography.",
    },
    note: "「人生如梦」不是消极，是看透后的释然——英文用 Life is like a dream 配 libation，完成祭奠的动作。",
    noteEn: "「Life is like a dream」 is not despair but release, sealed by the poured cup.",
  },
  {
    slug: "shengshengman",
    title: "声声慢",
    titleEn: "Shengshengman",
    author: "李清照",
    authorEn: "Li Qingzhao",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "高中",
    kind: "词",
    theme: "人生",
    themeEn: "Life",
    level: 3,
    lines: [
      { zh: "寻寻觅觅，冷冷清清，凄凄惨惨戚戚。", en: "Seeking and searching, cold and desolate, bleak and bitter and forlorn." },
      { zh: "梧桐更兼细雨，到黄昏、点点滴滴。", en: "And then the paulownia, with fine rain on top of it — until dusk, drop by drop." },
      { zh: "这次第，怎一个愁字了得！", en: "All of this together — how could one word, sorrow, ever suffice!" },
    ],
    keywords: [
      { w: "desolate (adj.)", zh: "冷清的" },
      { w: "forlorn (adj.)", zh: "凄惨的（戚戚）" },
      { w: "paulownia (n.)", zh: "梧桐" },
      { w: "suffice (v.)", zh: "了得、足够" },
    ],
    cross: {
      field: "语言",
      fieldEn: "Linguistics",
      title: "七组叠字为什么难译？",
      titleEn: "Why are the seven reduplications untranslatable?",
      body: "开篇十四字用了七组叠字（寻寻、觅觅、冷冷、清清、凄凄、惨惨、戚戚），中文叠字兼具三重效果：音节重复产生节奏、程度加深（比单字更甚）、以及口语的叹息感。英语缺少这种能产性极强的形容词重叠，只能靠并列形容词与头韵（seeking/searching, cold/desolate）部分弥补。这是汉语音乐性最难转移的一处。",
      bodyEn: "Fourteen characters, seven reduplications: the device triples its effect — rhythmic repetition, intensification, and a sighing colloquial quality. English has no comparably productive adjectival reduplication, so translation falls back on parallel adjectives and alliteration (seeking/searching, cold/desolate). It is among the hardest transfers of Chinese musicality.",
    },
    note: "全词几乎全是声音的堆叠——英文用并列形容词 + 头韵（bitter/bleak）尽量复现。",
    noteEn: "Built almost entirely of sound; English leans on alliteration to echo it.",
  },
  {
    slug: "yongyule-beiguting",
    title: "永遇乐 · 京口北固亭怀古",
    titleEn: "Yongyule · Remembering the Past at Beigu Pavilion in Jingkou",
    author: "辛弃疾",
    authorEn: "Xin Qiji",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "高中",
    kind: "词",
    theme: "家国",
    themeEn: "Nation",
    level: 3,
    lines: [
      { zh: "千古江山，英雄无觅孙仲谋处。", en: "A thousand ages of rivers and hills — nowhere to seek the hero Sun Zhongmou." },
      { zh: "想当年，金戈铁马，气吞万里如虎。", en: "Think of those years: metal spears, iron horses — a spirit that would swallow ten thousand li like a tiger." },
      { zh: "凭谁问：廉颇老矣，尚能饭否？", en: "Through whom can I ask: Lian Po is old — can he still eat his rice?" },
    ],
    keywords: [
      { w: "nowhere to seek", zh: "无处寻觅" },
      { w: "swallow (v.)", zh: "（气）吞" },
      { w: "iron horses", zh: "铁马（战马）" },
      { w: "old (adj.)", zh: "（廉颇）老矣" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "「廉颇老矣，尚能饭否」的典故",
      titleEn: "The allusion to Lian Po",
      body: "出自《史记·廉颇蔺相如列传》：赵国名将廉颇被免职后流亡魏国，赵王想复用他，派使者探视；廉颇当面吃下一斗米、十斤肉，披甲上马以示可用，但使者受奸臣郭开贿赂，回报说「廉将军虽老，尚善饭，然与臣坐，顷之三遗矢矣」（一会儿上了三次厕所）——赵王遂不再召他。辛弃疾写此词时六十六岁，朝廷起用他却又很快罢免，他问的正是：我还能用吗？",
      bodyEn: "From the Records of the Grand Historian: the Zhao general Lian Po, dismissed and exiled in Wei, was reconsidered by the king, who sent an envoy to inspect him. Lian Po ate a peck of rice and ten catties of meat and rode in armour to prove his fitness, but the envoy, bribed by the minister Guo Kai, reported that although the old general still ate well, he had excused himself three times during a short visit. The king never recalled him. Xin Qiji was sixty-six: appointed, then set aside — and asking exactly whether he was still usable.",
    },
    note: "全词连用五个典故（孙权、刘裕、刘义隆、拓跋焘、廉颇）——这是辛弃疾的「以文为词」，密度极高。",
    noteEn: "Five allusions in one lyric: Xin Qiji's prose-like density.",
  },
];
