import type { Poem } from "./types";

/** 高中阶段 · 第 3 批（先秦散文、史传、记、志） */
export const SENIOR_3: Poem[] = [
  {
    slug: "shizuo",
    title: "子路、曾皙、冉有、公西华侍坐",
    titleEn: "Zilu, Zengxi, Ranyou and Gongxihua Attend the Master",
    author: "《论语》",
    authorEn: "The Analects",
    dynasty: "先秦",
    dynastyEn: "Pre-Qin",
    stage: "高中",
    kind: "文言文",
    theme: "理想",
    themeEn: "Ideals",
    level: 3,
    lines: [
      { zh: "以吾一日长乎尔，毋吾以也。居则曰：『不吾知也！』如或知尔，则何以哉？", en: "Because I am a day older than you, do not defer to me. At home you say, 「No one knows me!」 Suppose someone did know you — then what would you do?" },
      { zh: "千乘之国，摄乎大国之间，加之以师旅，因之以饥馑。", en: "A state of a thousand chariots, squeezed between great powers, with armies sent against it and famine following in their wake." },
      { zh: "莫春者，春服既成，冠者五六人，童子六七人，浴乎沂，风乎舞雩，咏而归。", en: "In late spring, when the spring clothes are ready: five or six capped men, six or seven boys — bathing in the Yi, taking the air at the Rain Dance altar, and coming home singing." },
      { zh: "夫子喟然叹曰：吾与点也！", en: "The Master heaved a sigh and said: I am with Dian!" },
    ],
    fullText: "子路、曾皙、冉有、公西华侍坐。子曰：「以吾一日长乎尔，毋吾以也。居则曰：『不吾知也！』如或知尔，则何以哉？」子路率尔而对曰：「千乘之国，摄乎大国之间，加之以师旅，因之以饥馑；由也为之，比及三年，可使有勇，且知方也。」夫子哂之……「点！尔何如？」……曰：「莫春者，春服既成，冠者五六人，童子六七人，浴乎沂，风乎舞雩，咏而归。」夫子喟然叹曰：「吾与点也！」",
    keywords: [
      { w: "defer to", zh: "（以）因…而拘束" },
      { w: "squeeze (v.)", zh: "夹处（摄乎）" },
      { w: "famine (n.)", zh: "饥馑" },
      { w: "take the air", zh: "吹风（风乎）" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "孔子为什么赞同曾皙？",
      titleEn: "Why did Confucius side with Zengxi?",
      body: "子路要治军强国，冉有要富民，公西华要司礼，曾皙（名点）却描述了一场春游。孔子赞同后者，历来解释是：前三人的志向是「手段」，而曾皙描述的是「目的」——天下太平之后人们才能从容沐浴歌咏。这也是儒家「礼乐化成」的理想图景：治理的最高境界不是富国强兵，而是让日常生活本身从容自得。值得注意的是，曾皙的志向看似无用，实则最难。",
      bodyEn: "Zilu would make a state warlike, Ranyou prosperous, Gongxihua ceremonious — but Zengxi (Dian) describes a spring outing. The traditional reading: the first three name means, Zengxi names the end — only when the world is at peace can people bathe, take the air and sing. It is the Confucian vision of transformation through ritual and music, where good governance is not wealth or arms but unhurried daily life. Note that Zengxi's aim, though it looks useless, is the hardest of all.",
    },
    note: "四人四种志向，孔子只笑子路（「哂之」）——英文用 smiled at him 保留了那个不赞许的笑。",
    noteEn: "Four ambitions, one smile of disapproval.",
  },
  {
    slug: "paodingjieniu",
    title: "庖丁解牛（节选）",
    titleEn: "Cook Ding Carves an Ox (excerpt)",
    author: "《庄子》",
    authorEn: "Zhuangzi",
    dynasty: "先秦",
    dynastyEn: "Pre-Qin",
    stage: "高中",
    kind: "文言文",
    theme: "哲学",
    themeEn: "Philosophy",
    level: 3,
    lines: [
      { zh: "手之所触，肩之所倚，足之所履，膝之所踦，砉然向然，奏刀騞然，莫不中音。", en: "Where his hand touches, his shoulder leans, his foot treads, his knee presses — whish, whir, as the blade goes huok — nothing fails to be in tune." },
      { zh: "依乎天理，批大郤，导大窾，因其固然。", en: "He follows the natural grain, cleaves the great gaps, guides the blade through the great hollows, going by what is inherently so." },
      { zh: "彼节者有间，而刀刃者无厚；以无厚入有间，恢恢乎其于游刃必有余地矣。", en: "The joints have spaces, and the blade's edge has no thickness — put what has no thickness into what has space, and there is ample room for the blade to play." },
    ],
    fullText: "庖丁为文惠君解牛，手之所触，肩之所倚，足之所履，膝之所踦，砉然向然，奏刀騞然，莫不中音……文惠君曰：「嘻，善哉！技盖至此乎？」庖丁释刀对曰：「臣之所好者道也，进乎技矣。始臣之解牛之时，所见无非牛者。三年之后，未尝见全牛也。方今之时，臣以神遇而不以目视，官知止而神欲行。依乎天理，批大郤，导大窾，因其固然……彼节者有间，而刀刃者无厚；以无厚入有间，恢恢乎其于游刃必有余地矣，是以十九年而刀刃若新发于硎。」",
    keywords: [
      { w: "in tune", zh: "合于音律（中音）" },
      { w: "grain (n.)", zh: "纹理（天理）" },
      { w: "cleave (v.)", zh: "劈开（批）" },
      { w: "ample (adj.)", zh: "宽绰的（恢恢）" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "刀真的十九年不损吗？",
      titleEn: "Can a blade really stay sharp nineteen years?",
      body: "原理上成立。刀刃变钝主要是刃口与硬质材料（骨头、砧板）反复接触造成的塑性变形与微崩刃；庖丁的关键在于「以无厚入有间」——始终让刀刃在肌肉筋膜间隙中运动，避开骨骼，接触应力极低，磨损自然小。这在现代加工里叫「顺纹理切削」；外科医生解剖时也强调沿筋膜间隙分离，原理相同。庄子借刀讲养生：不要和环境硬碰硬。",
      bodyEn: "In principle, yes. Blades dull from plastic deformation and micro-chipping where the edge meets hard material — bone, board. Cook Ding's secret is to keep the edge in the gaps between fascia, avoiding bone, so contact stress is minimal and wear negligible. Modern machining calls this cutting along the grain; surgeons likewise separate along fascial planes. Zhuangzi turns it into advice on living: do not grind against the world.",
    },
    note: "「以神遇而不以目视」——从技艺到直觉的跨越。英文用 meet it with the spirit rather than the eye 保留了这层。",
    noteEn: "From technique to intuition: meeting it with the spirit, not the eye.",
  },
  {
    slug: "zhuzhiwutuiqinshi",
    title: "烛之武退秦师（节选）",
    titleEn: "Zhu Zhiwu Dissuades the Qin Army (excerpt)",
    author: "《左传》",
    authorEn: "Zuo Zhuan",
    dynasty: "先秦",
    dynastyEn: "Pre-Qin",
    stage: "高中",
    kind: "文言文",
    theme: "军事",
    themeEn: "Warfare",
    level: 3,
    lines: [
      { zh: "臣之壮也，犹不如人；今老矣，无能为也已。", en: "In my prime I was still no match for others; now that I am old, there is nothing I can do." },
      { zh: "若亡郑而有益于君，敢以烦执事。越国以鄙远，君知其难也。", en: "If destroying Zheng would benefit you, I would dare to trouble your officers with it. But to cross another state and make distant land your border — you know how hard that is." },
      { zh: "夫晋，何厌之有？既东封郑，又欲肆其西封。", en: "As for Jin — when has it ever been satisfied? Having made Zheng its eastern frontier, it will want to extend its western one." },
    ],
    fullText: "晋侯、秦伯围郑，以其无礼于晋，且贰于楚也……佚之狐言于郑伯曰：「国危矣！若使烛之武见秦君，师必退。」公从之。辞曰：「臣之壮也，犹不如人；今老矣，无能为也已。」公曰：「吾不能早用子，今急而求子，是寡人之过也……」……见秦伯曰：「秦、晋围郑，郑既知亡矣。若亡郑而有益于君，敢以烦执事。越国以鄙远，君知其难也。焉用亡郑以陪邻？邻之厚，君之薄也……夫晋，何厌之有？既东封郑，又欲肆其西封，若不阙秦，将焉取之？阙秦以利晋，唯君图之。」秦伯说，与郑人盟。",
    keywords: [
      { w: "in one's prime", zh: "壮年时" },
      { w: "no match for", zh: "比不上（不如人）" },
      { w: "satisfied (adj.)", zh: "满足的（何厌之有）" },
      { w: "benefit", zh: "得利（阙秦以利晋）" },
    ],
    cross: {
      field: "政治",
      fieldEn: "Politics",
      title: "烛之武的说服术有什么结构？",
      titleEn: "What is the structure of his persuasion?",
      body: "他完全没有谈郑国的立场，而是替秦国算账，三步递进：① 灭郑对秦无利——郑离秦远，中间隔着晋，秦得不到土地（「越国以鄙远」）；② 灭郑反而增强晋——邻之厚即君之薄；③ 晋国贪得无厌，扩张的下一刀必落在秦身上。这是标准的「利益重构」：把对方从「盟友共赢」的框架中拉出来，放进「零和博弈」的框架里重新计算。盟约当场破裂。",
      bodyEn: "He never pleads Zheng's case; he does Qin's arithmetic in three steps. (1) Destroying Zheng brings Qin nothing — Zheng is far, with Jin in between: 「cross another state to make distant land your border」. (2) It strengthens Jin: the neighbour's gain is your loss. (3) Jin is insatiable, and its next expansion falls on Qin. This is classic interest-reframing: pull the listener out of an alliance frame and make him recompute in a zero-sum one. The pact broke on the spot.",
    },
    note: "「何厌之有」是反问句式——英文用 when has it ever been satisfied 保留了反问的锋利。",
    noteEn: "A rhetorical question sharpened in English.",
  },
  {
    slug: "lianpo-linxiangru",
    title: "廉颇蔺相如列传（节选）",
    titleEn: "Biographies of Lian Po and Lin Xiangru (excerpt)",
    author: "司马迁",
    authorEn: "Sima Qian",
    dynasty: "西汉",
    dynastyEn: "Western Han",
    stage: "高中",
    kind: "文言文",
    theme: "人物",
    themeEn: "People",
    level: 3,
    lines: [
      { zh: "王必无人，臣愿奉璧往使。城入赵而璧留秦；城不入，臣请完璧归赵。", en: "If there is truly no one else, I am willing to take the jade and go. If the cities come to Zhao, the jade stays in Qin; if they do not, I beg to return the jade intact to Zhao." },
      { zh: "臣观大王无意偿赵王城邑，故臣复取璧。大王必欲急臣，臣头今与璧俱碎于柱矣！", en: "I see that your majesty has no intention of paying Zhao's cities, so I have taken the jade back. If you press me, my head and the jade shall both be dashed against this pillar!" },
      { zh: "吾所以为此者，以先国家之急而后私仇也。", en: "The reason I act so is that I put the state's emergency first and my private quarrel after." },
    ],
    fullText: "赵惠文王时，得楚和氏璧。秦昭王闻之，使人遗赵王书，愿以十五城请易璧……相如曰：「王必无人，臣愿奉璧往使。城入赵而璧留秦；城不入，臣请完璧归赵。」……相如视秦王无意偿赵城，乃前曰：「璧有瑕，请指示王。」王授璧，相如因持璧却立，倚柱，怒发上冲冠……曰：「大王必欲急臣，臣头今与璧俱碎于柱矣！」……相如曰：「……吾所以为此者，以先国家之急而后私仇也。」廉颇闻之，肉袒负荆，因宾客至蔺相如门谢罪。",
    keywords: [
      { w: "intact (adj.)", zh: "完整的（完璧）" },
      { w: "dash (v.)", zh: "撞碎" },
      { w: "pillar (n.)", zh: "柱" },
      { w: "emergency (n.)", zh: "急难（之急）" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "和氏璧后来成了什么？",
      titleEn: "What became of the He shi jade?",
      body: "据《史记》记载，和氏璧最终落入秦始皇之手，被制成「传国玉玺」，由李斯篆书「受命于天，既寿永昌」八字，作为皇权正统的象征，此后在历代王朝间传承，至五代后唐末帝李从珂自焚时失踪（936 年）。所以「完璧归赵」里的璧，是后来中国两千年帝位象征的那块玉——当然，玉料的真实性在流传过程中已无法考证。",
      bodyEn: "According to the Records of the Grand Historian, the jade reached the First Emperor, who had it carved into the imperial seal with the eight characters 「Having received the mandate of heaven, may he long live and prosper」 by Li Si's seal script — the emblem of legitimate sovereignty, passed down through dynasties until it vanished when Li Congke, last emperor of the Later Tang, burned himself to death in 936. So the jade of 「returned intact」 became the seal of empire for two millennia, though its material identity through transmission cannot be verified.",
    },
    note: "「完璧归赵」「负荆请罪」两个成语都出自此篇——英文用 return the jade intact 与 bare his back and carry brambles 保留了动作。",
    noteEn: "Two idioms from one chapter: the jade returned intact, and the brambles carried on a bare back.",
  },
  {
    slug: "suwuzhuan",
    title: "苏武传（节选）",
    titleEn: "Biography of Su Wu (excerpt)",
    author: "班固",
    authorEn: "Ban Gu",
    dynasty: "东汉",
    dynastyEn: "Eastern Han",
    stage: "高中",
    kind: "文言文",
    theme: "人物",
    themeEn: "People",
    level: 3,
    lines: [
      { zh: "屈节辱命，虽生，何面目以归汉！", en: "To bend my integrity and disgrace my commission — though I live, with what face could I return to Han!" },
      { zh: "乃幽武置大窖中，绝不饮食。天雨雪，武卧啮雪，与旃毛并咽之，数日不死。", en: "They shut Su Wu in a great pit and gave him no food or drink. When it snowed, he lay and chewed the snow, swallowing it with the felt's wool — for days he did not die." },
      { zh: "杖汉节牧羊，卧起操持，节旄尽落。", en: "He tended sheep with the Han envoy's staff in hand, holding it lying down and rising; the yak-tail plumes of the staff all fell away." },
    ],
    fullText: "武字子卿，少以父任，兄弟并为郎……武帝嘉其义，乃遣武以中郎将使持节送匈奴使留在汉者……单于使卫律召武受辞。武谓惠等：「屈节辱命，虽生，何面目以归汉！」引佩刀自刺……乃幽武置大窖中，绝不饮食。天雨雪，武卧啮雪，与旃毛并咽之，数日不死。匈奴以为神，乃徙武北海上无人处，使牧羝……武既至海上，廪食不至，掘野鼠去草实而食之。杖汉节牧羊，卧起操持，节旄尽落……武留匈奴凡十九岁，始以强壮出，及还，须发尽白。",
    keywords: [
      { w: "bend (v.)", zh: "屈（节）" },
      { w: "disgrace (v.)", zh: "辱（使命）" },
      { w: "chew (v.)", zh: "咬、嚼（啮）" },
      { w: "felt (n.)", zh: "毡（旃）" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "人能靠雪和毡毛活下来吗？",
      titleEn: "Can a man survive on snow and felt?",
      body: "短期可以，但很危险。雪提供水分（融化后即可饮用），但融化雪要消耗体热；毛毡的羊毛主要成分是角蛋白，人体无法消化，只能提供极少的能量，反而增加肠道负担。真正的生存依靠是体内的脂肪与肌肉储备——健康成年人在有水的情况下可依靠自身储备存活数周。苏武能撑下来，靠的是有水（雪）、低温降低代谢消耗，以及极强的意志。",
      bodyEn: "Briefly, and dangerously. Snow supplies water once melted, though melting it costs body heat; felt is largely keratin, indigestible, yielding almost no energy while burdening the gut. Real survival rests on internal fat and muscle reserves — a healthy adult with water can last weeks on those alone. Su Wu survived because he had water, because cold lowered metabolic demand, and because he refused to die.",
    },
    note: "「节旄尽落」是最有力的细节——旌节上的旄牛尾都掉光了，人还握着。英文用 all fell away 保留了这个意象。",
    noteEn: "The strongest detail: the plumes are gone, the staff is still held.",
  },
  {
    slug: "quyuanliezhuan",
    title: "屈原列传（节选）",
    titleEn: "Biography of Qu Yuan (excerpt)",
    author: "司马迁",
    authorEn: "Sima Qian",
    dynasty: "西汉",
    dynastyEn: "Western Han",
    stage: "高中",
    kind: "文言文",
    theme: "人物",
    themeEn: "People",
    level: 3,
    lines: [
      { zh: "博闻强志，明于治乱，娴于辞令。", en: "Wide in learning and strong in memory, clear about order and disorder, skilled in the language of diplomacy." },
      { zh: "信而见疑，忠而被谤，能无怨乎？", en: "Trustworthy, yet suspected; loyal, yet slandered — could he be without resentment?" },
      { zh: "其志洁，故其称物芳。其行廉，故死而不容。", en: "His aims were pure, and so the things he names are fragrant. His conduct was blameless, and so he would not be tolerated even in death." },
      { zh: "推此志也，虽与日月争光可也。", en: "Extrapolating from such a purpose — it may rival the sun and moon in brightness." },
    ],
    fullText: "屈原者，名平，楚之同姓也。为楚怀王左徒。博闻强志，明于治乱，娴于辞令。入则与王图议国事，以出号令；出则接遇宾客，应对诸侯。王甚任之……屈平疾王听之不聪也，谗谄之蔽明也，邪曲之害公也，方正之不容也，故忧愁幽思而作《离骚》……信而见疑，忠而被谤，能无怨乎？……其志洁，故其称物芳。其行廉，故死而不容。自疏濯淖污泥之中，蝉蜕于浊秽，以浮游尘埃之外，不获世之滋垢，皭然泥而不滓者也。推此志也，虽与日月争光可也。",
    keywords: [
      { w: "slander (v.)", zh: "诽谤（被谤）" },
      { w: "resentment (n.)", zh: "怨恨" },
      { w: "blameless (adj.)", zh: "清廉的（行廉）" },
      { w: "rival (v.)", zh: "与…媲美（争光）" },
    ],
    cross: {
      field: "语言",
      fieldEn: "Linguistics",
      title: "「称物芳」是什么意思？",
      titleEn: "What does 「the things he names are fragrant」 mean?",
      body: "这是司马迁对《离骚》修辞体系的概括：屈原以香草美人比喻美德与贤才（江离、辟芷、秋兰、木兰、宿莽、杜衡等数十种植物），以恶草比喻奸佞。这种系统性的象征在当时是首创，文学史上称为「香草美人」传统。认知语言学的解释是：嗅觉与道德评价在许多语言中都存在隐喻映射（「臭名」「芬芳的品德」），屈原做的是把零散的映射变成完整的体系。",
      bodyEn: "Sima Qian is summarising the rhetoric of Encountering Sorrow: Qu Yuan uses fragrant plants and beautiful women to figure virtue and talent — jiangli, angelica, autumn orchid, magnolia, winter grass, asarum, dozens of species — and noxious weeds for flatterers. Such systematic symbolism was new; literary history calls it the 「fragrant plants and fair lady」 tradition. Cognitive linguistics notes that smell maps onto moral judgement in many languages (a foul name, a fragrant virtue); Qu Yuan's achievement was turning scattered mappings into a complete system.",
    },
    note: "「虽与日月争光可也」是司马迁对屈原的最高评价——英文用 may rival the sun and moon 保留了亮度隐喻。",
    noteEn: "The highest praise: rival the sun and moon.",
  },
  {
    slug: "baorenanshu",
    title: "报任安书（节选）",
    titleEn: "Letter in Reply to Ren An (excerpt)",
    author: "司马迁",
    authorEn: "Sima Qian",
    dynasty: "西汉",
    dynastyEn: "Western Han",
    stage: "高中",
    kind: "文言文",
    theme: "人生",
    themeEn: "Life",
    level: 3,
    lines: [
      { zh: "人固有一死，死有重于泰山，或轻于鸿毛，用之所趋异也。", en: "All men must die. A death may be weightier than Mount Tai, or lighter than a goose feather — all depending on what it is directed toward." },
      { zh: "所以隐忍苟活，幽于粪土之中而不辞者，恨私心有所不尽，鄙陋没世，而文采不表于后世也。", en: "The reason I bear disgrace and cling to life, shut in a foul place without refusing it, is that I grieve my heart's purpose is unfulfilled, and despise the thought of my writings never being shown to later ages." },
      { zh: "究天人之际，通古今之变，成一家之言。", en: "To examine the boundary between heaven and man, to penetrate the changes of past and present, and to make a teaching of one's own." },
    ],
    fullText: "古者富贵而名摩灭，不可胜记，唯倜傥非常之人称焉……人固有一死，死有重于泰山，或轻于鸿毛，用之所趋异也……所以隐忍苟活，幽于粪土之中而不辞者，恨私心有所不尽，鄙陋没世，而文采不表于后世也……亦欲以究天人之际，通古今之变，成一家之言。草创未就，会遭此祸，惜其不成，是以就极刑而无愠色。仆诚已著此书，藏之名山，传之其人，通邑大都，则仆偿前辱之责，虽万被戮，岂有悔哉！",
    keywords: [
      { w: "weightier (adj.)", zh: "更重的" },
      { w: "a goose feather", zh: "鸿毛" },
      { w: "cling to life", zh: "苟活" },
      { w: "penetrate (v.)", zh: "通晓（通）" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "他为什么宁受腐刑？",
      titleEn: "Why did he accept castration rather than death?",
      body: "公元前 99 年，司马迁为投降匈奴的李陵辩护，触怒汉武帝，被判死刑。按汉律，死刑可以「赎」或以腐刑（宫刑）替代。他家贫无法赎罪，若死则《史记》未成；受刑则是极大的耻辱（「诟莫大于宫刑」）。他选择了后者——理由正是文中这句「恨私心有所不尽」。这是中国史学史上最重要的一次抉择：《史记》得以完成，代价是他个人的名节。",
      bodyEn: "In 99 BC Sima Qian defended Li Ling, who had surrendered to the Xiongnu, and incurred Emperor Wu's wrath: a death sentence. Han law allowed commutation by payment or by castration. He was too poor to pay, and dying would leave the Records unfinished; the operation meant supreme disgrace (he calls it the worst of shames). He chose the operation for exactly the reason he gives: a purpose unfulfilled. It is the most consequential decision in Chinese historiography — the price of the Records was his own honour.",
    },
    note: "「重于泰山，轻于鸿毛」已成成语——英文用 weightier than Mount Tai, lighter than a goose feather 保留了重量的两极。",
    noteEn: "An idiom of two weights: a mountain, a feather.",
  },
  {
    slug: "youbaochanshanji",
    title: "游褒禅山记（节选）",
    titleEn: "An Excursion to Baochan Mountain (excerpt)",
    author: "王安石",
    authorEn: "Wang Anshi",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "高中",
    kind: "文言文",
    theme: "哲学",
    themeEn: "Philosophy",
    level: 3,
    lines: [
      { zh: "世之奇伟、瑰怪、非常之观，常在于险远，而人之所罕至焉。", en: "The world's rare, magnificent, marvellous and extraordinary sights are always found in perilous and distant places, which few men reach." },
      { zh: "故非有志者不能至也……然力不足者，亦不能至也……至于幽暗昏惑而无物以相之，亦不能至也。", en: "Therefore none but the resolved can arrive… yet those without strength also cannot arrive… and when all is dark and confusing with nothing to guide one, one cannot arrive either." },
      { zh: "尽吾志也而不能至者，可以无悔矣，其孰能讥之乎？", en: "If I have exhausted my purpose and yet failed to arrive, I may have no regret — and who could mock me?" },
    ],
    fullText: "褒禅山亦谓之华山……其下平旷，有泉侧出，而记游者甚众，所谓前洞也。由山以上五六里，有穴窈然，入之甚寒，问其深，则其好游者不能穷也，谓之后洞……余与四人拥火以入，入之愈深，其进愈难，而其见愈奇……既其出，则或咎其欲出者，而余亦悔其随之而不得极夫游之乐也……世之奇伟、瑰怪、非常之观，常在于险远，而人之所罕至焉，故非有志者不能至也……尽吾志也而不能至者，可以无悔矣。",
    keywords: [
      { w: "rare (adj.)", zh: "奇伟的" },
      { w: "perilous (adj.)", zh: "险远的" },
      { w: "resolved (adj.)", zh: "有志的" },
      { w: "exhaust (v.)", zh: "竭尽（尽吾志）" },
    ],
    cross: {
      field: "逻辑",
      fieldEn: "Logic",
      title: "王安石给出了成功的三个条件",
      titleEn: "The three conditions for reaching the goal",
      body: "他提出「志、力、物」三要素：有志（主观意志）、有力（客观能力）、有物以相之（外部条件/工具），三者缺一不可，但权重不同——「志」是第一位的，因为「尽吾志也而不能至者，可以无悔」。这在方法论上是很清晰的必要条件分析：把成功拆成可分别检验的三个变量，然后明确责任归属（失败时先看志向是否已尽）。",
      bodyEn: "He names three factors: purpose (zhi), strength (li), and external aids (wu). All three are necessary, but not equal — purpose comes first, since one who has exhausted purpose without arriving need feel no regret. Methodologically it is a clean analysis of necessary conditions: success decomposed into three separately checkable variables, with responsibility assigned (when failing, first ask whether purpose was fully spent).",
    },
    note: "全文从一次没走到头的洞中游览，推出治学与行事的方法——英文用 none but the resolved can arrive 保留了层层递进。",
    noteEn: "An unfinished cave visit becomes a method for study and action.",
  },
  {
    slug: "xiangjixuanzhi",
    title: "项脊轩志（节选）",
    titleEn: "The Xiangji Studio (excerpt)",
    author: "归有光",
    authorEn: "Gui Youguang",
    dynasty: "明",
    dynastyEn: "Ming",
    stage: "高中",
    kind: "文言文",
    theme: "人生",
    themeEn: "Life",
    level: 3,
    lines: [
      { zh: "百年老屋，尘泥渗漉，雨泽下注；每移案，顾视无可置者。", en: "A hundred-year-old room: dust and mud seep through, rain drips down inside; whenever I moved my desk, I looked round and found nowhere to put it." },
      { zh: "三五之夜，明月半墙，桂影斑驳，风移影动，珊珊可爱。", en: "On the night of the fifteenth, the bright moon fills half the wall, the cassia's shadows are dappled; as the wind moves, the shadows stir — graceful and lovely." },
      { zh: "庭有枇杷树，吾妻死之年所手植也，今已亭亭如盖矣。", en: "In the courtyard stands a loquat tree, planted by my wife's own hands in the year she died; now it stands tall, its crown like a canopy." },
    ],
    fullText: "项脊轩，旧南阁子也。室仅方丈，可容一人居。百年老屋，尘泥渗漉，雨泽下注……余稍为修葺，使不上漏。前辟四窗，垣墙周庭，以当南日，日影反照，室始洞然。又杂植兰桂竹木于庭，旧时栏楯，亦遂增胜。借书满架，偃仰啸歌，冥然兀坐，万籁有声；而庭阶寂寂，小鸟时来啄食，人至不去。三五之夜，明月半墙，桂影斑驳，风移影动，珊珊可爱……庭有枇杷树，吾妻死之年所手植也，今已亭亭如盖矣。",
    keywords: [
      { w: "seep (v.)", zh: "渗漏" },
      { w: "dappled (adj.)", zh: "斑驳的" },
      { w: "graceful (adj.)", zh: "珊珊（美好的样子）" },
      { w: "canopy (n.)", zh: "（如）盖" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "枇杷树能长多快？",
      titleEn: "How fast does a loquat grow?",
      body: "枇杷（Eriobotrya japonica）是常绿小乔木，实生苗生长较慢，前几年每年增高约 30—50 厘米，十年左右可长到 3—5 米高并开始大量结果，成年树冠幅可达 4—6 米，确实「亭亭如盖」。它的特殊之处还在花期：秋冬（10—12 月）开花，次年春夏结果，是少见的「秋萌冬花春实」果树。归有光写这棵树时距妻子去世已多年——树的生长成了时间的刻度。",
      bodyEn: "The loquat is a small evergreen tree. Seedlings grow slowly, perhaps 30–50 cm a year at first, reaching 3–5 m and fruiting well by about ten years, with a mature crown 4–6 m across — genuinely 「tall as a canopy」. It is unusual in flowering: bloom comes in autumn to early winter (October–December) and fruit the following spring or summer, a rare 「autumn bud, winter flower, spring fruit」 cycle. Gui Youguang wrote years after his wife's death; the tree measures the interval.",
    },
    note: "全文没有任何抒情词，最后一句只写树——英文用 planted by my wife's own hands in the year she died 让事实自己说话。",
    noteEn: "No emotion anywhere except in a fact: the tree she planted the year she died.",
  },
  {
    slug: "shizhongshanji",
    title: "石钟山记（节选）",
    titleEn: "On Stone Bell Mountain (excerpt)",
    author: "苏轼",
    authorEn: "Su Shi",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "高中",
    kind: "文言文",
    theme: "哲学",
    themeEn: "Philosophy",
    level: 3,
    lines: [
      { zh: "事不目见耳闻，而臆断其有无，可乎？", en: "To decide by guess whether a thing exists, without seeing it with one's eyes or hearing it with one's ears — is that permissible?" },
      { zh: "郦元之所见闻，殆与余同，而言之不详。", en: "What Li Daoyuan saw and heard was much the same as I, yet he did not describe it in detail." },
      { zh: "士大夫终不肯以小舟夜泊绝壁之下，故莫能知；而渔工水师虽知而不能言。", en: "Gentlemen would never moor a small boat at night beneath sheer cliffs, and so could not know; while fishermen and boatmen knew, but could not put it into words." },
    ],
    fullText: "《水经》云：「彭蠡之口有石钟山焉。」郦元以为下临深潭，微风鼓浪，水石相搏，声如洪钟……至唐李渤始访其遗踪……然是说也，余尤疑之……余方心动欲还，而大声发于水上，噌吰如钟鼓不绝……徐而察之，则山下皆石穴罅，不知其浅深，微波入焉，涵澹澎湃而为此也……事不目见耳闻，而臆断其有无，可乎？郦元之所见闻，殆与余同，而言之不详；士大夫终不肯以小舟夜泊绝壁之下，故莫能知；而渔工水师虽知而不能言。此世所以不传也。",
    keywords: [
      { w: "by guess", zh: "凭臆测（臆断）" },
      { w: "moor (v.)", zh: "停泊" },
      { w: "sheer cliffs", zh: "绝壁" },
      { w: "put into words", zh: "（不能）言" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "石钟山为什么会发声？",
      titleEn: "Why does Stone Bell Mountain ring?",
      body: "苏轼的实地考察给出了答案：山下有许多石洞与裂缝（喀斯特溶蚀形成的石灰岩孔洞），波浪涌入后在其中激荡，形成空腔共鸣——原理类似敲击编钟或吹瓶口：空腔的体积与开口决定共鸣频率，孔穴大小不一，所以声音高低错落「如钟鼓不绝」。他同时否定了李渤「扣石发声」的说法（单纯敲击石头不会持续作响）。这是中国科学史上著名的实证案例。",
      bodyEn: "Su Shi's field trip supplied the answer: the hill is riddled with caves and fissures in limestone (karst solution cavities), and waves surging into them produce cavity resonance — the principle of a struck bell or a bottle blown across: cavity volume and mouth size set the resonant frequency, and cavities of different sizes give the varied tones that ring 「like bells and drums without cease」. He also rejected Li Bo's claim that striking the rock made the sound (a single tap does not sustain). A celebrated case of empirical inquiry in Chinese science.",
    },
    note: "「事不目见耳闻而臆断其有无，可乎」——这是中国科学史上最早的方法论宣言之一。",
    noteEn: "One of the earliest methodological statements in Chinese science: do not guess, go and see.",
  },
  {
    slug: "dengtaishanji",
    title: "登泰山记（节选）",
    titleEn: "Climbing Mount Tai (excerpt)",
    author: "姚鼐",
    authorEn: "Yao Nai",
    dynasty: "清",
    dynastyEn: "Qing",
    stage: "高中",
    kind: "文言文",
    theme: "山水",
    themeEn: "Landscape",
    level: 3,
    lines: [
      { zh: "道中迷雾冰滑，磴几不可登。及既上，苍山负雪，明烛天南。", en: "On the way, dense fog and slippery ice made the steps almost unclimbable. Once up: the dark hills carry snow, lighting the southern sky like a candle." },
      { zh: "望晚日照城郭，汶水、徂徕如画，而半山居雾若带然。", en: "Watching at dusk, the sun lights city and wall; the Wen river and Culai are like a painting, while the mist that rests halfway up the mountain is like a girdle." },
      { zh: "日上，正赤如丹，下有红光动摇承之。", en: "The sun rises, sheer vermilion like cinnabar, and beneath it a red light stirs and bears it up." },
    ],
    fullText: "泰山之阳，汶水西流；其阴，济水东流……余以乾隆三十九年十二月，自京师乘风雪，历齐河、长清，穿泰山西北谷，越长城之限，至于泰安……道中迷雾冰滑，磴几不可登。及既上，苍山负雪，明烛天南。望晚日照城郭，汶水、徂徕如画，而半山居雾若带然……大风扬积雪击面。亭东自足下皆云漫。稍见云中白若樗蒱数十立者，山也。极天云一线异色，须臾成五采。日上，正赤如丹，下有红光动摇承之，或曰，此东海也。",
    keywords: [
      { w: "slippery (adj.)", zh: "（冰）滑" },
      { w: "step (n.)", zh: "石磴" },
      { w: "vermilion (n.)", zh: "朱砂红" },
      { w: "girdle (n.)", zh: "（雾）带" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "日出为什么是「正赤如丹」？",
      titleEn: "Why is the rising sun pure vermilion?",
      body: "原理是瑞利散射：阳光穿过大气时，短波的蓝紫光被空气分子强烈散射掉，剩下长波的红橙光；日出时阳光要斜穿的大气路径最长（可达正午的数十倍），蓝光几乎被散射殆尽，只剩最纯的红。此外日出时太阳在地平线附近，还会被大气折射略微抬升（约 0.5°），所以我们看到的日出比几何时刻略早。姚鼐写「下有红光动摇承之」，那是海面或云海反射的阳光。",
      bodyEn: "Rayleigh scattering: short blue and violet wavelengths are scattered out by air molecules, leaving long red and orange. At sunrise the path through atmosphere is longest — tens of times that at noon — so the blue is almost entirely removed and the red is purest. Refraction also lifts the sun near the horizon by about half a degree, so we see it slightly before it geometrically rises. Yao Nai's 「red light stirring beneath that bears it up」 is sunlight reflected from the sea or a sea of cloud.",
    },
    note: "全文几乎没有形容词堆砌，只记路线、里程与天象——英文用简洁的过去时叙事保留了桐城派的「雅洁」。",
    noteEn: "No ornament: route, distance, weather. The Tongcheng school's austerity survives in plain past tense.",
  },
];
