import type { Poem } from "./types";

/** 高中阶段 · 第 4 批（盛唐名篇、宋词绝唱、庄子） */
export const SENIOR_4: Poem[] = [
  {
    slug: "shuxiang",
    title: "蜀相",
    titleEn: "The Prime Minister of Shu",
    author: "杜甫",
    authorEn: "Du Fu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "高中",
    kind: "诗",
    theme: "怀古",
    themeEn: "Admiration",
    level: 3,
    lines: [
      { zh: "丞相祠堂何处寻？锦官城外柏森森。", en: "Where to seek the Chancellor's shrine? Outside Brocade City, cypress-dark and deep." },
      { zh: "映阶碧草自春色，隔叶黄鹂空好音。", en: "Green grass across the steps, spring there for no one; orioles beyond the leaves, singing to no one." },
      { zh: "三顾频烦天下计，两朝开济老臣心。", en: "Three visits, world-shaping plans received; two reigns of service, an old minister's heart." },
      { zh: "出师未捷身先死，长使英雄泪满襟。", en: "The northern campaign unwon, he died first — and ever since, heroes wet their sleeves with tears." },
    ],
    keywords: [
      { w: "shrine", zh: "祠堂" },
      { w: "cypress", zh: "柏树" },
      { w: "campaign", zh: "出师" },
    ],
    note: "「自」「空」二字把满园春色关进了无人领受里——怀古怀的其实是「来不及」。",
    noteEn: "'For no one' and 'to no one' lock the spring inside an ungreeted courtyard — what he mourns is running out of time.",
  },
  {
    slug: "shanjuqiuming",
    title: "山居秋暝",
    titleEn: "Autumn Evening in the Mountains",
    author: "王维",
    authorEn: "Wang Wei",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "高中",
    kind: "诗",
    theme: "山水",
    themeEn: "Landscape",
    level: 3,
    lines: [
      { zh: "空山新雨后，天气晚来秋。", en: "The empty mountain after fresh rain; the air carries autumn in the evening." },
      { zh: "明月松间照，清泉石上流。", en: "A bright moon lights through the pines; a clear spring flows over the stones." },
      { zh: "竹喧归浣女，莲动下渔舟。", en: "Rustle in the bamboo — washing girls coming home; stir in the lotus — a fishing boat drifting down." },
      { zh: "随意春芳歇，王孙自可留。", en: "Let spring's blooms fade when they will; the prince himself could wish to stay." },
    ],
    keywords: [
      { w: "rustle", zh: "喧响" },
      { w: "drift down", zh: "顺流而下" },
      { w: "fade", zh: "凋歇" },
    ],
    note: "竹喧、莲动都是先有声音动静，人影最后才出现——王维的诗是眼睛有半拍的延迟。",
    noteEn: "Rustle first, figures last: in Wang Wei's poems the eye runs half a beat behind the ear.",
  },
  {
    slug: "chunjiang",
    title: "春江花月夜（节选）",
    titleEn: "A River of Flowers under the Spring Moon (excerpt)",
    author: "张若虚",
    authorEn: "Zhang Ruoxu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "高中",
    kind: "诗",
    theme: "哲思",
    themeEn: "Cosmic",
    level: 3,
    lines: [
      { zh: "春江潮水连海平，海上明月共潮生。", en: "The spring river's tide runs level with the sea; over the sea the bright moon rises with the tide." },
      { zh: "滟滟随波千万里，何处春江无月明。", en: "Shimmering along the waves ten thousand li — where on the spring river is there no moonlight?" },
      { zh: "江畔何人初见月？江月何年初照人？", en: "Who by the riverside first saw the moon? In what year did the river moon first shine on men?" },
      { zh: "人生代代无穷已，江月年年望相似。", en: "Life passes, generation after generation without end; the river moon looks the same, year after year." },
    ],
    keywords: [
      { w: "tide", zh: "潮水" },
      { w: "shimmer", zh: "滟滟（波光）" },
      { w: "generation", zh: "代" },
    ],
    cross: {
      field: "天文",
      fieldEn: "Astronomy",
      title: "明月为什么「共潮生」？",
      titleEn: "Why does the moon rise with the tide?",
      body: "潮汐由月球引力引起：月球对地球朝向面与背向面的引力差把海水「拉」成两处隆起，一天两次涨落。「共潮生」是准确的观察——满月（望）时日月引潮力同向，潮最大，月出与潮涨几乎同时；张若虚看到的正是天文与海洋的一次同步。",
      bodyEn: "Tides arise from the Moon's differential pull on the oceans, two bulges a day. 'Rising with the tide' is precise: at full moon the Sun's and Moon's tidal forces align for spring tides, and moonrise coincides with the tide's crest. Zhang Ruoxu caught an astronomical and oceanic synchrony in one word.",
    },
    note: "一个「共」字把江、月、潮写成了同一件事；问月无人答，因为答案在每个人身上。",
    noteEn: "One word — 'with' — makes river, moon and tide a single event. No one answers his question, because everyone is the answer.",
  },
  {
    slug: "dingfengbo",
    title: "定风波·莫听穿林打叶声",
    titleEn: "Dingfengbo: Do Not Hear the Rain",
    author: "苏轼",
    authorEn: "Su Shi",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "高中",
    kind: "词",
    theme: "人生态度",
    themeEn: "Attitude",
    level: 3,
    lines: [
      { zh: "莫听穿林打叶声，何妨吟啸且徐行。", en: "Do not hear the rain that strikes through the woods and beats the leaves — why not chant and whistle and walk on slow?" },
      { zh: "竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。", en: "A bamboo staff, straw sandals, lighter than a horse. Who is afraid? In straw cloak through misty rain, let the whole life be so." },
      { zh: "料峭春风吹酒醒，微冷，山头斜照却相迎。", en: "A chill spring wind sobers me; slightly cold — but the slanting sun on the hilltop comes out to meet me." },
      { zh: "回首向来萧瑟处，归去，也无风雨也无晴。", en: "I look back at the bleak place I have been. Going home: no storm there, and no sunshine either." },
    ],
    keywords: [
      { w: "straw sandals", zh: "芒鞋" },
      { w: "sober (v.)", zh: "（酒）醒" },
      { w: "bleak", zh: "萧瑟" },
    ],
    note: "最后「也无风雨也无晴」把天气和人生一起放平——这不是没淋过雨的人能写的话。",
    noteEn: "'No storm, and no sunshine either' lays weather and life flat in one line — words only a man who has been rained on could write.",
  },
  {
    slug: "jiangchengzi-jimeng",
    title: "江城子·乙卯正月二十日夜记梦",
    titleEn: "Jiangchengzi: A Dream Recorded",
    author: "苏轼",
    authorEn: "Su Shi",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "高中",
    kind: "词",
    theme: "悼亡",
    themeEn: "Mourning",
    level: 3,
    lines: [
      { zh: "十年生死两茫茫，不思量，自难忘。", en: "Ten years — the dead and the living, boundless between them. Not thinking of it, yet never forgetting." },
      { zh: "千里孤坟，无处话凄凉。", en: "A lone grave a thousand li away; nowhere to speak my desolation." },
      { zh: "纵使相逢应不识，尘满面，鬓如霜。", en: "Even if we met you would not know me: dust all over my face, temples like frost." },
      { zh: "夜来幽梦忽还乡，小轩窗，正梳妆。", en: "Last night in a dark dream I was suddenly home — by the little window, combing your hair." },
      { zh: "相顾无言，惟有泪千行。料得年年肠断处，明月夜，短松冈。", en: "We looked at each other and said nothing; only a thousand streams of tears. I know where the heart breaks, year upon year: moonlit night, the ridge of short pines." },
    ],
    keywords: [
      { w: "boundless", zh: "茫茫" },
      { w: "temples", zh: "鬓角" },
      { w: "the heart breaks", zh: "肠断（心碎处）" },
    ],
    note: "梦里最清楚的不是大事，是「正梳妆」——思念的细节从来都是日常。",
    noteEn: "The clearest thing in the dream is not some great event but 'combing her hair' — the details of longing are always daily ones.",
  },
  {
    slug: "queqiaoxian",
    title: "鹊桥仙·纤云弄巧",
    titleEn: "Queqiaoxian: Clouds Weaving Skillfully",
    author: "秦观",
    authorEn: "Qin Guan",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "高中",
    kind: "词",
    theme: "爱情",
    themeEn: "Love",
    level: 3,
    lines: [
      { zh: "纤云弄巧，飞星传恨，银汉迢迢暗度。", en: "Fine clouds weave their skill; flying stars carry the ache; across the boundless Milky Way they steal to meet." },
      { zh: "金风玉露一相逢，便胜却人间无数。", en: "One meeting amid golden wind and jade dew outdoes countless meetings in the world of men." },
      { zh: "柔情似水，佳期如梦，忍顾鹊桥归路。", en: "Tenderness like water; the time together like a dream — how to bear looking back at the magpie-bridge way home?" },
      { zh: "两情若是久长时，又岂在朝朝暮暮。", en: "If two hearts are true for long, what need have they of morning and evening together?" },
    ],
    keywords: [
      { w: "the Milky Way", zh: "银汉（银河）" },
      { w: "tenderness", zh: "柔情" },
      { w: "morning and evening", zh: "朝朝暮暮" },
    ],
    cross: {
      field: "天文",
      fieldEn: "Astronomy",
      title: "牛郎星和织女星真的能相会吗？",
      titleEn: "Can Altair and Vega ever meet?",
      body: "牛郎星（河鼓二）与织女星隔着银河相望，实际距离约16光年——就算以光速奔赴，单程也要16年，神话里的「一年一渡」在物理上不可能。但它们确实属于夏季大三角，七月初升到天顶，与七夕的时间刚好重合：古人把天象读成了日历，又把日历读成了爱情。",
      bodyEn: "Altair and Vega face each other across the Milky Way, some 16 light-years apart — even at light speed, a one-way trip takes sixteen years, so the myth's yearly crossing is physically impossible. Yet the two stars, with Deneb, form the Summer Triangle that culminates in early July, coinciding with the Qixi festival: the ancients read the sky as a calendar, then read the calendar as love.",
    },
    note: "中国人第一次把「异地」论证成了正当关系——论据只有两个字：久长。",
    noteEn: "The first rigorous defence of long-distance love in Chinese: the entire argument rests on two characters, 'long-lasting'.",
  },
  {
    slug: "yulinling",
    title: "雨霖铃·寒蝉凄切",
    titleEn: "Yulinling: Cold Cicadas",
    author: "柳永",
    authorEn: "Liu Yong",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "高中",
    kind: "词",
    theme: "送别",
    themeEn: "Parting",
    level: 3,
    lines: [
      { zh: "寒蝉凄切，对长亭晚，骤雨初歇。", en: "Cold cicadas cry thin and sharp; evening at the long pavilion; a sudden shower just ended." },
      { zh: "都门帐饮无绪，留恋处，兰舟催发。", en: "Drinking in farewell tents outside the capital, no heart for it; still lingering, when the boat urges departure." },
      { zh: "执手相看泪眼，竟无语凝噎。", en: "Hands clasped, eyes wet, looking at each other — no words at all, only a lump in the throat." },
      { zh: "念去去，千里烟波，暮霭沉沉楚天阔。", en: "I think of the journey on: a thousand li of misty waves, evening gloom thickening under the wide southern sky." },
      { zh: "多情自古伤离别，更那堪，冷落清秋节！", en: "Lovers have grieved at parting since ancient times — worse in this bleak clear-autumn season!" },
      { zh: "今宵酒醒何处？杨柳岸，晓风残月。", en: "Where will I be when the wine wears off tonight? A willow bank, dawn wind, a waning moon." },
    ],
    keywords: [
      { w: "pavilion", zh: "长亭" },
      { w: "a lump in the throat", zh: "凝噎" },
      { w: "waning moon", zh: "残月" },
    ],
    note: "「执手相看泪眼，竟无语凝噎」——真正的告别没有台词。",
    noteEn: "Hands clasped, no words at all: a true farewell has no dialogue.",
  },
  {
    slug: "beiming",
    title: "北冥有鱼（节选）",
    titleEn: "In the Northern Darkness There Is a Fish (excerpt)",
    author: "庄子",
    authorEn: "Zhuangzi",
    dynasty: "战国",
    dynastyEn: "Warring States",
    stage: "高中",
    kind: "文言文",
    theme: "哲理",
    themeEn: "Freedom",
    level: 3,
    lines: [
      { zh: "北冥有鱼，其名为鲲。鲲之大，不知其几千里也；化而为鸟，其名为鹏。", en: "In the Northern Darkness there is a fish, named Kun. So vast you cannot know how many thousand li it is. It becomes a bird, named Peng." },
      { zh: "鹏之背，不知其几千里也；怒而飞，其翼若垂天之云。", en: "The Peng's back — who knows how many thousand li? It rouses itself to fly, its wings like clouds hanging from the sky." },
      { zh: "鹏之徙于南冥也，水击三千里，抟扶摇而上者九万里，去以六月息者也。", en: "When the Peng migrates to the Southern Darkness, water is struck for three thousand li; it rides the whirlwind up ninety thousand li, and goes off on the six months' wind." },
    ],
    fullText: "北冥有鱼，其名为鲲。鲲之大，不知其几千里也；化而为鸟，其名为鹏。鹏之背，不知其几千里也；怒而飞，其翼若垂天之云。是鸟也，海运则将徙于南冥。南冥者，天池也。《齐谐》者，志怪者也。谐之言曰：「鹏之徙于南冥也，水击三千里，抟扶摇而上者九万里，去以六月息者也。」野马也，尘埃也，生物之以息相吹也。天之苍苍，其正色邪？其远而无所至极邪？其视下也，亦若是则已矣。",
    keywords: [
      { w: "so vast", zh: "不知其大（几千里）" },
      { w: "rouse oneself", zh: "怒（振翅）" },
      { w: "whirlwind", zh: "扶摇" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "大鹏为什么要飞九万里高？",
      titleEn: "Why does the Peng fly ninety thousand li high?",
      body: "庄子写大鹏「抟扶摇而上」——借螺旋上升的大风。现代气象学里，高空才有稳定而强劲的西风带与急流，翅膀越大的飞行体越需要依托强劲气流；蜩与学鸠在低空扑腾就够了，「大小」决定了你能借到什么风。九万里是诗的夸张，底层逻辑却是对的：高度即资源。",
      bodyEn: "The Peng rides a spiralling wind upward. In modern terms: strong, steady winds — the westerlies and jet streams — exist only at high altitude, and the larger the flyer the more it depends on powerful airflow, while little cicadas and doves manage near the ground. Scale decides what wind you can borrow. Ninety thousand li is poetic excess, but the logic — altitude is resource — is sound.",
    },
    note: "「怒而飞」的「怒」是使劲——庄子最大的自由也要借六个月的风，自由从来不是无凭无据。",
    noteEn: "'Rouses itself' means strains. Even Zhuangzi's greatest freedom must borrow the six months' wind — freedom is never without its conditions.",
  },
];
