import type { Poem } from "./types";

/** 高中阶段 · 第 2 批（文言文：论说、赋、序、表、史传） */
export const SENIOR_2: Poem[] = [
  {
    slug: "quanxue",
    title: "劝学（节选）",
    titleEn: "Encouraging Learning (excerpt)",
    author: "荀子",
    authorEn: "Xunzi",
    dynasty: "先秦",
    dynastyEn: "Pre-Qin",
    stage: "高中",
    kind: "文言文",
    theme: "勤学",
    themeEn: "Study",
    level: 3,
    lines: [
      { zh: "君子曰：学不可以已。", en: "The gentleman says: learning must never cease." },
      { zh: "青，取之于蓝，而青于蓝；冰，水为之，而寒于水。", en: "Indigo comes from the blue plant, yet is bluer than it; ice is made of water, yet is colder than water." },
      { zh: "君子生非异也，善假于物也。", en: "The gentleman is not born different — he is good at making use of things." },
      { zh: "不积跬步，无以至千里；不积小流，无以成江海。", en: "Without accumulating single steps, one cannot reach a thousand li; without accumulating small streams, one cannot make a river or a sea." },
    ],
    fullText: "君子曰：学不可以已。青，取之于蓝，而青于蓝；冰，水为之，而寒于水。木直中绳，𫐓以为轮，其曲中规……故木受绳则直，金就砺则利，君子博学而日参省乎己，则知明而行无过矣……君子生非异也，善假于物也……积土成山，风雨兴焉；积水成渊，蛟龙生焉；积善成德，而神明自得，圣心备焉。故不积跬步，无以至千里；不积小流，无以成江海。",
    keywords: [
      { w: "cease (v.)", zh: "停止（已）" },
      { w: "indigo (n.)", zh: "靛青（青）" },
      { w: "be born different", zh: "生而异" },
      { w: "accumulate (v.)", zh: "积累" },
    ],
    cross: {
      field: "化学",
      fieldEn: "Chemistry",
      title: "「青出于蓝」是真化学吗？",
      titleEn: "Is indigo-bluer-than-indigo real chemistry?",
      body: "是。蓝草（蓼蓝、菘蓝等）本身不含靛蓝，而是含靛苷（indican）。古人把蓝草浸泡发酵，靛苷经酶水解为吲哚酚，再在碱性条件下通空气氧化，两分子缩合成靛蓝（indigo）——靛蓝正是从蓝草中「提取并转化」出来的，颜色比原料更深更纯。这个工艺在世界各地独立发明，1880 年代才实现人工合成。荀子用这个身边的化学过程说明学习能改变人，比喻非常扎实。",
      bodyEn: "Yes. The indigo plant contains not indigo but indican. Soaking and fermenting the leaves hydrolyses indican to indoxyl, which oxidises in alkaline solution and couples into indigo — the pigment is literally extracted and transformed, deeper and purer than the raw plant. The process was invented independently across the world and synthesised chemically only in the 1880s. Xunzi used everyday chemistry to argue that learning transforms a person.",
    },
    note: "通篇用比喻说理（青蓝、冰水、木轮、积土成山）——英文保留比喻本身，不做义译。",
    noteEn: "Argument by metaphor throughout: indigo, ice, the bent wheel, piled earth.",
  },
  {
    slug: "shishuo",
    title: "师说（节选）",
    titleEn: "On Teachers (excerpt)",
    author: "韩愈",
    authorEn: "Han Yu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "高中",
    kind: "文言文",
    theme: "勤学",
    themeEn: "Study",
    level: 3,
    lines: [
      { zh: "古之学者必有师。师者，所以传道受业解惑也。", en: "Those who learned in ancient times always had a teacher. A teacher is one who transmits the Way, hands on the craft, and resolves perplexity." },
      { zh: "人非生而知之者，孰能无惑？惑而不从师，其为惑也，终不解矣。", en: "No man is born knowing: who can be free of perplexity? If perplexed and yet following no teacher, the perplexity will never be resolved." },
      { zh: "是故无贵无贱，无长无少，道之所存，师之所存也。", en: "Therefore, noble or base, old or young — where the Way is, there is the teacher." },
      { zh: "弟子不必不如师，师不必贤于弟子。闻道有先后，术业有专攻。", en: "A student need not be inferior to his teacher, nor a teacher worthier than his student; there is only an order in hearing the Way, and each craft has its speciality." },
    ],
    fullText: "古之学者必有师。师者，所以传道受业解惑也。人非生而知之者，孰能无惑？惑而不从师，其为惑也，终不解矣……是故无贵无贱，无长无少，道之所存，师之所存也……孔子曰：三人行，则必有我师。是故弟子不必不如师，师不必贤于弟子，闻道有先后，术业有专攻，如是而已。",
    keywords: [
      { w: "transmit (v.)", zh: "传授（道）" },
      { w: "perplexity (n.)", zh: "疑惑" },
      { w: "base (adj.)", zh: "低贱的" },
      { w: "speciality (n.)", zh: "专长（专攻）" },
    ],
    cross: {
      field: "教育",
      fieldEn: "Education",
      title: "「闻道有先后」的现代含义",
      titleEn: "What 「an order in hearing the Way」 means today",
      body: "这句话给出了一种基于信息差而非身份的师生定义：先知道的人教后知道的人，关系由知识时序决定，不由年龄与地位决定。这与现代教育学里「学习共同体」和「同伴互教」（peer instruction）的理念接近——研究表明，教别人的人自己获益最大（protégé effect）。韩愈写此文时，唐代士大夫耻于相师成风，他是在直接对抗当时的社会风气。",
      bodyEn: "This defines teacher and student by information, not status: whoever learned first teaches whoever learned later; the relation is set by sequence of knowledge, not age or rank. It resembles modern notions of learning communities and peer instruction — research finds those who teach gain most (the protégé effect). Han Yu wrote against a Tang fashion among officials who thought it shameful to take a teacher.",
    },
    note: "「传道受业解惑」六个字定义了教师的三重职能——英文用 transmits / hands on / resolves 三个动词对应。",
    noteEn: "Three functions, three verbs: transmit, hand on, resolve.",
  },
  {
    slug: "chibifu",
    title: "赤壁赋（节选）",
    titleEn: "The Red Cliff Fu (excerpt)",
    author: "苏轼",
    authorEn: "Su Shi",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "高中",
    kind: "文言文",
    theme: "哲学",
    themeEn: "Philosophy",
    level: 3,
    lines: [
      { zh: "清风徐来，水波不兴。举酒属客，诵明月之诗，歌窈窕之章。", en: "A cool wind comes softly; the water's surface is unruffled. I raise wine to my guests, reciting the poem of the bright moon, singing the stanza of the lovely maid." },
      { zh: "寄蜉蝣于天地，渺沧海之一粟。", en: "We lodge like mayflies between heaven and earth, small as a grain of millet in the vast sea." },
      { zh: "逝者如斯，而未尝往也；盈虚者如彼，而卒莫消长也。", en: "What passes is like this river, yet it has never gone; what waxes and wanes is like that moon, and in the end neither increases nor decreases." },
      { zh: "是造物者之无尽藏也，而吾与子之所共适。", en: "This is the inexhaustible store of the Creator, and my guest and I enjoy it together." },
    ],
    fullText: "壬戌之秋，七月既望，苏子与客泛舟游于赤壁之下。清风徐来，水波不兴。举酒属客，诵明月之诗，歌窈窕之章……客曰：「『月明星稀，乌鹊南飞』，此非曹孟德之诗乎？……固一世之雄也，而今安在哉？……寄蜉蝣于天地，渺沧海之一粟。哀吾生之须臾，羡长江之无穷……」苏子曰：「客亦知夫水与月乎？逝者如斯，而未尝往也；盈虚者如彼，而卒莫消长也。盖将自其变者而观之，则天地曾不能以一瞬；自其不变者而观之，则物与我皆无尽也……」",
    keywords: [
      { w: "unruffled (adj.)", zh: "（波）不兴" },
      { w: "mayfly (n.)", zh: "蜉蝣" },
      { w: "a grain of millet", zh: "一粟" },
      { w: "inexhaustible (adj.)", zh: "无尽的（藏）" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "水真的「未尝往」吗？",
      titleEn: "Has the river really never gone?",
      body: "从物质守恒的角度看，苏轼是对的：水分子在循环中不断变换形态（蒸发、凝结、降雪、成冰、入海），但氢原子与氧原子既不会凭空产生也不会消失。从热力学第二定律看，他也是对的——宇宙的总熵增加，但物质总量恒定。当然，组成这条河的每一个具体水分子确实流走了（这叫「赫拉克利特之流」）。苏轼的高明在于同时看到两个尺度：变的那一面和不变的那一面。",
      bodyEn: "On conservation of matter, Su Shi is right: water molecules cycle — evaporating, condensing, falling as snow, freezing, reaching the sea — while the hydrogen and oxygen atoms are neither created nor destroyed. The second law of thermodynamics agrees: entropy rises but the total remains. Of course any given molecule does flow away (Heraclitus's river). His insight is to hold both scales at once: what changes and what does not.",
    },
    note: "「逝者如斯」引自《论语》，苏轼却反用了它——孔子感叹流逝，苏轼指出「未尝往」。英文用 yet it has never gone 保留了这个反转。",
    noteEn: "He quotes Confucius and reverses him: the river flows, yet never leaves.",
  },
  {
    slug: "tengwanggexu",
    title: "滕王阁序（节选）",
    titleEn: "Preface to the Pavilion of Prince Teng (excerpt)",
    author: "王勃",
    authorEn: "Wang Bo",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "高中",
    kind: "文言文",
    theme: "山水",
    themeEn: "Landscape",
    level: 3,
    lines: [
      { zh: "星分翼轸，地接衡庐。襟三江而带五湖，控蛮荆而引瓯越。", en: "In the sky it belongs to the constellations Yi and Zhen; on earth it adjoins Heng and Lu. It drapes the three rivers and girdles the five lakes, holding the wild Jing and drawing in Ou and Yue." },
      { zh: "落霞与孤鹜齐飞，秋水共长天一色。", en: "The falling glow of sunset and a solitary duck fly together; the autumn water and the long sky are one colour." },
      { zh: "老当益壮，宁移白首之心？穷且益坚，不坠青云之志。", en: "Growing old, one should grow stronger — how could a white-haired head change its purpose? In adversity one grows firmer, and lets not fall the ambition that reaches the blue clouds." },
    ],
    fullText: "豫章故郡，洪都新府。星分翼轸，地接衡庐。襟三江而带五湖，控蛮荆而引瓯越……层峦耸翠，上出重霄；飞阁流丹，下临无地……云销雨霁，彩彻区明。落霞与孤鹜齐飞，秋水共长天一色。渔舟唱晚，响穷彭蠡之滨；雁阵惊寒，声断衡阳之浦……老当益壮，宁移白首之心？穷且益坚，不坠青云之志。酌贪泉而觉爽，处涸辙以犹欢。",
    keywords: [
      { w: "drape (v.)", zh: "（襟）以…为衣襟" },
      { w: "girdle (v.)", zh: "（带）以…为腰带" },
      { w: "solitary duck", zh: "孤鹜" },
      { w: "adversity (n.)", zh: "穷困（穷）" },
    ],
    cross: {
      field: "天文",
      fieldEn: "Astronomy",
      title: "「星分翼轸」是什么？",
      titleEn: "What does 「stars divided at Yi and Zhen」 mean?",
      body: "这是中国古代的星野（分野）理论：把天上的星宿与地上的州国一一对应，用以占验。二十八宿中的翼、轸二宿对应荆州，而豫章（今南昌）在古荆州范围，所以说「星分翼轸」。分野体系成形于战国至汉代，依据是岁星（木星）运行与二十八宿的方位对应。王勃开篇用天文定位地理，是当时骈文的标准起法。",
      bodyEn: "This is the ancient Chinese system of field allocation: pairing constellations with terrestrial regions for divination. The mansions Yi and Zhen correspond to Jing province, and Yuzhang (modern Nanchang) lay within ancient Jing — hence 「stars divided at Yi and Zhen」. The scheme took shape between the Warring States and Han, based on the position of Jupiter against the twenty-eight mansions. Opening a parallel-prose piece by locating a place astronomically was standard practice.",
    },
    note: "「落霞与孤鹜齐飞，秋水共长天一色」是骈文的巅峰之一——英文用 fly together 与 one colour 保留了动静与色彩的对仗。",
    noteEn: "The high point of parallel prose: motion and colour in perfect balance.",
  },
  {
    slug: "efanggongfu",
    title: "阿房宫赋（节选）",
    titleEn: "The Epang Palace Fu (excerpt)",
    author: "杜牧",
    authorEn: "Du Mu",
    dynasty: "唐",
    dynastyEn: "Tang",
    stage: "高中",
    kind: "文言文",
    theme: "咏史",
    themeEn: "History",
    level: 3,
    lines: [
      { zh: "六王毕，四海一，蜀山兀，阿房出。", en: "The six kings were finished, the four seas made one; the hills of Shu were bared, and Epang arose." },
      { zh: "覆压三百余里，隔离天日。", en: "It roofed over three hundred li and more, shutting out the sky and sun." },
      { zh: "戍卒叫，函谷举，楚人一炬，可怜焦土！", en: "A conscript raised the cry, Hangu Pass was taken, and a man of Chu set one torch — alas, a scorched earth!" },
      { zh: "秦人不暇自哀，而后人哀之；后人哀之而不鉴之，亦使后人而复哀后人也。", en: "The men of Qin had no time to pity themselves, and later men pitied them; if later men pity them but do not learn from them, they will leave still later men to pity them in turn." },
    ],
    fullText: "六王毕，四海一，蜀山兀，阿房出。覆压三百余里，隔离天日……长桥卧波，未云何龙？复道行空，不霁何虹？……戍卒叫，函谷举，楚人一炬，可怜焦土！呜呼！灭六国者六国也，非秦也；族秦者秦也，非天下也。嗟乎！使六国各爱其人，则足以拒秦；使秦复爱六国之人，则递三世可至万世而为君，谁得而族灭也？秦人不暇自哀，而后人哀之；后人哀之而不鉴之，亦使后人而复哀后人也。",
    keywords: [
      { w: "bare (v.)", zh: "（山）光秃（兀）" },
      { w: "roof over", zh: "覆压" },
      { w: "torch (n.)", zh: "（一）炬（火把）" },
      { w: "learn from", zh: "以…为鉴" },
    ],
    cross: {
      field: "考古",
      fieldEn: "Archaeology",
      title: "阿房宫真的被烧了吗？",
      titleEn: "Was Epang Palace really burned?",
      body: "考古证据不支持。2002—2007 年中国社科院与西安市文保考古所对阿房宫前殿遗址（今西安西郊，夯土台基面积约 54 万平方米）进行了大面积勘探与试掘，未发现大面积红烧土、木炭等焚烧痕迹，也未找到秦代宫殿建筑遗存——说明前殿可能只完成了夯土台基，尚未建成，更未被焚烧。史载项羽「烧秦宫室」应指咸阳宫而非阿房宫。杜牧的赋是文学，借秦讽唐。",
      bodyEn: "The evidence says no. Between 2002 and 2007, teams from the Chinese Academy of Social Sciences and Xi'an surveyed and sampled the Epang front-hall site (west Xi'an; a rammed-earth platform of some 540,000 m²) and found no extensive burnt earth or charcoal, and no Qin palace structures — suggesting the terrace was built but the hall never completed, let alone burned. Xiang Yu's burning of Qin palaces refers to Xianyang Palace. Du Mu's fu is literature, using Qin to warn Tang.",
    },
    note: "最后一句的「后人复哀后人」是递归结构——英文用 in turn 保留了这种层层递推。",
    noteEn: "A recursive ending: later men, pitied by still later men, in turn.",
  },
  {
    slug: "liuguolun",
    title: "六国论（节选）",
    titleEn: "On the Six States (excerpt)",
    author: "苏洵",
    authorEn: "Su Xun",
    dynasty: "宋",
    dynastyEn: "Song",
    stage: "高中",
    kind: "文言文",
    theme: "史论",
    themeEn: "Historical Argument",
    level: 3,
    lines: [
      { zh: "六国破灭，非兵不利，战不善，弊在赂秦。", en: "The ruin of the six states lay not in weak weapons nor in bad fighting, but in bribing Qin." },
      { zh: "赂秦而力亏，破灭之道也。", en: "Bribing Qin drained their strength — that was the road to ruin." },
      { zh: "以地事秦，犹抱薪救火，薪不尽，火不灭。", en: "To serve Qin with land is like carrying firewood to put out a fire: until the firewood is gone, the fire will not go out." },
      { zh: "苟以天下之大，下而从六国破亡之故事，是又在六国下矣。", en: "If, with a realm so great, one lowers oneself to repeat the old story of the six states' ruin, then one falls below even them." },
    ],
    fullText: "六国破灭，非兵不利，战不善，弊在赂秦。赂秦而力亏，破灭之道也。或曰：六国互丧，率赂秦耶？曰：不赂者以赂者丧。盖失强援，不能独完。故曰：弊在赂秦也……思厥先祖父，暴霜露，斩荆棘，以有尺寸之地。子孙视之不甚惜，举以予人，如弃草芥……以地事秦，犹抱薪救火，薪不尽，火不灭……苟以天下之大，下而从六国破亡之故事，是又在六国下矣。",
    keywords: [
      { w: "bribe (v.)", zh: "贿赂（赂）" },
      { w: "drain (v.)", zh: "消耗（力亏）" },
      { w: "firewood (n.)", zh: "薪（柴）" },
      { w: "repeat (v.)", zh: "重蹈（从…故事）" },
    ],
    cross: {
      field: "政治",
      fieldEn: "Politics",
      title: "苏洵的论点成立吗？",
      titleEn: "Does Su Xun's thesis hold up?",
      body: "史学上有争议。苏洵说六国亡于「赂秦」（割地求和导致自我削弱），但实际历史更复杂：六国多次合纵抗秦，失败原因在于地理分割、各国利害不一、秦国商鞅变法后的耕战体制与远交近攻策略更高效。把原因单一化为「赂秦」，是宋代策论的特点——苏洵此文真正的靶子是北宋对辽、西夏的岁币政策，他是在谏当下而非论古。",
      bodyEn: "Historians dispute it. Su Xun blames the six states for buying off Qin with land, but the reality was messier: they formed several coalitions, and failure came from geographic division, conflicting interests, and the efficiency of Qin's Shang Yang system of agriculture and war combined with its strategy of befriending distant states while attacking near ones. Reducing all this to bribery is typical of Song policy essays — Su Xun's real target was the Northern Song's annual payments to the Liao and Western Xia.",
    },
    note: "「抱薪救火」已成成语——英文用 carrying firewood to put out a fire 保留了悖论式的比喻。",
    noteEn: "The metaphor is a paradox: feeding a fire to quench it.",
  },
  {
    slug: "guoqinlun",
    title: "过秦论 · 上（节选）",
    titleEn: "The Faults of Qin · Part I (excerpt)",
    author: "贾谊",
    authorEn: "Jia Yi",
    dynasty: "西汉",
    dynastyEn: "Western Han",
    stage: "高中",
    kind: "文言文",
    theme: "史论",
    themeEn: "Historical Argument",
    level: 3,
    lines: [
      { zh: "奋六世之余烈，振长策而御宇内，吞二周而亡诸侯。", en: "He carried forward the remaining might of six reigns, cracked the long whip and drove the world within the seas, swallowed the two Zhou and destroyed the feudal lords." },
      { zh: "乃使蒙恬北筑长城而守藩篱，却匈奴七百余里。", en: "He sent Meng Tian north to build the long wall as a fence, and pushed the Xiongnu back more than seven hundred li." },
      { zh: "一夫作难而七庙隳，身死人手，为天下笑者，何也？仁义不施而攻守之势异也。", en: "One man raised a revolt and the seven ancestral temples fell; he himself died by another's hand and became the laughing-stock of the world — why? Because he did not practise benevolence and righteousness, and the balance of attack and defence had changed." },
    ],
    fullText: "及至始皇，奋六世之余烈，振长策而御宇内，吞二周而亡诸侯，履至尊而制六合，执敲扑而鞭笞天下，威振四海。南取百越之地，以为桂林、象郡……乃使蒙恬北筑长城而守藩篱，却匈奴七百余里；胡人不敢南下而牧马，士不敢弯弓而报怨……然而陈涉瓮牖绳枢之子，氓隶之人，而迁徙之徒也……天下云集响应，赢粮而景从……一夫作难而七庙隳，身死人手，为天下笑者，何也？仁义不施而攻守之势异也。",
    keywords: [
      { w: "crack the whip", zh: "振长策" },
      { w: "fence (n.)", zh: "藩篱（屏障）" },
      { w: "push back", zh: "击退（却）" },
      { w: "benevolence (n.)", zh: "仁义" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "秦亡的真正原因是什么？",
      titleEn: "Why did Qin really fall?",
      body: "贾谊归因为「仁义不施」，是汉初总结秦亡的标准答案（陆贾、贾谊皆主此说）。现代史学则补充了制度与技术因素：统一后未休养生息而同时兴筑长城、驰道、骊山陵与阿房宫，征发劳力达数百万；严刑峻法与连坐使地方失去弹性；郡县制推行过快、旧贵族势力仍在；加上二世即位不正、赵高乱政——多重压力叠加导致陈胜起义后迅速崩解。贾谊抓住了最关键的一条：打天下与治天下需要不同的治理逻辑。",
      bodyEn: "Jia Yi's verdict — failure to practise benevolence — was the standard early-Han answer (Lu Jia said the same). Modern historians add institutional factors: after unification the state never let the country rest, running the Great Wall, highways, the Lishan tomb and Epang simultaneously with millions of conscripted labourers; harsh law and collective punishment removed local flexibility; the commandery system was imposed faster than old elites could be absorbed; and the Second Emperor's dubious succession with Zhao Gao's misrule compounded it all. Jia Yi grasped the essential point: conquest and governance need different logics.",
    },
    note: "全文用「攻守之势异也」作结——英文用 the balance of attack and defence had changed 保留了这句战略判断。",
    noteEn: "The closing judgement: attacking and holding require different arts.",
  },
  {
    slug: "chenqingbiao",
    title: "陈情表（节选）",
    titleEn: "Memorial Declaring My Feelings (excerpt)",
    author: "李密",
    authorEn: "Li Mi",
    dynasty: "西晋",
    dynastyEn: "Western Jin",
    stage: "高中",
    kind: "文言文",
    theme: "孝道",
    themeEn: "Filial Duty",
    level: 3,
    lines: [
      { zh: "臣以险衅，夙遭闵凶。生孩六月，慈父见背。", en: "Because of ill-starred fortune I met with misfortune early: six months after I was born, my kind father turned his back on me." },
      { zh: "茕茕孑立，形影相吊。", en: "Alone and forlorn, I stand by myself; only my body and its shadow console each other." },
      { zh: "臣无祖母，无以至今日；祖母无臣，无以终余年。", en: "Without my grandmother I could not have reached this day; without me, she cannot finish her remaining years." },
      { zh: "乌鸟私情，愿乞终养。", en: "With the private feeling of the crow — I beg to be allowed to nurse her to the end." },
    ],
    fullText: "臣密言：臣以险衅，夙遭闵凶。生孩六月，慈父见背；行年四岁，舅夺母志。祖母刘愍臣孤弱，躬亲抚养……茕茕孑立，形影相吊。而刘夙婴疾病，常在床蓐，臣侍汤药，未曾废离……臣无祖母，无以至今日；祖母无臣，无以终余年。母孙二人，更相为命，是以区区不能废远……乌鸟私情，愿乞终养……臣生当陨首，死当结草。",
    keywords: [
      { w: "ill-starred (adj.)", zh: "命运坎坷的（险衅）" },
      { w: "forlorn (adj.)", zh: "孤单的（茕茕）" },
      { w: "console (v.)", zh: "安慰（相吊）" },
      { w: "nurse (v.)", zh: "奉养（终养）" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "乌鸦真的反哺吗？",
      titleEn: "Do crows really feed their parents?",
      body: "严格说没有可靠证据。古人称乌鸦「反哺」（幼鸟长大后衔食喂母），是一种道德化的观察附会。现代鸟类学确实发现乌鸦（尤其渡鸦、松鸦）具备合作繁殖行为：前一窝的幼鸟会留在巢中帮助亲鸟哺育下一窝（helpers at the nest），这在鸦科中相当普遍。所以「反哺」的具体行为不存在，但鸦科的合作育雏确实是一种「帮助亲代」的行为——古人观察到了这个群体的亲密性。",
      bodyEn: "Strictly, there is no good evidence — the ancient belief that young crows feed their mothers (fanbu) is a moralising interpretation. Ornithology does, however, find cooperative breeding in corvids: offspring from an earlier brood stay and help parents feed the next (helpers at the nest), common in crows, ravens and jays. So the specific behaviour is absent, but corvid family cooperation is real, and the ancients sensed that closeness.",
    },
    note: "这是一份拒绝皇帝征召的表——全程不说「不去」，只说祖母需要我。英文用 two people keeping each other alive 保留了这份无奈。",
    noteEn: "A refusal that never says no: only that his grandmother needs him.",
  },
  {
    slug: "lantingjixu",
    title: "兰亭集序（节选）",
    titleEn: "Preface to the Orchid Pavilion Collection (excerpt)",
    author: "王羲之",
    authorEn: "Wang Xizhi",
    dynasty: "东晋",
    dynastyEn: "Eastern Jin",
    stage: "高中",
    kind: "文言文",
    theme: "哲学",
    themeEn: "Philosophy",
    level: 3,
    lines: [
      { zh: "此地有崇山峻岭，茂林修竹，又有清流激湍，映带左右。", en: "Here there are lofty mountains and steep ridges, dense woods and tall bamboo, and a clear rushing stream that glints and girdles both sides." },
      { zh: "仰观宇宙之大，俯察品类之盛，所以游目骋怀，足以极视听之娱。", en: "Looking up, one takes in the vastness of the universe; looking down, the abundance of kinds — thus the eye roams and the heart runs free, more than enough for the utmost delight of sight and sound." },
      { zh: "固知一死生为虚诞，齐彭殇为妄作。", en: "Thus I know that to treat life and death as one is empty talk, and to equalise Pengzu with the child who died young is a false invention." },
    ],
    fullText: "永和九年，岁在癸丑，暮春之初，会于会稽山阴之兰亭，修禊事也。群贤毕至，少长咸集。此地有崇山峻岭，茂林修竹，又有清流激湍，映带左右，引以为流觞曲水，列坐其次……是日也，天朗气清，惠风和畅，仰观宇宙之大，俯察品类之盛，所以游目骋怀，足以极视听之娱，信可乐也……固知一死生为虚诞，齐彭殇为妄作。后之视今，亦犹今之视昔，悲夫！",
    keywords: [
      { w: "lofty (adj.)", zh: "高峻的（崇山）" },
      { w: "abundance (n.)", zh: "繁盛（品类之盛）" },
      { w: "empty talk", zh: "虚诞" },
      { w: "false invention", zh: "妄作" },
    ],
    cross: {
      field: "哲学",
      fieldEn: "Philosophy",
      title: "王羲之为什么反对庄子？",
      titleEn: "Why does Wang Xizhi reject Zhuangzi?",
      body: "《庄子·大宗师》主张「死生为一条」，认为生与死是同一自然过程的不同形态，不必哀乐。王羲之明确反驳：这是「虚诞」「妄作」。他的理由是体验性的——正因为快乐如此真实（「信可乐也」），死亡的终结才如此不可接受。这是东晋「人的觉醒」的典型时刻：不再用玄学消解情感，而是承认情感的实在性。这种直面有限性的态度，与后来存在主义的思路有相通之处。",
      bodyEn: "Zhuangzi holds life and death to be one continuous natural process, not to be grieved. Wang Xizhi rejects this outright as empty and false — and his reason is experiential: precisely because joy is so real, its ending is unacceptable. It is a signature moment of the Eastern Jin awakening: no longer dissolving feeling in metaphysics but granting feeling reality. Facing finitude head-on has an affinity with later existentialism.",
    },
    note: "「后之视今，亦犹今之视昔」——英文用 those after us will look on us as we look on those before 保留了时间的三层结构。",
    noteEn: "Three layers of time: those before, us, those after.",
  },
  {
    slug: "guiqulaixi",
    title: "归去来兮辞（节选）",
    titleEn: "Homeward I Go (excerpt)",
    author: "陶渊明",
    authorEn: "Tao Yuanming",
    dynasty: "东晋",
    dynastyEn: "Eastern Jin",
    stage: "高中",
    kind: "文言文",
    theme: "田园",
    themeEn: "Pastoral",
    level: 3,
    lines: [
      { zh: "悟已往之不谏，知来者之可追。实迷途其未远，觉今是而昨非。", en: "I understand that the past cannot be remonstrated with, and know that what is to come may yet be pursued. Indeed I strayed, but not far — I wake to find today right and yesterday wrong." },
      { zh: "云无心以出岫，鸟倦飞而知还。", en: "Clouds, without purpose, come out of the peaks; birds, tired of flying, know to return." },
      { zh: "木欣欣以向荣，泉涓涓而始流。善万物之得时，感吾生之行休。", en: "Trees thrive in glad abundance; springs begin to flow in thin threads. I rejoice that all things have their season, and feel that my own life is drawing to its rest." },
    ],
    fullText: "归去来兮，田园将芜胡不归？既自以心为形役，奚惆怅而独悲？悟已往之不谏，知来者之可追。实迷途其未远，觉今是而昨非……乃瞻衡宇，载欣载奔。僮仆欢迎，稚子候门。三径就荒，松菊犹存……云无心以出岫，鸟倦飞而知还。景翳翳以将入，抚孤松而盘桓……木欣欣以向荣，泉涓涓而始流。善万物之得时，感吾生之行休。已矣乎！寓形宇内复几时？曷不委心任去留？",
    keywords: [
      { w: "stray (v.)", zh: "迷途" },
      { w: "without purpose", zh: "无心（自然而然）" },
      { w: "thrive (v.)", zh: "欣欣向荣" },
      { w: "draw to its rest", zh: "（生）行休" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "「鸟倦飞而知还」准确吗？",
      titleEn: "Is 「the tired bird knows to return」 accurate?",
      body: "相当准确。多数鸟类有强烈的日节律：白天外出觅食，黄昏前归巢归栖（roosting），由视交叉上核调控的生物钟与光照变化共同驱动。归巢行为还受安全性驱动——集群栖息可降低个体被捕食风险。候鸟的归巢（返家）能力更惊人，信鸽能从上千公里外返回鸽舍，靠的是地磁感应与嗅觉地图。陶渊明用鸟归巢比喻自己辞官，是因为这是每天黄昏都能看见的真实现象。",
      bodyEn: "Quite accurate. Most birds follow a strong circadian rhythm: foraging by day, returning to roost before dusk, driven by the suprachiasmatic clock together with changing light. Roosting is also safety-driven — flocks reduce individual predation risk. Homing is even more striking: pigeons return from over a thousand kilometres using magnetoreception and olfactory maps. Tao Yuanming's image works because everyone could watch it happen each evening.",
    },
    note: "「觉今是而昨非」是全篇的转折——英文用 today right and yesterday wrong 保留了这份决然的自我修正。",
    noteEn: "The turning point: yesterday wrong, today right.",
  },
  {
    slug: "jianzhukeshu",
    title: "谏逐客书（节选）",
    titleEn: "Remonstrance against Expelling Guests (excerpt)",
    author: "李斯",
    authorEn: "Li Si",
    dynasty: "秦",
    dynastyEn: "Qin",
    stage: "高中",
    kind: "文言文",
    theme: "政治",
    themeEn: "Politics",
    level: 3,
    lines: [
      { zh: "臣闻吏议逐客，窃以为过矣。", en: "I have heard that the officials propose to expel the guest-ministers; I humbly think this is a mistake." },
      { zh: "泰山不让土壤，故能成其大；河海不择细流，故能就其深。", en: "Mount Tai does not refuse a handful of soil, and so achieves its greatness; rivers and seas do not pick and choose among small streams, and so attain their depth." },
      { zh: "今乃弃黔首以资敌国，却宾客以业诸侯，使天下之士退而不敢西向。", en: "Now you cast away your black-haired people to supply enemy states, and turn away guests to build up the feudal lords, so that men of talent throughout the world draw back and dare not turn west." },
    ],
    fullText: "臣闻吏议逐客，窃以为过矣……昔穆公求士，西取由余于戎，东得百里奚于宛……孝公用商鞅之法，移风易俗，民以殷盛，国以富强……惠王用张仪之计，拔三川之地……昭王得范雎……皆以客之功。由此观之，客何负于秦哉！……臣闻地广者粟多，国大者人众，兵强则士勇。是以泰山不让土壤，故能成其大；河海不择细流，故能就其深；王者不却众庶，故能明其德……今乃弃黔首以资敌国，却宾客以业诸侯……求国无危，不可得也。",
    keywords: [
      { w: "expel (v.)", zh: "驱逐（逐客）" },
      { w: "humbly (adv.)", zh: "私下、窃以为" },
      { w: "refuse (v.)", zh: "拒绝（不让）" },
      { w: "build up", zh: "成就（业诸侯）" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "逐客令是怎么来的？",
      titleEn: "What prompted the order to expel foreigners?",
      body: "公元前 237 年，秦国发现韩国派水工郑国入秦修渠，实为消耗秦国国力（「疲秦」之计），宗室大臣遂请「一切逐客」。李斯是楚国人，也在被逐之列，途中上此书。秦王嬴政读后收回成命，恢复李斯官职，并最终用他的策略统一六国。有趣的是：郑国渠修成后反而使关中沃野千里、为秦统一提供了粮仓——「疲秦」之计变成了「强秦」之实。",
      bodyEn: "In 237 BC Qin discovered that the hydrologist Zheng Guo, sent by Han to build a canal, was really draining Qin's strength; the royal clan demanded that all foreign advisers be expelled. Li Si, a man of Chu, was on the list and submitted this memorial while being deported. King Zheng revoked the order, restored him, and eventually unified China with his strategies. The irony: the Zheng Guo canal ended up irrigating Guanzhong and feeding the unification it was meant to prevent.",
    },
    note: "通篇用排比（穆公、孝公、惠王、昭王四代客卿之功）——英文用并列的史实罗列保留气势。",
    noteEn: "Four reigns, four foreign ministers, one accumulating argument.",
  },
  {
    slug: "hongmenyan",
    title: "鸿门宴（节选）",
    titleEn: "The Feast at Hong Gate (excerpt)",
    author: "司马迁",
    authorEn: "Sima Qian",
    dynasty: "西汉",
    dynastyEn: "Western Han",
    stage: "高中",
    kind: "文言文",
    theme: "历史",
    themeEn: "History",
    level: 3,
    lines: [
      { zh: "吾入关，秋毫不敢有所近，籍吏民，封府库，而待将军。", en: "Since I entered the pass, I have not dared touch so much as an autumn hair; I registered the officials and people, sealed the treasuries, and waited for you, general." },
      { zh: "今者项庄拔剑舞，其意常在沛公也。", en: "Now Xiang Zhuang draws his sword and dances — his intent is always on the Lord of Pei." },
      { zh: "大行不顾细谨，大礼不辞小让。如今人方为刀俎，我为鱼肉，何辞为？", en: "In great acts one ignores small scruples; in great courtesies one does not stand on petty refusals. Now they are the chopping board and knife, and we are the fish and meat — why take leave at all?" },
    ],
    fullText: "沛公旦日从百余骑来见项王，至鸿门，谢曰：「臣与将军戮力而攻秦，将军战河北，臣战河南……今者有小人之言，令将军与臣有郤。」项王曰：「此沛公左司马曹无伤言之……」……范增数目项王，举所佩玉玦以示之者三，项王默然不应……项庄拔剑起舞，项伯亦拔剑起舞，常以身翼蔽沛公……樊哙曰：「大行不顾细谨，大礼不辞小让。如今人方为刀俎，我为鱼肉，何辞为？」……沛公则置车骑，脱身独骑……从郦山下，道芷阳间行。",
    keywords: [
      { w: "register (v.)", zh: "登记（籍吏民）" },
      { w: "treasury (n.)", zh: "府库" },
      { w: "scruple (n.)", zh: "细谨（小节）" },
      { w: "chopping board", zh: "刀俎" },
    ],
    cross: {
      field: "历史",
      fieldEn: "History",
      title: "鸿门宴为什么会放过刘邦？",
      titleEn: "Why was Liu Bang spared at Hong Gate?",
      body: "公元前 206 年，项羽四十万军驻鸿门，刘邦十万军驻霸上，兵力悬殊。项羽不杀刘邦的原因史家众说：一是刘邦亲自谢罪、姿态极低，项羽碍于贵族荣誉观不愿在宴席上偷袭；二是项伯（项羽叔父）事先通融并在席间以身掩护；三是项羽当时更在意的是诸侯联盟的政治正当性。司马迁通过这场宴会塑造了两个性格：项羽的犹豫与刘邦的机变——四年后，正是这种差别决定了垓下的结局。",
      bodyEn: "In 206 BC Xiang Yu held Hong Gate with 400,000 men against Liu Bang's 100,000 at Bashang. Why he relented is debated: Liu Bang came in person to apologise, making an ambush at a feast dishonourable for a nobleman; Xiang Bo, Xiang Yu's uncle, had smoothed the way and shielded Liu with his body during the sword dance; and Xiang Yu was still more concerned with the legitimacy of his coalition of lords. Sima Qian uses the banquet to fix two characters — hesitation versus improvisation — and four years later, at Gaixia, that difference decided everything.",
    },
    note: "「人为刀俎，我为鱼肉」已成成语——英文用 they are the chopping board and knife, and we are the fish and meat 保留了字面意象。",
    noteEn: "The idiom survives literally: board, knife, fish, meat.",
  },
];
