/**
 * 古诗词英译数据库
 *
 * 英译说明：所有英译均为本站点自行撰写的「学习化译文」——
 * 以准确传达诗意、用词现代清晰为第一目标，兼顾可朗读性，
 * 避免引用现代译家的受版权保护译本。原诗均为公有领域。
 */

/* 类型统一由 ./poem-data/types 提供（含学段 stage、文体 kind、文言文全文 fullText） */
export type { PoemLine, CrossCard, Stage, Kind, Poem } from "./poem-data/types";
import type { Poem } from "./poem-data/types";
import { PRIMARY_1 } from "./poem-data/primary-1";
import { PRIMARY_2 } from "./poem-data/primary-2";
import { PRIMARY_3 } from "./poem-data/primary-3";
import { PRIMARY_4 } from "./poem-data/primary-4";
import { PRIMARY_5 } from "./poem-data/primary-5";
import { JUNIOR_1 } from "./poem-data/junior-1";
import { JUNIOR_2 } from "./poem-data/junior-2";
import { JUNIOR_3 } from "./poem-data/junior-3";
import { JUNIOR_4 } from "./poem-data/junior-4";
import { JUNIOR_5 } from "./poem-data/junior-5";
import { JUNIOR_6 } from "./poem-data/junior-6";
import { SENIOR_1 } from "./poem-data/senior-1";
import { SENIOR_2 } from "./poem-data/senior-2";
import { SENIOR_3 } from "./poem-data/senior-3";
import { SENIOR_4 } from "./poem-data/senior-4";

/**
 * 站点初版内置的 20 首经典篇目（多为小学必背）。
 * 历史数据没有 stage / kind 字段，合并时统一补全。
 */
const LEGACY: Omit<Poem, "stage" | "kind">[] = [
  {
    slug: "jingyesi",
    title: "静夜思",
    titleEn: "Thoughts on a Quiet Night",
    author: "李白",
    authorEn: "Li Bai",
    dynasty: "唐",
    dynastyEn: "Tang",
    theme: "思乡",
    themeEn: "Homesickness",
    level: 1,
    lines: [
      { zh: "床前明月光，疑是地上霜。", en: "Before my bed the moonlight glows — I took it for frost upon the ground." },
      { zh: "举头望明月，低头思故乡。", en: "I raise my head to gaze at the bright moon, then lower it, and dream of home." },
    ],
    keywords: [
      { w: "moonlight", zh: "月光" },
      { w: "frost", zh: "霜" },
      { w: "raise / lower", zh: "抬起 / 低下" },
      { w: "gaze at", zh: "凝视" },
      { w: "dream of home", zh: "思念故乡" },
    ],
    cross: {
      field: "天文",
      fieldEn: "Astronomy",
      title: "为什么月光会「像霜」？",
      titleEn: "Why does moonlight look like frost?",
      body: "月光本身是反射的太阳光，色温偏冷（约 4100K），洒在地面时会形成一层均匀的冷白色。人在半梦半醒之间看到地面泛白，第一反应就是「结霜了」。李白写的不是比喻技巧，而是一次真实的错觉。另外诗里的「床」历来有争议：一说坐榻，一说井栏（井边的围栏），在井栏边看到满地月光更像霜。",
      bodyEn: "Moonlight is reflected sunlight with a cool color temperature (about 4100K). Falling evenly on the ground, it produces a pale white sheet — which a half-awake poet naturally mistakes for frost. Li Bai recorded a real illusion, not a decorative metaphor. Note also that the word 「床」 is disputed: it may mean a couch, or the railing around a well — the latter makes the frost illusion far more plausible.",
    },
    note: "全诗没有一个生僻字，却把「异乡夜醒」那一瞬间的错觉写绝了。注意 raise / lower 这对反义动词的节奏感。",
    noteEn: "Not one rare word, yet it captures the split second of waking in a strange place. Notice the rhythmic contrast of raise / lower.",
  },
  {
    slug: "chunxiao",
    title: "春晓",
    titleEn: "Spring Dawn",
    author: "孟浩然",
    authorEn: "Meng Haoran",
    dynasty: "唐",
    dynastyEn: "Tang",
    theme: "四季",
    themeEn: "Seasons",
    level: 1,
    lines: [
      { zh: "春眠不觉晓，处处闻啼鸟。", en: "In spring I sleep, and dawn breaks unawares; everywhere I hear the birds crying." },
      { zh: "夜来风雨声，花落知多少。", en: "Last night came the sound of wind and rain — how many flowers must have fallen?" },
    ],
    keywords: [
      { w: "unawares", zh: "不知不觉地" },
      { w: "everywhere", zh: "处处" },
      { w: "cry (of birds)", zh: "（鸟）啼鸣" },
      { w: "must have fallen", zh: "（推测）一定落了" },
    ],
    cross: {
      field: "生物",
      fieldEn: "Biology",
      title: "春天的鸟为什么叫得特别凶？",
      titleEn: "Why are spring birds so noisy?",
      body: "春季是鸟类的繁殖季，日照变长刺激垂体分泌促性腺激素，雄鸟睾酮水平上升，于是频繁鸣唱——一是宣示领地，二是吸引雌鸟。而且它们集中在黎明前后叫得最响（dawn chorus，黎明合唱），因为清晨光线暗、不适合觅食，最省力的做法就是唱歌。孟浩然是被一场真实的黎明合唱吵醒的。",
      bodyEn: "Spring is breeding season. Longer daylight triggers the pituitary to release gonadotropins; testosterone rises in males, and they sing constantly — to defend territory and attract mates. They are loudest around dawn (the dawn chorus), because dim light makes foraging inefficient. Meng Haoran was literally woken up by one.",
    },
    note: "「不觉晓」三个字最妙——睡得太沉，连天亮都不知道。英译用 sleep 与 dawn breaks unawares 承接，把「错过」写出来了。",
    noteEn: "The genius is in 「不觉晓」 — sleeping so deeply that dawn slips by unnoticed. The English carries it with unawares.",
  },
  {
    slug: "dengguanquelou",
    title: "登鹳雀楼",
    titleEn: "Climbing Stork Tower",
    author: "王之涣",
    authorEn: "Wang Zhihuan",
    dynasty: "唐",
    dynastyEn: "Tang",
    theme: "山水",
    themeEn: "Landscape",
    level: 1,
    lines: [
      { zh: "白日依山尽，黄河入海流。", en: "The pale sun leans upon the mountains and dies; the Yellow River flows on toward the sea." },
      { zh: "欲穷千里目，更上一层楼。", en: "To take in a thousand miles of sight, climb yet one more flight of stairs." },
    ],
    keywords: [
      { w: "lean upon", zh: "倚靠" },
      { w: "flows on toward", zh: "流向" },
      { w: "take in (a view)", zh: "尽收（眼底）" },
      { w: "a flight of stairs", zh: "一段楼梯" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "「千里目」真的看得到吗？",
      titleEn: "Can you really see a thousand miles?",
      body: "不能。地球是球体，站在鹳雀楼（今山西永济，高约 30 米）上，地平线视距大约只有 20 公里。要看到 500 公里（千里）外的东西，需要站在约 2 万米高空。王之涣当然知道这不是写实——他要说的是「视野取决于高度」这个道理，而这在物理上完全正确：地平线距离 d ≈ 3.57 × √h（h 为眼高，单位米；d 单位公里）。这大概是中文里最早的一句「站得高看得远」公式。",
      bodyEn: "Not literally. On a sphere, the horizon from Stork Tower (about 30 m high, in present-day Yongji, Shanxi) is only ~20 km away. Seeing 500 km would require standing at roughly 20,000 m. Wang Zhihuan was making a point, not a measurement — and the physics backs him: horizon distance d ≈ 3.57 × √h (h in metres, d in kilometres). Possibly the earliest Chinese statement of the altitude-horizon relation.",
    },
    note: "前两句写空间（山、河），后两句写行动（更上一层）。中文里的「更」对应 yet one more，语气最贴。",
    noteEn: "Two lines of space, two lines of action. The word 「更」 maps perfectly onto yet one more.",
  },
  {
    slug: "minnong",
    title: "悯农",
    titleEn: "Sympathy for the Farmer",
    author: "李绅",
    authorEn: "Li Shen",
    dynasty: "唐",
    dynastyEn: "Tang",
    theme: "劳作",
    themeEn: "Labour",
    level: 1,
    lines: [
      { zh: "锄禾日当午，汗滴禾下土。", en: "Hoeing the grain at high noon, sweat drips down into the soil beneath the plants." },
      { zh: "谁知盘中餐，粒粒皆辛苦。", en: "Who knows that every grain upon the plate comes from such bitter toil?" },
    ],
    keywords: [
      { w: "hoe (v.)", zh: "锄地" },
      { w: "at high noon", zh: "正午" },
      { w: "sweat drips", zh: "汗滴落" },
      { w: "grain", zh: "谷粒" },
      { w: "bitter toil", zh: "辛苦劳作" },
    ],
    cross: {
      field: "农学",
      fieldEn: "Agronomy",
      title: "为什么偏要在大中午锄地？",
      titleEn: "Why hoe at noon, of all times?",
      body: "这是有农学道理的。锄地的主要目的之一是除草，而刚锄下来的杂草必须在烈日下暴晒才能彻底枯死；如果赶在清晨或傍晚锄，夜里露水一返潮，有些草还能复活。所以「日当午」不是写苦情，是写行家的操作规范。代价是劳动者要在一天里体温负荷最大的时段干活，靠出汗蒸发散热——这正是「汗滴禾下土」的生理背景。",
      bodyEn: "There is real agronomy here. One purpose of hoeing is weeding, and freshly cut weeds must be scorched by direct sun to die completely; hoe at dawn or dusk and some revive overnight with the dew. So 「日当午」 is professional practice, not poetic misery. The cost is that the labourer works during peak heat load, relying on sweat evaporation to cool the body — the physiology behind 「汗滴禾下土」.",
    },
    note: "粒粒皆辛苦 —— 注意 every grain 与 bitter toil 的搭配，英文里 grain 既是「谷粒」也是「一点点」，双关刚好对上。",
    noteEn: "Note how every grain pairs with bitter toil — grain means both a seed and a tiny amount, which the Chinese also implies.",
  },
  {
    slug: "jiangxue",
    title: "江雪",
    titleEn: "River Snow",
    author: "柳宗元",
    authorEn: "Liu Zongyuan",
    dynasty: "唐",
    dynastyEn: "Tang",
    theme: "山水",
    themeEn: "Landscape",
    level: 2,
    lines: [
      { zh: "千山鸟飞绝，万径人踪灭。", en: "A thousand mountains — no bird in flight; ten thousand paths — no trace of a man." },
      { zh: "孤舟蓑笠翁，独钓寒江雪。", en: "A lone boat, an old man in straw cloak and hat — fishing alone in the cold river snow." },
    ],
    keywords: [
      { w: "no bird in flight", zh: "鸟飞绝" },
      { w: "trace", zh: "踪迹" },
      { w: "straw cloak", zh: "蓑衣" },
      { w: "fishing alone", zh: "独钓" },
    ],
    cross: {
      field: "生态",
      fieldEn: "Ecology",
      title: "冬天鱼还会咬钩吗？",
      titleEn: "Do fish bite in winter?",
      body: "会，但极少。鱼是变温动物，水温降到 4℃ 左右时体温随之下降，代谢率和消化酶活性大幅降低，摄食欲望接近停摆，往往沉底不动。所以寒冬江上垂钓，收获概率极低。柳宗元写的其实不是一个渔夫，而是一个「明知钓不到还在钓」的人——这正是他被贬永州后的自画像。诗里的「绝」和「灭」都是生态意义上的绝对干净：迁徙的候鸟走了，留鸟藏了，人也不出门了。",
      bodyEn: "Yes, but barely. Fish are ectothermic: as water drops toward 4°C their metabolism slows and digestive enzymes lose activity, so feeding nearly stops and they sit on the bottom. Winter angling on a cold river is close to futile. Liu Zongyuan is not painting a fisherman — he is painting a man who fishes knowing he will catch nothing, which is exactly his self-portrait after exile to Yongzhou. 「绝」 and 「灭」 are ecological absolutes: migrants gone, residents hidden, people indoors.",
    },
    note: "二十个字，前两句是「千山/万径」的极致铺张，后两句收成一个小点。英文用 em dash 收束，节奏与中文一致。",
    noteEn: "Twenty characters: two lines of vast expansion, then a single dot of a man. The em dash mirrors that contraction in English.",
  },
  {
    slug: "xiangsi",
    title: "相思",
    titleEn: "Red Beans",
    author: "王维",
    authorEn: "Wang Wei",
    dynasty: "唐",
    dynastyEn: "Tang",
    theme: "离别",
    themeEn: "Parting",
    level: 2,
    lines: [
      { zh: "红豆生南国，春来发几枝。", en: "Red beans grow in the southern land; when spring comes, how many branches put forth?" },
      { zh: "愿君多采撷，此物最相思。", en: "I wish you would gather plenty of them — nothing speaks of longing more." },
    ],
    keywords: [
      { w: "put forth", zh: "（枝叶）生长、萌发" },
      { w: "gather", zh: "采摘" },
      { w: "longing", zh: "思念、渴望" },
      { w: "speak of", zh: "诉说、表明" },
    ],
    cross: {
      field: "植物",
      fieldEn: "Botany",
      title: "⚠️ 相思豆有毒，千万别吃",
      titleEn: "⚠️ Red beans are toxic — never eat them",
      body: "诗里的红豆是相思子（Abrus precatorius），豆科相思子属，鲜红带黑点，非常漂亮，但种子含有鸡母珠毒蛋白（abrin）——比蓖麻毒素还毒，一颗嚼碎的种子就可能致命，完整吞下反而相对安全（种皮不易消化）。它常被串成手工艺品，所以要提醒一句：好看不等于能吃。我们平时煮粥吃的「红豆」是赤小豆/赤豆（Vigna angularis），和它完全是两种植物。",
      bodyEn: "The red bean of the poem is Abrus precatorius — glossy scarlet with a black spot, and genuinely dangerous: the seeds contain abrin, a toxin more potent than ricin. One chewed seed can be fatal, while swallowing it whole is comparatively safer because the coat resists digestion. It is widely used in beadwork, so the warning matters: beautiful is not edible. The red bean in your congee is adzuki (Vigna angularis), an entirely different species.",
    },
    note: "「愿君多采撷」的「愿」是祝愿而非命令，英文用 I wish you would 最贴，语气柔而有分寸。",
    noteEn: "「愿」 is a wish, not a command — I wish you would keeps that gentle distance.",
  },
  {
    slug: "jiuyuejiuri",
    title: "九月九日忆山东兄弟",
    titleEn: "Thinking of My Brothers in Shandong on Double Ninth",
    author: "王维",
    authorEn: "Wang Wei",
    dynasty: "唐",
    dynastyEn: "Tang",
    theme: "思乡",
    themeEn: "Homesickness",
    level: 2,
    lines: [
      { zh: "独在异乡为异客，每逢佳节倍思亲。", en: "Alone in a foreign land, a stranger I remain; on every fair festival, my longing doubles." },
      { zh: "遥知兄弟登高处，遍插茱萸少一人。", en: "Far off I know my brothers climb the heights, dogwood sprigs in hand — all but one." },
    ],
    keywords: [
      { w: "a stranger", zh: "异客" },
      { w: "fair festival", zh: "佳节" },
      { w: "longing doubles", zh: "倍思亲" },
      { w: "dogwood", zh: "茱萸" },
      { w: "all but one", zh: "少一人" },
    ],
    cross: {
      field: "民俗",
      fieldEn: "Folklore",
      title: "此「山东」非彼山东",
      titleEn: "This Shandong is not that Shandong",
      body: "王维是蒲州人（今山西永济），在华山的东边，所以诗题里的「山东」指的是华山以东的故乡一带，跟今天的山东省没有关系——这个误读非常常见。重阳节（农历九月初九）的习俗是登高、佩插茱萸、饮菊花酒，古人认为茱萸气味辛烈可以祛邪避灾。王维写这首诗时十七岁，在长安谋仕途，是标准的外省青年第一个想家的节日。",
      bodyEn: "Wang Wei was from Puzhou (present-day Yongji, Shanxi), which lies east of Mount Hua — so the Shandong in his title means the country east of Hua, not today's Shandong province. A very common misreading. Double Ninth (9th day, 9th lunar month) customs include climbing heights, wearing dogwood sprigs and drinking chrysanthemum wine; the pungent dogwood was believed to ward off evil. Wang Wei wrote this at seventeen, job-hunting in Chang'an — a classic first-homesick-holiday poem.",
    },
    note: "「倍」字是全诗的重量所在，英文用 doubles 直译反而最有力；结尾 all but one 三个词就把空缺写出来了。",
    noteEn: "The whole poem rests on 「倍」 — doubles carries it exactly. And all but one states the empty place in three words.",
  },
  {
    slug: "wanglushanpubu",
    title: "望庐山瀑布",
    titleEn: "Watching the Lu Mountain Waterfall",
    author: "李白",
    authorEn: "Li Bai",
    dynasty: "唐",
    dynastyEn: "Tang",
    theme: "山水",
    themeEn: "Landscape",
    level: 2,
    lines: [
      { zh: "日照香炉生紫烟，遥看瀑布挂前川。", en: "Sunlight on Incense Burner Peak kindles a purple haze; far off I see the falls hang before the stream." },
      { zh: "飞流直下三千尺，疑是银河落九天。", en: "It plunges straight down three thousand feet — as if the Milky Way had fallen from the ninth heaven." },
    ],
    keywords: [
      { w: "kindle", zh: "点燃、激起" },
      { w: "purple haze", zh: "紫烟" },
      { w: "plunge", zh: "（瀑布）直落" },
      { w: "the Milky Way", zh: "银河" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "「紫烟」是光学现象，不是烟雾",
      titleEn: "The purple haze is optics, not smoke",
      body: "香炉峰并无香炉。所谓紫烟，是瀑布激起的大量细小水雾在阳光照射下发生散射形成的视觉效果：水雾粒径接近可见光波长，散射偏短波（偏蓝紫），加上山体阴影与逆光，就呈现出紫色。这和天空为什么是蓝的（瑞利散射）是同一类机制。至于「银河」，李白看到的是一条白色水柱，而真正的银河是我们在银河系盘面内看到的密集恒星带——两者视觉相似，成因毫不相干，这个比喻却因此格外天才。",
      bodyEn: "No incense burner ever stood on that peak. The purple haze is sunlight scattered by the fine spray the falls throw up: droplets near the wavelength of visible light scatter short wavelengths most, so the mist reads blue-violet, intensified by shadow and backlighting — the same Rayleigh scattering that makes the sky blue. As for the Milky Way: Li Bai saw a white column of water; the real Milky Way is the dense star band we see from inside our galaxy's disk. Visually alike, causally unrelated — which is what makes the comparison brilliant.",
    },
    note: "「挂」字把瀑布写成一幅挂着的布，英文用 hang 正好对上；plunge 则把下一句的动势释放出来。",
    noteEn: "「挂」 turns the falls into hanging cloth — hang carries it; then plunge releases all the momentum in the next line.",
  },
  {
    slug: "zaofabaidicheng",
    title: "早发白帝城",
    titleEn: "Leaving Baidi at Dawn",
    author: "李白",
    authorEn: "Li Bai",
    dynasty: "唐",
    dynastyEn: "Tang",
    theme: "行旅",
    themeEn: "Travel",
    level: 2,
    lines: [
      { zh: "朝辞白帝彩云间，千里江陵一日还。", en: "At dawn I leave Baidi, high among rainbow clouds; a thousand miles to Jiangling — back in a single day." },
      { zh: "两岸猿声啼不住，轻舟已过万重山。", en: "Both banks echo with unceasing gibbon cries — yet my light boat has passed ten thousand ranges." },
    ],
    keywords: [
      { w: "at dawn", zh: "清晨" },
      { w: "unceasing", zh: "不停的" },
      { w: "gibbon", zh: "长臂猿" },
      { w: "ranges", zh: "（层叠的）山峦" },
    ],
    cross: {
      field: "地理",
      fieldEn: "Geography",
      title: "一日千里，是夸张还是写实？",
      titleEn: "A thousand miles a day — hyperbole or fact?",
      body: "基本写实。白帝城到江陵（今湖北荆州）约 350 公里，长江三峡段落差大、水流急，顺流而下的木船日行三百余里是常态，遇到汛期更快。李白写这首诗时被赦免东归，心情极好，所以「轻」字是写实也是写心。两岸的猿是长臂猿，古代三峡两岸森林密布确有猿群；如今因栖息地破坏已难觅其踪——郦道元《水经注》里「猿鸣三声泪沾裳」写的就是这一段。",
      bodyEn: "Mostly factual. Baidi to Jiangling (present-day Jingzhou, Hubei) is about 350 km; the Three Gorges drop steeply and run fast, so a drifting wooden boat covering 300+ li a day was routine, faster in flood season. Li Bai was pardoned and heading home, so 「轻」 describes both the boat and his mood. The gibbons were real: the gorges were forested and full of them — today habitat loss has driven them away. Li Daoyuan's Commentary on the Water Classic writes of the same stretch.",
    },
    note: "「轻舟」的「轻」是全诗情绪开关，英文 light boat 一语双关：船轻，心情也轻。",
    noteEn: "「轻」 is the mood switch of the poem; light boat keeps the double meaning — light in weight and light in heart.",
  },
  {
    slug: "youziyin",
    title: "游子吟",
    titleEn: "Song of the Wandering Son",
    author: "孟郊",
    authorEn: "Meng Jiao",
    dynasty: "唐",
    dynastyEn: "Tang",
    theme: "亲情",
    themeEn: "Family",
    level: 2,
    lines: [
      { zh: "慈母手中线，游子身上衣。", en: "The thread in a loving mother's hand becomes the coat upon her wandering son." },
      { zh: "临行密密缝，意恐迟迟归。", en: "She sews close and fine before he leaves, fearing he will tarry long upon the road." },
      { zh: "谁言寸草心，报得三春晖。", en: "Who says the heart of an inch of grass can repay the sunshine of three spring months?" },
    ],
    keywords: [
      { w: "wandering son", zh: "游子" },
      { w: "sew close and fine", zh: "密密缝" },
      { w: "tarry", zh: "耽搁、逗留" },
      { w: "an inch of grass", zh: "寸草" },
      { w: "repay", zh: "报答" },
    ],
    cross: {
      field: "材料",
      fieldEn: "Materials",
      title: "「密密缝」是有力学依据的",
      titleEn: "Close stitching has real mechanics behind it",
      body: "手工缝衣的针脚密度直接决定接缝强度：针距越密，单根缝线承担的拉力越小，接缝越不容易在受力处崩开。儿子远行，衣物要经得起长期摩擦和洗涤，母亲把针脚走密，是经验之谈而不是煽情。孟郊写这首诗时已五十岁，任溧阳尉，刚刚把母亲接到任上——中文里最著名的母爱诗，出自一个迟到的、终于安定下来的儿子笔下。",
      bodyEn: "Stitch density directly controls seam strength: the closer the stitches, the less tension each loop carries, and the less likely the seam bursts under load. A son's travelling clothes had to survive months of wear and washing, so dense stitching was practical knowledge, not sentiment. Meng Jiao wrote this at fifty, newly appointed to a minor post in Liyang, having just brought his mother to live with him — China's most famous poem of motherly love, written by a son who settled down late.",
    },
    note: "最后两句是全诗的重量：寸草 vs 三春晖，英文保留 an inch of grass / three spring months 的尺度对比，不要意译。",
    noteEn: "The closing couplet carries the weight: keep the scale contrast — an inch of grass against three spring months. Do not paraphrase it away.",
  },
  {
    slug: "yuanri",
    title: "元日",
    titleEn: "New Year's Day",
    author: "王安石",
    authorEn: "Wang Anshi",
    dynasty: "宋",
    dynastyEn: "Song",
    theme: "节俗",
    themeEn: "Festivals",
    level: 2,
    lines: [
      { zh: "爆竹声中一岁除，春风送暖入屠苏。", en: "Amid the crack of firecrackers a year departs; the spring breeze carries warmth into the tusu wine." },
      { zh: "千门万户曈曈日，总把新桃换旧符。", en: "On a thousand doors, ten thousand homes the bright sun shines; each puts up new peach-wood charms in place of old." },
    ],
    keywords: [
      { w: "crack (n.)", zh: "爆裂声" },
      { w: "depart (of a year)", zh: "（岁月）过去" },
      { w: "breeze", zh: "微风" },
      { w: "in place of", zh: "代替" },
      { w: "charms", zh: "符、辟邪物" },
    ],
    cross: {
      field: "化学",
      fieldEn: "Chemistry",
      title: "爆竹为什么会响？黑火药的反应",
      titleEn: "Why do firecrackers bang? The black-powder reaction",
      body: "古法爆竹烧的是黑火药：硝石（硝酸钾，供氧）、硫磺（降低着火点）、木炭（燃料），典型配比约 75:10:15。反应大体为 2KNO₃ + S + 3C → K₂S + N₂↑ + 3CO₂↑，瞬间产生大量高温气体，体积急剧膨胀冲破纸筒，形成冲击波——「爆」字是声学结果，也是化学结果。顺带说一句：古人最初真的烧竹子（竹节受热爆裂发声），火药发明后才有了纸包火药的「爆竹」，名字沿用了下来。至于屠苏酒，是除夕饮用的药酒，古人认为可避疫，常用大黄、白术、桂枝一类药材。",
      bodyEn: "Traditional firecrackers burn black powder: saltpetre (potassium nitrate, the oxygen source), sulphur (lowers ignition temperature) and charcoal (fuel), roughly 75:10:15. The reaction runs approximately 2KNO₃ + S + 3C → K₂S + N₂↑ + 3CO₂↑, generating hot gas almost instantly; the volume surge bursts the paper tube and produces a shock wave — the 「爆」 is chemistry heard as acoustics. Incidentally, people once literally burned bamboo (its joints cracked loudly); when gunpowder arrived, the name stuck. The tusu wine was a herbal drink taken on New Year's Eve, believed to ward off plague — rhubarb, atractylodes, cinnamon twig and the like.",
    },
    note: "王安石写这首诗时正推行新法，「新桃换旧符」既是习俗也是政治宣言——英文用 in place of old 保留替换义。",
    noteEn: "Wang Anshi wrote this while pushing his reforms: new charms replacing old is custom and political manifesto at once — in place of old keeps that edge.",
  },
  {
    slug: "tixilinbi",
    title: "题西林壁",
    titleEn: "Written on the Wall of Xilin Temple",
    author: "苏轼",
    authorEn: "Su Shi",
    dynasty: "宋",
    dynastyEn: "Song",
    theme: "哲理",
    themeEn: "Philosophy",
    level: 2,
    lines: [
      { zh: "横看成岭侧成峰，远近高低各不同。", en: "Seen side-on a ridge, end-on a peak — far, near, high, low, never the same." },
      { zh: "不识庐山真面目，只缘身在此山中。", en: "We cannot know Mount Lu's true face, only because we stand within the mountain." },
    ],
    keywords: [
      { w: "ridge", zh: "山岭" },
      { w: "peak", zh: "山峰" },
      { w: "true face", zh: "真面目" },
      { w: "only because", zh: "只因为" },
      { w: "within", zh: "在……之内" },
    ],
    cross: {
      field: "数学",
      fieldEn: "Mathematics",
      title: "这其实是一句投影几何",
      titleEn: "This is really a line of projective geometry",
      body: "同一个三维物体，从不同的观察点投影到二维视平面上，得到的轮廓本来就不同——横看是一条延展的山脊，侧看是一个孤立的尖峰。苏轼在 1084 年说出的，正是「观测结果依赖于观测者的位置」这一现代科学的基本前提。它的延伸版本今天有各种名字：人类学叫「主位与客位」，系统论叫「观察者不可忽略」，管理学叫「当局者迷」。这首诗其实是一句方法论，不是风景诗。",
      bodyEn: "The same solid object projects different outlines onto a 2-D view plane from different viewpoints — an extended ridge from one side, an isolated peak from the end. What Su Shi stated in 1084 is precisely the modern premise that observation depends on the observer's position. Its descendants have many names: emic vs. etic in anthropology, the non-negligible observer in systems theory, the proverbial blindness of the insider in management. This is methodology dressed as landscape.",
    },
    note: "英文用 side-on / end-on 对译「横/侧」，比写成 horizontally / vertically 自然得多。",
    noteEn: "side-on / end-on renders 「横/侧」 far more naturally than horizontally / vertically.",
  },
  {
    slug: "zhushi",
    title: "竹石",
    titleEn: "Bamboo and Rock",
    author: "郑燮",
    authorEn: "Zheng Xie",
    dynasty: "清",
    dynastyEn: "Qing",
    theme: "咏物",
    themeEn: "Object",
    level: 2,
    lines: [
      { zh: "咬定青山不放松，立根原在破岩中。", en: "It bites into the green hill and will not let go; its roots hold fast in the broken rock." },
      { zh: "千磨万击还坚劲，任尔东西南北风。", en: "Battered ten thousand times it still stands firm — let the winds blow from east, west, south or north." },
    ],
    keywords: [
      { w: "bite into", zh: "咬住、紧紧抓住" },
      { w: "hold fast", zh: "牢牢抓住" },
      { w: "battered", zh: "被反复击打" },
      { w: "stands firm", zh: "挺立不动摇" },
      { w: "let … blow", zh: "任凭……吹" },
    ],
    cross: {
      field: "力学",
      fieldEn: "Mechanics",
      title: "竹子为什么折不断？",
      titleEn: "Why won't bamboo snap?",
      body: "竹子的抗拉强度可达 150–200 MPa，接近普通钢材的三分之一，而密度只有钢的十分之一左右——比强度（强度除以密度）反而优于钢。秘密在于它中空的筒状结构：中空截面在同等用料下抗弯刚度最大，加上维管束沿纵向密集排列、节间有横隔加固。地下的竹鞭纵横成网，所以「咬定青山不放松」是字面成立的。竹子随风弯曲而不折，也是同样的结构弹性在起作用。",
      bodyEn: "Bamboo's tensile strength reaches 150–200 MPa — about a third of ordinary steel — at roughly one-tenth the density, so its specific strength beats steel. The secret is the hollow tube: a hollow section maximises bending stiffness for a given amount of material, reinforced by longitudinally packed vascular bundles and solid nodes. The underground rhizome network is why 「咬定青山」 is literally true. And bending with the wind instead of breaking is the same elastic structure at work.",
    },
    note: "咬定 → bite into，坚劲 → stands firm。四个动词撑起全诗，英文也靠动词，别用形容词凑。",
    noteEn: "bite into, hold fast, stands firm — four verbs carry the poem. Keep verbs in English too; do not pad with adjectives.",
  },
  {
    slug: "chunyexiyu",
    title: "春夜喜雨",
    titleEn: "Delighting in Rain on a Spring Night",
    author: "杜甫",
    authorEn: "Du Fu",
    dynasty: "唐",
    dynastyEn: "Tang",
    theme: "四季",
    themeEn: "Seasons",
    level: 3,
    lines: [
      { zh: "好雨知时节，当春乃发生。", en: "A good rain knows its season — it comes in spring to make things grow." },
      { zh: "随风潜入夜，润物细无声。", en: "Riding the wind it steals into the night, moistening all things silently." },
    ],
    keywords: [
      { w: "knows its season", zh: "知时节" },
      { w: "make things grow", zh: "使万物生长" },
      { w: "steal into", zh: "悄悄潜入" },
      { w: "moisten", zh: "滋润" },
      { w: "silently", zh: "无声地" },
    ],
    cross: {
      field: "气象",
      fieldEn: "Meteorology",
      title: "为什么春雨要「细无声」才好？",
      titleEn: "Why is gentle spring rain the good kind?",
      body: "这里有实打实的土壤物理学：同样一场雨，强度越大，落到地面的雨滴动能越大，越容易击碎表层土壤团粒、形成板结并引发地表径流，水还没渗下去就流走了；而小雨强度低，几乎全部入渗，根系真正能用到。春季又是播种和返青的关键期，土壤表层含水率直接决定出苗率。所以杜甫说「好雨」，标准不是下得大，而是下得对——「知时节」三个字是农业判断。",
      bodyEn: "This is soil physics. For the same total rainfall, higher intensity means greater drop kinetic energy: it breaks surface aggregates, seals the crust and drives runoff before water can infiltrate. Low-intensity rain infiltrates almost entirely, which is what roots actually use. Spring is also the critical window for germination and green-up, where surface moisture decides emergence rates. So Du Fu's 「好雨」 is judged by timing and gentleness, not volume — 「知时节」 is an agronomic verdict.",
    },
    note: "「潜」字最精——雨是偷着来的。英文 steal into 保留了「偷偷」这一层，润只能译 moisten。",
    noteEn: "「潜」 is the sharpest word — the rain sneaks in. steal into keeps that; moisten is the only honest rendering of 润.",
  },
  {
    slug: "qiuxi",
    title: "秋夕",
    titleEn: "An Autumn Night",
    author: "杜牧",
    authorEn: "Du Mu",
    dynasty: "唐",
    dynastyEn: "Tang",
    theme: "四季",
    themeEn: "Seasons",
    level: 3,
    lines: [
      { zh: "银烛秋光冷画屏，轻罗小扇扑流萤。", en: "Silver candle, autumn light — the painted screen grows cold; a gauze fan flutters at the drifting fireflies." },
      { zh: "天阶夜色凉如水，卧看牵牛织女星。", en: "The palace steps at night are cool as water; she lies watching the Herdboy and Weaver stars." },
    ],
    keywords: [
      { w: "gauze fan", zh: "轻罗小扇" },
      { w: "flutter at", zh: "扑打" },
      { w: "fireflies", zh: "萤火虫" },
      { w: "cool as water", zh: "凉如水" },
      { w: "the Herdboy and Weaver", zh: "牛郎织女" },
    ],
    cross: {
      field: "天文",
      fieldEn: "Astronomy",
      title: "牛郎织女其实是哪两颗星？",
      titleEn: "Which stars are the Herdboy and the Weaver?",
      body: "牛郎星是天鹰座的河鼓二（Altair），距地球约 16.7 光年；织女星是天琴座的织女一（Vega），约 25 光年。两者分处银河两岸，角距离约 34 度，实际相距约 16 光年——「每年七夕相会一次」是神话，不是天文。七夕（农历七月初七）在公历中大致落在 8 月，正是夏秋之交的晴夜，银河清晰可见，所以这个节日起源于真实的观星条件。诗中另一个细节：萤火虫发光靠荧光素酶催化荧光素氧化，几乎不产热（冷光），效率远高于白炽灯。",
      bodyEn: "The Herdboy is Altair (Alpha Aquilae), about 16.7 light-years away; the Weaver is Vega (Alpha Lyrae), about 25. They sit on opposite sides of the Milky Way, roughly 34 degrees apart on the sky and about 16 light-years apart in space — the annual meeting is myth, not astronomy. Double Seventh falls around August, when the summer sky is clear and the Milky Way prominent, which is why the festival grew out of real observing conditions. One more detail: fireflies glow via luciferase-catalysed oxidation of luciferin, a cold light with almost no heat and far better efficiency than an incandescent bulb.",
    },
    note: "「冷」与「凉」两次温度描写，英文分别用 grows cold 和 cool as water，避免重复。",
    noteEn: "Two temperature words, 「冷」 and 「凉」 — render them separately (grows cold, cool as water) to avoid repetition.",
  },
  {
    slug: "shanxing",
    title: "山行",
    titleEn: "Travelling in the Mountains",
    author: "杜牧",
    authorEn: "Du Mu",
    dynasty: "唐",
    dynastyEn: "Tang",
    theme: "山水",
    themeEn: "Landscape",
    level: 1,
    lines: [
      { zh: "远上寒山石径斜，白云生处有人家。", en: "Far up the cold hill a stone path slants; where white clouds are born, there are homes." },
      { zh: "停车坐爱枫林晚，霜叶红于二月花。", en: "I stop the carriage, loving the maple woods at dusk — frost-bitten leaves out-red the flowers of February." },
    ],
    keywords: [
      { w: "slant (v.)", zh: "倾斜" },
      { w: "where clouds are born", zh: "白云生处" },
      { w: "maple woods", zh: "枫林" },
      { w: "frost-bitten", zh: "经霜的" },
      { w: "out-red (v.)", zh: "比……更红" },
    ],
    cross: {
      field: "化学",
      fieldEn: "Chemistry",
      title: "霜叶为什么比春花还红？",
      titleEn: "Why are frost-bitten leaves redder than spring flowers?",
      body: "秋天日照变短、气温下降，叶绿素开始分解，原本被绿色掩盖的类胡萝卜素（黄橙）显现出来；更关键的是，低温促使叶片积累可溶性糖，糖分作为原料合成大量花青素，于是枫叶呈现出鲜艳的红色。糖越多、昼夜温差越大、光照越足，红色越浓——这就是「霜叶红于二月花」的化学机制：二月春花靠的是花瓣细胞里现成的色素，枫叶靠的是一场低温驱动的糖代谢。",
      bodyEn: "Shorter days and cold trigger chlorophyll breakdown, unmasking carotenoids (yellow-orange). More importantly, low temperature drives soluble-sugar accumulation in the leaf, and that sugar feeds synthesis of anthocyanin — the vivid red of maple. More sugar, bigger day-night temperature swing and stronger light all intensify the red. That is the chemistry behind 「霜叶红于二月花」: spring flowers use pigment already in petal cells, while maple leaves run a cold-driven sugar pathway.",
    },
    note: "「红于」是「比……更红」，造一个 out-red 最省事也最有冲击力（out- 前缀表示「超过」）。",
    noteEn: "「红于」 means redder than — coining out-red uses the out- prefix and keeps the punch.",
  },
  {
    slug: "luzhai",
    title: "鹿柴",
    titleEn: "Deer Enclosure",
    author: "王维",
    authorEn: "Wang Wei",
    dynasty: "唐",
    dynastyEn: "Tang",
    theme: "山水",
    themeEn: "Landscape",
    level: 3,
    lines: [
      { zh: "空山不见人，但闻人语响。", en: "Empty hills — no one in sight, only the echo of voices is heard." },
      { zh: "返景入深林，复照青苔上。", en: "The returning light enters the deep wood and shines again upon the green moss." },
    ],
    keywords: [
      { w: "empty hills", zh: "空山" },
      { w: "echo", zh: "回响" },
      { w: "returning light", zh: "返景（夕阳回照）" },
      { w: "moss", zh: "青苔" },
      { w: "shine again upon", zh: "又照在……上" },
    ],
    cross: {
      field: "物理",
      fieldEn: "Physics",
      title: "「但闻人语响」是声学现象",
      titleEn: "Hearing voices without seeing people is acoustics",
      body: "诗里有两个可测量的事实。第一，听得见看不见，是因为声波波长较长（人声基频约 100–300 Hz，波长 1–3 米），远大于林木尺度，因此能绕过树干发生明显衍射；而可见光波长约 0.5 微米，几乎直线传播，被枝叶挡住就是挡住。第二，「返景」指夕阳经外部反射后重新进入林中的光，强度很弱，只能照亮最耐阴的植物——青苔（苔藓）正是一类典型的耐阴植物，能在不足全日照 5% 的环境下生存。王维写的不是玄，是观察。",
      bodyEn: "Two measurable facts sit in this poem. First, hearing without seeing works because speech wavelengths (1–3 m at 100–300 Hz) are far larger than tree trunks and diffract around them, whereas visible light at about 0.5 micrometres travels essentially straight and is blocked by foliage. Second, the 「返景」 is sunlight re-entering the wood after reflection — so weak that only the most shade-tolerant plants catch it, and moss is precisely that, surviving on under 5% of full sunlight. Wang Wei observed; he did not mystify.",
    },
    note: "「响」译 echo 还是 voice？这里译 echo，因为空山之中传来的正是回声。",
    noteEn: "Render 「响」 as echo rather than voice — in an empty mountain what arrives is the reverberation.",
  },
  {
    slug: "yesushansi",
    title: "夜宿山寺",
    titleEn: "Staying Overnight in a Mountain Temple",
    author: "李白",
    authorEn: "Li Bai",
    dynasty: "唐",
    dynastyEn: "Tang",
    theme: "山水",
    themeEn: "Landscape",
    level: 1,
    lines: [
      { zh: "危楼高百尺，手可摘星辰。", en: "This tower stands a hundred feet high — my hand could pluck the stars." },
      { zh: "不敢高声语，恐惊天上人。", en: "I dare not speak aloud, for fear of waking those who dwell in heaven." },
    ],
    keywords: [
      { w: "pluck (stars)", zh: "摘取" },
      { w: "dare not", zh: "不敢" },
      { w: "speak aloud", zh: "大声说话" },
      { w: "for fear of", zh: "唯恐" },
      { w: "dwell", zh: "居住" },
    ],
    cross: {
      field: "天文",
      fieldEn: "Astronomy",
      title: "星星到底有多远？",
      titleEn: "How far away are the stars, really?",
      body: "离我们最近的恒星是半人马座比邻星，约 4.2 光年，也就是 40 万亿公里——即使楼高百尺（约 30 米），离摘到星星也差了十五个数量级。夜空中最亮的几颗：天狼星 8.6 光年、织女星 25 光年、牛郎星 16.7 光年，我们看到的都是它们多年前发出的光。所以「手可摘星辰」是纯粹的夸张修辞，但这恰恰是李白的办法：用物理上的不可能，写出心理上的震撼。",
      bodyEn: "The nearest star is Proxima Centauri at about 4.2 light-years — some 40 trillion kilometres. Even a hundred-foot tower (about 30 m) falls some fifteen orders of magnitude short. The brightest stars: Sirius 8.6 light-years, Vega 25, Altair 16.7 — all seen as they were years ago. So plucking stars is pure hyperbole, and that is exactly Li Bai's method: use physical impossibility to register psychological impact.",
    },
    note: "「恐惊天上人」的「恐」是唯恐、生怕，英文 for fear of 比 I'm afraid 更准确（后者语气偏弱）。",
    noteEn: "「恐」 means lest — for fear of is stronger and more accurate than I'm afraid.",
  },
  {
    slug: "meihua",
    title: "梅花",
    titleEn: "Plum Blossoms",
    author: "王安石",
    authorEn: "Wang Anshi",
    dynasty: "宋",
    dynastyEn: "Song",
    theme: "咏物",
    themeEn: "Object",
    level: 1,
    lines: [
      { zh: "墙角数枝梅，凌寒独自开。", en: "A few plum branches by the corner wall — they bloom alone, defying the cold." },
      { zh: "遥知不是雪，为有暗香来。", en: "I know from afar that it is not snow, because a faint fragrance comes." },
    ],
    keywords: [
      { w: "defying the cold", zh: "凌寒" },
      { w: "bloom alone", zh: "独自开" },
      { w: "from afar", zh: "远远地" },
      { w: "faint fragrance", zh: "暗香" },
    ],
    cross: {
      field: "植物",
      fieldEn: "Botany",
      title: "梅为什么偏在冬天开？",
      titleEn: "Why does plum bloom in winter?",
      body: "梅需要经过一段持续低温才能打破花芽休眠，这个机制叫春化作用；它所需的低温阈值不高，因此在冬末早春、别的植物还休眠时就能开花。它先花后叶，所以满枝是花、看不见叶子。香气则是花瓣释放的挥发性芳香物质（如苯甲醇、乙酸苄酯）在空气中扩散——这也是「遥知不是雪」的依据：视觉上梅花和雪确实容易混淆，但雪没有气味。王安石用一个嗅觉线索就完成了判断，是很聪明的写法。",
      bodyEn: "The plum needs a sustained cold period to break flower-bud dormancy — vernalization — but its chilling threshold is modest, so it blooms in late winter while everything else is still dormant. It flowers before leafing out, hence branches of pure blossom. The scent comes from volatile aromatics (benzyl alcohol, benzyl acetate) diffusing through air, which is exactly how one tells it from snow: visually similar, but snow has no smell. Wang Anshi solves the puzzle with a single olfactory clue.",
    },
    note: "「暗香」的「暗」是「隐约、不张扬」，译 faint 比 hidden 好——faint 是气味淡，符合实际。",
    noteEn: "「暗」 here means faint and unobtrusive — faint beats hidden, since the scent is subtle rather than concealed.",
  },
  {
    slug: "gucaosongbie",
    title: "赋得古原草送别",
    titleEn: "Grass on the Ancient Plain — A Farewell",
    author: "白居易",
    authorEn: "Bai Juyi",
    dynasty: "唐",
    dynastyEn: "Tang",
    theme: "离别",
    themeEn: "Parting",
    level: 1,
    lines: [
      { zh: "离离原上草，一岁一枯荣。", en: "Lush, lush the grass on the ancient plain — each year it withers, each year it thrives." },
      { zh: "野火烧不尽，春风吹又生。", en: "Wildfire cannot burn it all away; the spring wind blows and it lives again." },
    ],
    keywords: [
      { w: "lush", zh: "茂盛的" },
      { w: "wither", zh: "枯萎" },
      { w: "thrive", zh: "繁盛" },
      { w: "burn … away", zh: "烧尽" },
      { w: "lives again", zh: "复生" },
    ],
    cross: {
      field: "生态",
      fieldEn: "Ecology",
      title: "野火真的烧不尽草吗？",
      titleEn: "Can wildfire really not kill the grass?",
      body: "是真的。多数多年生草本的地上部分极易燃烧，但地下根茎和芽库埋在土壤中，而土壤是良好的隔热层——一场快速掠过的地表火，土下 2–3 厘米处的温度几乎不升高。火过之后，灰分把原本锁在枯草里的钾、磷等矿质养分一次性释放成速效肥，加上失去遮阴、光照充足，草反而爆发式再生。生态学上这叫火后演替，草原生态系统正是靠周期性火灾维持的。白居易十六岁时写的这句，是一条准确的生态学观察。",
      bodyEn: "It is true. The above-ground parts of perennial grasses burn readily, but rhizomes and bud banks sit in soil, and soil is an excellent insulator — in a fast surface fire, temperature a few centimetres down barely rises. Afterwards, ash releases potassium, phosphorus and other minerals locked in dead biomass as fast-acting fertilizer; with the shading canopy gone and light abundant, the grass regrows explosively. Ecologists call this post-fire succession, and grassland ecosystems actually depend on periodic fire. Bai Juyi wrote an accurate ecological observation at sixteen.",
    },
    note: "枯荣是一对反义，英文 withers / thrives 要保持同样的对比；「又生」用 lives again 而不是 grows again，更有生命力。",
    noteEn: "Keep the wither/thrive contrast. For 「又生」, lives again carries more force than grows again.",
  },
];

/** 初版 20 首补全学段与文体 */
const CORE: Poem[] = LEGACY.map((p) => ({
  ...p,
  stage: "小学" as const,
  kind: "诗" as const,
}));

/**
 * 全站篇目总表：小学 → 初中 → 高中
 * 新增篇目只需在 app/config/poem-data/ 对应分片里追加一条配置即可。
 */
export const POEMS: Poem[] = [
  ...CORE,
  ...PRIMARY_1,
  ...PRIMARY_2,
  ...PRIMARY_3,
  ...PRIMARY_4,
  ...PRIMARY_5,
  ...JUNIOR_1,
  ...JUNIOR_2,
  ...JUNIOR_3,
  ...JUNIOR_4,
  ...JUNIOR_5,
  ...JUNIOR_6,
  ...SENIOR_1,
  ...SENIOR_2,
  ...SENIOR_3,
  ...SENIOR_4,
];

/** 按 slug 取诗 */
export const POEM_MAP: Record<string, Poem> = Object.fromEntries(
  POEMS.map((p) => [p.slug, p])
);

/** 学段标签（中英） */
export const STAGE_LABEL: Record<string, { zh: string; en: string }> = {
  小学: { zh: "小学", en: "Primary" },
  初中: { zh: "初中", en: "Junior High" },
  高中: { zh: "高中", en: "Senior High" },
};

/** 文体标签（中英） */
export const KIND_LABEL: Record<string, { zh: string; en: string }> = {
  诗: { zh: "诗", en: "Poem" },
  词: { zh: "词", en: "Ci" },
  文言文: { zh: "文言文", en: "Classical Prose" },
};

/** 全部主题（用于筛选与出题） */
export const ALL_THEMES = Array.from(new Set(POEMS.map((p) => p.theme)));

/** 按日期确定性地选一首诗（每日一诗） */
export function poemOfTheDay(date = new Date()): Poem {
  const seed =
    date.getFullYear() * 10000 + (date.getMonth() + 1) * 100 + date.getDate();
  return POEMS[seed % POEMS.length];
}
